// 社区与网点文案（矩阵 P-2.1 / P-2.2）。
import type { PageCopy } from "@/lib/use-copy";

const zh = {
  applyNoValue: "—",
  colApplyName: "小区名",
  colApplyMerchant: "提报商家",
  colApplyAddress: "地址",
  colApplyRegion: "所属区划",
  colApplyStatus: "状态",
  colApplyTime: "提报时间",
  apPending: "待核实",
  apApproved: "已建社区",
  apRejected: "已驳回",
  filterApplyStatus: "按状态筛",
  filterApplyStatusAll: "全部状态",
  emptyApply: "没有待核实的提报",
  secApplyWhat: "商家提了什么",
  secApplyRegion: "挂到哪个区划",
  secApplyReject: "驳回",
  secApplyResult: "裁决结果",
  fieldApplyNote: "补充说明",
  fieldApplyRegion: "区划码",
  fieldApplyReason: "驳回原因",
  fieldApplyCommunity: "建出的社区号",
  applyDupHint: "先核对地址：同一个小区常有两个叫法，批重了商家会分不清该勾哪个",
  applyRegionPlaceholder: "如 330106002（建议到街道级）",
  applyRegionHint: "不挂区划的话，这个新社区在任何「按区覆盖」里都出不来 —— 而界面上它看起来完全正常",
  applyReasonPlaceholder: "如：这个小区已经在平台上，叫「翠苑一区」，直接勾选即可",
  applyReasonHint: "原样发给商家。不写理由他不知道该改什么，只会原样再提一次",
  btnApplyPass: "通过并建社区",
  btnApplyReject: "驳回",
  toastApplyApproved: "已通过，社区已建出",
  toastApplyRejected: "已驳回，理由已回给商家",
  readOnlyApplyWhat: "裁决商家提报",
  readOnlyApplyNote: "通过会建出一个新社区，属于主数据操作",

  openedYes: "已开城",
  openedNo: "未开城",

  /** `{name}` 是社区名 */
  toastOpened: "{name} 已开城",
  toastClosed: "{name} 已停止开城",
  toastPickupStatus: "已更新自提点状态",
  toastFeeSaved: "已更新履约服务费费率",

  colCommunityNo: "社区编号",
  colCommunity: "社区",
  colCityGrid: "城市 / 网格",
  colRegion: "所属区划",
  regionUnset: "未归属",
  regionUnsetNote: "没挂区划的社区，商家按「整个西湖区」这样勾范围时命中不到它 —— 它只能被逐个点名。平台不按名字猜归属：猜错不会报错，只会让它悄悄出现在别人的经营范围里。",
  regionConfigure: "归属",
  regionSectionNow: "当前归属",
  regionSectionPick: "重新选择",
  regionRoot: "全国",
  regionLeafReached: "已经到街道，不用再往下选了。",
  regionNoChild: "这一级下面没有数据",
  regionDisabled: "已停用",
  regionSave: "保存归属",
  regionClear: "清空归属",
  regionSaveHint: "建议挂到街道级：挂到区县也能用，但那样「按街道覆盖」就退化成了「按区覆盖」。",
  regionSaved: "归属已更新",
  colOpened: "开城",
  ariaOpenSwitch: "{name} 开城开关",
  colRadius: "覆盖半径",
  colPickupCount: "自提点",
  colCreatedAt: "创建时间",
  colActions: "操作",
  archiveHintCommunity: "该社区下仍有自提点，请先迁移或停用",
  entityCommunity: "社区",
  entityPickup: "自提点",

  colPickupNo: "自提点编号",
  colName: "名称",
  colType: "类型",
  colCarrier: "承接商家",
  colTimes: "到货 / 营业",
  colFeeRate: "服务费费率",
  zeroFee: "零报酬",
  ariaFeeRate: "费率（万分比）",
  save: "存",
  cancel: "取消",
  colStatus: "状态",
  btnSuspend: "停用",
  btnActivate: "启用",
  btnFinishMigrate: "完成迁移",

  col30dAccept: "30 天承接",
  suspectPro: "疑似职业化",
  colFiledAt: "建档时间",
  btnPauseIntake: "暂停接单",

  readOnlyCommunityWhat: "社区开城与围栏配置",
  readOnlyCommunityNote: "不能开城、改半径或归档",
  readOnlyPickupWhat: "自提点建档与启停",
  readOnlyPickupNote: "不能启停、改费率或归档",

  /** `{n}` 是阈值次数 */
  neighborNotice:
    "近 30 天承接 ≥ {n} 次的邻里自提点（ADR-005 §F6 建议阈值）。频繁承接说明它已经不是「顺手帮邻居带一次」，而是在无证经营自提点 —— 需要人工复核后转为常驻点或暂停。",
  searchGrid: "搜索社区编号 / 名称 / 网格",
  searchPickup: "搜索自提点编号 / 名称 / 地址",
  filterOpened: "按开城状态筛选",
  filterOpenedAll: "全部开城状态",
  filterType: "按类型筛选",
  filterTypeAll: "全部类型",
  filterStatus: "按状态筛选",
  filterStatusAll: "全部状态",

  emptyGrid: "没有符合条件的社区。清空筛选，或先在城市网格里建一个社区。",
  emptyPickup: "没有符合条件的自提点。自提点是履约的落点，缺它货到了没人能核销。",
  emptyNeighbor: "当前没有触发阈值的临时自提点（近 30 天承接 ≥ {n} 次）。这是好事，不是数据缺失。",
};

const en: typeof zh = {
  applyNoValue: "—",
  colApplyName: "Community",
  colApplyMerchant: "Requested by",
  colApplyAddress: "Address",
  colApplyRegion: "Region",
  colApplyStatus: "Status",
  colApplyTime: "Submitted",
  apPending: "To verify",
  apApproved: "Community created",
  apRejected: "Rejected",
  filterApplyStatus: "Filter by status",
  filterApplyStatusAll: "All statuses",
  emptyApply: "Nothing to verify",
  secApplyWhat: "What was requested",
  secApplyRegion: "Region to attach",
  secApplyReject: "Reject",
  secApplyResult: "Decision",
  fieldApplyNote: "Note",
  fieldApplyRegion: "Region code",
  fieldApplyReason: "Rejection reason",
  fieldApplyCommunity: "Created community",
  applyDupHint: "Check the address first: one community often goes by two names, and a duplicate leaves merchants unsure which to pick",
  applyRegionPlaceholder: "e.g. 330106002 (street level preferred)",
  applyRegionHint: "Without a region this community never shows up in any district-level coverage — while the screen looks perfectly fine",
  applyReasonPlaceholder: "e.g. already on the platform as “Cuiyuan No.1”, just select it",
  applyReasonHint: "Sent to the merchant verbatim. Without a reason they will simply resubmit the same thing",
  btnApplyPass: "Approve & create",
  btnApplyReject: "Reject",
  toastApplyApproved: "Approved, community created",
  toastApplyRejected: "Rejected, reason sent to the merchant",
  readOnlyApplyWhat: "decide merchant requests",
  readOnlyApplyNote: "Approving creates a new community — that is a master-data change",

  openedYes: "Launched",
  openedNo: "Not launched",

  toastOpened: "{name} is now live",
  toastClosed: "{name} is no longer live",
  toastPickupStatus: "Pickup point status updated",
  toastFeeSaved: "Fulfillment service fee updated",

  colCommunityNo: "Community no.",
  colCommunity: "Community",
  colCityGrid: "City / grid",
  colRegion: "Division",
  regionUnset: "Unassigned",
  regionUnsetNote: "A community with no division cannot be matched when a merchant selects a whole district — it can only be named one by one. The platform will not guess by name: a wrong guess raises no error, it just quietly puts this community inside someone else\u2019s service area.",
  regionConfigure: "Division",
  regionSectionNow: "Current",
  regionSectionPick: "Choose again",
  regionRoot: "China",
  regionLeafReached: "You have reached street level; nothing further to pick.",
  regionNoChild: "Nothing under this level",
  regionDisabled: "Disabled",
  regionSave: "Save",
  regionClear: "Clear",
  regionSaveHint: "Prefer street level: a district works too, but then \u201ccover by street\u201d degrades into \u201ccover by district\u201d.",
  regionSaved: "Division updated",
  colOpened: "Launched",
  ariaOpenSwitch: "Launch toggle for {name}",
  colRadius: "Geofence radius",
  colPickupCount: "Pickup points",
  colCreatedAt: "Created at",
  colActions: "Actions",
  archiveHintCommunity: "This community still has pickup points — migrate or suspend them first",
  entityCommunity: "community",
  entityPickup: "pickup point",

  colPickupNo: "Pickup no.",
  colName: "Name",
  colType: "Type",
  colCarrier: "Host merchant",
  colTimes: "Arrival / opening hours",
  colFeeRate: "Service fee rate",
  zeroFee: "Unpaid",
  ariaFeeRate: "Rate (basis points)",
  save: "Save",
  cancel: "Cancel",
  colStatus: "Status",
  btnSuspend: "Suspend",
  btnActivate: "Activate",
  btnFinishMigrate: "Finish migration",

  col30dAccept: "Handled in 30 days",
  suspectPro: "Likely commercial",
  colFiledAt: "Registered at",
  btnPauseIntake: "Pause intake",

  readOnlyCommunityWhat: "community launch & geofence settings",
  readOnlyCommunityNote: "cannot launch, change the radius or archive",
  readOnlyPickupWhat: "pickup point registration & activation",
  readOnlyPickupNote: "cannot activate, change the fee rate or archive",

  neighborNotice:
    "Neighbour pickup points that handled {n} or more parcels in the last 30 days (suggested threshold, ADR-005 §F6). That frequency is no longer “helping a neighbour out once” — it is running an unlicensed pickup point, and needs a human review to either convert it to a fixed point or suspend it.",
  searchGrid: "Search community no. / name / grid",
  searchPickup: "Search pickup no. / name / address",
  filterOpened: "Filter by launch status",
  filterOpenedAll: "Any launch status",
  filterType: "Filter by type",
  filterTypeAll: "All types",
  filterStatus: "Filter by status",
  filterStatusAll: "All statuses",

  emptyGrid: "No communities match these filters. Clear the filters, or create a community under a city grid first.",
  emptyPickup: "No pickup points match these filters. A pickup point is where fulfillment lands — without one, goods arrive and nobody can redeem them.",
  emptyNeighbor: "No temporary pickup point is over the threshold ({n}+ parcels in 30 days). That is good news, not missing data.",
};

export const COMMUNITIES_COPY: PageCopy<typeof zh> = { zh, en };

/** 拆出去的子组件靠它接文案（与 system / stores 那两页同一个写法）。 */
export type CommunityCopy = typeof zh;
