// 社区与网点文案（矩阵 P-2.1 / P-2.2）。
import type { PageCopy } from "@/lib/use-copy";

const zh = {
  applyNoValue: "—",
  colApplyName: "小区名",
  colApplyMerchant: "提报商家",
  colApplyAddress: "地址",
  colApplyRegion: "所属区划",
  colApplyStatus: "状态",
  colApplyTime: "提报时间",
  apPending: "待核实",
  apApproved: "已建社区",
  apRejected: "已驳回",
  filterApplyStatus: "按状态筛",
  filterApplyStatusAll: "全部状态",
  emptyApply: "没有待核实的提报",
  secApplyWhat: "提报内容",
  secApplyRegion: "挂到哪个区划",
  secApplyReject: "驳回",
  secApplyResult: "裁决结果",
  fieldApplyNote: "补充说明",
  fieldApplyRegion: "区划码",
  fieldApplyReason: "驳回原因",
  fieldApplyCommunity: "建出的社区号",
  applyDupHint: "先核对地址：同一个小区常有两个叫法，批重了商家会分不清该勾哪个",
  applyRegionPlaceholder: "如 330106002（建议到街道级）",
  applyRegionHint: "不挂区划的话，这个新社区在任何「按区覆盖」里都出不来 —— 而界面上它看起来完全正常",
  applyReasonPlaceholder: "如：这个小区已经在平台上，叫「翠苑一区」，直接勾选即可",
  applyReasonHint: "原样发给商家。不写理由他不知道该改什么，只会原样再提一次",
  btnApplyPass: "通过并建社区",
  btnApplyReject: "驳回",
  toastApplyApproved: "已通过，社区已建出",
  toastApplyRejected: "已驳回，理由已回给商家",
  readOnlyApplyWhat: "裁决商家提报",
  readOnlyApplyNote: "通过会建出一个新社区，属于主数据操作",

  openedYes: "已开城",
  openedNo: "未开城",

  /** `{name}` 是社区名 */
  toastOpened: "{name} 已开城",
  toastClosed: "{name} 已停止开城",
  toastPickupStatus: "已更新自提点状态",
  toastFeeSaved: "已更新履约服务费费率",

  colCommunityNo: "社区编号",
  colCommunity: "社区",
  colCityGrid: "城市 / 网格",
  colRegion: "所属区划",
  regionUnset: "未归属",
  regionUnsetNote: "没挂区划的社区，商家按「整个西湖区」这样勾范围时命中不到它 —— 它只能被逐个点名。平台不按名字猜归属：猜错不会报错，只会让它悄悄出现在别人的经营范围里。",
  fenceTitle: "覆盖围栏 · {name}",
  fenceRadiusLabel: "覆盖半径（米）",
  fenceMustBePositive: "必须大于 0 —— 0 米等于这个聚落谁也覆盖不到，而界面上看起来只是「还没配」",
  fenceImpactLabel: "圈内收货地址",
  fenceDenominator: "全库有坐标的收货地址 {n} 条。分母小的时候，「没变化」说明不了任何事",
  fenceNoCoords: "这个聚落还没标点，算不出任何圈。先补坐标，再谈半径",
  fenceImpactFailed: "影响预览没取到 —— 下面这个半径可以存，但存之前你没看到它会圈进来多少人",
  fenceConfigure: "围栏",
  toastFenceSaved: "「{name}」的覆盖半径已改为 {n} 米",
  buildingNew: "建楼",
  buildingTitle: "新建楼栋",
  buildingName: "楼栋名",
  buildingNamePlaceholder: "如：阳光里 3 幢",
  buildingAddress: "地址（可空）",
  buildingParent: "所属小区 / 园区",
  buildingParentHint: "街道从所属聚落继承，不用另填 —— 两处各填一次就会有不一致的那一天",
  buildingParentEmpty: "先选一个所属聚落",
  buildingTwoLevels: "只列顶层聚落：归属只做两层，楼底下不再挂楼",
  buildingFenceHint: "楼栋默认围栏 150 米，不是小区那个 1000 —— 一栋楼套 1000 米会把周围整片都算进来",
  toastBuildingCreated: "「{name}」已建好，挂在「{parent}」下",
  colBuyers: "买家",
  colMerchants: "在售商家",
  colGoods: "在售商品",
  kindBuilding: "楼栋",
  distSmallSample: "全平台只有 {n} 条能定位的收货地址 —— 这张表现在还不能用来做决定，任何一行的高低都不说明任何事",
  gapNoCoords: "没坐标的收货地址",
  gapNoCoordsHint: "推不出任何聚落，因此不在下面任何一行里。不是没人 —— 混进「没需求」会让人去撤一个其实有人的片区的商家",
  gapOutside: "落在所有围栏之外",
  gapOutsideHint: "有坐标、但不在任何聚落的围栏里。那儿真的有人，只是平台还没在那儿开聚落 —— 这一格是开城线索",
  gapStores: "没标点的门店",
  gapStoresHint: "自送半径对它形同虚设：商家填了三公里，实际多远的单都进得来，等他准备送货那一刻才发现送不到",
  gapClosed: "已关闭的聚落",
  gapClosedHint: "不在下面的表里，但它们的历史订单还在。撤片区之前先看这一格，别把「关过」当成「没有过」",
  gapTabAll: "全部",
  gapTabSupply: "缺供给",
  gapTabDemand: "缺需求",
  gapTabEmpty: "空聚落",
  gapTabAllHint: "开通中的全部聚落",
  gapTabSupplyHint: "有人、没商家 —— 这一格就是招商清单",
  gapTabDemandHint: "有商家、没人。先别急着撤 —— 分母小的时候几乎所有聚落都会落进这一格，那说明的是数据不够，不是那儿没人",
  gapTabEmptyHint: "既没人也没货，多半是刚开通还没运营过",
  gapGoHealth: "去看坐标缺口 ›",
  gapGoStores: "去看是哪几家店 ›",
  gapGoClosed: "去看未开城的聚落 ›",
  regionConfigure: "归属",
  regionSectionNow: "当前归属",
  regionSectionPick: "重新选择",
  regionRoot: "全国",
  regionLeafReached: "已经到街道，不用再往下选了。",
  regionNoChild: "这一级下面没有数据",
  regionDisabled: "已停用",
  regionSave: "保存归属",
  regionClear: "清空归属",
  regionSaveHint: "建议挂到街道级：挂到区县也能用，但那样「按街道覆盖」就退化成了「按区覆盖」。",
  regionSaved: "归属已更新",
  colOpened: "开城",
  ariaOpenSwitch: "{name} 开城开关",
  colRadius: "覆盖半径",
  colPickupCount: "自提点",
  colCreatedAt: "创建时间",
  colActions: "操作",
  archiveHintCommunity: "该社区下仍有自提点，请先迁移或停用",
  entityCommunity: "社区",
  entityPickup: "自提点",

  colPickupNo: "自提点编号",
  colName: "名称",
  colType: "类型",
  colCarrier: "承接商家",
  colTimes: "到货 / 营业",
  colFeeRate: "服务费费率",
  zeroFee: "零报酬",
  ariaFeeRate: "费率（万分比）",
  save: "存",
  cancel: "取消",
  colStatus: "状态",
  btnSuspend: "停用",
  btnActivate: "启用",
  btnFinishMigrate: "完成迁移",
  btnPickupApprove: "通过",
  btnPickupReject: "驳回",
  pickupApproveTitle: "通过自建点「{name}」？",
  pickupRejectTitle: "驳回自建点「{name}」",
  pickupRejectDesc: "理由会原样回给商家 —— 不写他只会原样再提一次",
  pickupNoCoords: "这个点没有坐标：买家用定位找不到它。建议先驳回，让商家在店里重新提交",
  toastPickupApproved: "已通过，该点即刻可被门店引用",
  toastPickupRejected: "已驳回",

  col30dAccept: "30 天承接",
  suspectPro: "疑似职业化",
  colFiledAt: "建档时间",
  btnPauseIntake: "暂停接单",

  dupTitle: "疑似重复：{n} 组",
  dupHint: "商家在地图上点中小区就直接建档，改名、补坐标、误挂街道都会让两条事后才撞上。撞上不报错 —— 甲选了 A、乙选了 B，买家在 B 里搜不到甲的货，两边都以为自己上架了。",
  dupReasonSameName: "同名",
  dupReasonNearby: "相距 {n} 米，名字相似",
  dupKeepLeft: "保留左边，合并右边",
  dupKeepRight: "保留右边，合并左边",
  dupConfirmTitle: "把「{from}」并进「{into}」？",
  dupConfirmBody: "被并掉的那条会关掉（历史订单仍指着它），商家的经营范围、社区货架会改到保留的那条上。这一步会改一批商家的可见范围，错了要一条条捞回来。",
  dupMerged: "已合并",
  dupEmpty: "没有疑似重复",
  readOnlyCommunityWhat: "社区开城与围栏配置",
  readOnlyCommunityNote: "不能开城、改半径或归档",
  readOnlyPickupWhat: "自提点建档与启停",
  readOnlyPickupNote: "不能启停、改费率或归档",

  /** `{n}` 是阈值次数 */
  neighborNotice:
    "近 30 天承接 ≥ {n} 次的邻里自提点（ADR-005 §F6 建议阈值）。频繁承接说明它已经不是「顺手帮邻居带一次」，而是在无证经营自提点 —— 需要人工复核后转为常驻点或暂停。",
  searchGrid: "搜索社区编号 / 名称 / 网格",
  searchPickup: "搜索自提点编号 / 名称 / 地址",
  filterOpened: "按开城状态筛选",
  filterOpenedAll: "全部开城状态",
  filterType: "按类型筛选",
  filterTypeAll: "全部类型",
  filterStatus: "按状态筛选",
  filterStatusAll: "全部状态",

  emptyGrid: "没有符合条件的社区。清空筛选，或先在城市网格里建一个社区。",
  emptyPickup: "没有符合条件的自提点。自提点是履约的落点，缺它货到了没人能核销。",
  emptyNeighbor: "当前没有触发阈值的临时自提点（近 30 天承接 ≥ {n} 次）。这是好事，不是数据缺失。",
  readOnlyRegionWhat: "裁决区划补录",
  readOnlyRegionNote: "你能看队列，但通过/驳回要「community:region:update」——通过一条会让这个村对全平台商家可见。",
  rgRoot: "全国",
  colRgNodeName: "名称",
  colRgNodeCode: "区划码",
  colRgNodeState: "状态",
  rgEnabled: "启用",
  rgDisabled: "已停用",
  rgRename: "改名",
  rgDisable: "停用",
  rgEnable: "启用",
  rgAdd: "＋ 新增下级",
  rgAddPh: "下级名称",
  rgSave: "保存",
  rgCancel: "取消",
  rgRenamed: "已改名",
  rgToggled: "已更新",
  rgCreated: "已新增",
  rgEmpty: "这一层没有区划",
  rgStreetLeaf: "街道/镇是区划的最末级 —— 村和小区是聚落，在「社区网格」里维护",
  apKindEstate: "小区",
  apKindVillage: "村",
  apNoCoords: "未带定位，且官方村码也查不到坐标 —— 通过后买家用定位找不到它。建议驳回，让商家在小区里重新提报",
  apCoordsFallback: "商家没带定位，但官方村码有坐标，通过时会自动补上：",
  regionPickNext: "选择下一级…",
  regionSuggestTitle: "按提报信息推断",
  regionSuggestAddress: "地址",
  regionSuggestCoords: "坐标",
  regionSuggestUse: "用这个",
  mapNoKey: "还没配高德 JS API key（ops-web/.env.local 的 NEXT_PUBLIC_AMAP_JS_KEY），地图不显示，不影响裁决",
  mapNoScode: "高德 JS API 还缺安全密钥（NEXT_PUBLIC_AMAP_JS_SECURITY_CODE）—— 2021-12 后申请的 key 必须配它，否则只出白框",
  mapNearbyHint: "红钉是这条提报的落点；蓝点是附近已开通的 {n} 个聚落 —— 位置挨得很近的多半是同一个小区的另一个叫法",
  mapNoNearby: "红钉是这条提报的落点。附近 2 公里内没有已开通的聚落",
  fieldApplyCoords: "提报坐标",
  apOrigin: "官方村码",
  // ── 坐标健康度（这一页是位置模块的分母）──────────────────────────
  tabHealth: "坐标健康",
  loading: "读取中…",
  statStores: "门店已标点",
  statAddresses: "收货地址有坐标",
  statCommunities: "聚落有坐标",
  storeConsequence: "没标点 = 自送半径不生效：商家以为限了几公里，实际多远的单都会进来，等他要送货才发现送不到，而那时钱已经收了",
  addressConsequence: "没坐标的地址推不出任何聚落 —— 它进不了任何片区的统计，位置分析里要单列一格，不能算成「这一带没需求」",
  communityConsequence: "没坐标的聚落谁也匹配不到，而它看起来一切正常：建档成功、列表里有、买家就是选不到",
  missingStoresTitle: "还没在地图上标点的门店",
  missingCommunitiesTitle: "还没有坐标的聚落",
  allStoresPinned: "门店都标过点了",
  colStoreName: "门店",
  colStoreNo: "门店号",
  colMerchant: "所属商家",
  colSetRadius: "他设的自送半径",
  radiusSuffix: " 米（未生效）",
  radiusUnset: "没设",
  storeAllGood: "都标过点了 —— 商家设的自送半径现在是真生效的",
  addressAllGood: "都有坐标 —— 位置分析的分母是干净的",
  communityAllGood: "都有坐标 —— 每个聚落都匹配得到",

};

const en: typeof zh = {
  applyNoValue: "—",
  colApplyName: "Community",
  colApplyMerchant: "Requested by",
  colApplyAddress: "Address",
  colApplyRegion: "Region",
  colApplyStatus: "Status",
  colApplyTime: "Submitted",
  apPending: "To verify",
  apApproved: "Community created",
  apRejected: "Rejected",
  filterApplyStatus: "Filter by status",
  filterApplyStatusAll: "All statuses",
  emptyApply: "Nothing to verify",
  secApplyWhat: "Submission",
  secApplyRegion: "Region to attach",
  secApplyReject: "Reject",
  secApplyResult: "Decision",
  fieldApplyNote: "Note",
  fieldApplyRegion: "Region code",
  fieldApplyReason: "Rejection reason",
  fieldApplyCommunity: "Created community",
  applyDupHint: "Check the address first: one community often goes by two names, and a duplicate leaves merchants unsure which to pick",
  applyRegionPlaceholder: "e.g. 330106002 (street level preferred)",
  applyRegionHint: "Without a region this community never shows up in any district-level coverage — while the screen looks perfectly fine",
  applyReasonPlaceholder: "e.g. already on the platform as “Cuiyuan No.1”, just select it",
  applyReasonHint: "Sent to the merchant verbatim. Without a reason they will simply resubmit the same thing",
  btnApplyPass: "Approve & create",
  btnApplyReject: "Reject",
  toastApplyApproved: "Approved, community created",
  toastApplyRejected: "Rejected, reason sent to the merchant",
  readOnlyApplyWhat: "decide merchant requests",
  readOnlyApplyNote: "Approving creates a new community — that is a master-data change",

  openedYes: "Launched",
  openedNo: "Not launched",

  toastOpened: "{name} is now live",
  toastClosed: "{name} is no longer live",
  toastPickupStatus: "Pickup point status updated",
  toastFeeSaved: "Fulfillment service fee updated",

  colCommunityNo: "Community no.",
  colCommunity: "Community",
  colCityGrid: "City / grid",
  colRegion: "Division",
  regionUnset: "Unassigned",
  regionUnsetNote: "A community with no division cannot be matched when a merchant selects a whole district — it can only be named one by one. The platform will not guess by name: a wrong guess raises no error, it just quietly puts this community inside someone else\u2019s service area.",
  fenceTitle: "Geofence · {name}",
  fenceRadiusLabel: "Radius (m)",
  fenceMustBePositive: "Must be greater than 0 — 0 m means this settlement covers nobody",
  fenceImpactLabel: "Addresses inside",
  fenceDenominator: "{n} addresses have coordinates platform-wide. With a small denominator, no change means little",
  fenceNoCoords: "This settlement has no coordinates yet, so no circle can be computed",
  fenceImpactFailed: "Impact preview unavailable — you can still save, but you have not seen who it will cover",
  fenceConfigure: "Geofence",
  toastFenceSaved: "Radius for {name} set to {n} m",
  buildingNew: "New building",
  buildingTitle: "New building",
  buildingName: "Building name",
  buildingNamePlaceholder: "e.g. Sunnyside Block 3",
  buildingAddress: "Address (optional)",
  buildingParent: "Parent estate / park",
  buildingParentHint: "The street is inherited from the parent — filling it twice invites divergence",
  buildingParentEmpty: "Pick a parent first",
  buildingTwoLevels: "Top-level settlements only: nesting stops at two levels",
  buildingFenceHint: "Buildings default to a 150 m geofence, not the 1000 m used for estates",
  toastBuildingCreated: "{name} created under {parent}",
  colBuyers: "Buyers",
  colMerchants: "Merchants selling",
  colGoods: "Goods on sale",
  kindBuilding: "Building",
  distSmallSample: "Only {n} addresses platform-wide can be located — this table cannot support a decision yet",
  gapNoCoords: "Addresses without coordinates",
  gapNoCoordsHint: "Cannot be attributed to any settlement, so they are in no row below. Not the same as nobody living there",
  gapOutside: "Outside every geofence",
  gapOutsideHint: "Located, but inside no settlement — people do live there; the platform has not opened one yet",
  gapStores: "Stores without coordinates",
  gapStoresHint: "Their delivery radius is inert: the merchant set 3 km, but orders from any distance get through",
  gapClosed: "Closed settlements",
  gapClosedHint: "Not in the table below, but their order history remains. Check here before withdrawing from an area",
  gapTabAll: "All",
  gapTabSupply: "No supply",
  gapTabDemand: "No demand",
  gapTabEmpty: "Empty",
  gapTabAllHint: "All open settlements",
  gapTabSupplyHint: "Buyers but no merchants — this is the recruiting list",
  gapTabDemandHint: "Merchants but no buyers. Do not withdraw yet — with a small denominator almost everything lands here",
  gapTabEmptyHint: "Neither buyers nor goods; usually just opened and not worked yet",
  gapGoHealth: "See coordinate gaps ›",
  gapGoStores: "See which stores ›",
  gapGoClosed: "See closed settlements ›",
  regionConfigure: "Division",
  regionSectionNow: "Current",
  regionSectionPick: "Choose again",
  regionRoot: "China",
  regionLeafReached: "You have reached street level; nothing further to pick.",
  regionNoChild: "Nothing under this level",
  regionDisabled: "Disabled",
  regionSave: "Save",
  regionClear: "Clear",
  regionSaveHint: "Prefer street level: a district works too, but then \u201ccover by street\u201d degrades into \u201ccover by district\u201d.",
  regionSaved: "Division updated",
  colOpened: "Launched",
  ariaOpenSwitch: "Launch toggle for {name}",
  colRadius: "Geofence radius",
  colPickupCount: "Pickup points",
  colCreatedAt: "Created at",
  colActions: "Actions",
  archiveHintCommunity: "This community still has pickup points — migrate or suspend them first",
  entityCommunity: "community",
  entityPickup: "pickup point",

  colPickupNo: "Pickup no.",
  colName: "Name",
  colType: "Type",
  colCarrier: "Host merchant",
  colTimes: "Arrival / opening hours",
  colFeeRate: "Service fee rate",
  zeroFee: "Unpaid",
  ariaFeeRate: "Rate (basis points)",
  save: "Save",
  cancel: "Cancel",
  colStatus: "Status",
  btnSuspend: "Suspend",
  btnActivate: "Activate",
  btnFinishMigrate: "Finish migration",
  btnPickupApprove: "Approve",
  btnPickupReject: "Reject",
  pickupApproveTitle: "Approve self-built point “{name}”?",
  pickupRejectTitle: "Reject self-built point “{name}”",
  pickupRejectDesc: "The reason goes back to the merchant verbatim — without one they will just resubmit the same thing",
  pickupNoCoords: "This point has no coordinates: buyers cannot find it by location. Reject and ask the merchant to resubmit from the shop",
  toastPickupApproved: "Approved — stores can reference it now",
  toastPickupRejected: "Rejected",

  col30dAccept: "Handled in 30 days",
  suspectPro: "Likely commercial",
  colFiledAt: "Registered at",
  btnPauseIntake: "Pause intake",

  dupTitle: "Possible duplicates: {n}",
  dupHint: "Merchants create settlements by tapping a map result, so renames, added coordinates or a wrong street let two rows collide after the fact. Nothing errors — one merchant picks A, another picks B, and buyers in B cannot find A's goods.",
  dupReasonSameName: "Same name",
  dupReasonNearby: "{n} m apart, similar names",
  dupKeepLeft: "Keep left, merge right",
  dupKeepRight: "Keep right, merge left",
  dupConfirmTitle: "Merge \u201c{from}\u201d into \u201c{into}\u201d?",
  dupConfirmBody: "The merged-away row is closed (past orders still point at it). Merchant service areas and community shelves move to the surviving row. This changes what a batch of merchants can reach — undoing it is row by row.",
  dupMerged: "Merged",
  dupEmpty: "No duplicates found",
  readOnlyCommunityWhat: "community launch & geofence settings",
  readOnlyCommunityNote: "cannot launch, change the radius or archive",
  readOnlyPickupWhat: "pickup point registration & activation",
  readOnlyPickupNote: "cannot activate, change the fee rate or archive",

  neighborNotice:
    "Neighbour pickup points that handled {n} or more parcels in the last 30 days (suggested threshold, ADR-005 §F6). That frequency is no longer “helping a neighbour out once” — it is running an unlicensed pickup point, and needs a human review to either convert it to a fixed point or suspend it.",
  searchGrid: "Search community no. / name / grid",
  searchPickup: "Search pickup no. / name / address",
  filterOpened: "Filter by launch status",
  filterOpenedAll: "Any launch status",
  filterType: "Filter by type",
  filterTypeAll: "All types",
  filterStatus: "Filter by status",
  filterStatusAll: "All statuses",

  emptyGrid: "No communities match these filters. Clear the filters, or create a community under a city grid first.",
  emptyPickup: "No pickup points match these filters. A pickup point is where fulfillment lands — without one, goods arrive and nobody can redeem them.",
  emptyNeighbor: "No temporary pickup point is over the threshold ({n}+ parcels in 30 days). That is good news, not missing data.",
  readOnlyRegionWhat: "decide region entries",
  readOnlyRegionNote: "You can view the queue, but approving needs community:region:update — approval makes the village visible to every merchant.",
  rgRoot: "China",
  colRgNodeName: "Name",
  colRgNodeCode: "Code",
  colRgNodeState: "State",
  rgEnabled: "Enabled",
  rgDisabled: "Disabled",
  rgRename: "Rename",
  rgDisable: "Disable",
  rgEnable: "Enable",
  rgAdd: "＋ Add child",
  rgAddPh: "Child name",
  rgSave: "Save",
  rgCancel: "Cancel",
  rgRenamed: "Renamed",
  rgToggled: "Updated",
  rgCreated: "Created",
  rgEmpty: "No regions at this level",
  rgStreetLeaf: "Streets/towns are the last region level — villages and estates are settlements, managed under Communities",
  apKindEstate: "Estate",
  apKindVillage: "Village",
  apNoCoords: "No location, and the official village code has none either — buyers will never find it by GPS. Reject and ask the merchant to resubmit on site",
  apCoordsFallback: "No location from the merchant, but the official village code has one — it will be filled in on approval:",
  regionPickNext: "Pick the next level…",
  regionSuggestTitle: "Inferred from the submission",
  regionSuggestAddress: "Address",
  regionSuggestCoords: "Coordinates",
  regionSuggestUse: "Use this",
  mapNoKey: "AMap JS API key is not set (NEXT_PUBLIC_AMAP_JS_KEY) — the map is hidden; review still works",
  mapNoScode: "AMap JS API security code is missing (NEXT_PUBLIC_AMAP_JS_SECURITY_CODE) — keys issued after 2021-12 need it, otherwise the map renders blank",
  mapNearbyHint: "Red pin: this submission. Blue dots: {n} community/ies already open nearby — very close ones are usually the same place under another name",
  mapNoNearby: "Red pin: this submission. No open communities within 2 km",
  fieldApplyCoords: "Submitted coordinates",
  apOrigin: "Official village code",
  tabHealth: "Coordinates",
  loading: "Loading…",
  statStores: "Stores pinned",
  statAddresses: "Addresses with coordinates",
  statCommunities: "Communities with coordinates",
  storeConsequence: "No pin = the delivery radius does nothing: the merchant thinks he capped it at a few km, but every order gets through — he finds out on delivery day, after the money is taken",
  addressConsequence: "An address without coordinates resolves to no community — it belongs in its own bucket, never counted as \"no demand here\"",
  communityConsequence: "A community without coordinates matches nobody, while everything looks fine: created, listed, and simply unselectable",
  missingStoresTitle: "Stores not pinned on the map yet",
  missingCommunitiesTitle: "Communities without coordinates",
  allStoresPinned: "Every store is pinned",
  colStoreName: "Store",
  colStoreNo: "Store no.",
  colMerchant: "Merchant",
  colSetRadius: "Radius they set",
  radiusSuffix: " m (inactive)",
  radiusUnset: "Not set",
  storeAllGood: "All pinned — the delivery radius merchants set is actually in force",
  addressAllGood: "All have coordinates — the denominator for location analysis is clean",
  communityAllGood: "All have coordinates — every community is matchable",

};

export const COMMUNITIES_COPY: PageCopy<typeof zh> = { zh, en };

/** 拆出去的子组件靠它接文案（与 system / stores 那两页同一个写法）。 */
export type CommunityCopy = typeof zh;
