// 素材中心文案（矩阵 P-15.1）。
import type { PageCopy } from "@/lib/use-copy";

const zh = {

  auditNotice: "命中风险词的内容不进批量通过 —— 批量 + 风险内容 = 事故，那几条必须逐条看，所以界面上根本不给它们勾选框。驳回与下架都要写原因，作者看到的就是那段话。",
  searchPost: "搜内容编号 / 标题 / 作者",
  filterPostStatus: "按内容状态筛选",
  filterPostStatusAll: "全部内容状态",
  filterRisk: "按风险词筛选",
  filterRiskAll: "全部内容",
  riskOnly: "只看命中风险词",
  riskNone: "只看未命中",
  psPending: "待审核",
  psPassed: "已通过",
  psRejected: "已驳回",
  psOffline: "已下架",
  colPostNo: "内容编号",
  colPostTitle: "标题",
  colAuthor: "作者",
  colCommunity: "社区",
  colRisk: "风险词",
  colPostStatus: "状态",
  colSku: "关联商品",
  colLikes: "点赞",
  authorUser: "用户",
  authorMerchant: "商家",
  noRisk: "未命中",
  selectAll: "全选可批量的内容",
  none: "—",
  actionAudit: "审核",
  actionView: "查看",
  btnBatchPass: "批量通过（{n}）",
  batchHint: "只有未命中风险词的待审内容可以勾选。",
  emptyPost: "没有符合条件的种草内容。用户与商家在 C/B 端发布后会进入这里排队。",
  secPostOverview: "内容概况",
  secRisk: "命中的风险词",
  riskHint: "命中风险词不等于一定违规，但必须有人逐字看过再决定 —— 极限词、医疗暗示、站外导流都在这一档。",
  secPostBody: "正文",
  secPostRemark: "审核意见",
  fieldPostRemark: "意见",
  postRemarkPlaceholder: "例：正文含「全网最低」等极限词，请修改后重新提交",
  postRemarkHint: "驳回与下架必填，原样回作者。",
  lastRemark: "上次意见：{text}",
  toastPostDecided: "已处理，意见已回作者",
  toastBatchPassed: "已通过 {n} 条",
  auditReadOnlyWhat: "种草内容审核",

  rankNotice: "算出来的榜（热销/好评/新品）不接受人工指定商品，人工榜必须自己选货 —— 两种榜的校验路径完全不同，所以人工选品区只在选了「人工榜」时才出现。榜单最多取前 {n} 名，再往下没人翻。",
  colRankName: "榜单名称",
  colRankKind: "口径",
  colRankSize: "条数",
  colManualSkus: "人工选品",
  colRankStatus: "状态",
  colUpdatedAt: "最近修改",
  rkSales: "热销榜",
  rkRating: "好评榜",
  rkNew: "新品榜",
  rkManual: "人工榜",
  topN: "前 {n} 名",
  pickedSkus: "已选 {n} 个",
  autoComputed: "按数据自动计算",
  rankOn: "已上线",
  rankOff: "未上线",
  actionNewRank: "新建榜单",
  actionEditRank: "编辑",
  actionRankOn: "上线",
  actionRankOff: "下线",
  emptyRank: "还没有榜单。榜单是首页货架的填充物 —— 没有榜单，首页就只剩搜索框。",
  newRankTitle: "新建榜单",
  editRankTitle: "编辑 {name}",
  secRankBasic: "基本信息",
  secManualSkus: "人工选品",
  kindHint: "热销/好评/新品由数据算出；人工榜由你指定商品，顺序即榜位。",
  manualSkusHint: "已选 {n} 个，不能超过榜单条数 {size}。只列在售商品 —— 下架商品进了榜，用户点进去是空页。",
  btnSaveRank: "保存榜单",
  toastRankSaved: "榜单已保存",
  toastRankToggled: "榜单状态已更新",

  secQuestions: "商品问答",
  qaNotice: "已回答的问题不能直接改答案：要改先隐藏再重新回答，让改动这件事本身留下痕迹。隐藏也要写原因，否则用户来问时没人说得清。",
  searchQuestion: "搜提问编号 / 商品 / 内容",
  filterQStatus: "按提问状态筛选",
  filterQStatusAll: "全部提问状态",
  qsPending: "待回答",
  qsAnswered: "已回答",
  qsHidden: "已隐藏",
  colQuestionNo: "提问编号",
  colQuestion: "提问",
  colAnswer: "回答",
  colQStatus: "状态",
  actionAnswer: "回答",
  emptyQuestion: "没有符合条件的提问。用户在商品详情页提问后会出现在这里。",
  answerTitle: "提问 {no}",
  secQuestion: "提问",
  secAnswer: "回答",
  secHide: "或者隐藏这条提问",
  answerPlaceholder: "例：当天清晨采摘，下午到自提点。",
  answerHint: "回答会显示在商品详情页，署名为平台客服。",
  fieldHideReason: "隐藏原因",
  hideReasonPlaceholder: "例：内容为站外导流",
  btnAnswer: "提交回答",
  btnHide: "隐藏",
  toastAnswered: "已回答",
  toastHidden: "已隐藏，原因已留痕",
  rankReadOnlyWhat: "榜单与问答",

  kindCopy: "文案",
  kindImage: "图片",
  kindPoster: "海报",
  kindVideo: "短视频",

  scopeAll: "全部商家",
  scopeAllHint: "通用素材，所有入驻商家都能下载",
  scopeCommunity: "指定社区",
  scopeCommunityHint: "如某社区开城专用海报",
  scopeMerchant: "指定商家",
  scopeMerchantHint: "如为某商家定制的短视频",

  toastSaved: "素材已保存",
  toastPublished: "已更新上架状态",

  colNo: "素材号",
  colTitle: "标题",
  colKind: "类型",
  colContent: "内容",
  colScope: "可见范围",
  colDownloads: "下载",
  colCreatedAt: "创建时间",
  colPublished: "上架",
  colActions: "操作",
  actionEdit: "编辑",
  /** `{title}` 是素材标题 */
  ariaPublish: "{title} 上架",

  readOnlyWhat: "素材维护",
  readOnlyNote: "不能新增、编辑或上下架",
  notice:
    "素材是给商家用的：他们下载后发到自己的顾客群里。所以「投给谁」必须明确 —— 范围选了社区或商家却不填对象，这份素材谁都看不到，但列表里显示得好好的。",
  searchPlaceholder: "搜索素材号 / 标题 / 内容",
  addLabel: "新增素材",
  filterKind: "按类型筛选",
  filterKindAll: "全部类型",
  filterScope: "按范围筛选",
  filterScopeAll: "全部范围",
  empty: "素材库是空的。商家最需要的是「开团文案模板」——他们要发到顾客群里。",

  drawerEdit: "编辑素材",
  drawerNew: "新增素材",
  save: "保存",
  fieldTitle: "标题",
  fieldKind: "类型",
  fieldContent: "内容",
  contentPlaceholderCopy: "文案正文，可用 {商品名} {价格} 占位",
  contentPlaceholderFile: "文件地址（接后端后改为上传）",
  fieldScope: "可见范围",
  fieldCommunityNo: "社区编号",
  fieldMerchantNo: "商家编号",
  refsPlaceholderCommunity: "如 C001、C003",
  refsPlaceholderMerchant: "如 M903",
  refsHint: "多个用逗号分隔。留空会被服务端拒绝。",
};

const en: typeof zh = {

  auditNotice: "Posts that hit a risk term stay out of bulk approval — bulk plus risky content is how incidents happen, so those rows get no checkbox at all and have to be read one by one. Rejections and takedowns both need a reason; the author sees exactly that text.",
  searchPost: "Search post no. / title / author",
  filterPostStatus: "Filter by post state",
  filterPostStatusAll: "All post states",
  filterRisk: "Filter by risk terms",
  filterRiskAll: "All posts",
  riskOnly: "Risk terms hit",
  riskNone: "No risk terms",
  psPending: "Awaiting review",
  psPassed: "Published",
  psRejected: "Rejected",
  psOffline: "Taken down",
  colPostNo: "Post no.",
  colPostTitle: "Title",
  colAuthor: "Author",
  colCommunity: "Community",
  colRisk: "Risk terms",
  colPostStatus: "State",
  colSku: "Linked item",
  colLikes: "Likes",
  authorUser: "shopper",
  authorMerchant: "merchant",
  noRisk: "None",
  selectAll: "Select all bulk-eligible posts",
  none: "—",
  actionAudit: "Review",
  actionView: "View",
  btnBatchPass: "Approve selected ({n})",
  batchHint: "Only pending posts with no risk terms can be selected.",
  emptyPost: "No posts match. Anything shoppers and merchants publish queues up here.",
  secPostOverview: "Post overview",
  secRisk: "Risk terms hit",
  riskHint: "A hit does not mean a violation, but someone has to read it word by word first — superlatives, health claims and off-platform contact all land in this bucket.",
  secPostBody: "Body",
  secPostRemark: "Review note",
  fieldPostRemark: "Note",
  postRemarkPlaceholder: "e.g. The body uses absolute claims like “lowest anywhere”; revise and resubmit",
  postRemarkHint: "Required for rejection and takedown; the author sees it verbatim.",
  lastRemark: "Previous note: {text}",
  toastPostDecided: "Handled — the note went back to the author",
  toastBatchPassed: "{n} posts approved",
  auditReadOnlyWhat: "post moderation",

  rankNotice: "Computed rankings (best sellers, top rated, new arrivals) take no hand-picked items, and a manual ranking has to pick its own — the two validate along completely different paths, so the picker only appears once you choose “manual”. A ranking tops out at {n} places; nobody scrolls past that.",
  colRankName: "Ranking",
  colRankKind: "Basis",
  colRankSize: "Places",
  colManualSkus: "Hand-picked",
  colRankStatus: "State",
  colUpdatedAt: "Last changed",
  rkSales: "Best sellers",
  rkRating: "Top rated",
  rkNew: "New arrivals",
  rkManual: "Hand-picked",
  topN: "Top {n}",
  pickedSkus: "{n} picked",
  autoComputed: "Computed from data",
  rankOn: "Live",
  rankOff: "Not live",
  actionNewRank: "New ranking",
  actionEditRank: "Edit",
  actionRankOn: "Go live",
  actionRankOff: "Take down",
  emptyRank: "No rankings yet. Rankings are what fills the home shelf — without them the home page is just a search box.",
  newRankTitle: "New ranking",
  editRankTitle: "Edit {name}",
  secRankBasic: "Basics",
  secManualSkus: "Hand-picked items",
  kindHint: "Best sellers, top rated and new arrivals come from data; a hand-picked ranking takes the items you choose, in the order you choose them.",
  manualSkusHint: "{n} picked, and it cannot exceed the {size} places. Only items on sale are listed — a delisted item in a ranking leads to an empty page.",
  btnSaveRank: "Save ranking",
  toastRankSaved: "Ranking saved",
  toastRankToggled: "Ranking state updated",

  secQuestions: "Product Q&A",
  qaNotice: "An answered question cannot be edited in place: hide it and answer again, so the change itself leaves a trace. Hiding needs a reason too, or nobody can explain it when the shopper asks.",
  searchQuestion: "Search question no. / item / text",
  filterQStatus: "Filter by question state",
  filterQStatusAll: "All question states",
  qsPending: "Awaiting answer",
  qsAnswered: "Answered",
  qsHidden: "Hidden",
  colQuestionNo: "Question no.",
  colQuestion: "Question",
  colAnswer: "Answer",
  colQStatus: "State",
  actionAnswer: "Answer",
  emptyQuestion: "No questions match. Anything asked on a product page lands here.",
  answerTitle: "Question {no}",
  secQuestion: "Question",
  secAnswer: "Answer",
  secHide: "Or hide this question",
  answerPlaceholder: "e.g. Picked at dawn the same day and at the pickup point by afternoon.",
  answerHint: "The answer shows on the product page, attributed to platform support.",
  fieldHideReason: "Reason for hiding",
  hideReasonPlaceholder: "e.g. Pushing shoppers to contact off-platform",
  btnAnswer: "Submit answer",
  btnHide: "Hide",
  toastAnswered: "Answered",
  toastHidden: "Hidden — the reason is recorded",
  rankReadOnlyWhat: "rankings and Q&A",

  kindCopy: "Copy",
  kindImage: "Image",
  kindPoster: "Poster",
  kindVideo: "Short video",

  scopeAll: "All merchants",
  scopeAllHint: "Generic material — every onboarded merchant can download it",
  scopeCommunity: "Selected communities",
  scopeCommunityHint: "e.g. a launch poster for one community",
  scopeMerchant: "Selected merchants",
  scopeMerchantHint: "e.g. a short video made for one merchant",

  toastSaved: "Material saved",
  toastPublished: "Listing status updated",

  colNo: "Material no.",
  colTitle: "Title",
  colKind: "Type",
  colContent: "Content",
  colScope: "Visible to",
  colDownloads: "Downloads",
  colCreatedAt: "Created at",
  colPublished: "Listed",
  colActions: "Actions",
  actionEdit: "Edit",
  ariaPublish: "List {title}",

  readOnlyWhat: "material maintenance",
  readOnlyNote: "cannot create, edit, list or unlist materials",
  notice:
    "Materials are for merchants to download and forward to their own customer groups, so “who gets it” must be explicit — pick Community or Merchant scope without naming any, and nobody can see the material even though it looks fine in this list.",
  searchPlaceholder: "Search material no. / title / content",
  addLabel: "New material",
  filterKind: "Filter by type",
  filterKindAll: "All types",
  filterScope: "Filter by scope",
  filterScopeAll: "All scopes",
  empty: "The material library is empty. What merchants need most is a group-buy copy template — that is what they paste into customer groups.",

  drawerEdit: "Edit material",
  drawerNew: "New material",
  save: "Save",
  fieldTitle: "Title",
  fieldKind: "Type",
  fieldContent: "Content",
  contentPlaceholderCopy: "Body text; {product} and {price} work as placeholders",
  contentPlaceholderFile: "File URL (switches to upload once the backend is wired up)",
  fieldScope: "Visible to",
  fieldCommunityNo: "Community no.",
  fieldMerchantNo: "Merchant no.",
  refsPlaceholderCommunity: "e.g. C001, C003",
  refsPlaceholderMerchant: "e.g. M903",
  refsHint: "Separate multiple with commas. Leaving it blank is rejected by the server.",
};

export const CONTENTS_COPY: PageCopy<typeof zh> = { zh, en };

/** 拆出去的 tab 组件靠它接文案。 */
export type ContentsCopy = typeof zh;
