// 商家治理文案（矩阵 P-11.1）。
import type { PageCopy } from "@/lib/use-copy";

const zh = {
  tabAudit: "入驻审核",
  // ── 入驻审核（申请单模型，已接真后端）──
  applyColIndustry: "行业",
  applyColSubject: "主体类型",
  applyColCategory: "主营类目",
  applyColScope: "服务范围",
  applyScopeEmpty: "未设置",
  applySearchPh: "店名 / 联系人 / 手机号",
  applyFilterTodo: "待办（待审+审核中）",
  applyActionAccept: "受理",
  applyActionApprove: "通过",
  applyActionReject: "驳回",
  applySectionInfo: "申请信息",
  applySectionLicenses: "资质",
  applySectionDecide: "审核",
  applyAsPickup: "愿意承接自提点",
  applyScopeNotice: "通过前必须确定服务范围：商家可以不填，但空着上架后对谁都不可见，而且不会报错。",
  applyScopeLabel: "服务范围",
  applyScopeCommunity: "仅指定小区",
  applyScopeCity: "整个城市",
  applyScopePlatform: "全平台",
  applyCommunities: "覆盖小区",
  applyScopeNeedCommunity: "按小区经营至少要选一个，否则买家一个也看不到这家店",
  applyReasonLabel: "审核意见",
  applyReasonPh: "驳回必填 —— 不写理由对方只能猜着改",
  toastAccepted: "已受理，商家能看到有人在跟进了",
  toastApproved: "已通过，商家主体已创建",
  toastRejected: "已驳回，理由已发给商家",
  tabList: "商家档案",
  tabCategories: "类目授权",
  tabVerify: "认证标管理",
  tabCredit: "信用档案",
  tabBan: "违规处置与封禁",

  colAuthCodes: "已授类目",
  colQualifications: "已上传资质",
  colVerified: "认证标",
  colBreach: "毁约次数",
  colSettleReady: "分账报备",
  colViolationNo: "记录号",
  colViolationType: "违规类型",
  colViolationAction: "处置",
  colDetail: "事实与证据",
  colAt: "时间",
  colOperator: "操作人",
  breachTimes: "{n} 次",
  noQualification: "未上传",
  badgeVerified: "已认证",
  badgeUnverified: "未认证",
  loading: "加载中…",
  emptyApproved: "没有已通过审核的商家。类目授权与认证标都只对过审商家开放 —— 没过审就授权等于提前放行。",

  categoryNotice: "按授权码授权，不是按类目节点：类目树会重构，而「能不能卖菜」这件事不会。撤销授权前要先把该类目下的在售商品下架，否则架上还挂着那类商品，谁也说不清它算不算违规。",
  actionGrant: "配置授权",
  grantTitle: "{name} 的类目授权",
  secQualification: "已上传资质",
  qualificationHint: "资质由商家在 B 端上传、平台在入驻审核时核验。这一页只用它做授权门槛，不在这里改。",
  secAuthCodes: "授权范围",
  needQualification: "需要「{q}」",
  needQualificationMissing: "缺「{q}」，无法授权",
  authCodesHint: "不能全部取消：撤空之后商家会静默失去上架能力。要停止经营请走封禁或归档，那是明示的动作。",
  secAuthReason: "变更原因",
  fieldReason: "原因",
  authReasonPlaceholder: "例：商家补交食品经营许可证，扩类目至水果",
  btnSaveAuth: "保存授权",
  toastAuthSaved: "授权范围已更新",

  verifyNotice: "认证标是平台给用户看的背书。只有已过审、且毁约次数未达 {n} 次的商家能拿标 —— 挂在一个正在毁约的商家身上，赔的是平台的信用。",
  actionGrantVerify: "授予认证标",
  actionRevokeVerify: "撤销认证标",
  confirmGrantTitle: "授予认证标？",
  confirmGrantDesc: "「{name}」将在 C 端商品与店铺页显示认证标识。",
  confirmRevokeTitle: "撤销认证标？",
  confirmRevokeDesc: "「{name}」的认证标识会立刻从 C 端消失。",

  creditNotice: "信用档案是只读的 —— 它是处置的依据，不是处置本身。毁约次数达 {n} 次会同时触发两条既有规则：不能拿认证标（P-11.1.2）、报价受限（ADR-003）。",
  actionCredit: "查看档案",
  creditTitle: "{name} 的信用档案",
  secBrief: "商家概况",
  secViolations: "违规记录",
  noViolation: "这家商家没有违规记录。",

  banNotice: "处置要写清事实与证据出处 —— 没有事实的处置在申诉时站不住。只有「毁约」计入毁约次数：别的违规也计的话，报价受限那条阈值就失去意义了。",
  filterViolationType: "按违规类型筛选",
  filterViolationTypeAll: "全部违规类型",
  vtFake: "售假",
  vtBreach: "毁约",
  vtPrice: "价格欺诈",
  vtService: "服务问题",
  vaWarn: "警告",
  vaLimit: "限制经营",
  vaSuspend: "封禁",
  btnRecordFor: "处置 {name}",
  secBanned: "当前封禁中",
  actionUnban: "解封",
  unbanRemark: "整改完成，恢复经营",
  recordTitle: "处置 {name}",
  secViolationForm: "违规与处置",
  typeHint: "只有「毁约」计入毁约次数，累计 {n} 次会触发认证标与报价限制。",
  detailPlaceholder: "例：连续 2 次成团后不发货，工单 #2026-0712 / #2026-0718",
  detailHint: "这段文字会进商家的信用档案，申诉时也以它为准。",
  btnRecordViolation: "记录并执行处置",
  emptyViolation: "没有违规记录。这是好事 —— 有处置时会出现在这里，并同时进对应商家的信用档案。",
  toastViolationRecorded: "已记录并执行处置",
  toastUnbanned: "已解封，商家恢复经营",
  authorizeReadOnlyWhat: "类目授权与认证标",
  banReadOnlyWhat: "违规处置与封禁",

  tierPersonal: "个人",
  tierIndividual: "个体户",
  tierCompany: "企业",

  readOnlyWhat: "商家入驻审核",
  readOnlyNote: "不能通过、驳回或归档商家",
  searchPlaceholder: "搜索商家编号 / 名称 / 联系人",
  filterStatus: "按状态筛选",
  filterStatusAll: "全部状态",
  filterTier: "按主体筛选",
  filterTierAll: "全部主体",
  empty: "没有符合条件的商家。换个状态筛选，或让 BD 先去拉一家店入驻。",

  colNo: "商家编号",
  colName: "商家名称",
  colTier: "主体",
  colCommunity: "归属社区",
  communityRequired: "通过前必须选择覆盖社区 —— 不选的话买家搜不到这家店",
  colContact: "联系人",
  colStatus: "状态",
  colSettleAccount: "分账账户",
  colCreatedAt: "提交时间",
  colActions: "操作",
  actionView: "查看",

  settleReady: "已报备",
  settleNotReady: "未报备",
  fieldPickupIntent: "承接自提点",
  pickupWanted: "申请人愿意承接（需另行建点）",
  pickupNo: "否",

  entity: "商家",
  toastStatusSaved: "已更新审核状态",
  toastVerifyGranted: "已授予认证标",
  toastVerifyRevoked: "已撤销认证标",

  btnStartReview: "开始审核",
  btnReject: "驳回并要求补交",
  btnApprove: "通过",
  btnRevokeVerify: "撤销认证标",
  btnGrantVerify: "授予认证标",

  fieldAuditStatus: "审核状态",
  fieldTier: "主体类型",
  fieldPhone: "联系电话",
  fieldBreach: "毁约次数",
  fieldCategories: "经营类目",
  fieldRemark: "审核意见",
  remarkPlaceholder: "驳回时必须写清补交项，商家在 B 端看到的就是这段话",
};

const en: typeof zh = {
  tabAudit: "Onboarding review",
  applyColIndustry: "Industry",
  applyColSubject: "Legal form",
  applyColCategory: "Category",
  applyColScope: "Service area",
  applyScopeEmpty: "Not set",
  applySearchPh: "Shop / contact / phone",
  applyFilterTodo: "To do (pending + reviewing)",
  applyActionAccept: "Accept",
  applyActionApprove: "Approve",
  applyActionReject: "Reject",
  applySectionInfo: "Application",
  applySectionLicenses: "Documents",
  applySectionDecide: "Decision",
  applyAsPickup: "Willing to host a pickup point",
  applyScopeNotice: "Set the service area before approving. Merchants may leave it blank, but an empty area means nobody can see the shop — and nothing reports it.",
  applyScopeLabel: "Service area",
  applyScopeCommunity: "Selected communities",
  applyScopeCity: "Whole city",
  applyScopePlatform: "Platform-wide",
  applyCommunities: "Communities covered",
  applyScopeNeedCommunity: "Pick at least one community, otherwise no buyer can see this shop",
  applyReasonLabel: "Decision note",
  applyReasonPh: "Required when rejecting — without a reason they can only guess",
  toastAccepted: "Accepted — the merchant can see someone is on it",
  toastApproved: "Approved — the merchant entity has been created",
  toastRejected: "Rejected — the reason has been sent to the merchant",
  tabList: "Merchant profiles",
  tabCategories: "Category permits",
  tabVerify: "Verification badges",
  tabCredit: "Credit records",
  tabBan: "Penalties & suspensions",

  colAuthCodes: "Granted categories",
  colQualifications: "Uploaded credentials",
  colVerified: "Verified badge",
  colBreach: "Breaches",
  colSettleReady: "Settlement account",
  colViolationNo: "Record no.",
  colViolationType: "Violation",
  colViolationAction: "Action",
  colDetail: "Facts and evidence",
  colAt: "Time",
  colOperator: "Operator",
  breachTimes: "{n}",
  noQualification: "None uploaded",
  badgeVerified: "Verified",
  badgeUnverified: "Not verified",
  loading: "Loading…",
  emptyApproved: "No approved merchants. Category permissions and verified badges are open to approved merchants only — granting before approval lets them through early.",

  categoryNotice: "Permissions are granted by code, not by category node: the category tree gets restructured, whereas “may they sell vegetables” does not. Take a category’s live listings down before revoking it, or the shelf still carries goods nobody can say are allowed.",
  actionGrant: "Edit permissions",
  grantTitle: "Category permissions for {name}",
  secQualification: "Uploaded credentials",
  qualificationHint: "Merchants upload credentials in the B-end app and the platform verifies them at onboarding. This page only uses them as a gate; it does not edit them.",
  secAuthCodes: "Granted scope",
  needQualification: "Requires “{q}”",
  needQualificationMissing: "Missing “{q}” — cannot grant",
  authCodesHint: "You cannot clear every one: the merchant would silently lose the ability to list anything. To stop them trading, ban or archive them — that is the explicit action.",
  secAuthReason: "Why change it",
  fieldReason: "Reason",
  authReasonPlaceholder: "e.g. Food licence resubmitted; extending scope to fruit",
  btnSaveAuth: "Save permissions",
  toastAuthSaved: "Granted scope updated",

  verifyNotice: "The verified badge is the platform’s endorsement to shoppers. Only approved merchants under {n} breaches can hold one — on a merchant who is currently defaulting, it is the platform’s credibility that pays.",
  actionGrantVerify: "Grant badge",
  actionRevokeVerify: "Revoke badge",
  confirmGrantTitle: "Grant the verified badge?",
  confirmGrantDesc: "“{name}” will show the verified mark on listings and its storefront.",
  confirmRevokeTitle: "Revoke the verified badge?",
  confirmRevokeDesc: "The verified mark disappears from the shopper app immediately for “{name}”.",

  creditNotice: "Credit records are read-only — they are the basis for action, not the action. Hitting {n} breaches trips two existing rules at once: no verified badge (P-11.1.2) and restricted quoting (ADR-003).",
  actionCredit: "View record",
  creditTitle: "Credit record for {name}",
  secBrief: "Merchant overview",
  secViolations: "Violations",
  noViolation: "This merchant has no violations on record.",

  banNotice: "State the facts and where the evidence sits — an action with no facts does not hold up on appeal. Only “breach of contract” counts toward the breach tally: count everything and the quoting threshold stops meaning anything.",
  filterViolationType: "Filter by violation",
  filterViolationTypeAll: "All violations",
  vtFake: "Counterfeit goods",
  vtBreach: "Breach of contract",
  vtPrice: "Price fraud",
  vtService: "Service failure",
  vaWarn: "Warning",
  vaLimit: "Trading restricted",
  vaSuspend: "Banned",
  btnRecordFor: "Act on {name}",
  secBanned: "Currently banned",
  actionUnban: "Lift ban",
  unbanRemark: "Remediation complete; trading resumed",
  recordTitle: "Act on {name}",
  secViolationForm: "Violation and action",
  typeHint: "Only “breach of contract” adds to the tally; {n} of them trip the badge and quoting limits.",
  detailPlaceholder: "e.g. Failed to ship two group buys, tickets #2026-0712 / #2026-0718",
  detailHint: "This text goes into the merchant’s credit record and is what an appeal is judged against.",
  btnRecordViolation: "Record and apply",
  emptyViolation: "No violations on record. That is a good thing — actions show up here and in the merchant’s credit record at the same time.",
  toastViolationRecorded: "Recorded and applied",
  toastUnbanned: "Ban lifted; the merchant may trade again",
  authorizeReadOnlyWhat: "category permissions and verified badges",
  banReadOnlyWhat: "violation handling and bans",

  tierPersonal: "Individual",
  tierIndividual: "Sole trader",
  tierCompany: "Company",

  readOnlyWhat: "merchant onboarding review",
  readOnlyNote: "cannot approve, reject or archive merchants",
  searchPlaceholder: "Search merchant no. / name / contact",
  filterStatus: "Filter by status",
  filterStatusAll: "All statuses",
  filterTier: "Filter by entity type",
  filterTierAll: "All entity types",
  empty: "No merchants match these filters. Try another status, or ask BD to onboard a store first.",

  colNo: "Merchant no.",
  colName: "Merchant name",
  colTier: "Entity",
  colCommunity: "Community",
  communityRequired: "Pick at least one community before approving — otherwise buyers cannot find this shop",
  colContact: "Contact",
  colStatus: "Status",
  colSettleAccount: "Payout account",
  colCreatedAt: "Submitted at",
  colActions: "Actions",
  actionView: "View",

  settleReady: "Registered",
  settleNotReady: "Not registered",
  fieldPickupIntent: "Pickup point",
  pickupWanted: "Willing to host (point set up separately)",
  pickupNo: "No",

  entity: "merchant",
  toastStatusSaved: "Review status updated",
  toastVerifyGranted: "Verification badge granted",
  toastVerifyRevoked: "Verification badge revoked",

  btnStartReview: "Start review",
  btnReject: "Reject & request resubmission",
  btnApprove: "Approve",
  btnRevokeVerify: "Revoke badge",
  btnGrantVerify: "Grant badge",

  fieldAuditStatus: "Review status",
  fieldTier: "Entity type",
  fieldPhone: "Phone",
  fieldBreach: "Breaches",
  fieldCategories: "Categories",
  fieldRemark: "Review note",
  remarkPlaceholder: "When rejecting, spell out what must be resubmitted — the merchant sees this text verbatim in the B-end app",
};

export const MERCHANTS_COPY: PageCopy<typeof zh> = { zh, en };

/** 拆出去的 tab 组件靠它接文案。 */
export type MerchantsCopy = typeof zh;
