// 商家治理文案（矩阵 P-11.1）。
import type { PageCopy } from "@/lib/use-copy";

const zh = {
  // ── 入驻审核（申请单模型，已接真后端）──
  applyColIndustry: "行业",
  applyColSubject: "主体类型",
  applyColCategory: "主营类目",
  applyColScope: "服务范围",
  applyScopeEmpty: "未设置",
  applySearchPh: "店名 / 联系人 / 手机号",
  applyFilterTodo: "待办（待审+审核中）",
  applyActionAccept: "受理",
  applyActionApprove: "通过",
  applyActionReject: "驳回",
  applySectionInfo: "申请信息",
  applySectionLicenses: "资质",
  applySectionDecide: "审核",
  applyAsPickup: "愿意承接自提点",
  applyScopeNotice: "通过前必须确定服务范围：商家可以不填，但空着上架后对谁都不可见，而且不会报错。",
  applyScopeLabel: "服务范围",
  applyScopeCommunity: "仅指定小区",
  applyScopeCity: "整个城市",
  applyScopePlatform: "全平台",
  applyCommunities: "覆盖小区",
  applyScopeNeedCommunity: "按小区经营至少要选一个，否则买家一个也看不到这家店",
  applyReasonLabel: "审核意见",
  applyReasonPh: "驳回必填 —— 不写理由对方只能猜着改",
  toastAccepted: "已受理，商家能看到有人在跟进了",
  toastApproved: "已通过，商家主体已创建",
  toastRejected: "已驳回，理由已发给商家",
  adNotice:
    "平台**无仓、不碰货**，「自营」只是资质代持的外壳 —— 最弱一档（小微）没有「入平台仓让平台验货」这条出路。平台在法律上是销售主体、承担全部产品责任却没有货物控制手段，这个缺口只能用准入和钱去补：**保证金 / 限品类 / 限额三样必须同时生效**，任何一样调成 0，另外两样都会失效。",
  adPolicyTitle: "准入策略（按主体档位）",
  adPolicyHint: "策略挂档位不挂商户：三档三行，改规则改一行。三档就是小微 / 个体户 / 企业，不再增删。",
  adColForm: "主体档位",
  adColDeposit: "应缴保证金",
  adColSingle: "单笔限额",
  adColDaily: "日累计限额",
  adColBanQualified: "需资质品类",
  adColRemark: "说明",
  adFormMicro: "小微",
  adFormIndividual: "个体工商户",
  adFormEnterprise: "企业",
  adFree: "免缴",
  adUnlimited: "不限",
  adBanned: "禁售",
  adAllowed: "可售",
  adSearchPlaceholder: "输入商家编号查保证金",
  adSearch: "查询",
  adDepositTitle: "保证金账户 · {no}",
  adPaid: "实缴",
  adFrozen: "冻结中",
  adAvailable: "可用",
  adRequired: "应缴",
  adSufficient: "保证金充足，可正常上架。",
  adInsufficient: "可用余额低于应缴，该商家不能上架。判定用的是可用而非实缴 —— 冻结中的钱不能同时用来撑准入。",
  adColTxnType: "变动类型",
  adColAmount: "变动额",
  adColBalanceAfter: "变动后实缴",
  adColReason: "原因",
  adColOperator: "操作人",
  adColTime: "时间",
  adFieldAmount: "金额（分）",
  adFieldReason: "原因",
  adAddTxn: "记一笔",
  adToastTxnAdded: "已记录保证金变动",
  adTxnTitle: "保证金流水",
  adTxnHint: "只有余额字段的账户是不可审计的：出争议时说不清这笔钱什么时候少的、谁扣的。冻结动的是冻结额不是实缴 —— 理赔不成立时要能还原「本来缴了多少」。",
  adTxnPay: "缴纳",
  adTxnRefund: "退还",
  adTxnFreeze: "冻结",
  adTxnUnfreeze: "解冻",
  adTxnDeduct: "扣划",

  // ── 无照 × 自营（税务敞口）──────────────────────────────
  colFundsMode: "资金路径",
  fundsAggregated: "归集（平台收款）",
  fundsDirect: "直连（商家收款）",
  fundsModeTitle: "资金路径",
  fundsModeHint: "钱先进谁的账户。**能走哪条由主体档位决定** —— 无照主体开不出进项票，平台按全额确认收入而成本不可税前扣除，所以禁归集；自产农产品除外。与「经营模式」是两件事：那个说谁是销售主体。",
  fundsModeChanged: "资金路径已更新",
  applySectionRawFiles: "其他上传文件",
  applyRawFilesHint: "旧版上传，只有图片没有类型与有效期 —— 不会转存为资质记录",
  applyQualForever: "长期有效",
  qualBUSINESS_LICENSE: "营业执照",
  qualFOOD_PERMIT: "食品经营许可证",
  qualFOOD_WORKSHOP: "食品小作坊登记证",
  qualOTHER: "其他",
  qualTitle: "已登记资质",
  qualHint: "上架时的「资质过期」「类目授权」两个闸门读的就是这里 —— 空着等于闸门不生效",
  qualColType: "类型",
  qualColName: "证件名",
  qualColNumber: "证件号",
  qualColExpire: "有效期至",
  qualColStatus: "状态",
  qualColActions: "操作",
  qualRevoke: "撤销",
  qualRevoked: "已撤销",
  qualRevokeConfirm: "撤销后该证不再参与上架校验。不会物理删除 —— 「当初有没有这张证」仍可查。",
  qualEmpty: "尚未登记任何资质",
  qualStatusVALID: "有效",
  qualStatusEXPIRED: "已过期",
  qualStatusREVOKED: "已撤销",
  mrTitle: "无执照主体的自营门店",
  mrDesc: "自营下平台是销售方，需要供应商的进项发票才能列支成本",
  mrNoLicense: "无营业执照",
  mrColMerchant: "商家主体",
  mrColLegalForm: "主体资格",
  mrColStore: "门店",
  mrColBills: "已结算单数",
  mrColExposure: "累计商家实得",
  mrNotTraded: "尚未成交",
  mrEmpty: "没有无执照主体挂在自营门店上",
  mrWarning:
    "这些门店的经营主体没有营业执照，而门店按自营结算 —— 平台是销售方，"
    + "需取得进项发票才能列支成本。无票的支出不得在企业所得税前扣除，"
    + "等于账面上凭空多出等额利润。处置方式请与财务确认。",
  mrSummary: "共 {stores} 家门店，其中 {traded} 家已产生成交，累计 {amount}。",
  adQuotaTitle: "收款额度",
  adQuotaHint: "小微收款号有单日/单笔的通道额度，超过就收不进钱 —— 订单会在支付这一步失败，而商家看到的只是「支付失败」。0 = 未设置（不拦），不是「额度为零」；填小了会把正常商家的货全拦下来，所以阈值要由服务商确认后再填。已用量是支付累加出来的事实，运营改不了。",
  adQuotaNoAccount: "这家还没有收款号 —— 要先走进件，不是把额度调大。",
  adColPayAccount: "收款号",
  adEntityLevel: "主体级（默认）",
  adColChannel: "通道",
  adColApplyStatus: "进件状态",
  adColQuotaLimit: "上限",
  adColQuotaUsed: "已用",
  adQuotaUnset: "未设置（不拦）",
  adQuotaSet: "设置额度",
  adQuotaFieldLimit: "上限（元，0 = 取消限制）",
  adToastQuotaSaved: "额度已保存",
  adModeTitle: "门店经营模式",
  adModeHint: "只对新单生效 —— 结算单生成时已快照经营模式，改它不会修正历史账。自营意味着平台是销售主体，这个身份不能由商家自己勾选，所以只开在运营端。",
  adColStore: "门店",
  adColMode: "经营模式",
  adColPayMerchant: "收款号",
  adColAction: "操作",
  adModeSelfOperated: "自营",
  adModeThirdParty: "第三方",
  adModeUnset: "未设置",
  adNoPayAccount: "无",
  adNoPayAccountHint: "该门店没有可用收款账户，切第三方后钱会卡在平台侧下不去",
  adSwitchSelfOperated: "切自营",
  adSwitchThirdParty: "切第三方",
  adToastModeChanged: "经营模式已更新（仅对新单生效）",
  colLegalForm: "主体档位",
  formMicro: "自然人",
  formIndividual: "个体户",
  formEnterprise: "企业",
  formUnknown: "未知",

  colAuthCodes: "已授类目",
  colQualifications: "已上传资质",
  colVerified: "认证标",
  colBreach: "毁约次数",
  colSettleReady: "分账报备",
  colViolationNo: "记录号",
  colViolationType: "违规类型",
  colViolationAction: "处置",
  colDetail: "事实与证据",
  colAt: "时间",
  colOperator: "操作人",
  breachTimes: "{n} 次",
  noQualification: "未上传",
  badgeVerified: "已认证",
  badgeUnverified: "未认证",
  loading: "加载中…",
  emptyApproved: "没有已通过审核的商家。类目授权与认证标都只对过审商家开放 —— 没过审就授权等于提前放行。",

  categoryNotice: "按授权码授权，不是按类目节点：类目树会重构，而「能不能卖菜」这件事不会。撤销会即时生效，该类目下的在架商品下次上架将被拒 —— 保存前会先告诉你影响多少件。",
  actionGrant: "配置授权",
  grantTitle: "{name} 的类目授权",
  secQualification: "已上传资质",
  qualificationHint: "资质由商家在 B 端上传、平台在入驻审核时核验。这一页只用它做授权门槛，不在这里改。",
  grantByQual: "按已传的证勾选",
  grantByQualHint: "只勾选，不保存 —— 授权仍旧由你按下保存那一刻决定。",
  secAuthCodes: "授权范围",
  needQualification: "需要「{q}」",
  needQualificationMissing: "缺「{q}」，无法授权",
  authCodesHint: "不能全部取消：撤空之后商家会静默失去上架能力。要停止经营请走封禁或归档，那是明示的动作。",
  secAuthReason: "变更原因",
  fieldReason: "原因",
  authReasonPlaceholder: "例：商家补交食品经营许可证，扩类目至水果",
  btnSaveAuth: "保存授权",
  authRevokeWarn: "本次将撤销：{s}。这些类目下的在架商品，下次上架会被拒。",
  toastAuthRevoked: "授权已更新；{n} 件在架商品下次上架会被拒",
  applyGrantLabel: "经营类目授权",
  applyGrantSaid: "商家填写：{s}",
  toastAuthSaved: "授权范围已更新",

  verifyNotice: "认证标是平台给用户看的背书。只有已过审、且毁约次数未达 {n} 次的商家能拿标 —— 挂在一个正在毁约的商家身上，赔的是平台的信用。",
  actionGrantVerify: "授予认证标",
  actionRevokeVerify: "撤销认证标",
  confirmGrantTitle: "授予认证标？",
  confirmGrantDesc: "「{name}」将在 C 端商品与店铺页显示认证标识。",
  confirmRevokeTitle: "撤销认证标？",
  confirmRevokeDesc: "「{name}」的认证标识会立刻从 C 端消失。",

  creditNoteTitle: "信用档案怎么用",
  creditNotice: "信用档案是只读的 —— 它是处置的依据，不是处置本身。毁约次数达 {n} 次会同时触发两条既有规则：不能拿认证标（P-11.1.2）、报价受限（ADR-003）。",
  actionCredit: "查看档案",
  colBorne: "责任归属",
  bornePlatform: "服务/时效由平台承担",
  borneMerchant: "全部维度",
  borneNoteTitle: "归集路径下评分怎么算",
  borneNotice: "归集路径（平台收款）下平台是销售主体 —— 客服、配送、售后都是平台在做。消费者打的服务分与时效分照常展示给他们（那是真实体验），但不该拿来考核这家供应商：那是拿他控制不了的事罚他。商品分不在此列 —— 货是他的。",
  creditTitle: "{name} 的信用档案",
  secBrief: "商家概况",
  secViolations: "违规记录",
  noViolation: "这家商家没有违规记录。",

  banNotice: "处置要写清事实与证据出处 —— 没有事实的处置在申诉时站不住。只有「毁约」计入毁约次数：别的违规也计的话，报价受限那条阈值就失去意义了。",
  filterViolationType: "按违规类型筛选",
  filterViolationTypeAll: "全部违规类型",
  vtFake: "售假",
  vtBreach: "毁约",
  vtPrice: "价格欺诈",
  vtService: "服务问题",
  vaWarn: "警告",
  vaLimit: "限制经营",
  vaSuspend: "封禁",
  vaStoreOffline: "门店强制下线",
  vlStoreLabel: "对象门店",
  vlStoreHint: "只有「门店强制下线」需要指定门店；其余处置作用于该商家的全部门店。",
  vlStorePick: "请选择门店",
  vlStoreEmpty: "该商家还没有门店，无法做门店级处置",
  btnRecordFor: "处置 {name}",
  secBanned: "当前封禁中",
  actionUnban: "解封",
  unbanRemark: "整改完成，恢复经营",
  recordTitle: "处置 {name}",
  secViolationForm: "违规与处置",
  typeHint: "只有「毁约」计入毁约次数，累计 {n} 次会触发认证标与报价限制。",
  detailPlaceholder: "例：连续 2 次成团后不发货，工单 #2026-0712 / #2026-0718",
  detailHint: "这段文字会进商家的信用档案，申诉时也以它为准。",
  btnRecordViolation: "记录并执行处置",
  emptyViolation: "没有违规记录。这是好事 —— 有处置时会出现在这里，并同时进对应商家的信用档案。",
  toastViolationRecorded: "已记录并执行处置",
  toastUnbanned: "已解封，商家恢复经营",
  authorizeReadOnlyWhat: "类目授权与认证标",
  banReadOnlyWhat: "违规处置与封禁",

  tierPersonal: "个人",
  tierIndividual: "个体户",
  tierCompany: "企业",

  readOnlyWhat: "商家入驻审核",
  readOnlyNote: "不能通过、驳回或归档商家",
  searchPlaceholder: "搜索商家编号 / 名称 / 联系人",
  filterStatus: "按状态筛选",
  filterStatusAll: "全部状态",
  filterTier: "按主体筛选",
  filterTierAll: "全部主体",
  empty: "没有符合条件的商家。换个状态筛选，或让 BD 先去拉一家店入驻。",

  colNo: "商家编号",
  colName: "商家名称",
  colTier: "主体",
  colCommunity: "归属社区",
  communityRequired: "通过前必须选择覆盖社区 —— 不选的话买家搜不到这家店",
  colContact: "联系人",
  colStatus: "状态",
  colSettleAccount: "分账账户",
  colCreatedAt: "提交时间",
  colActions: "操作",
  actionView: "查看",

  settleReady: "已报备",
  settleNotReady: "未报备",
  fieldPickupIntent: "承接自提点",
  pickupWanted: "申请人愿意承接（需另行建点）",
  pickupNo: "否",

  entity: "商家",
  toastStatusSaved: "已更新审核状态",
  toastVerifyGranted: "已授予认证标",
  toastVerifyRevoked: "已撤销认证标",

  btnStartReview: "开始审核",
  btnReject: "驳回并要求补交",
  btnApprove: "通过",
  btnRevokeVerify: "撤销认证标",
  btnGrantVerify: "授予认证标",

  fieldAuditStatus: "审核状态",
  fieldTier: "主体类型",
  fieldPhone: "联系电话",
  fieldBreach: "毁约次数",
  fieldCategories: "经营类目",
  roleOWNER: "老板",
  roleMANAGER: "店长",
  roleCLERK: "店员",
  rolePICKER: "理货员",
  roleCOURIER: "配送员",
  roleCS: "客服",
  fieldFulfillment: "履约配置",
  fulfillLegacy: "尚未迁移到新模型（按旧履约档位生效）",
  chSTORE_PICKUP: "门店自取",
  chNEIGHBOR_PICKUP: "社区自提点",
  chMERCHANT_DELIVERY: "商家自送",
  chEXPRESS: "快递",
  chDenied: "准入不允许",
  chOff: "未开启",
  chLocked: "平台已锁",
  chSubset: "仅 {n} 项范围",
  btnLock: "锁路",
  btnUnlock: "解锁",
  lockTitle: "锁定「{ch}」？",
  lockDesc: "锁着时买家选不到这一路、商家也打不开；配置原样保留，解锁即恢复。理由进审计。",
  unlockTitle: "解锁「{ch}」？",
  toastChannelLocked: "已锁路，买家侧即刻不可选",
  toastChannelUnlocked: "已解锁",
  fieldStaff: "人员与授权",
  staffOwner: "老板",
  staffDisabled: "已停用",
  staffOwnerNote: "不受门店授权限制，所有门店都归他管",
  staffNoGrant: "没有任何门店授权 —— 他登录进去什么都看不到",
  fieldRemark: "审核意见",
  remarkPlaceholder: "驳回时必须写清补交项，商家在 B 端看到的就是这段话",

  // ── 门店档案（P-11.2.1）。平台**只读为主**：门店资料、价格、库存一律不改
  stNotice: "门店档案是**只读**的：资料、价格、库存归商家运营，平台的边界是「裁、定、兜」。这里唯一的写动作是解除强制下线 —— 压下那一侧在「违规处置与封禁」，处置动作与留痕必须是同一次提交。",
  stSearchPh: "门店号 / 门店名 / 地址 / 商家名",
  stFilterMerchantPh: "按商家号筛（如 M901）",
  stFilterStatus: "按经营状态筛选",
  stFilterStatusAll: "全部经营状态",
  stFilterMode: "按经营模式筛选",
  stFilterModeAll: "全部经营模式",
  stStatusActive: "营业中",
  stStatusReadonly: "商家自助停用",
  stStatusSuspended: "平台强制下线",
  stModeSelf: "自营",
  stModeThird: "第三方",
  stColNo: "门店号",
  stColName: "门店名",
  stColMerchant: "所属商家",
  stColStatus: "经营状态",
  stColMode: "经营模式",
  stColDefault: "默认店",
  stColPayMerchant: "收款商户号",
  stColActions: "操作",
  stIsDefault: "默认",
  stPayFallback: "主体默认收款号",
  stEmpty: "没有门店。含停用与强制下线的店都会出现在这里 —— 治理视角更不能看不见。",
  stDetail: "档案",
  stSecProfile: "门店档案",
  stSecStats: "经营状况",
  stSecActions: "平台动作",
  stFieldAddress: "地址",
  stFieldAnnouncement: "门店公告",
  stFieldOpenHours: "营业时间",
  stFieldRadius: "配送半径",
  stFieldMinOrder: "起送价",
  stFieldFee: "配送费",
  stFieldFreeThreshold: "免配送费门槛",
  stAnnouncementEmpty: "没有公告",
  stMeters: "{n} 米",
  stStatsLoading: "正在取经营数据…",
  stStatTodayOrders: "今日订单",
  stStatTodayGmv: "今日 GMV",
  stStatMonthOrders: "本月订单",
  stStatMonthGmv: "本月 GMV",
  stStatOwnedTraffic: "自带客流占比",
  stStatToShip: "待发货",
  stStatToDeliver: "待自送",
  stStatToStock: "缺货待补",
  stBtnRestore: "解除下线",
  stRestoreHint: "只有被平台压下的店解得开。商家自助停用的由商家自己开回来 —— 平台替他开等于替他做经营决定。",
  stNoAction: "当前没有可执行的平台动作：这家店不在强制下线状态。",
  stToastRestored: "已解除强制下线，货架恢复",
  stReadOnlyWhat: "解除门店强制下线",
  // ── 增值包与门店额度（P-11.2.2~11.2.6）──
  plNotice: "一期没有在线支付：商家点「升级」→ 联系平台 → 运营在这里授予。到期后先进 7 天宽限期（能力全保留），宽限期满才降级压店。",
  plSearchPh: "商家名 / 商家号",
  plFilterAll: "全部订阅",
  plFilterExpiring: "7 天内到期",
  plFilterGrace: "宽限期中（还救得回来）",
  plFilterDowngraded: "已降级",
  plColMerchant: "商家",
  plColPlan: "档位",
  plColQuota: "门店额度",
  plColStaff: "子账号",
  plColStatus: "状态",
  plColExpire: "到期",
  plColActions: "操作",
  plStatusActive: "生效中",
  plStatusGrace: "宽限期",
  plStatusExpired: "已过期",
  plFieldQuotaSource: "额度来源",
  plSourcePlan: "档位快照",
  plSourceOverride: "单独覆盖",
  plSourceConfig: "配置兜底",
  // 套餐下拉的选项文案。「店」这个量词以前是硬编码在 plans-tab.tsx 里的 ——
  // 页面切 EN 之后名字和数字是英文、量词还是中文。
  plDefOption: "{name}（{quota} 店）",
  plQuotaFull: "额度已满",
  plExpireNone: "长期",
  plDowngradedAt: "降级于",
  plEmpty: "没有符合条件的订阅。",
  plDetail: "详情",
  plSecPlan: "订阅",
  plSecGrant: "授予 / 延长",
  plSecQuota: "额度覆盖",
  plSecDefs: "档位定义",
  plFieldTrialUsed: "试用已用完",
  plFieldGrantedBy: "授予方",
  plGrantPlan: "档位",
  plGrantMonths: "延长月数",
  plGrantMonthsHint: "留空 = 只补缴不延长。延长从原到期日接着算，不从今天重算 —— 提前续费不该吃亏。",
  plGrantReason: "理由",
  plGrantReasonPh: "必填：谁谈的、什么条件",
  plBtnGrant: "授予",
  plToastGranted: "已授予；额度立即生效，降级压下的门店已恢复",
  plQuotaStore: "门店额度",
  plQuotaStaff: "子账号额度",
  plQuotaHint: "覆盖值优先于档位快照。清空 = 回到快照，不是设成 0。",
  plBtnQuota: "保存覆盖",
  plToastQuota: "额度覆盖已保存",
  plDefsHint: "改档位定义只影响之后新订阅的人 —— 已订阅的用的是自己那份额度快照。",
  plDefCol: "档位",
  plDefColStore: "门店",
  plDefColStaff: "子账号",
  plDefColCross: "跨店总览",
  plDefColTrial: "试用天数",
  plDefColSubs: "在用",
  plDefColEnabled: "在售",
  plDefEnabled: "在售",
  plDefRetired: "已停售",
  plDefEdit: "编辑",
  plBtnDefSave: "保存定义",
  plDefConfirmTitle: "确认修改「{name}」的定义？",
  plDefConfirmDesc: "当前有 {n} 家在用这一档。改动**只影响之后的新订阅** —— 已订阅的商家用的是自己那份额度快照，不会变。",
  plToastDefSaved: "档位定义已保存，只影响之后的新订阅",
  plSecSignals: "升档信号",
  plSignalsHint: "一个人名下有多个主体 = 他已经在多店经营，只是绕过了额度。这是最该打的电话。",
  plSignalOwner: "开户人",
  plSignalEntities: "名下主体",
  plSignalsEmpty: "暂无一人多主体的情况。",
  plReadOnlyGrant: "授予与延长套餐",
  plReadOnlyDef: "修改档位定义",

  // 进件看板（WS-C）
  obNotice: "审核通过 = 能上架，进件通过 = 能收钱，是两条链。这里盯的是「审核过了但还收不了钱」的商家 —— 进件没有回调，商家不自己点刷新就不会推进，卡住时运营在这里替他回查一次。",
  obSearchPh: "店名 / 主体号 / 收款号",
  obFilterAllStatus: "全部状态",
  obFilterAllChannel: "全部通道",
  obFilterTodo: "待处理（审核中+被拒）",
  obChannelWECHAT: "微信",
  obChannelALIPAY: "支付宝",
  obStNONE: "未开通",
  obStAPPLYING: "审核中",
  obStACTIVE: "已开通",
  obStREJECTED: "已驳回",
  obStFROZEN: "已冻结",
  obColMerchant: "商家",
  obColChannel: "通道",
  obColStatus: "进件状态",
  obColBlocker: "卡点",
  obColPayNo: "收款号",
  obColStay: "停留",
  obColAppliedAt: "提交时间",
  obColActions: "操作",
  obBlockerNoPayNo: "收款号未生成",
  obStayNotSubmitted: "未提交",
  obStayDays: "{n} 天",
  obStayHours: "{n} 小时",
  obActionRefresh: "回查",
  obToastRefreshed: "已回查",
  qualAdd: "补录资质",
  qualEdit: "更新",
  qualDrawerNew: "补录资质",
  qualDrawerEdit: "更新资质",
  qualFieldType: "证件类型",
  qualFieldName: "证件名",
  qualFieldNameHelp: "类目授权按前缀比对（LIKE「营业执照%」），所以要以标准名开头，别写成「食品证」",
  qualFieldNumber: "证件编号",
  qualFieldNumberHelp: "证面上印的那一串，与证件一致",
  qualFieldImage: "证件图片地址",
  qualFieldExpire: "到期日",
  qualFieldExpireHelp: "留空 = 长期有效；填了就会开始过期 —— 到期后上架会被拦，别为了「填满」而随手填一个",
  qualSaved: "资质已保存",
  adPolicyEdit: "改门槛",
  adPolicyEditTitle: "准入门槛 · {form}",
  adPolicyDeposit: "应缴保证金（元）",
  adPolicyDepositHelp: "0 = 免缴。这笔钱是出事之后唯一赔得出来的东西",
  adPolicySingle: "单笔限额（元）",
  adPolicySingleHelp: "0 = 不限。限额与保证金要一起看：赔付上限就是这个数",
  adPolicyDaily: "日累计限额（元）",
  adPolicyDailyHelp: "0 = 不限",
  adPolicyBanQualified: "禁售需资质品类",
  adPolicyBanQualifiedHelp: "打开后这一档不能经营任何「需资质」类目",
  adPolicyEnabled: "该档限制生效",
  adPolicyEnabledHelp: "关掉 = 这一档不做任何限制。关之前想清楚：它管的是最弱的那批主体",
  adPolicyRemark: "为什么这么定",
  adPolicyRemarkHelp: "被回溯质问「那单当时为什么放行」时，这句话比数字有用",
  adToastPolicySaved: "准入门槛已更新",
  adPolicyReadOnly: "改准入门槛",

  obNotSubmittedHint: "这家还没把资料提交给通道，没有单号可查 —— 要催的是商家补料，不是等通道",
  obToastNotSubmitted: "这家还没把资料提交给通道，回查不到东西 —— 要催的是商家，不是通道",
  obEmpty: "没有匹配的进件记录",
};

const en: typeof zh = {
  applyColIndustry: "Industry",
  applyColSubject: "Legal form",
  applyColCategory: "Category",
  applyColScope: "Service area",
  applyScopeEmpty: "Not set",
  applySearchPh: "Shop / contact / phone",
  applyFilterTodo: "To do (pending + reviewing)",
  applyActionAccept: "Accept",
  applyActionApprove: "Approve",
  applyActionReject: "Reject",
  applySectionInfo: "Application",
  applySectionLicenses: "Documents",
  applySectionDecide: "Decision",
  applyAsPickup: "Willing to host a pickup point",
  applyScopeNotice: "Set the service area before approving. Merchants may leave it blank, but an empty area means nobody can see the shop — and nothing reports it.",
  applyScopeLabel: "Service area",
  applyScopeCommunity: "Selected communities",
  applyScopeCity: "Whole city",
  applyScopePlatform: "Platform-wide",
  applyCommunities: "Communities covered",
  applyScopeNeedCommunity: "Pick at least one community, otherwise no buyer can see this shop",
  applyReasonLabel: "Decision note",
  applyReasonPh: "Required when rejecting — without a reason they can only guess",
  toastAccepted: "Accepted — the merchant can see someone is on it",
  toastApproved: "Approved — the merchant entity has been created",
  toastRejected: "Rejected — the reason has been sent to the merchant",
  adNotice:
    "The platform has no warehouse and never handles the goods, so \"self-operated\" is only a licensing shell. The weakest tier has no \"send it through our warehouse\" escape hatch, because that warehouse does not exist. The platform is the legal seller and carries full product liability without any control over the goods, so the gap can only be closed with admission rules and money: deposit, category limits and amount caps must all be in force — set any one to zero and the other two stop working.",
  adPolicyTitle: "Admission policy (by entity tier)",
  adPolicyHint: "Policy is attached to the tier, not the merchant: three tiers, three rows, one edit changes the rule. The tiers are micro / sole proprietor / company and will not grow.",
  adColForm: "Entity tier",
  adColDeposit: "Required deposit",
  adColSingle: "Per-order cap",
  adColDaily: "Daily cap",
  adColBanQualified: "Licensed categories",
  adColRemark: "Note",
  adFormMicro: "Micro",
  adFormIndividual: "Sole proprietor",
  adFormEnterprise: "Company",
  adFree: "None",
  adUnlimited: "Unlimited",
  adBanned: "Blocked",
  adAllowed: "Allowed",
  adSearchPlaceholder: "Merchant number",
  adSearch: "Look up",
  adDepositTitle: "Deposit account · {no}",
  adPaid: "Paid in",
  adFrozen: "Frozen",
  adAvailable: "Available",
  adRequired: "Required",
  adSufficient: "Deposit is sufficient; the merchant can list items.",
  adInsufficient: "Available balance is below the requirement, so this merchant cannot list items. The check uses available, not paid-in — frozen money cannot back admission at the same time.",
  adColTxnType: "Type",
  adColAmount: "Amount",
  adColBalanceAfter: "Balance after",
  adColReason: "Reason",
  adColOperator: "Operator",
  adColTime: "Time",
  adFieldAmount: "Amount (minor units)",
  adFieldReason: "Reason",
  adAddTxn: "Record entry",
  adToastTxnAdded: "Deposit entry recorded",
  adTxnTitle: "Deposit ledger",
  adTxnHint: "An account with only a balance field cannot be audited: in a dispute nobody can say when the money left or who took it. Freezing moves the frozen figure, not the paid-in one — if the claim fails you must be able to recover what was originally paid.",
  adTxnPay: "Paid in",
  adTxnRefund: "Refunded",
  adTxnFreeze: "Frozen",
  adTxnUnfreeze: "Unfrozen",
  adTxnDeduct: "Deducted",

  // ── Unlicensed x self-operated (tax exposure) ─────────────
  colFundsMode: "Funds path",
  fundsAggregated: "Aggregated (platform collects)",
  fundsDirect: "Direct (merchant collects)",
  fundsModeTitle: "Funds path",
  fundsModeHint: "Whose account the money lands in first. **Which path is allowed follows from the legal form** — unlicensed entities cannot issue input invoices, so the platform books full revenue with non-deductible cost. Self-produced agricultural goods are the exception. This is not the same axis as business mode, which says who the seller is.",
  fundsModeChanged: "Funds path updated",
  applySectionRawFiles: "Other uploads",
  applyRawFilesHint: "Legacy upload: images only, no type or expiry — these are not turned into qualification records",
  applyQualForever: "No expiry",
  qualBUSINESS_LICENSE: "Business licence",
  qualFOOD_PERMIT: "Food operation permit",
  qualFOOD_WORKSHOP: "Food workshop registration",
  qualOTHER: "Other",
  qualTitle: "Registered qualifications",
  qualHint: "The expiry and category-authorisation gates read this table — empty means neither gate fires",
  qualColType: "Type",
  qualColName: "Certificate",
  qualColNumber: "Number",
  qualColExpire: "Valid until",
  qualColStatus: "Status",
  qualColActions: "Actions",
  qualRevoke: "Revoke",
  qualRevoked: "Revoked",
  qualRevokeConfirm: "A revoked certificate no longer counts towards listing checks. It is not deleted — the record stays queryable.",
  qualEmpty: "No qualification registered yet",
  qualStatusVALID: "Valid",
  qualStatusEXPIRED: "Expired",
  qualStatusREVOKED: "Revoked",
  mrTitle: "Self-operated stores under unlicensed entities",
  mrDesc: "In self-operated mode the platform is the seller and needs supplier invoices to deduct costs",
  mrNoLicense: "No business licence",
  mrColMerchant: "Merchant",
  mrColLegalForm: "Legal status",
  mrColStore: "Store",
  mrColBills: "Settled bills",
  mrColExposure: "Paid to supplier",
  mrNotTraded: "No sales yet",
  mrEmpty: "No unlicensed entity is attached to a self-operated store",
  mrWarning:
    "These stores belong to entities without a business licence, yet settle as self-operated. "
    + "The platform is the seller and needs input invoices to deduct costs. "
    + "Spending without an invoice is not deductible for corporate income tax, "
    + "which inflates reported profit by the same amount. Confirm the handling with finance.",
  mrSummary: "{stores} stores, {traded} with sales, {amount} in total.",
  adQuotaTitle: "Payment quota",
  adQuotaHint: "Micro-merchant payment accounts carry per-day and per-transaction channel limits; once exceeded, money simply stops coming in — the order fails at the payment step and all the merchant sees is \"payment failed\". 0 means unset (no limit enforced), not \"a quota of zero\". Setting it too low blocks a healthy merchant entirely, so confirm the threshold with the payment provider before entering it. Used amounts accumulate from real payments and cannot be edited.",
  adQuotaNoAccount: "This merchant has no payment account yet — the fix is onboarding, not a bigger quota.",
  adColPayAccount: "Account",
  adEntityLevel: "Entity level (default)",
  adColChannel: "Channel",
  adColApplyStatus: "Onboarding",
  adColQuotaLimit: "Limit",
  adColQuotaUsed: "Used",
  adQuotaUnset: "Unset (no limit)",
  adQuotaSet: "Set quota",
  adQuotaFieldLimit: "Limit (yuan, 0 = remove limit)",
  adToastQuotaSaved: "Quota saved",
  adModeTitle: "Store business mode",
  adModeHint: "Applies to new orders only — settlements snapshot the business mode when they are generated, so changing it never rewrites history. Self-operated makes the platform the legal seller, which is not something a merchant may tick for themselves, so this lives in the ops console.",
  adColStore: "Store",
  adColMode: "Business mode",
  adColPayMerchant: "Payment account",
  adColAction: "Actions",
  adModeSelfOperated: "Self-operated",
  adModeThirdParty: "Third-party",
  adModeUnset: "Not set",
  adNoPayAccount: "None",
  adNoPayAccountHint: "This store has no active payment account; in third-party mode the money would be stuck on the platform side",
  adSwitchSelfOperated: "Set self-operated",
  adSwitchThirdParty: "Set third-party",
  adToastModeChanged: "Business mode updated (new orders only)",
  colLegalForm: "Entity tier",
  formMicro: "Individual",
  formIndividual: "Sole proprietor",
  formEnterprise: "Company",
  formUnknown: "Unknown",

  colAuthCodes: "Granted categories",
  colQualifications: "Uploaded credentials",
  colVerified: "Verified badge",
  colBreach: "Breaches",
  colSettleReady: "Settlement account",
  colViolationNo: "Record no.",
  colViolationType: "Violation",
  colViolationAction: "Action",
  colDetail: "Facts and evidence",
  colAt: "Time",
  colOperator: "Operator",
  breachTimes: "{n}",
  noQualification: "None uploaded",
  badgeVerified: "Verified",
  badgeUnverified: "Not verified",
  loading: "Loading…",
  emptyApproved: "No approved merchants. Category permissions and verified badges are open to approved merchants only — granting before approval lets them through early.",

  categoryNotice: "Permissions are granted by code, not by category node: the category tree gets restructured, whereas “may they sell vegetables” does not. Revoking takes effect at once — listed items in that category will be refused on their next listing, and you are told how many before you save.",
  actionGrant: "Edit permissions",
  grantTitle: "Category permissions for {name}",
  secQualification: "Uploaded credentials",
  qualificationHint: "Merchants upload credentials in the B-end app and the platform verifies them at onboarding. This page only uses them as a gate; it does not edit them.",
  grantByQual: "Tick by uploaded licences",
  grantByQualHint: "Ticks only — the grant still happens when you press save.",
  secAuthCodes: "Granted scope",
  needQualification: "Requires “{q}”",
  needQualificationMissing: "Missing “{q}” — cannot grant",
  authCodesHint: "You cannot clear every one: the merchant would silently lose the ability to list anything. To stop them trading, ban or archive them — that is the explicit action.",
  secAuthReason: "Why change it",
  fieldReason: "Reason",
  authReasonPlaceholder: "e.g. Food licence resubmitted; extending scope to fruit",
  btnSaveAuth: "Save permissions",
  authRevokeWarn: "Revoking: {s}. Items in those categories will be refused the next time they are listed.",
  toastAuthRevoked: "Scope updated; {n} listed item(s) will be refused on the next listing",
  applyGrantLabel: "Category permissions",
  applyGrantSaid: "Merchant wrote: {s}",
  toastAuthSaved: "Granted scope updated",

  verifyNotice: "The verified badge is the platform’s endorsement to shoppers. Only approved merchants under {n} breaches can hold one — on a merchant who is currently defaulting, it is the platform’s credibility that pays.",
  actionGrantVerify: "Grant badge",
  actionRevokeVerify: "Revoke badge",
  confirmGrantTitle: "Grant the verified badge?",
  confirmGrantDesc: "“{name}” will show the verified mark on listings and its storefront.",
  confirmRevokeTitle: "Revoke the verified badge?",
  confirmRevokeDesc: "The verified mark disappears from the shopper app immediately for “{name}”.",

  creditNoteTitle: "How credit records are used",
  creditNotice: "Credit records are read-only — they are the basis for action, not the action. Hitting {n} breaches trips two existing rules at once: no verified badge (P-11.1.2) and restricted quoting (ADR-003).",
  actionCredit: "View record",
  colBorne: "Borne by",
  bornePlatform: "Service/speed borne by platform",
  borneMerchant: "All dimensions",
  borneNoteTitle: "Ratings under the aggregated path",
  borneNotice: "Under the aggregated funds path the platform is the seller of record \u2014 support, delivery and after-sales are all done by the platform. Buyers' service and speed ratings are still shown to them (that is their real experience), but they must not count against this supplier: that would penalise them for things they do not control. Goods rating is excluded \u2014 the goods are theirs.",
  creditTitle: "Credit record for {name}",
  secBrief: "Merchant overview",
  secViolations: "Violations",
  noViolation: "This merchant has no violations on record.",

  banNotice: "State the facts and where the evidence sits — an action with no facts does not hold up on appeal. Only “breach of contract” counts toward the breach tally: count everything and the quoting threshold stops meaning anything.",
  filterViolationType: "Filter by violation",
  filterViolationTypeAll: "All violations",
  vtFake: "Counterfeit goods",
  vtBreach: "Breach of contract",
  vtPrice: "Price fraud",
  vtService: "Service failure",
  vaWarn: "Warning",
  vaLimit: "Trading restricted",
  vaSuspend: "Banned",
  vaStoreOffline: "Force store offline",
  vlStoreLabel: "Target store",
  vlStoreHint: "Only “force store offline” needs a store; every other action hits all of the merchant’s stores.",
  vlStorePick: "Pick a store",
  vlStoreEmpty: "This merchant has no stores, so a store-level action is not possible",
  btnRecordFor: "Act on {name}",
  secBanned: "Currently banned",
  actionUnban: "Lift ban",
  unbanRemark: "Remediation complete; trading resumed",
  recordTitle: "Act on {name}",
  secViolationForm: "Violation and action",
  typeHint: "Only “breach of contract” adds to the tally; {n} of them trip the badge and quoting limits.",
  detailPlaceholder: "e.g. Failed to ship two group buys, tickets #2026-0712 / #2026-0718",
  detailHint: "This text goes into the merchant’s credit record and is what an appeal is judged against.",
  btnRecordViolation: "Record and apply",
  emptyViolation: "No violations on record. That is a good thing — actions show up here and in the merchant’s credit record at the same time.",
  toastViolationRecorded: "Recorded and applied",
  toastUnbanned: "Ban lifted; the merchant may trade again",
  authorizeReadOnlyWhat: "category permissions and verified badges",
  banReadOnlyWhat: "violation handling and bans",

  tierPersonal: "Individual",
  tierIndividual: "Sole trader",
  tierCompany: "Company",

  readOnlyWhat: "merchant onboarding review",
  readOnlyNote: "cannot approve, reject or archive merchants",
  searchPlaceholder: "Search merchant no. / name / contact",
  filterStatus: "Filter by status",
  filterStatusAll: "All statuses",
  filterTier: "Filter by entity type",
  filterTierAll: "All entity types",
  empty: "No merchants match these filters. Try another status, or ask BD to onboard a store first.",

  colNo: "Merchant no.",
  colName: "Merchant name",
  colTier: "Entity",
  colCommunity: "Community",
  communityRequired: "Pick at least one community before approving — otherwise buyers cannot find this shop",
  colContact: "Contact",
  colStatus: "Status",
  colSettleAccount: "Payout account",
  colCreatedAt: "Submitted at",
  colActions: "Actions",
  actionView: "View",

  settleReady: "Registered",
  settleNotReady: "Not registered",
  fieldPickupIntent: "Pickup point",
  pickupWanted: "Willing to host (point set up separately)",
  pickupNo: "No",

  entity: "merchant",
  toastStatusSaved: "Review status updated",
  toastVerifyGranted: "Verification badge granted",
  toastVerifyRevoked: "Verification badge revoked",

  btnStartReview: "Start review",
  btnReject: "Reject & request resubmission",
  btnApprove: "Approve",
  btnRevokeVerify: "Revoke badge",
  btnGrantVerify: "Grant badge",

  fieldAuditStatus: "Review status",
  fieldTier: "Entity type",
  fieldPhone: "Phone",
  fieldBreach: "Breaches",
  fieldCategories: "Categories",
  roleOWNER: "Owner",
  roleMANAGER: "Manager",
  roleCLERK: "Clerk",
  rolePICKER: "Picker",
  roleCOURIER: "Courier",
  roleCS: "Support",
  fieldFulfillment: "Fulfillment channels",
  fulfillLegacy: "Not migrated yet (legacy reach still applies)",
  chSTORE_PICKUP: "In-store pickup",
  chNEIGHBOR_PICKUP: "Community pickup",
  chMERCHANT_DELIVERY: "Merchant delivery",
  chEXPRESS: "Courier",
  chDenied: "tier denied",
  chOff: "off",
  chLocked: "locked by ops",
  chSubset: "{n} areas only",
  btnLock: "Lock",
  btnUnlock: "Unlock",
  lockTitle: "Lock “{ch}”?",
  lockDesc: "While locked, buyers cannot choose it and the merchant cannot turn it on; config is kept and unlock restores it. The reason is audited.",
  unlockTitle: "Unlock “{ch}”?",
  toastChannelLocked: "Locked — unavailable to buyers now",
  toastChannelUnlocked: "Unlocked",
  fieldStaff: "Staff and access",
  staffOwner: "Owner",
  staffDisabled: "Disabled",
  staffOwnerNote: "Not limited by per-store access — every store is theirs",
  staffNoGrant: "No store access — they see nothing after signing in",
  fieldRemark: "Review note",
  remarkPlaceholder: "When rejecting, spell out what must be resubmitted — the merchant sees this text verbatim in the B-end app",

  stNotice: "Store records are **read only**: details, pricing and stock belong to the merchant. The one write action here is lifting a forced offline — pushing a store offline lives under “Penalties & suspensions”, where the action and its audit trail are one submission.",
  stSearchPh: "Store no. / name / address / merchant",
  stFilterMerchantPh: "Filter by merchant no. (e.g. M901)",
  stFilterStatus: "Filter by trading status",
  stFilterStatusAll: "All trading statuses",
  stFilterMode: "Filter by operating model",
  stFilterModeAll: "All operating models",
  stStatusActive: "Trading",
  stStatusReadonly: "Paused by merchant",
  stStatusSuspended: "Forced offline",
  stModeSelf: "Self-operated",
  stModeThird: "Third party",
  stColNo: "Store no.",
  stColName: "Store",
  stColMerchant: "Merchant",
  stColStatus: "Trading status",
  stColMode: "Operating model",
  stColDefault: "Default",
  stColPayMerchant: "Payee merchant no.",
  stColActions: "Actions",
  stIsDefault: "Default",
  stPayFallback: "Entity default payee",
  stEmpty: "No stores. Paused and forced-offline stores show up here too — governance least of all can afford not to see them.",
  stDetail: "Record",
  stSecProfile: "Store record",
  stSecStats: "Trading",
  stSecActions: "Platform actions",
  stFieldAddress: "Address",
  stFieldAnnouncement: "Notice",
  stFieldOpenHours: "Opening hours",
  stFieldRadius: "Delivery radius",
  stFieldMinOrder: "Minimum order",
  stFieldFee: "Delivery fee",
  stFieldFreeThreshold: "Free delivery over",
  stAnnouncementEmpty: "No notice",
  stMeters: "{n} m",
  stStatsLoading: "Loading trading data…",
  stStatTodayOrders: "Orders today",
  stStatTodayGmv: "GMV today",
  stStatMonthOrders: "Orders this month",
  stStatMonthGmv: "GMV this month",
  stStatOwnedTraffic: "Owned traffic share",
  stStatToShip: "To ship",
  stStatToDeliver: "To deliver",
  stStatToStock: "Out of stock",
  stBtnRestore: "Lift forced offline",
  stRestoreHint: "Only a store the platform pushed offline can be lifted. One the merchant paused reopens on their side — doing it for them is making their call for them.",
  stNoAction: "Nothing to do here: this store is not forced offline.",
  stToastRestored: "Forced offline lifted; the shelf is back",
  stReadOnlyWhat: "lifting a forced store offline",
  // ── Plans and store quota ──
  plNotice: "No online payment in phase one: the merchant taps Upgrade, contacts the platform, and ops grants it here. On expiry they get a 7-day grace period with every capability intact; only after that do stores get pushed read-only.",
  plSearchPh: "Merchant name / no.",
  plFilterAll: "All subscriptions",
  plFilterExpiring: "Expiring within 7 days",
  plFilterGrace: "In grace period (still savable)",
  plFilterDowngraded: "Downgraded",
  plColMerchant: "Merchant",
  plColPlan: "Tier",
  plColQuota: "Store quota",
  plColStaff: "Sub-accounts",
  plColStatus: "Status",
  plColExpire: "Expires",
  plColActions: "Actions",
  plStatusActive: "Active",
  plStatusGrace: "Grace",
  plStatusExpired: "Expired",
  plFieldQuotaSource: "Quota source",
  plSourcePlan: "Tier snapshot",
  plSourceOverride: "Per-merchant override",
  plSourceConfig: "Config fallback",
  plDefOption: "{name} ({quota} stores)",
  plQuotaFull: "Quota full",
  plExpireNone: "No expiry",
  plDowngradedAt: "Downgraded at",
  plEmpty: "No subscriptions match.",
  plDetail: "Details",
  plSecPlan: "Subscription",
  plSecGrant: "Grant / extend",
  plSecQuota: "Quota override",
  plSecDefs: "Tier definitions",
  plFieldTrialUsed: "Trial used",
  plFieldGrantedBy: "Granted by",
  plGrantPlan: "Tier",
  plGrantMonths: "Months to extend",
  plGrantMonthsHint: "Leave empty to settle up without extending. Extensions run from the current expiry date, not from today — renewing early must not cost them days.",
  plGrantReason: "Reason",
  plGrantReasonPh: "Required: who agreed to what",
  plBtnGrant: "Grant",
  plToastGranted: "Granted; quota is live now and stores pushed read-only by downgrade are back",
  plQuotaStore: "Store quota",
  plQuotaStaff: "Sub-account quota",
  plQuotaHint: "An override wins over the tier snapshot. Clearing it returns to the snapshot — it does not set the quota to zero.",
  plBtnQuota: "Save override",
  plToastQuota: "Quota override saved",
  plDefsHint: "Editing a tier only affects subscriptions made after the change — existing subscribers keep their own quota snapshot.",
  plDefCol: "Tier",
  plDefColStore: "Stores",
  plDefColStaff: "Sub-accounts",
  plDefColCross: "Cross-store stats",
  plDefColTrial: "Trial days",
  plDefColSubs: "In use",
  plDefColEnabled: "On sale",
  plDefEnabled: "On sale",
  plDefRetired: "Retired",
  plDefEdit: "Edit",
  plBtnDefSave: "Save definition",
  plDefConfirmTitle: "Change the \"{name}\" definition?",
  plDefConfirmDesc: "{n} merchants are on this tier. The change only affects subscriptions made from now on — existing subscribers keep their own quota snapshot.",
  plToastDefSaved: "Tier definition saved; it only affects new subscriptions from now on",
  plSecSignals: "Upgrade signals",
  plSignalsHint: "One person holding several merchant entities is already running multiple stores — just outside the quota. These are the calls worth making.",
  plSignalOwner: "Account owner",
  plSignalEntities: "Entities held",
  plSignalsEmpty: "No one currently holds more than one entity.",
  plReadOnlyGrant: "granting or extending a plan",
  plReadOnlyDef: "editing tier definitions",

  // Payment onboarding board (WS-C)
  obNotice: "Approval lets a merchant list goods; onboarding lets them get paid — two separate chains. This board tracks merchants who are approved but still cannot receive money. Onboarding has no callback, so it only advances when the merchant hits refresh; when one is stuck, ops can re-query here.",
  obSearchPh: "Store name / entity no. / pay merchant no.",
  obFilterAllStatus: "All statuses",
  obFilterAllChannel: "All channels",
  obFilterTodo: "Needs attention (applying + rejected)",
  obChannelWECHAT: "WeChat",
  obChannelALIPAY: "Alipay",
  obStNONE: "Not opened",
  obStAPPLYING: "Applying",
  obStACTIVE: "Active",
  obStREJECTED: "Rejected",
  obStFROZEN: "Frozen",
  obColMerchant: "Merchant",
  obColChannel: "Channel",
  obColStatus: "Onboarding",
  obColBlocker: "Blocker",
  obColPayNo: "Pay merchant no.",
  obColStay: "Waiting",
  obColAppliedAt: "Submitted",
  obColActions: "Actions",
  obBlockerNoPayNo: "Pay merchant no. not issued",
  obStayNotSubmitted: "Not submitted",
  obStayDays: "{n}d",
  obStayHours: "{n}h",
  obActionRefresh: "Re-query",
  obToastRefreshed: "Re-queried",
  qualAdd: "Add qualification",
  qualEdit: "Update",
  qualDrawerNew: "Add qualification",
  qualDrawerEdit: "Update qualification",
  qualFieldType: "Document type",
  qualFieldName: "Document name",
  qualFieldNameHelp: "Category authorisation matches by prefix (LIKE 'business licence%'), so start with the standard name",
  qualFieldNumber: "Document number",
  qualFieldNumberHelp: "Exactly as printed on the document",
  qualFieldImage: "Image URL",
  qualFieldExpire: "Expiry date",
  qualFieldExpireHelp: "Empty = never expires; filling it starts the clock — listings get blocked once it passes",
  qualSaved: "Qualification saved",
  adPolicyEdit: "Edit thresholds",
  adPolicyEditTitle: "Admission thresholds · {form}",
  adPolicyDeposit: "Required deposit (CNY)",
  adPolicyDepositHelp: "0 = waived. This is the only money available if something goes wrong",
  adPolicySingle: "Per-order limit (CNY)",
  adPolicySingleHelp: "0 = unlimited. Read it together with the deposit: it caps the exposure",
  adPolicyDaily: "Daily limit (CNY)",
  adPolicyDailyHelp: "0 = unlimited",
  adPolicyBanQualified: "Ban qualified-only categories",
  adPolicyBanQualifiedHelp: "On = this tier may not sell any category that requires a licence",
  adPolicyEnabled: "Tier restrictions active",
  adPolicyEnabledHelp: "Off = no restriction at all for this tier — it governs the weakest merchants",
  adPolicyRemark: "Why these numbers",
  adPolicyRemarkHelp: "When asked later why an order was allowed, this sentence beats the numbers",
  adToastPolicySaved: "Admission thresholds updated",
  adPolicyReadOnly: "edit admission thresholds",

  obNotSubmittedHint: "Never submitted to the channel, so there is no application to query — chase the merchant for documents",
  obToastNotSubmitted: "Never submitted to the channel — nothing to re-query. Chase the merchant, not the channel.",
  obEmpty: "No matching onboarding records",
};

export const MERCHANTS_COPY: PageCopy<typeof zh> = { zh, en };

/** 拆出去的 tab 组件靠它接文案。 */
export type MerchantsCopy = typeof zh;
