// 系统配置文案（矩阵 P-17.1）。
import type { PageCopy } from "@/lib/use-copy";

const zh = {

  // ── 存储空间治理（TDD-图片存储与空间回收）──
  stNotice: "扫描每晚跑一次，它只算「谁还被引用着」，「一个文件都不删」。删除一律要在这里勾选、确认之后才发起。\n\n「可回收理由」不是推断出来的：扫描遇到还在被引用的图时会记下它挂在哪，所以一旦失去引用，这一列就能说出它原来是谁的。",
  stAbnormal: "可回收占比超过一半，多半是有图片列没登记进引用清单 —— 那会让一批在用的图被误判成垃圾。批量回收已暂时禁用，先查清楚再说。",
  stCardTotal: "总占用",
  stCardActive: "在用",
  stCardReclaimable: "待回收",
  stCardScan: "上次扫描",
  stViewStores: "门店占用",
  stViewReclaimable: "待回收",
  stViewBatches: "回收记录",
  stColStore: "门店",
  stColCount: "图片数",
  stColActive: "在用",
  stColReclaimable: "待回收",
  stColRatio: "占比",
  stEntityScope: "主体级",
  stEntityScopeHint: "证件，以及门店维度出现之前的存量图 —— 它们属于哪家店没有答案，不猜",
  stColThumb: "缩略图",
  stColBizType: "用途",
  stColOwner: "归属",
  stColSize: "大小 · 尺寸",
  stColUploaded: "上传时间 · 上传人",
  stColReason: "可回收理由",
  stColMarked: "进清单时间",
  stBizGoods: "商品图",
  stBizQual: "证件",
  stBizAftersale: "售后凭证",
  stIncludeQual: "包含证件",
  stIncludeQualHint: "证件的留存期是法务口径，默认不列进清单。要连它一起清，先确认留存要求",
  stFilterReason: "理由",
  stReasonAll: "全部",
  stReasonNeverUsed: "从未被引用",
  stReasonReplaced: "被替换掉",
  stRescan: "重新扫描",
  stBackfill: "磁盘对账",
  stBackfillHint: "把「磁盘上有、库里没有」的文件补录进来。备份恢复或手工拷贝之后需要跑一次",
  stBackfillDone: "对账完成：扫描 {scanned} 个文件，补录 {inserted} 条",
  stScanDone: "扫描完成：{total} 张在册，本轮新进清单 {marked}，救回 {rescued}",
  stSelected: "已选 {n} 张 · 共 {bytes}",
  stSelectAllFiltered: "选中筛选结果全部",
  stPurge: "发起回收任务",
  stConfirmTitle: "确认发起回收任务",
  stConfirmBody: "将删除 {n} 张图片，共 {bytes}。「文件删除后不可恢复」；记账行会保留，谁在什么时候删了什么永远可查。",
  stConfirmHint: "请输入本次删除的张数以确认",
  stPurgeSubmitted: "回收任务已提交：{batchNo}",
  stEmptyNoScan: "还没有待回收的图片。扫描每晚跑一次，空着说明上一轮扫下来没有失去引用的文件。",
  stEmptyNoScanDesc: "点右上角「重新扫描」重新算一遍，或者确实没有垃圾 —— 那是好事。",
  stEmptyStores: "还没有任何图片记账。商家传过图之后这里才会有数。",
  stColBatchNo: "批次号",
  stColOperator: "发起人",
  stColBatchStatus: "状态",
  stColBatchCount: "张数 / 字节",
  stColBatchTime: "发起 / 完成",
  stBatchQueued: "排队中",
  stBatchRunning: "执行中",
  stBatchDone: "已完成",
  stBatchPartial: "部分失败",
  stBatchPartialHint: "失败的那几张仍留在批次里，可以重跑",
  stBatchDetail: "批次明细",
  stBatchEmpty: "这一批没有可回收的文件明细。批次跑完而明细为空，通常是这些文件已被上一批删掉了。",
  stBatchDetailDesc: "这一批里每一张的结果。失败的仍留在批次里，重跑会接着删。",
  stRunningNotice: "有一批回收正在执行（{batchNo}，{done}/{total}）。执行完再发起下一批 —— 同一张图不会被两批领走，但两批同时跑会让「删了多少」在审计里说不清。",
  stColItemStatus: "结果",
  stItemPurged: "已删除",
  stItemPending: "待删除",
  stViewBatchDetail: "查看明细",
  stScanning: "正在重新扫描 —— 它只重算引用关系，不删任何文件",
  stEmptyBatches: "还没有发起过回收任务。勾选可回收的文件并确认之后，这里会出现一条批次记录。",
  stReadOnly: "你只有查看权限。发起回收需要「存储回收」权限 —— 看清单是日常查看，删是不可逆操作，两者是两个岗位。",

  acNotice: "这里定义的是「一共有哪些经营门槛、各要什么证」；给具体商家发证在「商家 · 类目授权」。两件事分开，是因为改这里影响的是全平台，而发证只影响一家店。",
  acColCode: "授权码",
  acColName: "名称",
  acColQual: "所需资质",
  acColEnabled: "可发放",
  acColMerchants: "持有商家",
  acColCategories: "引用类目",
  acColActions: "操作",
  acEnabled: "可发放",
  acDisabled: "已停用",
  acNoQual: "无证件要求",
  acConfigure: "配置",
  acNew: "新建授权码",
  acEmpty: "还没有任何授权码。类目授权靠它做门槛，一条都没有就等于所有类目都不要求资质。",
  acSectionNow: "当前配置",
  acSectionEdit: "修改",
  acFieldCode: "授权码",
  acFieldCodePh: "大写字母与下划线，如 FRESH_MEAT",
  acCodeLocked: "建成之后不可改 —— 改它等于换一张证",
  acFieldName: "名称",
  acFieldQual: "所需资质证件名",
  acFieldQualPh: "留空表示无证件要求",
  acFieldSort: "排序",
  acReasonLabel: "原因（为什么停用或恢复）",
  acReasonPh: "它决定一批商家还能不能上新品，事后要能查到依据",
  acSave: "保存",
  acDisableAct: "停用",
  acEnableAct: "恢复",
  acDisableNote: "停用「不撤销」已持有该授权的商家 —— 他们的店照常经营，只是不再发放新的。仍有类目引用它时不允许停用：那些类目会变成永远拒绝所有人。",
  acSaved: "已保存",

  scNotice: "档位本身是固定的三档（ADR-009），这里配的是「这一期开放哪几档」。一期自营模式关掉了「全平台」—— 没有虚拟商品、卡券或自营快递品支撑它。拿到 EDI 切平台模式时在这里打开即可，不用发版。",
  scEmpty: "一档服务范围都没有，商家选不了经营范围。这是初始化数据，为空说明迁移没跑到，不要在这里补。",
  scSectionNow: "当前配置",
  scColScope: "档位",
  scColDesc: "适用于",
  scColEnabled: "本期开放",
  scColMerchants: "在用商家",
  scColActions: "操作",
  scCommunity: "仅指定社区",
  scCity: "全市",
  scPlatform: "全平台",
  scCommunityDesc: "楼下的菜摊、理发店。靠自提点履约，出了这几个小区就送不到",
  scCityDesc: "家政、维修这类上门服务，或有同城配送能力的商家",
  scPlatformDesc: "无履约半径的：虚拟商品、卡券、平台自营的快递品",
  scOpen: "开放",
  scClosed: "未开放",
  scConfigure: "配置",
  scReasonLabel: "原因（为什么开或关）",
  scReasonPh: "关掉一档等于把一类商家挡在门外",
  scOpenAct: "开放这一档",
  scCloseAct: "关闭这一档",
  scLastOneNote: "至少要留一档 —— 全关等于所有商家都保存不了门店，而他们看到的只是「当前不支持这个经营范围」，会以为是自己选错了。",
  scSaved: "已保存",

  indNotice: "小微白名单按行业给。改这里会直接改变商家能选哪种主体 —— 判错的后果不是显示错误，是他进件被通道拒，而那时店已经开完了。",
  indEmpty: "行业表是空的，商家入驻时的行业选择会是一张空表。这是初始化数据，为空说明迁移没跑到，不要在这里补。",
  indColCode: "行业码",
  indColName: "名称",
  indColEnabled: "启用",
  indColWechat: "微信小微",
  indColAlipay: "支付宝小微",
  indColPoints: "强制积分",
  indColRemark: "备注",
  indColActions: "操作",
  indAllowed: "允许",
  indNotAllowed: "不允许",
  indEnabled: "启用",
  indDisabled: "停用",
  indForced: "强制",
  indConfigure: "配置",
  indSectionNow: "当前配置",
  indSectionEdit: "修改",
  indSort: "排序",
  indYes: "是",
  indNo: "否",
  indRemarkLabel: "备注（为什么这么配）",
  indRemarkPh: "改白名单会被商家追问，这里是唯一记得住原因的地方",
  indWechatOff: "关闭微信小微",
  indWechatOn: "开启微信小微",
  indAlipayOff: "关闭支付宝小微",
  indAlipayOn: "开启支付宝小微",
  indPointsOff: "取消强制积分",
  indPointsOn: "设为强制积分",
  indDisableAct: "停用该行业",
  indEnableAct: "启用该行业",
  indDisableNote: "停用只是让入驻表单里不再出现这个行业，不影响已入驻的商家。",
  indSaved: "已保存",

  toastSkinSaved: "已下发外观配置",
  toastTextsSaved: "规则文案已保存",
  toastMarketSaved: "已保存市场配置",
  toastFlagSaved: "已保存开关",

  colMarket: "市场",
  colCurrency: "货币",
  colTimezone: "时区",
  colRate: "汇率",
  colEnabled: "启用",
  colActions: "操作",
  baseCurrencyBadge: "基准货币",
  /** `{code}` 是货币代码 */
  ariaRate: "{code} 汇率",
  /** `{name}` 是市场/开关名 */
  ariaEnable: "{name} 启用",
  btnSaveRate: "保存汇率",

  colFlag: "开关",
  colKey: "键",
  colPercent: "灰度比例",
  colUpdatedAt: "上次修改",
  ariaPercent: "{name} 灰度比例",
  btnSavePercent: "保存比例",

  cardSkin: "C 端皮肤下发",
  skinReadOnlyWhat: "皮肤下发",
  skinNotice: "这里配的是 C 端的默认皮肤（C-TH-05）。用户手动选过皮肤后以本地偏好优先 —— 所以改这里只影响没自己选过的人。",
  skinSaveLabel: "下发",
  fieldDefaultSkin: "默认皮肤",
  defaultSkinHint:
    "这里只列可下发给 C 端的皮肤（与 packages/shared 的 SKINS 同名同色，改一处要改两处）。运营端专有的「商务蓝」不在其中 —— C 端没有这套。",
  fieldFestivalSkin: "节日皮肤（可空）",
  festivalOff: "不启用",
  /** `{from}` / `{to}` 是时间 */
  festivalRange: "生效区间：{from} ~ {to}",

  cardTexts: "规则文案（C 端展示）",
  textsNotice: "这三条会原样出现在 C 端的退款页、取货页和生鲜商详页。留空的话用户看到的是空白，所以服务端不允许保存空文案。",
  textRefund: "退款规则",
  textPickup: "自提规则",
  textWeighDiff: "称重差价规则",

  marketNotice: "多市场分别定价（B6）在商品域配，这里只维护市场本身与汇率。",
  /** `{cur}` 是基准货币代码 */
  baseCurrencyNotice: "{cur} 是基准货币，汇率恒为 1 —— 改了整套价格换算的原点就没了，所以界面上直接锁死。",
  marketEmpty: "还没有配置市场。市场决定了 C 端按哪种货币与时区展示，至少要有一个。",

  flagsReadOnlyWhat: "开关与灰度",
  flagsReadOnlyNote: "不能开关功能或调整灰度比例",
  flagsNotice: "灰度比例 0–100，只对支持灰度的开关有效；规则型开关（如类目资质校验）只认开/关 —— 一半商家被拦一半不被拦，没人解释得清。",
  flagsEmpty: "还没有功能开关。开关用于灰度放量，没有它新功能只能全量上线。",
  // ── 测试号固定验证码白名单（TDD-测试号固定验证码）──
  //
  // 这一页的文案要担一件事：让运营明白**它不是一个普通配置项**。
  // 只写「白名单」两个字的话，下一个人会顺手把自己的号加进去试功能。
  tpNotice: "这里每一行都是一把能登进那个手机号账号的钥匙：列表里的号请求验证码时不发真实短信，收到的码恒为这里配的值。\n\n它存在的唯一理由是苹果审核 —— 审核员在美国，收不到中国短信，而 App 登录是手机号 + 验证码。用完请停用。",
  tpGuard: "已经有账号的手机号录不进来。测试号的用法是「先录号、再用它注册」，所以录的时候它必须是个没注册过的号 —— 这条拦住的正是「拿白名单登进别人的店」。",
  tpColPhone: "手机号",
  tpColCode: "固定验证码",
  tpColEnabled: "状态",
  tpColRemark: "为什么有这一条",
  tpColActions: "操作",
  tpEnabled: "启用中",
  tpDisabled: "已停用",
  tpNoRemark: "没写",
  tpEmpty: "白名单是空的。空着是正常状态 —— 只有在送审期间才需要往里加号。",
  tpNew: "录一个测试号",
  tpEdit: "改这一条",
  tpSectionNow: "当前",
  tpFieldPhone: "手机号",
  tpFieldPhonePh: "11 位大陆手机号",
  tpFieldCode: "固定验证码",
  tpFieldCodePh: "至少 6 位",
  tpFieldRemark: "为什么有这一条",
  tpFieldRemarkPh: "这一条的来由",
  tpRemarkWhy: "不写清楚，半年后没人敢删也没人敢留。",
  tpSectionNew: "填写",
  tpPhoneLocked: "手机号建成之后不能改 —— 改它等于换一把钥匙，而旧的那把没有留痕",
  tpSave: "保存",
  tpSaved: "已保存，下一次发码即生效",
  tpEnableAct: "启用",
  tpDisableAct: "停用",
  tpRemoveAct: "删除",
  tpRemoveConfirm: "删掉之后这个号可以重新录。要删吗？",
  tpEnabledNote: "停用即时生效，不用等部署 —— 出事在这里当场关掉就行。",
};

const en: typeof zh = {
  stNotice: "The scan runs nightly. It only works out what is still referenced — 「it deletes nothing」. Deletion always starts here, from an explicit selection and confirmation.\n\nThe reclaim reason is recorded, not inferred: when the scan meets an image that is still in use it notes where it hangs, so once that reference disappears this column can still say what it used to belong to.",
  stAbnormal: "More than half of all images are marked reclaimable — most likely a column holding image URLs was never registered, which would misjudge images that are still in use. Bulk reclaim is disabled until this is understood.",
  stCardTotal: "Total",
  stCardActive: "In use",
  stCardReclaimable: "Reclaimable",
  stCardScan: "Last scan",
  stViewStores: "By store",
  stViewReclaimable: "Reclaimable",
  stViewBatches: "History",
  stColStore: "Store",
  stColCount: "Images",
  stColActive: "In use",
  stColReclaimable: "Reclaimable",
  stColRatio: "Share",
  stEntityScope: "Entity level",
  stEntityScopeHint: "Credentials, plus legacy images uploaded before stores existed — which store they belong to has no answer, so we do not guess",
  stColThumb: "Preview",
  stColBizType: "Kind",
  stColOwner: "Owner",
  stColSize: "Size · dimensions",
  stColUploaded: "Uploaded",
  stColReason: "Why reclaimable",
  stColMarked: "Listed at",
  stBizGoods: "Product",
  stBizQual: "Credential",
  stBizAftersale: "After-sale proof",
  stIncludeQual: "Include credentials",
  stIncludeQualHint: "Credential retention is a legal call, so they stay out of the list by default. Confirm the retention rules before clearing them",
  stFilterReason: "Reason",
  stReasonAll: "All",
  stReasonNeverUsed: "Never referenced",
  stReasonReplaced: "Replaced",
  stRescan: "Rescan",
  stBackfill: "Reconcile disk",
  stBackfillHint: "Records files that exist on disk but not in the ledger. Run it after a restore or a manual copy",
  stBackfillDone: "Reconciled: {scanned} files scanned, {inserted} recorded",
  stScanDone: "Scan finished: {total} tracked, {marked} newly listed, {rescued} rescued",
  stSelected: "{n} selected · {bytes}",
  stSelectAllFiltered: "Select all matching",
  stPurge: "Start reclaim",
  stConfirmTitle: "Confirm reclaim task",
  stConfirmBody: "This deletes {n} images, {bytes} in total. 「Files cannot be recovered」; the ledger rows stay, so who deleted what and when is always answerable.",
  stConfirmHint: "Type the number of images to confirm",
  stPurgeSubmitted: "Reclaim task submitted: {batchNo}",
  stEmptyNoScan: "No reclaimable images. The scan runs nightly — an empty list means the last pass found nothing that lost its references.",
  stEmptyNoScanDesc: "Hit Rescan to recompute, or there really is no garbage — which is good news.",
  stEmptyStores: "No images recorded yet. Numbers appear once merchants start uploading.",
  stColBatchNo: "Batch",
  stColOperator: "Started by",
  stColBatchStatus: "Status",
  stColBatchCount: "Images / bytes",
  stColBatchTime: "Started / finished",
  stBatchQueued: "Queued",
  stBatchRunning: "Running",
  stBatchDone: "Done",
  stBatchPartial: "Partly failed",
  stBatchPartialHint: "The failed ones stay in the batch and can be re-run",
  stBatchDetail: "Batch detail",
  stBatchEmpty: "No reclaimable files in this batch. A finished batch with no detail usually means an earlier batch already deleted them.",
  stBatchDetailDesc: "Every image in this batch. Failed ones stay in the batch; a re-run picks up where it stopped.",
  stRunningNotice: "A reclaim is running ({batchNo}, {done}/{total}). Wait for it before starting another — no image is ever claimed by two batches, but two running at once makes the audit trail ambiguous about how much was deleted.",
  stColItemStatus: "Result",
  stItemPurged: "Deleted",
  stItemPending: "Pending",
  stViewBatchDetail: "Detail",
  stScanning: "Rescanning — it only recomputes references and deletes nothing",
  stEmptyBatches: "No reclaim batches yet. Pick reclaimable files and confirm, and a batch row appears here.",
  stReadOnly: "You have view access only. Starting a reclaim needs the storage-reclaim permission — reading the list is routine, deleting is irreversible, and they are two different jobs.",


  acNotice: "This defines what trading permissions exist and which licence each one needs. Granting them to a specific merchant lives under Merchants \u00b7 Category authorisation. They are separate because a change here affects every merchant, while granting affects one shop.",
  acColCode: "Code",
  acColName: "Name",
  acColQual: "Licence required",
  acColEnabled: "Grantable",
  acColMerchants: "Merchants holding",
  acColCategories: "Categories using",
  acColActions: "Actions",
  acEnabled: "Grantable",
  acDisabled: "Disabled",
  acNoQual: "No licence needed",
  acConfigure: "Configure",
  acNew: "New auth code",
  acEmpty: "No auth codes yet. Category authorisation is gated on them, so an empty list means no category requires any licence at all.",
  acSectionNow: "Current",
  acSectionEdit: "Edit",
  acFieldCode: "Code",
  acFieldCodePh: "Upper case and underscores, e.g. FRESH_MEAT",
  acCodeLocked: "Fixed once created \u2014 changing it means a different licence",
  acFieldName: "Name",
  acFieldQual: "Licence name",
  acFieldQualPh: "Leave blank if no licence is needed",
  acFieldSort: "Sort",
  acReasonLabel: "Reason (why disable or restore)",
  acReasonPh: "It decides whether a group of merchants can still list new items",
  acSave: "Save",
  acDisableAct: "Disable",
  acEnableAct: "Restore",
  acDisableNote: "Disabling does not revoke merchants who already hold it \u2014 their shops keep running, the code simply stops being granted. Disabling is blocked while categories still require it: those categories would reject everyone forever.",
  acSaved: "Saved",

  scNotice: "The three scopes themselves are fixed (ADR-009); what you set here is which ones this phase opens. Phase one runs first-party and keeps Platform-wide closed \u2014 nothing supports it yet (no virtual goods, vouchers or first-party shipping). Open it here once the EDI licence lands; no release needed.",
  scEmpty: "No service scope tiers at all, so merchants cannot pick a business scope. This is seed data — an empty table means the migration never ran; do not fill it in here.",
  scSectionNow: "Current",
  scColScope: "Scope",
  scColDesc: "Fits",
  scColEnabled: "Open this phase",
  scColMerchants: "Merchants using",
  scColActions: "Actions",
  scCommunity: "Selected communities",
  scCity: "City-wide",
  scPlatform: "Platform-wide",
  scCommunityDesc: "The veg stall downstairs. Fulfilled through pickup points; it cannot reach beyond those blocks",
  scCityDesc: "Home services and repairs, or merchants with city-wide delivery",
  scPlatformDesc: "No fulfilment radius: virtual goods, vouchers, first-party shipped items",
  scOpen: "Open",
  scClosed: "Closed",
  scConfigure: "Configure",
  scReasonLabel: "Reason (why open or close)",
  scReasonPh: "Closing a scope shuts a whole class of merchants out",
  scOpenAct: "Open this scope",
  scCloseAct: "Close this scope",
  scLastOneNote: "At least one must stay open \u2014 closing them all means no merchant can save a shop, and all they see is \u201cthat service scope is not available\u201d, which reads as their own mistake.",
  scSaved: "Saved",

  indNotice: "The micro-merchant allowlist is granted per industry. Changing it changes which legal form a merchant may pick — get it wrong and the channel rejects their onboarding, by which time the shop is already open.",
  indEmpty: "The industry table is empty, so merchants get an empty picker at onboarding. This is seed data — an empty table means the migration never ran; do not fill it in here.",
  indColCode: "Code",
  indColName: "Name",
  indColEnabled: "Enabled",
  indColWechat: "WeChat micro",
  indColAlipay: "Alipay micro",
  indColPoints: "Points forced",
  indColRemark: "Note",
  indColActions: "Actions",
  indAllowed: "Allowed",
  indNotAllowed: "Not allowed",
  indEnabled: "Enabled",
  indDisabled: "Disabled",
  indForced: "Forced",
  indConfigure: "Configure",
  indSectionNow: "Current",
  indSectionEdit: "Change",
  indSort: "Sort",
  indYes: "Yes",
  indNo: "No",
  indRemarkLabel: "Note (why this setting)",
  indRemarkPh: "Merchants will ask about allowlist changes; this is the only place that remembers why",
  indWechatOff: "Disable WeChat micro",
  indWechatOn: "Enable WeChat micro",
  indAlipayOff: "Disable Alipay micro",
  indAlipayOn: "Enable Alipay micro",
  indPointsOff: "Stop forcing points",
  indPointsOn: "Force points",
  indDisableAct: "Disable industry",
  indEnableAct: "Enable industry",
  indDisableNote: "Disabling only hides it from the onboarding form; existing merchants are unaffected.",
  indSaved: "Saved",

  toastSkinSaved: "Appearance settings pushed",
  toastTextsSaved: "Policy copy saved",
  toastMarketSaved: "Market settings saved",
  toastFlagSaved: "Flag saved",

  colMarket: "Market",
  colCurrency: "Currency",
  colTimezone: "Time zone",
  colRate: "FX rate",
  colEnabled: "Enabled",
  colActions: "Actions",
  baseCurrencyBadge: "Base currency",
  ariaRate: "{code} FX rate",
  ariaEnable: "Enable {name}",
  btnSaveRate: "Save rate",

  colFlag: "Flag",
  colKey: "Key",
  colPercent: "Rollout %",
  colUpdatedAt: "Last changed",
  ariaPercent: "{name} rollout percentage",
  btnSavePercent: "Save percentage",

  cardSkin: "Push skin to C-end",
  skinReadOnlyWhat: "skin push",
  skinNotice:
    "This sets the default skin for the C-end app (C-TH-05). Once a user picks a skin themselves, their local choice wins — so changing this only affects people who never chose one.",
  skinSaveLabel: "Push",
  fieldDefaultSkin: "Default skin",
  defaultSkinHint:
    "Only skins that exist on the C-end are listed (same names and colours as SKINS in packages/shared — change one, change both). The ops-only “Business blue” is excluded: the C-end has no such skin.",
  fieldFestivalSkin: "Seasonal skin (optional)",
  festivalOff: "Off",
  festivalRange: "Active window: {from} ~ {to}",

  cardTexts: "Policy copy (shown on the C-end)",
  textsNotice:
    "These three appear verbatim on the C-end refund page, pickup page and fresh-produce detail page. Left blank the user sees nothing, so the server rejects empty copy.",
  textRefund: "Refund policy",
  textPickup: "Pickup policy",
  textWeighDiff: "Weight-difference policy",

  marketNotice: "Per-market pricing (B6) is configured in the catalog domain; this page only maintains markets and FX rates.",
  baseCurrencyNotice:
    "{cur} is the base currency and its rate is always 1 — change it and every price conversion loses its origin, so it is locked in the UI.",
  marketEmpty: "No markets configured yet. A market decides which currency and time zone the C-end shows, so there must be at least one.",

  flagsReadOnlyWhat: "flags & rollout",
  flagsReadOnlyNote: "cannot toggle features or change rollout percentages",
  flagsNotice: "Rollout is 0–100 and only applies to flags that support it; rule-style flags (such as the category qualification gate) are on/off only — half the merchants blocked and half not is impossible to explain.",
  flagsEmpty: "No feature flags yet. Flags are how features roll out gradually; without one a new feature can only ship to everybody at once.",
  tpNotice: "Every row here is a key that unlocks the account behind that phone number: numbers on this list get no real SMS, and the code they receive is always the one configured here.\n\nIt exists for one reason only \u2014 Apple review. Reviewers are in the US, cannot receive Chinese SMS, and the app signs in with phone + code. Disable the entry once you are done.",
  tpGuard: "A number that already has an account cannot be added. A test number is meant to be added first and registered afterwards, so it must be an unregistered number \u2014 that is what stops the list being used to walk into someone else's shop.",
  tpColPhone: "Phone",
  tpColCode: "Fixed code",
  tpColEnabled: "Status",
  tpColRemark: "Why this exists",
  tpColActions: "Actions",
  tpEnabled: "Active",
  tpDisabled: "Disabled",
  tpNoRemark: "Not stated",
  tpEmpty: "The list is empty. Empty is the normal state \u2014 numbers are only needed while an app review is in flight.",
  tpNew: "Add a test number",
  tpEdit: "Edit this entry",
  tpSectionNow: "Current",
  tpFieldPhone: "Phone",
  tpFieldPhonePh: "11-digit Chinese mainland mobile",
  tpFieldCode: "Fixed code",
  tpFieldCodePh: "At least 6 digits",
  tpFieldRemark: "Why this exists",
  tpFieldRemarkPh: "Why this entry exists",
  tpRemarkWhy: "Without this, nobody will dare delete it \u2014 or keep it \u2014 six months from now.",
  tpSectionNew: "Details",
  tpPhoneLocked: "The number cannot be changed once created \u2014 changing it swaps the key with no trace of the old one",
  tpSave: "Save",
  tpSaved: "Saved. It takes effect on the next code request",
  tpEnableAct: "Enable",
  tpDisableAct: "Disable",
  tpRemoveAct: "Delete",
  tpRemoveConfirm: "Once deleted the number can be added again. Delete it?",
  tpEnabledNote: "Disabling takes effect immediately, with no deploy \u2014 if something goes wrong, switch it off right here.",
};

export const SYSTEM_COPY: PageCopy<typeof zh> = { zh, en };

/** 拆出去的 tab 组件靠它接文案。 */
export type SystemCopy = typeof zh;
