// 订单页文案（矩阵 P-4.1）。与 page.tsx 挨着放，改页面时一起改。
//
// 译法沿用 `lib/i18n/messages/en.ts` 里定的三条：状态用运营台通用说法、
// 业务专名跟平台自己的英文名（子订单 = sub-order、自提 = pickup）、句子大小写。
import type { PageCopy } from "@/lib/use-copy";

const zh = {
  exceptionReadOnlyWhat: "异常单队列",
  proxyReadOnlyWhat: "代客下单与取消",
  exceptionNotice: "这是订单卡在某个状态超时的队列，实时算出来的 —— 单子一推进它就自己消失，不需要「标记已处理」。阈值按状态分别给：待支付 15 分钟就该关单，而「已送达待自提」放一天很正常。",
  searchException: "搜子订单号 / 商家 / 下单人",
  filterKind: "按成因筛选",
  filterKindAll: "全部成因",
  kindStuck: "卡在当前状态",
  kindPayTimeout: "待支付超时未关单",
  colKind: "成因",
  colStuck: "已卡时长",
  colThreshold: "允许时长",
  stuckValue: "{n} 分钟",
  actionIntervene: "人工干预",
  emptyException: "没有超时的订单 —— 所有在途单都在各自状态的时限内。有单卡住时会自动出现在这里。",
  interveneTitle: "干预 {no}",
  secIntervene: "改状态",
  secHistory: "干预记录",
  fieldTo: "推到哪个状态",
  toPick: "请选择目标状态",
  toHint: "只列出状态机允许的下一步：人工干预也不能绕过状态机。",
  fieldRemark: "原因",
  remarkPlaceholder: "例：骑手已送达，系统漏回传",
  noHistory: "这单还没有人工干预过。",
  toastIntervened: "已改状态，原因已留痕",
  proxyNotice: "客服代顾客下单或取消。「单落在顾客名下」（先按手机后四位找到本人），钱由他自己付：线下付是当面付给商家，线上付是他在小程序里付。券和积分不代用，地址不代填。一次只能下一个商家的货。",
  proxyCreateTitle: "代客下单",
  fieldBuyer: "下单人",
  fieldCommunity: "社区",
  fieldMerchant: "商家",
  pickCommunity: "请选择社区",
  pickMerchant: "请选择商家",
  merchantHint: "全站按商家拆单，一张单只能有一个商家的商品。",
  fieldFulfill: "履约方式",
  fieldItems: "商品",
  fieldQty: "数量",
  pickSku: "请选择商品",
  pickMerchantFirst: "请先选商家",
  stockLeft: "余 {n}",
  btnAddLine: "加一件",
  btnRemoveLine: "移除",
  fieldProxyReason: "代下原因",
  proxyReasonPlaceholder: "例：用户电话下单，不会用小程序",
  proxyReasonHint: "代客下单绕过了用户自主下单，得留下为什么。",

  // ── 代客下单：先有人，才有单
  fieldCustomer: "顾客",
  phoneTailPlaceholder: "手机后四位",
  customerPickHint: "输入手机后四位找到本人 —— 单要落在他名下，他才看得到、付得了",
  /** `{tail}` 是手机后四位，`{entity}` 是他在哪家店的会员 */
  customerCandidate: "尾号 {tail} · {entity}",
  /** `{tail}` 是手机后四位 */
  customerPicked: "已选：尾号 {tail}",
  customerNotFound: "没找到 —— 这个号还没在平台上留下过记录",
  customerNoAccount: "未绑账号",
  customerNoAccountHint: "这个人还没绑账号 —— 填完整手机号就行，下面会按这个号给他建一个。",
  fieldFullPhone: "完整手机号",
  fullPhonePlaceholder: "11 位手机号",
  fullPhoneHint: "没装过小程序的顾客走这条：按这个号给他建账号。他日后用同一个号登录，就能看到这张单并付款。",
  fulfillProxyHint: "只能到点自取。要送货得顾客自己在小程序里下单 —— 收货地址得他自己选",
  fieldPayMode: "支付方式",
  payModeOffline: "线下付（当面付给商家）",
  payModeOnline: "线上付（顾客自己在小程序里付）",
  payModeOfflineHint: "落「待线下付」，商家当面收款后自己确认。要商家开了线下收款才能选",
  payModeOnlineHint: "落「待支付」，顾客要在关单时限内自己付掉，否则会自动关单",
  proxyTotal: "合计 {amount}",
  btnProxyCreate: "代客下单",
  toastProxyCreated: "已生成 {no}，待用户支付",
  actionProxyCancel: "代客取消",
  cancelTitle: "代客取消 {no}",
  secCancel: "取消原因",
  fieldCancelReason: "原因",
  cancelReasonPlaceholder: "例：用户电话要求取消",
  cancelRefundHint: "这单已支付，取消即原路退款 —— 没有「取消但不退款」这条路。",
  cancelUnpaidHint: "这单还没付款，取消不涉及退款。",
  btnProxyCancel: "确认取消",
  toastProxyCancelled: "已取消，原因已留痕",
  toastResolved: "已处置，结论已留痕",
  toastIgnored: "已忽略，理由已留痕",
  toastCloseSaved: "关单策略已保存",
  secDecide: "处置",
  actionPick: "请选择处置方式",

  payReadOnlyWhat: "支付对账与掉单处置",
  payReadOnlyNote: "不能处置差异或改关单策略",
  payNotice:
    "对账差异分三类，处置方式完全不同：渠道有平台无 → 补单或退款；平台有渠道无 → 冲正；两边金额不符 → 查是折扣算错还是重复扣款。所以这里不把它们笼统叫「异常」。",
  repairNotice:
    "这一队列是「渠道收了钱、平台没记上」的那些单 —— 用户已经付款却没有订单。多数来自关单太快，所以处置完记得去看一眼关单策略。",
  searchRecon: "搜索差异号 / 渠道流水号 / 订单号",
  filterDiffType: "按差异类型筛选",
  filterDiffTypeAll: "全部类型",
  filterReconStatus: "按处置状态筛选",
  filterReconStatusAll: "全部状态",
  emptyRecon: "没有符合条件的对账差异。渠道账单每日凌晨拉取，当天的差异要次日才出现。",
  emptyRepair: "没有待补偿的掉单。这说明关单时限设得合适 —— 用户付款前订单没被关掉。",

  diffChannelOnly: "渠道有 · 平台无",
  diffPlatformOnly: "平台有 · 渠道无",
  diffAmount: "金额不符",
  reconOpen: "待处置",
  reconResolved: "已处置",
  reconIgnored: "已忽略",

  colDiffNo: "差异号",
  colBillDate: "账期",
  colChannel: "渠道",
  colDiffType: "差异类型",
  colChannelTxn: "渠道流水号",
  colChannelAmount: "渠道金额",
  colPlatformAmount: "平台金额",
  colGap: "差额",
  colReconStatus: "处置状态",
  actionResolve: "处置",
  none: "—",

  drawerRecon: "处置差异 {no}",
  fieldAction: "处置方式",
  actionCreateOrder: "补单（按渠道实收）",
  actionRefund: "原路退款",
  /** `{amount}` 是渠道实收 */
  actionHint: "补单金额恒等于渠道实收 {amount}，不提供修改入口 —— 能改就一定会有人改错。",
  fieldResolution: "处置结论",
  resolutionPlaceholder: "写清依据：下个月同样的差异，得靠这段话判断能不能照做",
  btnResolve: "标记已处置",
  btnIgnore: "忽略",
  fieldRecovered: "补单号",
  fieldResolvedBy: "处置人",

  closeTitle: "关单策略",
  closeReadOnlyWhat: "关单策略配置",
  closeNotice:
    "关单时限与掉单是直接因果：关得越快，「用户正在付款、订单已被关掉」的窗口就越大，而那正是对账差异的主要来源。所以这两件事放在同一页。",
  fieldUnpaidMinutes: "未支付自动关单（分钟）",
  /** `{min}` / `{max}` 是上下限 */
  unpaidHint: "{min}–{max} 分钟。收银台正常停留 1~3 分钟，留足余量比省那点库存重要。",
  fieldRemindBefore: "关单前提醒（分钟）",
  remindHint: "必须小于关单时限，否则提醒发出时订单已经关了。填 0 = 不提醒。",
  fieldAutoRefund: "关单后收到支付回调时自动退款",
  autoRefundHint: "关掉它意味着这笔钱要人工处理 —— 但至少不会静默退掉一笔本可以补单的钱。",

  desc: "全量子订单检索 · 按商家拆单视图（P-4.1）",
  notice: "列表展示的是「子订单」：一次结算按商家拆成多张子单，分账、售后、结算都以子单为单位（矩阵 §七 E3）。",
  searchPlaceholder: "搜索订单号 / 商家 / 买家",
  filterStatus: "按状态筛选",
  filterStatusAll: "全部状态",
  storeFilterChip: "只看门店 {no}",
  storeFilterClear: "看全部门店",
  filterFulfill: "按履约方式筛选",
  filterFulfillAll: "全部履约方式",
  empty: "没有符合条件的订单。一期交易闭环（M1-1）尚未打通时，这里只有 mock 数据。",

  colSubOrderNo: "子订单号",
  colMerchant: "商家",
  colCommunity: "社区",
  colFulfill: "履约方式",
  colTraffic: "流量来源",
  colBuyer: "买家",
  colPaid: "实付",
  colStatus: "状态",
  colCreatedAt: "下单时间",
  colActions: "操作",
  actionDetail: "详情",

  exportSheet: "订单",
  exportParentNo: "父单号",
  exportPaidYuan: "实付(元)",

  secOverview: "订单概况",
  secItems: "商品明细",
  secSiblings: "同次结算的其它子订单",
  secSiblingsDesc: "一次结算按商家拆成多张子单（矩阵 §七 E3）",
  fieldPickup: "自提点",
  fieldPaidAt: "支付时间",
  drawerParent: "父单 {no}",
  loading: "加载中…",
  noSiblings: "无 —— 本次结算只涉及一个商家",

  // ── 四轴对账总览 ──
  axesTitle: "对账覆盖",
  axesSubtitle: "四条轴各跑一轮",
  axesLoading: "正在跑四条轴…",
  axesBroken: "{axes} 今天没跑成 —— 「这一类差异今天没有人在看」。它与「零差异」在页面上长得一样，含义完全相反。",
  axisName_PAYMENT: "收款",
  axisName_SPLIT: "分账",
  axisName_PAYOUT: "出款",
  axisName_POINTS_POOL: "积分池",
  axisFailed: "没跑成",
  axisClean: "无新差异",
  axisOpened: "新增 {n} 条",
  axisCounts: "扫 {scanned} · 自动收口 {resolved} · 判不了 {deferred}",

};

const en: typeof zh = {
  exceptionReadOnlyWhat: "the exception queue",
  proxyReadOnlyWhat: "proxy ordering and cancellation",
  exceptionNotice: "This queue holds orders stuck in a state past its limit. It is computed live — an order leaves the moment it moves on, so there is no “mark as handled”. Limits are per state: an unpaid order should close after 15 minutes, while “arrived, awaiting pickup” sitting for a day is normal.",
  searchException: "Search sub-order no. / merchant / customer",
  filterKind: "Filter by cause",
  filterKindAll: "All causes",
  kindStuck: "Stuck in state",
  kindPayTimeout: "Unpaid past close time",
  colKind: "Cause",
  colStuck: "Stuck for",
  colThreshold: "Limit",
  stuckValue: "{n} min",
  actionIntervene: "Intervene",
  emptyException: "No orders are overdue — everything in flight is within the limit for its state. Anything that gets stuck shows up here on its own.",
  interveneTitle: "Intervene on {no}",
  secIntervene: "Change state",
  secHistory: "Intervention log",
  fieldTo: "Move to",
  toPick: "Choose the target state",
  toHint: "Only the steps the state machine allows are listed — a human override still cannot skip the machine.",
  fieldRemark: "Reason",
  remarkPlaceholder: "e.g. Courier delivered it; the system missed the callback",
  noHistory: "No one has intervened on this order yet.",
  toastIntervened: "State changed — the reason is recorded",
  proxyNotice: "Place or cancel an order for a customer. The order lands in their name (find them by the last 4 digits of their phone) and they pay for it — in person to the merchant, or in the app. Coupons, points and addresses are never filled in for them. One order covers one merchant only.",
  proxyCreateTitle: "Place a proxy order",
  fieldBuyer: "Customer",
  fieldCommunity: "Community",
  fieldMerchant: "Merchant",
  pickCommunity: "Choose a community",
  pickMerchant: "Choose a merchant",
  merchantHint: "Orders split by merchant platform-wide, so one order carries one merchant’s goods.",
  fieldFulfill: "Fulfilment",
  fieldItems: "Items",
  fieldQty: "Qty",
  pickSku: "Choose an item",
  pickMerchantFirst: "Choose a merchant first",
  stockLeft: "{n} left",
  btnAddLine: "Add an item",
  btnRemoveLine: "Remove",
  fieldProxyReason: "Why place it for them",
  proxyReasonPlaceholder: "e.g. Ordered by phone; cannot use the mini program",
  proxyReasonHint: "A proxy order bypasses the customer ordering for themselves, so the reason has to be on record.",

  // ── Proxy ordering: find the person first
  fieldCustomer: "Customer",
  phoneTailPlaceholder: "Last 4 digits",
  customerPickHint: "Find them by the last 4 digits — the order has to be theirs, or they cannot see or pay it",
  /** `{tail}` is the phone tail, `{entity}` the merchant they are a member of */
  customerCandidate: "…{tail} · {entity}",
  /** `{tail}` is the phone tail */
  customerPicked: "Chosen: …{tail}",
  customerNotFound: "No match — this number has no record on the platform yet",
  customerNoAccount: "no account",
  customerNoAccountHint: "No account yet — just type their full phone number below and one gets created for them.",
  fieldFullPhone: "Full phone number",
  fullPhonePlaceholder: "11 digits",
  fullPhoneHint: "For customers who have never used the app: an account is created for this number. When they later sign in with it, this order is waiting for them.",
  fulfillProxyHint: "Pickup only. Delivery has to be placed by the customer — they pick the address themselves",
  fieldPayMode: "Payment",
  payModeOffline: "In person (pay the merchant)",
  payModeOnline: "In the app (the customer pays)",
  payModeOfflineHint: "Lands as awaiting in-person payment; the merchant confirms after collecting. Only if they accept in-person payment",
  payModeOnlineHint: "Lands as awaiting payment; the customer has to pay before the order times out",
  proxyTotal: "Total {amount}",
  btnProxyCreate: "Place the order",
  toastProxyCreated: "{no} created — awaiting the customer’s payment",
  actionProxyCancel: "Cancel for customer",
  cancelTitle: "Cancel {no} for the customer",
  secCancel: "Cancellation reason",
  fieldCancelReason: "Reason",
  cancelReasonPlaceholder: "e.g. The customer asked to cancel by phone",
  cancelRefundHint: "This order is paid, so cancelling refunds to source — there is no “cancel without refunding”.",
  cancelUnpaidHint: "This order is unpaid, so cancelling involves no refund.",
  btnProxyCancel: "Confirm cancellation",
  toastProxyCancelled: "Cancelled — the reason is recorded",
  toastResolved: "Resolved — the note is recorded",
  toastIgnored: "Ignored — the reason is recorded",
  toastCloseSaved: "Auto-close rules saved",
  secDecide: "Resolution",
  actionPick: "Choose how to handle it",

  payReadOnlyWhat: "payment reconciliation & dropped-order handling",
  payReadOnlyNote: "cannot resolve differences or change the auto-close rules",
  payNotice:
    "Differences come in three kinds and are handled quite differently: channel-only → create the order or refund; platform-only → reverse the entry; amount mismatch → find out whether a discount was miscalculated or the customer was charged twice. That is why they are not lumped together as “errors”.",
  repairNotice:
    "This queue holds payments the channel took but the platform never recorded — the customer paid and has no order. Most come from closing orders too quickly, so check the auto-close rules once you are done here.",
  searchRecon: "Search difference no. / channel txn no. / order no.",
  filterDiffType: "Filter by difference type",
  filterDiffTypeAll: "All types",
  filterReconStatus: "Filter by state",
  filterReconStatusAll: "All states",
  emptyRecon: "No differences match these filters. Channel statements are pulled overnight, so today's differences appear tomorrow.",
  emptyRepair: "No dropped orders to recover. That means the close window is set sensibly — orders are not being closed before customers pay.",

  diffChannelOnly: "Channel only",
  diffPlatformOnly: "Platform only",
  diffAmount: "Amount mismatch",
  reconOpen: "Open",
  reconResolved: "Resolved",
  reconIgnored: "Ignored",

  colDiffNo: "Difference no.",
  colBillDate: "Statement date",
  colChannel: "Channel",
  colDiffType: "Kind",
  colChannelTxn: "Channel txn no.",
  colChannelAmount: "Channel amount",
  colPlatformAmount: "Platform amount",
  colGap: "Gap",
  colReconStatus: "State",
  actionResolve: "Resolve",
  none: "—",

  drawerRecon: "Resolve difference {no}",
  fieldAction: "How to handle it",
  actionCreateOrder: "Create the order (at the amount the channel took)",
  actionRefund: "Refund to source",
  actionHint: "The order is created for exactly what the channel took ({amount}); there is no field to change it — anything editable will eventually be edited wrong.",
  fieldResolution: "Resolution",
  resolutionPlaceholder: "State your reasoning: next month someone has to decide from this note whether the same call applies",
  btnResolve: "Mark resolved",
  btnIgnore: "Ignore",
  fieldRecovered: "Recovered order no.",
  fieldResolvedBy: "Resolved by",

  closeTitle: "Auto-close rules",
  closeReadOnlyWhat: "auto-close rule configuration",
  closeNotice:
    "The close window causes dropped orders directly: the shorter it is, the wider the window in which a customer is still paying while their order is already closed — and that is where most reconciliation differences come from. Hence both live on one page.",
  fieldUnpaidMinutes: "Close unpaid orders after (minutes)",
  unpaidHint: "{min}–{max} minutes. Customers spend 1–3 minutes at the checkout sheet; leaving headroom matters more than the stock it holds.",
  fieldRemindBefore: "Remind before closing (minutes)",
  remindHint: "Must be less than the close window, otherwise the reminder goes out after the order is already closed. 0 = no reminder.",
  fieldAutoRefund: "Auto-refund late payment callbacks",
  autoRefundHint: "Turning this off means a human handles the money — but nothing gets silently refunded when it could have become an order.",

  desc: "All sub-orders · split by merchant (P-4.1)",
  notice:
    "This list shows sub-orders: one checkout is split into several sub-orders by merchant, and settlement, after-sales and payouts all work per sub-order (matrix §7 E3).",
  searchPlaceholder: "Search order no. / merchant / buyer",
  filterStatus: "Filter by status",
  filterStatusAll: "All statuses",
  storeFilterChip: "Store {no} only",
  storeFilterClear: "All stores",
  filterFulfill: "Filter by fulfillment",
  filterFulfillAll: "All fulfillment types",
  empty: "No orders match these filters. Until the phase-1 transaction loop (M1-1) is wired up, this page only holds mock data.",

  colSubOrderNo: "Sub-order no.",
  colMerchant: "Merchant",
  colCommunity: "Community",
  colFulfill: "Fulfillment",
  colTraffic: "Traffic source",
  colBuyer: "Buyer",
  colPaid: "Paid",
  colStatus: "Status",
  colCreatedAt: "Placed at",
  colActions: "Actions",
  actionDetail: "Details",

  exportSheet: "Orders",
  exportParentNo: "Parent order no.",
  exportPaidYuan: "Paid (CNY)",

  secOverview: "Order overview",
  secItems: "Items",
  secSiblings: "Other sub-orders in the same checkout",
  secSiblingsDesc: "One checkout splits into several sub-orders by merchant (matrix §7 E3)",
  fieldPickup: "Pickup point",
  fieldPaidAt: "Paid at",
  drawerParent: "Parent order {no}",
  loading: "Loading…",
  noSiblings: "None — this checkout involved a single merchant",

  axesTitle: "Reconciliation coverage",
  axesSubtitle: "one pass per axis",
  axesLoading: "Running all four axes…",
  axesBroken: "{axes} did not run today — 「nobody is watching this class of difference right now」. It looks identical to «no differences» on this page but means the opposite.",
  axisName_PAYMENT: "Collection",
  axisName_SPLIT: "Split",
  axisName_PAYOUT: "Payout",
  axisName_POINTS_POOL: "Points pool",
  axisFailed: "Did not run",
  axisClean: "No new differences",
  axisOpened: "{n} new",
  axisCounts: "{scanned} scanned · {resolved} auto-closed · {deferred} undecidable",

};

export const ORDERS_COPY: PageCopy<typeof zh> = { zh, en };

/** 拆出去的 tab 组件靠它接文案，避免各自再写一遍 `ReturnType<typeof useCopy<…>>`。 */
export type OrdersCopy = typeof zh;
