// 营销活动文案（矩阵 P-13.1 / P-13.2）。
import type { PageCopy } from "@/lib/use-copy";

const zh = {
  tabCoupons: "券模板",
  tabIssues: "发放记录",
  tabCampaigns: "活动",
  tabSlots: "内容位",
  tabMember: "会员卡与权益",
  memberNotice: "会员卡卖出去的是承诺，不是配置：只要有人持卡，权益与月费就锁死 —— 要调整请新建一张卡并把这张停售，让在售的那张始终与用户当初买的一致。会员折扣不得低于 {zhe} 折，月费远补不回被打穿的毛利。",
  searchCard: "搜会员卡号 / 名称",
  filterCardStatus: "按会员卡状态筛选",
  filterCardStatusAll: "全部会员卡状态",
  mcDraft: "草稿",
  mcActive: "在售",
  mcPaused: "暂停售卖",
  mcEnded: "已停售",
  colCardNo: "会员卡号",
  colCardName: "名称",
  colLevel: "等级",
  colPrice: "月费",
  colBenefits: "权益",
  colHolders: "持卡人数",
  colCardStatus: "状态",
  colUpdatedAt: "最近修改",
  perMonth: "{amount}/月",
  holderCount: "{n} 人",
  bkDiscount: "会员折扣",
  bkFreeShipping: "免运费",
  bkCouponPack: "月赠券",
  bkPointsBoost: "积分加成",
  bvDiscount: "{zhe} 折",
  bvFreeShipping: "{n} 次/月",
  bvCouponPack: "{n} 张/月",
  bvPoints: "{n} 倍",
  actionNewCard: "新建会员卡",
  actionEditCard: "编辑",
  actionRemoveBenefit: "移除",
  emptyCard: "还没有会员卡。新建一张草稿卡、配好权益再启用 —— 启用后有人开卡，权益就锁死了。",
  newCardTitle: "新建会员卡",
  editCardTitle: "编辑 {name}",
  lockedNotice: "这张卡已有 {n} 人持卡，权益与月费已锁定。要调整请新建一张卡，并把这张停售。",
  secCardBasic: "基本信息",
  secBenefits: "权益",
  secHolders: "持卡情况",
  fieldPrice: "月费（元）",
  fieldBenefitKind: "权益类型",
  fieldBenefitValue: "权益值",
  fieldCoupon: "绑定券模板",
  pickCoupon: "请选择券模板",
  btnAddBenefit: "加一项权益",
  benefitsHint: "同一类权益只能配一条：配两条时命中哪条取决于顺序。月赠券必须绑一张已启用的券 —— 绑草稿券的话，用户开卡当天就领不到。",
  btnSaveCard: "保存会员卡",
  toastCardSaved: "会员卡已保存",
  toastCardStatus: "会员卡状态已更新",
  memberReadOnlyWhat: "会员卡与权益",

  targetAll: "全体用户",
  targetNewUser: "新客",
  targetCommunity: "指定社区",
  targetSingleUser: "指定用户",

  /** `{n}` 是折扣数，如 8.5 */
  discountValue: "{n} 折",

  toastCouponStatus: "已更新券状态",
  toastBudgetSaved: "已调整预算",
  /** `{n}` 张数，`{amount}` 金额 */
  toastIssued: "已发放 {n} 张，占用预算 {amount}",
  toastSlotStatus: "已更新上下线状态",

  colCouponNo: "券编号",
  colName: "名称",
  colType: "类型",
  colValue: "面额",
  colThreshold: "门槛",
  noThreshold: "无",
  colBudget: "预算使用",
  colIssuedRedeemed: "已发 / 已核销",
  colValidRange: "有效期",
  colStatus: "状态",
  colActions: "操作",
  entityCoupon: "券模板",
  entityCampaign: "活动",
  entitySlot: "内容位",
  btnActivate: "启用",
  btnIssue: "发券",
  btnResume: "恢复",

  colIssueNo: "发放单号",
  colCoupon: "券",
  colTarget: "发放对象",
  colCount: "张数",
  colAmount: "占用预算",
  colOperator: "操作人",
  colTime: "时间",

  colCampaignNo: "活动编号",
  colPosition: "位置",
  colRange: "起止时间",
  colSkuCount: "商品数",

  colSlotNo: "位号",
  colTitle: "标题",
  colSort: "排序",
  colCommunities: "投放社区",
  allCommunities: "全部社区",
  colOnOffline: "上线 / 下线",
  colEnabled: "启用",
  /** `{title}` 是内容位标题 */
  ariaEnable: "{title} 启用开关",

  readOnlyWhat: "券发放与预算调整",
  readOnlyNote: "不能发券、启停或归档",
  couponNotice:
    "预算是唯一挡住「发着发着超支」的地方：超预算的发放会被直接拒绝，改预算也不能改到低于已发放金额。客服的补偿券走同一套校验（矩阵 §2.3）。",
  campaignNotice: "同一位置的「秒杀场次不可重叠」—— 场次的意义就在这里；跨位置并行是允许的（首页与频道页可同时跑）。",
  searchCoupons: "搜索券编号 / 名称",
  searchIssues: "搜索发放单号 / 券名 / 操作人",
  searchCampaigns: "搜索活动编号 / 名称 / 位置",
  searchSlots: "搜索位号 / 标题",
  filterCouponType: "按券类型筛选",
  filterCouponTypeAll: "全部券类型",
  filterCampaignType: "按活动类型筛选",
  filterCampaignTypeAll: "全部活动类型",
  filterStatus: "按状态筛选",
  filterStatusAll: "全部状态",
  filterKind: "按位置筛选",
  filterKindAll: "全部位置",
  emptyCoupons: "没有符合条件的券模板。C 端领券中心的券都来自这里，没有券它就是空的。",
  emptyIssues: "还没有发放记录。每次发券都会在这里留痕（含客服的补偿券）。",
  emptyCampaigns: "没有符合条件的活动。清空筛选，或换个时间段看看。",
  emptySlots: "没有符合条件的内容位。C 端首页的楼层与 Banner 都由这里下发。",

  /** `{name}` 是券名 */
  issueTitle: "发放「{name}」",
  btnConfirmIssue: "确认发放",
  fieldRemainBudget: "剩余预算",
  /** `{value}` 是单张面额 */
  perCoupon: "（单张 {value}）",
  fieldTarget: "发放对象",
  fieldTargetDesc: "定向说明",
  targetDescPlaceholder: "如：锦绣花园 / 海棠（售后补偿）",
  fieldCount: "发放张数",
  countHint: "超出剩余预算会被拒绝，不会部分发放。",

  budgetTitle: "调整预算",
  fieldBudget: "预算（元）",
  budgetHint: "不能低于已发放金额，否则账面立刻超支。",
  save: "保存",
};

const en: typeof zh = {
  tabCoupons: "Coupon templates",
  tabIssues: "Issue records",
  tabCampaigns: "Campaigns",
  tabSlots: "Content slots",
  tabMember: "Membership & benefits",
  memberNotice: "A membership sold is a promise, not a setting: once anyone holds the card, its benefits and monthly fee lock. To change them, create a new card and retire this one, so what is on sale always matches what people bought. Member discounts cannot go below {off}% off — the monthly fee never covers the margin that deep a cut burns.",
  searchCard: "Search card no. / name",
  filterCardStatus: "Filter by card state",
  filterCardStatusAll: "All card states",
  mcDraft: "Draft",
  mcActive: "On sale",
  mcPaused: "Sales paused",
  mcEnded: "Retired",
  colCardNo: "Card no.",
  colCardName: "Name",
  colLevel: "Tier",
  colPrice: "Monthly fee",
  colBenefits: "Benefits",
  colHolders: "Holders",
  colCardStatus: "State",
  colUpdatedAt: "Last changed",
  perMonth: "{amount}/mo",
  holderCount: "{n}",
  bkDiscount: "Member discount",
  bkFreeShipping: "Free shipping",
  bkCouponPack: "Monthly coupons",
  bkPointsBoost: "Points boost",
  bvDiscount: "{off}% off",
  bvFreeShipping: "{n}/mo",
  bvCouponPack: "{n}/mo",
  bvPoints: "{n}x",
  actionNewCard: "New card",
  actionEditCard: "Edit",
  actionRemoveBenefit: "Remove",
  emptyCard: "No membership cards yet. Draft one, set its benefits, then put it on sale — once someone buys it, those benefits are locked.",
  newCardTitle: "New membership card",
  editCardTitle: "Edit {name}",
  lockedNotice: "{n} people hold this card, so its benefits and fee are locked. To change them, create a new card and retire this one.",
  secCardBasic: "Basics",
  secBenefits: "Benefits",
  secHolders: "Holders",
  fieldPrice: "Monthly fee (¥)",
  fieldBenefitKind: "Benefit type",
  fieldBenefitValue: "Value",
  fieldCoupon: "Linked coupon",
  pickCoupon: "Choose a coupon",
  btnAddBenefit: "Add a benefit",
  benefitsHint: "One entry per benefit type: with two, which one wins depends on order. Monthly coupons must link a coupon that is live — link a draft and the buyer gets nothing on day one.",
  btnSaveCard: "Save card",
  toastCardSaved: "Card saved",
  toastCardStatus: "Card state updated",
  memberReadOnlyWhat: "membership cards and benefits",

  targetAll: "All users",
  targetNewUser: "New customers",
  targetCommunity: "Selected communities",
  targetSingleUser: "Selected users",

  discountValue: "{n}% off",

  toastCouponStatus: "Coupon status updated",
  toastBudgetSaved: "Budget updated",
  toastIssued: "Issued {n} coupon(s), using {amount} of budget",
  toastSlotStatus: "Slot status updated",

  colCouponNo: "Coupon no.",
  colName: "Name",
  colType: "Type",
  colValue: "Value",
  colThreshold: "Minimum spend",
  noThreshold: "None",
  colBudget: "Budget used",
  colIssuedRedeemed: "Issued / redeemed",
  colValidRange: "Valid",
  colStatus: "Status",
  colActions: "Actions",
  entityCoupon: "coupon template",
  entityCampaign: "campaign",
  entitySlot: "content slot",
  btnActivate: "Activate",
  btnIssue: "Issue",
  btnResume: "Resume",

  colIssueNo: "Issue no.",
  colCoupon: "Coupon",
  colTarget: "Issued to",
  colCount: "Count",
  colAmount: "Budget used",
  colOperator: "Operator",
  colTime: "Time",

  colCampaignNo: "Campaign no.",
  colPosition: "Placement",
  colRange: "Runs",
  colSkuCount: "Products",

  colSlotNo: "Slot no.",
  colTitle: "Title",
  colSort: "Order",
  colCommunities: "Communities",
  allCommunities: "All communities",
  colOnOffline: "Online / offline",
  colEnabled: "Enabled",
  ariaEnable: "Enable {title}",

  readOnlyWhat: "coupon issuing & budget changes",
  readOnlyNote: "cannot issue coupons, pause them or archive",
  couponNotice:
    "The budget is the only thing standing between you and quietly overspending: an issue that exceeds it is rejected outright, and the budget itself cannot be lowered below what has already been issued. Support's goodwill coupons go through the same checks (matrix §2.3).",
  campaignNotice:
    "Flash-sale slots at the same placement cannot overlap — that is the whole point of a slot. Running in parallel across different placements is fine (home page and a channel page can both run).",
  searchCoupons: "Search coupon no. / name",
  searchIssues: "Search issue no. / coupon name / operator",
  searchCampaigns: "Search campaign no. / name / placement",
  searchSlots: "Search slot no. / title",
  filterCouponType: "Filter by coupon type",
  filterCouponTypeAll: "All coupon types",
  filterCampaignType: "Filter by campaign type",
  filterCampaignTypeAll: "All campaign types",
  filterStatus: "Filter by status",
  filterStatusAll: "All statuses",
  filterKind: "Filter by placement",
  filterKindAll: "All placements",
  emptyCoupons: "No coupon templates match these filters. Everything in the C-end coupon centre comes from here — with none, it is empty.",
  emptyIssues: "No issue records yet. Every issue is recorded here, including support's goodwill coupons.",
  emptyCampaigns: "No campaigns match these filters. Clear them, or try another period.",
  emptySlots: "No content slots match these filters. The C-end home floors and banners are all published from here.",

  issueTitle: "Issue “{name}”",
  btnConfirmIssue: "Confirm issue",
  fieldRemainBudget: "Remaining budget",
  perCoupon: " ({value} each)",
  fieldTarget: "Issue to",
  fieldTargetDesc: "Targeting note",
  targetDescPlaceholder: "e.g. Jinxiu Garden / Haitang (after-sales goodwill)",
  fieldCount: "Number of coupons",
  countHint: "Exceeding the remaining budget is rejected outright — nothing is partially issued.",

  budgetTitle: "Adjust budget",
  fieldBudget: "Budget (CNY)",
  budgetHint: "Cannot go below the amount already issued, or the books are instantly overspent.",
  save: "Save",
};

export const MARKETING_COPY: PageCopy<typeof zh> = { zh, en };

/** 拆出去的 tab 组件靠它接文案。 */
export type MarketingCopy = typeof zh;
