// 员工与权限文案（矩阵 P-1.1）。
import type { PageCopy } from "@/lib/use-copy";

const zh = {

  enabledOn: "启用中",
  enabledOff: "已停用",

  toastEnabled: "已启用",
  toastDisabled: "已停用",
  toastRoleChanged: "已调整角色",
  toastScopeChanged: "已调整数据域",
  toastPermsSaved: "已保存角色权限",
  critical: "高危",
  moveUp: "上移",
  moveDown: "下移",
  reorderHint: "调整菜单顺序（所有人可见）",
  menuOrderNotice: "这里调的是所有人看到的菜单顺序，不是个人偏好，也与角色无关。只能在同级内上下换位 —— 跨分区移动是改菜单结构，要走 nav.ts → 生成器 → 迁移那条链路。改完最多 60 秒各端生效。",

  colName: "姓名",
  colUsername: "登录名",
  colRole: "角色",
  /** `{name}` 是员工姓名 */
  ariaRoleOf: "{name} 的角色",
  /** `{name}` 是员工姓名 */
  confirmPromoteTitle: "将 {name} 升为超级管理员",
  confirmPromoteDesc: "超管拥有全部权限，包括授权、封禁、打款与环境切换。请输入工号确认。",
  confirmPromoteOk: "确认升权",
  colScope: "数据域",
  scopeAll: "全量",
  /** `{no}` 是编号 */
  scopeMerchant: "商家 {no}",
  scopeCommunity: "社区 {no}",
  scopePickup: "自提点 {no}",
  scopeUnbounded: "未限定（等同全量）",
  colLastLogin: "最近登录",
  colEnabled: "启用",
  ariaEnableSwitch: "{name} 启用开关",
  /** `{name}` 是员工姓名 */
  confirmDisableTitle: "停用超级管理员 {name}",
  confirmDisableDesc: "停用最后一个超管会让系统失去管理入口（服务端会拒绝）。请输入登录名确认。",
  confirmDisableOk: "确认停用",
  colActions: "操作",
  actionScope: "配数据域",

  colRoleLabel: "角色",
  colRoleCode: "编码",
  colStaffCount: "账号数",
  actionDelete: "删除",
  // 名字说它「做什么」，不是它「为了什么」 —— 叫「立即生效」会让人以为
  // 不点就不生效，而改完功能点本来就立刻生效
  actionForceLogout: "强制重新登录",
  confirmForceLogoutTitle: "强制「{role}」的成员重新登录？",
  confirmForceLogoutDesc:
    "{n} 个账号会立刻掉线，正在填写的表单与未提交的内容会丢失。\n\n"
    + "普通调权不需要这一步 —— 改完功能点下一个请求就生效。"
    + "只有「权限开错了要立刻收回」才用它。",
  confirmForceLogoutOk: "强制下线",
  toastForceLoggedOut: "已踢掉 {n} 个会话",
  toastRoleRemoved: "角色已删除",
  confirmDeleteRoleTitle: "删除角色「{role}」",
  confirmDeleteRoleDesc: "删除后这个角色码可能被系统认为「还存在但已删除」——如果重建同名角色，请先确认没有历史残留（已知问题，见开发备注）。",
  confirmDeleteRoleInUseDesc: "还有 {n} 个账号持有这个角色，服务端会拒绝删除。先把他们的角色改掉，再回来删。",
  confirmDeleteRoleOk: "确认删除",
  actionRename: "改名",
  renameRoleTitle: "重命名角色",
  renameRoleDesc: "只改展示名 —— 角色码是授权的键，改了等于换一个角色",
  toastStaffSaved: "员工已保存",
  toastRoleRenamed: "角色名已更新",
  roleNone: "无角色",
  roleNoneHint: "至少要有一个角色 —— 零角色的人能登录，但界面一片空白，且看不出原因。要停用请用右侧开关。",
  cannotEditSelf: "不能改自己的角色 —— 否则有账号管理权限的人可以给自己加超管",
  cannotDisableSelf: "不能停用自己 —— 停了就把自己锁在门外，只能去库里手改",
  actionEdit: "编辑",
  staffDrawerTitle: "编辑 {name}",
  fieldRoles: "角色（可多选）",
  fieldScope: "数据域",
  scopeAllHint: "当前角色都是全量数据角色，配数据域不会生效。要限定范围，先给他一个受限角色（社区运营 / 商家运营）。",
  newStaffTitle: "新建员工",
  newStaffDesc: "登录名建好后不可改；初始密码由系统生成",
  newStaffPasswordNotice: "保存后会生成一个一次性初始密码，只显示这一次。该员工首次登录必须改密。",
  fieldUsername: "登录名",
  fieldRealName: "姓名",
  phUsername: "如 ops.zhang@company.com",
  usernameNotEmail: "登录名必须是邮箱格式",
  phRealName: "如 张运营",
  initialPasswordTitle: "初始密码",
  initialPasswordDesc: "{username} 的一次性密码",
  initialPasswordWarn: "关掉这个抽屉就再也取不到了。现在把它交给本人，并让他首次登录后立即改密。",
  gotIt: "我已记下",
  colPermCount: "功能点数",
  colRoleKind: "类型",
  builtinRole: "预置",
  customRole: "自定义",
  notImplemented: "后端未实现",
  builtinReadOnly: "预置角色是代码里那份的镜像，改了会与回落表分叉 —— 只读。要调整请新建自定义角色。",
  permAll: "全部",
  colCriticalPerms: "高危权限",
  /** `{n}` 是高危权限项数 */
  criticalCount: "{n} 项",
  roleBuiltIn: "内置不可改",
  actionView: "查看",
  actionNewRole: "新建角色",
  newRoleTitle: "新建自定义角色",
  newRoleDesc: "角色码建大写英文与下划线；建好后在列表里勾功能点",
  fieldRoleCode: "角色码",
  fieldRoleName: "角色名",
  phRoleCode: "会跟着名字自动生成，也可以手动改",
  roleCodeNoSuggestion: "名字里没有英文字符，生成不出角色码——请手动填一个（大写字母开头）",
  roleCodeInvalid: "角色码格式不对：只能大写字母开头，包含大写字母/数字/下划线",
  phRoleName: "如 退款复核",
  toastRoleCreated: "角色已创建",
  actionPerms: "配权限",

  colTime: "时间",
  colOperator: "操作人",
  colAction: "动作",
  colTarget: "对象",
  colDetail: "详情",
  colCritical: "高危",
  colIp: "IP",
  colClientType: "操作端",
  colChange: "变更前 → 后",
  yes: "是",
  no: "否",
  none: "无",

  readOnlyWhat: "账号与权限管理",
  readOnlyNote: "不能改角色、数据域或权限",
  notice:
    "角色的授权单位是「功能点」，与库里存的一致：勾什么，那个人登录后就能看到什么、调得动哪些接口。改完会踢掉持有者的登录态 —— 权限是登录那一刻算好的快照，不踢就要等他下次登录。预置角色是代码里那份的镜像，只读；要调整请新建自定义角色。",
  searchStaff: "搜索工号 / 姓名 / 登录名",
  searchAudit: "搜索操作人 / 动作 / 对象",
  filterRole: "按角色筛选",
  filterRoleAll: "全部角色",
  filterStatus: "按状态筛选",
  filterStatusAll: "全部状态",
  filterCritical: "按高危筛选",
  filterCriticalOnly: "仅看高危操作",
  filterCriticalAll: "全部操作",
  emptyStaff: "没有符合条件的员工。清空筛选，或换个角色看看。",
  emptyRoles: "没有角色定义。角色是权限的载体，没有角色就没法给员工授权。",

  /** `{role}` 是角色名 */
  permCardTitle: "{role} 的权限",
  emptyPerms: "没有可配置的权限码。权限码来自各业务域的声明，缺了说明该域还没接入 RBAC。",
  /** `{role}` 是角色名 */
  confirmGrantTitle: "授予 {role} 高危权限",
  /** `{n}` 项数，`{list}` 权限码列表 */
  confirmGrantDesc: "本次包含 {n} 项高危权限：{list}。请输入角色编码确认。",
  confirmGrantOk: "确认授权",
  save: "保存",
  /** `{n}` 是已选数量 */
  selectedN: "已选 {n} 项",

  auditNotice:
    "审计日志「只读不可删」（合规）。当前覆盖本域的写操作；其它域的操作留痕等接后端后由后端统一记录 —— 前端埋点会漏，且能被绕过，不可信。",
  auditReadOnlyWhat: "操作审计日志",
  emptyAudit: "没有符合条件的审计记录。换个操作人或时间范围看看 —— 高危操作一定会留痕。",

  /** `{name}` 是员工姓名 */
  scopeDrawerTitle: "{name} 的数据域",
  scopeNotice:
    "⚠️ 配置会保存，但「裁剪尚未生效」：后端各域的查询目前还没有按数据域过滤，配了也仍然能看到全量。按它裁剪是单独一批。\n\n数据域只对受限角色生效（社区运营、商家运营）。留空 = 不限定，等同全量 —— 这一点在列表里会用橙色标出来，避免“以为限制了其实没限制”。",
  phCommunity: "如 C001",
  phMerchant: "如 M903",
  phPickup: "如 P001",
  fieldCommunityNo: "社区编号",
  fieldMerchantNo: "商家编号",
  fieldPickupNo: "自提点编号",
  fieldHowItWorks: "生效方式",
  scopeHowHint:
    "列表查询会自动带上这些归属键，mock 与真实后端行为一致。越权拦截以后端为准（矩阵 §2.3）—— 前端只做展示裁剪。",
};

const en: typeof zh = {

  enabledOn: "Active",
  enabledOff: "Disabled",

  toastEnabled: "Enabled",
  toastDisabled: "Disabled",
  toastRoleChanged: "Role updated",
  toastScopeChanged: "Data scope updated",
  toastPermsSaved: "Role permissions saved",
  critical: "High risk",
  moveUp: "Move up",
  moveDown: "Move down",
  reorderHint: "Reorder menu (affects everyone)",
  menuOrderNotice: "This changes the menu order everyone sees — not a personal preference, and unrelated to roles. Items can only swap with a sibling; moving across sections changes menu structure and goes through nav.ts → generator → migration. Takes effect within 60s.",

  colName: "Name",
  colUsername: "Username",
  colRole: "Role",
  ariaRoleOf: "Role of {name}",
  confirmPromoteTitle: "Promote {name} to super admin",
  confirmPromoteDesc:
    "A super admin holds every permission, including granting access, suspending merchants, releasing payouts and switching environments. Type the staff number to confirm.",
  confirmPromoteOk: "Promote",
  colScope: "Data scope",
  scopeAll: "Unrestricted",
  scopeMerchant: "Merchant {no}",
  scopeCommunity: "Community {no}",
  scopePickup: "Pickup point {no}",
  scopeUnbounded: "Unbounded (same as unrestricted)",
  colLastLogin: "Last sign-in",
  colEnabled: "Enabled",
  ariaEnableSwitch: "Enable {name}",
  confirmDisableTitle: "Disable super admin {name}",
  confirmDisableDesc:
    "Disabling the last super admin would leave the system with no way in (the server rejects it). Type the username to confirm.",
  confirmDisableOk: "Disable",
  colActions: "Actions",
  actionScope: "Set scope",

  colRoleLabel: "Role",
  colRoleCode: "Code",
  colStaffCount: "Accounts",
  actionDelete: "Delete",
  actionForceLogout: "Force re-login",
  confirmForceLogoutTitle: "Force members of \u201c{role}\u201d to sign in again?",
  confirmForceLogoutDesc:
    "{n} account(s) will be signed out immediately; unsaved forms will be lost.\n\n"
    + "Routine permission edits do not need this \u2014 they take effect on the next request. "
    + "Use it only to revoke a mistakenly granted permission right now.",
  confirmForceLogoutOk: "Force sign-out",
  toastForceLoggedOut: "{n} session(s) revoked",
  toastRoleRemoved: "Role deleted",
  confirmDeleteRoleTitle: "Delete role {role}",
  confirmDeleteRoleDesc: "A known backend issue can leave a soft-deleted role code looking reusable when it is not fully gone. If you recreate a role with the same code, check for leftovers first.",
  confirmDeleteRoleInUseDesc: "{n} account(s) still hold this role; the server will reject the deletion. Reassign them first.",
  confirmDeleteRoleOk: "Delete",
  actionRename: "Rename",
  renameRoleTitle: "Rename role",
  renameRoleDesc: "Display name only — the role code is the authorization key",
  toastStaffSaved: "Staff saved",
  toastRoleRenamed: "Role renamed",
  roleNone: "No role",
  roleNoneHint: "At least one role is required — someone with zero roles can log in but sees a blank app with no explanation. To suspend, use the switch instead.",
  cannotEditSelf: "You cannot change your own roles — otherwise anyone with staff admin could grant themselves super admin",
  cannotDisableSelf: "You cannot disable your own account — you would be locked out with no way back in",
  actionEdit: "Edit",
  staffDrawerTitle: "Edit {name}",
  fieldRoles: "Roles (multiple)",
  fieldScope: "Data scope",
  scopeAllHint: "All current roles see everything, so a data scope would change nothing. Assign a scoped role first (community / merchant ops).",
  newStaffTitle: "New staff",
  newStaffDesc: "Username cannot be changed later; the initial password is generated",
  newStaffPasswordNotice: "A one-time initial password is generated on save and shown only once. The new member must change it at first login.",
  fieldUsername: "Username",
  fieldRealName: "Full name",
  phUsername: "e.g. ops.zhang@company.com",
  usernameNotEmail: "Username must be a valid email address",
  phRealName: "e.g. Zhang",
  initialPasswordTitle: "Initial password",
  initialPasswordDesc: "One-time password for {username}",
  initialPasswordWarn: "Once you close this drawer it is gone for good. Hand it over now and have them change it at first login.",
  gotIt: "Got it",
  colPermCount: "Points",
  colRoleKind: "Kind",
  builtinRole: "Built-in",
  customRole: "Custom",
  notImplemented: "Backend not implemented",
  builtinReadOnly: "Built-in roles mirror the code-side table; editing them would diverge from the fallback path. Create a custom role instead.",
  permAll: "All",
  colCriticalPerms: "High-risk permissions",
  criticalCount: "{n}",
  roleBuiltIn: "Built-in, read-only",
  actionView: "View",
  actionNewRole: "New role",
  newRoleTitle: "New custom role",
  newRoleDesc: "Use uppercase letters and underscores; pick function points after creating",
  fieldRoleCode: "Role code",
  fieldRoleName: "Role name",
  phRoleCode: "Auto-generated from the name, or type your own",
  roleCodeNoSuggestion: "No ASCII characters in the name to derive a code from \u2014 please enter one manually (starts with an uppercase letter)",
  roleCodeInvalid: "Invalid role code: must start with an uppercase letter and contain only uppercase letters, digits, or underscores",
  phRoleName: "e.g. Refund reviewer",
  toastRoleCreated: "Role created",
  actionPerms: "Set permissions",

  colTime: "Time",
  colOperator: "Operator",
  colAction: "Action",
  colTarget: "Target",
  colDetail: "Details",
  colCritical: "High risk",
  colIp: "IP",
  colClientType: "Client",
  colChange: "Before → After",
  yes: "Yes",
  no: "No",
  none: "None",

  readOnlyWhat: "account & permission management",
  readOnlyNote: "cannot change roles, data scopes or permissions",
  notice:
    "The source of truth for role permissions is a constant in the code (lib/permissions.ts) — that is what can() reads. Edits here apply to mock data and will not change the signed-in user's real permissions before the backend is wired up. It is deliberately not runtime-mutable: one slip would lock you out of your own system.",
  searchStaff: "Search staff no. / name / username",
  searchAudit: "Search operator / action / target",
  filterRole: "Filter by role",
  filterRoleAll: "All roles",
  filterStatus: "Filter by status",
  filterStatusAll: "All statuses",
  filterCritical: "Filter by risk",
  filterCriticalOnly: "High-risk actions only",
  filterCriticalAll: "All actions",
  emptyStaff: "No staff match these filters. Clear them, or try another role.",
  emptyRoles: "No roles defined. Roles carry permissions — without one there is nothing to grant staff.",

  permCardTitle: "Permissions for {role}",
  emptyPerms: "No permission codes to configure. Codes are declared by each business domain; missing ones mean that domain has not adopted RBAC yet.",
  confirmGrantTitle: "Grant high-risk permissions to {role}",
  confirmGrantDesc: "This includes {n} high-risk permission(s): {list}. Type the role code to confirm.",
  confirmGrantOk: "Grant",
  save: "Save",
  selectedN: "{n} selected",

  auditNotice:
    "The audit log is append-only by design (compliance). It currently covers writes in this domain; other domains will be recorded by the backend once connected — front-end instrumentation misses events and can be bypassed, so it is not trustworthy.",
  auditReadOnlyWhat: "audit log",
  emptyAudit: "No audit records match. Try another operator or time range — high-risk actions are always recorded.",

  scopeDrawerTitle: "Data scope for {name}",
  scopeNotice:
    "⚠️ The setting is saved, but 「filtering is not live yet」: backend queries do not honour data scope today, so a scoped account still sees everything. Enforcement ships separately.\n\nData scope only applies to restricted roles (community ops, merchant ops). Leaving it blank means unbounded, i.e. the same as unrestricted — the list marks that in amber so nobody assumes a limit that is not there.",
  phCommunity: "e.g. C001",
  phMerchant: "e.g. M903",
  phPickup: "e.g. P001",
  fieldCommunityNo: "Community no.",
  fieldMerchantNo: "Merchant no.",
  fieldPickupNo: "Pickup point no.",
  fieldHowItWorks: "How it works",
  scopeHowHint:
    "List queries carry these ownership keys automatically, and the mock behaves like the real backend. Authorisation is enforced server-side (matrix §2.3) — the front end only trims what is shown.",
};

export const IAM_COPY: PageCopy<typeof zh> = { zh, en };
