// 门店主页文案（矩阵 P-10.1）。
import type { PageCopy } from "@/lib/use-copy";

const zh = {
  templateNotice: "模板改一次会同时作用在一批店铺页上，所以每一行都摆着「多少家店在用」—— 那是决定要不要动它的唯一依据。至少要启用 {n} 个板块：只剩店招的店铺页等于一张裸列表。",
  colTemplateName: "模板名称",
  colLayout: "商品区排布",
  colSections: "已启用板块",
  colUsedBy: "使用中店铺",
  colTemplateStatus: "状态",
  colDefault: "默认",
  colUpdatedAt: "最近修改",
  layoutGrid: "双列网格",
  layoutList: "单列大图",
  layoutFeature: "主推位优先",
  secBanner: "店招",
  secNotice: "公告",
  secHot: "热销",
  secCategory: "分类导航",
  secCoupon: "优惠券",
  secGroup: "拼团",
  usedByStores: "{n} 家",
  templateOn: "启用中",
  templateOff: "已停用",
  badgeDefault: "默认模板",
  actionNewTemplate: "新建模板",
  actionEditTemplate: "编辑",
  actionEnable: "启用",
  actionDisable: "停用",
  emptyTemplate: "还没有主页模板。至少要有一个默认模板，新店开出来才有页面可用。",
  newTemplateTitle: "新建主页模板",
  editTemplateTitle: "编辑 {name}",
  secTemplateBasic: "基本信息",
  secSections: "板块",
  sectionRequired: "必选，不能停用",
  sectionCount: "已启用 {n} 个板块，至少 {min} 个。",
  secImpact: "影响范围",
  impactHint: "改板块会立刻反映到这些店铺页。要停用模板，得先把这些店迁到别的模板。",
  btnSaveTemplate: "保存模板",
  toastTemplateSaved: "模板已保存",
  toastTemplateEnabled: "模板已启用",
  toastTemplateDisabled: "模板已停用",
  confirmDisableTitle: "停用这个模板？",
  confirmDisableDesc: "停用后「{name}」不再出现在商家可选列表里；已经在用它的店铺不受影响。",
  templateReadOnlyWhat: "主页模板配置",

  kindBanner: "店招图",
  kindNotice: "店铺公告",
  kindArea: "经营覆盖",
  areaHint: "商家自己框的区 / 街道。通过之后他的货才会在这一片露出 —— 一家菜摊声称覆盖整个西湖区，得有履约能力佐证",

  toastPassed: "已通过，商家主页即时生效",
  toastRejected: "已驳回，原因已发给商家",

  colAuditNo: "审核单号",
  colMerchant: "商家",
  colKind: "类型",
  colContent: "内容",
  colHits: "机审命中",
  colSubmittedAt: "提交时间",
  colStatus: "状态",
  colActions: "操作",
  actionAudit: "审核",
  actionView: "查看",
  none: "无",

  colMerchantNo: "商家编号",
  colCommunity: "社区",
  colCode: "码值",
  colSize: "贴纸尺寸",
  colPrinted: "已印",
  colScanCount: "累计扫码",

  printedUnset: "未登记",
  colStore: "门店",
  codeUnset: "待发码",
  issueAction: "发码",
  reissueAction: "换码",
  filterCodeless: "只看待发码",
  issued: "已发码 {code}",
  reissued: "已换码 {code}，旧码即刻失效",
  reissueTitle: "换码 · {store}",
  reissueWarn: "换码后旧码立刻失效 —— 已经贴在店里的物料会全部扫不出来。确认要换的话，写清楚为什么。",
  reissueReason: "换码原因",
  reissueConfirm: "确认换码",
  printSheet: "导出可印刷页",
  printSheetTitle: "店铺码印刷页",
  printSheetEmpty: "这批里没有一家有码图 —— 先发码，或检查微信通道有没有开。",
  printSheetNoImage: "无码图",
  printSheetBlocked: "浏览器拦住了新窗口 —— 允许本站弹窗后再点一次",
  printAction: "登记印量",
  printTitle: "登记印刷量",
  printQty: "本次印量",
  printQtyHint: "有符号：印多了要冲减就填负数，补一行而不是改历史行。0 不接受。",
  printSize: "贴纸尺寸",
  printRemark: "备注",
  printSubmit: "登记",
  printDone: "已登记",

  colScan: "扫码次数",
  colScanUv: "扫码人数",
  colEnter: "进店",
  colRegister: "首次归因",
  colFirstOrder: "首单",
  colConversion: "扫码→首单转化",
  acqNotice:
    "口径：扫码人数按设备去重（匿名访客还没有账号）；「首次归因」是第一次把这个人算到本店名下，"
    + "不等于平台新注册 —— 老用户第一次扫这家店的码也计入。转化率的分母是扫码人数，不是次数。",
  acqRange7: "近 7 天",
  acqRange30: "近 30 天",
  acqRange90: "近 90 天",

  readOnlyWhat: "店招与公告审核",
  readOnlyNote: "不能通过或驳回",
  notice:
    "店铺码是一期的主获客入口：BD 把它印成贴纸贴在店里，用户扫码进店即绑定 merchantNo 与 trafficSource=MERCHANT_OWNED（P-10.1.3 / P-9.1.5）。",
  searchAudit: "搜索审核单号 / 商家 / 内容",
  searchQrcode: "搜索商家编号 / 名称",
  exportSheet: "店铺码",
  exportLabel: "导出给印刷",
  filterKind: "按类型筛选",
  filterKindAll: "全部类型",
  filterStatus: "按状态筛选",
  filterStatusAll: "全部状态",

  emptyAudit: "待审队列已清空。商家改店招或公告后会重新出现在这里。",
  emptyQrcode: "还没有商家生成店铺码。商家入驻通过后自动生成。",
  emptyEffect: "还没有扫码数据。店铺码印出去贴到店里之后，这里才会有数。",

  btnReject: "驳回",
  btnPass: "通过",
  fieldPending: "待审内容",
  fieldHits: "机审命中",
  fieldRejectReason: "驳回原因",
  rejectPlaceholder: "商家会原样看到这段话，写清楚要改什么，别写「不符合规范」",
};

const en: typeof zh = {
  templateNotice: "One template edit lands on a batch of storefronts at once, which is why every row shows how many stores use it — that is the only basis for deciding whether to touch it. At least {n} blocks must stay on: a storefront with nothing but its header is a bare list.",
  colTemplateName: "Template",
  colLayout: "Product layout",
  colSections: "Blocks on",
  colUsedBy: "Stores using it",
  colTemplateStatus: "State",
  colDefault: "Default",
  colUpdatedAt: "Last changed",
  layoutGrid: "Two-column grid",
  layoutList: "Single column, large images",
  layoutFeature: "Featured first",
  secBanner: "Header",
  secNotice: "Announcement",
  secHot: "Best sellers",
  secCategory: "Category nav",
  secCoupon: "Coupons",
  secGroup: "Group buys",
  usedByStores: "{n}",
  templateOn: "On",
  templateOff: "Off",
  badgeDefault: "Default",
  actionNewTemplate: "New template",
  actionEditTemplate: "Edit",
  actionEnable: "Turn on",
  actionDisable: "Turn off",
  emptyTemplate: "No homepage templates yet. At least one default is needed so a new store has a page to open with.",
  newTemplateTitle: "New storefront template",
  editTemplateTitle: "Edit {name}",
  secTemplateBasic: "Basics",
  secSections: "Blocks",
  sectionRequired: "Required — cannot be turned off",
  sectionCount: "{n} blocks on, minimum {min}.",
  secImpact: "What this affects",
  impactHint: "Block changes reach these storefronts immediately. To turn the template off, move those stores to another one first.",
  btnSaveTemplate: "Save template",
  toastTemplateSaved: "Template saved",
  toastTemplateEnabled: "Template turned on",
  toastTemplateDisabled: "Template turned off",
  confirmDisableTitle: "Turn this template off?",
  confirmDisableDesc: "“{name}” stops appearing in the merchant’s choices; stores already on it are unaffected.",
  templateReadOnlyWhat: "homepage template configuration",

  kindBanner: "Storefront banner",
  kindNotice: "Store notice",
  kindArea: "Service coverage",
  areaHint: "A district or street the merchant claims. Only after approval do their goods appear there — a produce stall claiming all of West Lake needs the delivery capacity to back it",

  toastPassed: "Approved — the merchant's storefront updates immediately",
  toastRejected: "Rejected — the reason has been sent to the merchant",

  colAuditNo: "Review no.",
  colMerchant: "Merchant",
  colKind: "Type",
  colContent: "Content",
  colHits: "Auto-screen hits",
  colSubmittedAt: "Submitted at",
  colStatus: "Status",
  colActions: "Actions",
  actionAudit: "Review",
  actionView: "View",
  none: "None",

  colMerchantNo: "Merchant no.",
  colCommunity: "Community",
  colCode: "Code",
  colSize: "Sticker size",
  colPrinted: "Printed",
  colScanCount: "Total scans",

  printedUnset: "Not recorded",
  colStore: "Store",
  codeUnset: "No code yet",
  issueAction: "Issue code",
  reissueAction: "Re-issue",
  filterCodeless: "Needs a code",
  issued: "Code issued: {code}",
  reissued: "Re-issued as {code}; the old code stopped working",
  reissueTitle: "Re-issue · {store}",
  reissueWarn: "The old code stops working immediately — anything already printed and stuck up in the store will fail to scan. Say why.",
  reissueReason: "Reason",
  reissueConfirm: "Re-issue",
  printSheet: "Printable sheet",
  printSheetTitle: "Store code print sheet",
  printSheetEmpty: "None of these rows has a code image — issue codes first, or check the WeChat channel is on.",
  printSheetNoImage: "No image",
  printSheetBlocked: "The browser blocked the new window — allow pop-ups for this site and try again",
  printAction: "Record print run",
  printTitle: "Record a print run",
  printQty: "Quantity",
  printQtyHint:
    "Signed: to correct an over-print, enter a negative number — a new row, never an edit to history. Zero is rejected.",
  printSize: "Sticker size",
  printRemark: "Note",
  printSubmit: "Record",
  printDone: "Recorded",

  colScan: "Scans",
  colScanUv: "Unique scanners",
  colEnter: "Store visits",
  colRegister: "First attribution",
  colFirstOrder: "First orders",
  colConversion: "Scan → first order",
  acqNotice:
    "How to read this: unique scanners are de-duplicated by device (anonymous visitors have no account yet); "
    + "\"first attribution\" means the first time a person was credited to this store — it is not a platform sign-up, "
    + "since an existing user scanning this store's code for the first time also counts. "
    + "The conversion denominator is unique scanners, not raw scans.",
  acqRange7: "Last 7 days",
  acqRange30: "Last 30 days",
  acqRange90: "Last 90 days",

  readOnlyWhat: "storefront banner & notice review",
  readOnlyNote: "cannot approve or reject",
  notice:
    "Store codes are the main acquisition entry point in phase 1: BD prints them as stickers for the shop, and scanning binds merchantNo and trafficSource=MERCHANT_OWNED (P-10.1.3 / P-9.1.5).",
  searchAudit: "Search review no. / merchant / content",
  searchQrcode: "Search merchant no. / name",
  exportSheet: "Store codes",
  exportLabel: "Export for printing",
  filterKind: "Filter by type",
  filterKindAll: "All types",
  filterStatus: "Filter by status",
  filterStatusAll: "All statuses",

  emptyAudit: "The review queue is clear. Items reappear here when a merchant changes their banner or notice.",
  emptyQrcode: "No merchant has a store code yet. Codes are generated automatically once onboarding is approved.",
  emptyEffect: "No scan data yet. Numbers appear once the printed codes are actually up in the shops.",

  btnReject: "Reject",
  btnPass: "Approve",
  fieldPending: "Submitted content",
  fieldHits: "Auto-screen hits",
  fieldRejectReason: "Rejection reason",
  rejectPlaceholder: "The merchant sees this verbatim — say what to change, not just “does not meet the guidelines”",
};

export const STORES_COPY: PageCopy<typeof zh> = { zh, en };

/** 拆出去的 tab 组件靠它接文案。 */
export type StoresCopy = typeof zh;
