// 售后治理文案（矩阵 P-6.1）。
import type { PageCopy } from "@/lib/use-copy";

const zh = {
  tabTickets: "售后工单",
  tabIntervene: "平台介入",
  tabFastRefund: "极速退规则",

  liabMerchant: "供货商家",
  liabMerchantHint: "商品本身的问题：坏果、少发、货不对板",
  liabPickup: "自提点商家",
  liabPickupHint: "承接环节的问题：错发、丢件、保管不当",
  liabPlatform: "平台",
  liabPlatformHint: "规则或系统问题：超时未配送、价格展示错误",

  toastDecided: "已裁决，退款待资金域执行",
  toastRuleSaved: "极速退规则已保存",

  colAsNo: "售后单号",
  colOrderNo: "订单号",
  colMerchant: "商家",
  colBuyer: "买家",
  colType: "类型",
  colAmount: "金额",
  colReason: "原因",
  colEvidence: "凭证",
  colLiability: "责任",
  colCreatedAt: "申请时间",
  colStatus: "状态",
  colActions: "操作",
  actionDecide: "裁决",
  actionView: "查看",

  readOnlyWhat: "售后裁决",
  readOnlyNote: "不能介入、裁决或判定责任",
  interveneNotice:
    "平台介入队列：商家与用户谈不拢时才到这里。裁决要同时给出「责任方」与「三方赔付比例」—— 矩阵 M4（出资方比例）尚未拍板，当前默认值只是填单起点，以实际判定为准。",
  kpiIntervene: "平台介入待裁决",
  kpiInterveneSub: "用户在等结果",
  kpiInterveneNone: "无积压",
  kpiPending: "待处置金额",
  kpiPendingSub: "尚未退款的申请合计",
  kpiPageCount: "本页工单",
  searchPlaceholder: "搜索售后单号 / 订单号 / 商家 / 原因",
  filterType: "按类型筛选",
  filterTypeAll: "全部类型",
  filterStatus: "按状态筛选",
  filterStatusAll: "全部状态",
  emptyIntervene: "没有需要平台介入的争议。这是好事 —— 说明商家自己把问题解决了。",
  emptyTickets: "没有符合条件的售后单。清空筛选，或换个状态看看。",

  ruleTitle: "极速退阈值",
  ruleReadOnlyWhat: "极速退阈值配置",
  ruleReadOnlyNote: "不能修改金额上限与时限",
  ruleNotice: "满足阈值的小额售后由系统自动通过，不占人工。阈值给大了是白送钱，给小了客服会被小额工单淹没。",
  ariaEnableFastRefund: "启用极速退",
  enabled: "已启用",
  disabled: "已停用",
  fieldMaxAmount: "金额上限（元）",
  fieldWithinHours: "下单后可用时限（小时）",
  /** `{n}` 是最小小时数 */
  hoursHint: "至少 {n} 小时：填 0 等于关掉极速退，但开关还显示「已启用」，比停用更难排查。",

  /** `{no}` 是订单号 */
  drawerOrder: "订单 {no}",
  btnConfirmDecide: "确认裁决",
  secTicket: "工单情况",
  secTicketDesc: "以下为申请方提交的内容，不可修改",
  /** `{n}` 是凭证张数 */
  evidenceCount: "{n} 张",
  none: "无",
  fieldReason: "申请原因",
  secDecide: "平台裁决",
  secDecideDesc: "退款金额、责任方与出资比例三项互相牵连，请一起确认",
  fieldRefundAmount: "同意退款金额（元）",
  refundAmountHint: "不得超过订单实付 —— 超了会被服务端拒绝。",
  fieldLiability: "责任方",
  sharePlatform: "平台出资",
  shareMerchant: "供货商家",
  sharePickup: "自提点",
  /** `{sum}` 合计，`{total}` 要求值 */
  shareSum: "赔付比例合计：{sum}% / {total}%",
  shareSumBad: "（不等于 100% 无法提交）",
  fieldVerdict: "裁决说明",
  verdictPlaceholder: "用户与商家都会看到：写清楚依据了哪条规则、为什么这么判",

  secResult: "裁决结果",
  liabilityUndecided: "尚未判定",
  fieldShare: "赔付比例",
  /** `{p}` 平台、`{m}` 商家、`{k}` 自提点 */
  shareText: "平台 {p}% · 商家 {m}% · 自提点 {k}%",
  refundSplitPending: "退款回退分账（E4）依赖资金域 P-12，尚未接入 —— 这笔退款已判定但分账尚未回退，接入后需按标记补跑。",
};

const en: typeof zh = {
  tabTickets: "After-sales tickets",
  tabIntervene: "Platform review",
  tabFastRefund: "Instant-refund rules",

  liabMerchant: "Supplying merchant",
  liabMerchantHint: "A problem with the goods themselves: spoiled produce, short shipment, wrong item",
  liabPickup: "Pickup-point merchant",
  liabPickupHint: "A problem in handling: wrong handover, lost parcel, poor storage",
  liabPlatform: "Platform",
  liabPlatformHint: "A rule or system problem: missed delivery window, wrong price shown",

  toastDecided: "Decided — the refund now awaits execution in Settlement",
  toastRuleSaved: "Instant-refund rules saved",

  colAsNo: "After-sales no.",
  colOrderNo: "Order no.",
  colMerchant: "Merchant",
  colBuyer: "Buyer",
  colType: "Type",
  colAmount: "Amount",
  colReason: "Reason",
  colEvidence: "Evidence",
  colLiability: "Liability",
  colCreatedAt: "Filed at",
  colStatus: "Status",
  colActions: "Actions",
  actionDecide: "Decide",
  actionView: "View",

  readOnlyWhat: "after-sales adjudication",
  readOnlyNote: "cannot intervene, decide or assign liability",
  interveneNotice:
    "The platform review queue: cases land here only when merchant and customer cannot agree. A decision must give both the liable party and the three-way split — matrix item M4 (who pays what) is not settled, so the defaults are only a starting point for the form, not a ruling.",
  kpiIntervene: "Awaiting platform decision",
  kpiInterveneSub: "Customers are waiting",
  kpiInterveneNone: "Nothing queued",
  kpiPending: "Amount at stake",
  kpiPendingSub: "Total of claims not yet refunded",
  kpiPageCount: "Tickets on this page",
  searchPlaceholder: "Search after-sales no. / order no. / merchant / reason",
  filterType: "Filter by type",
  filterTypeAll: "All types",
  filterStatus: "Filter by status",
  filterStatusAll: "All statuses",
  emptyIntervene: "No disputes need platform review. That is good news — the merchants sorted it out themselves.",
  emptyTickets: "No after-sales tickets match these filters. Clear them, or try another status.",

  ruleTitle: "Instant-refund thresholds",
  ruleReadOnlyWhat: "instant-refund threshold settings",
  ruleReadOnlyNote: "cannot change the amount cap or the time limit",
  ruleNotice:
    "Small claims under the threshold are approved automatically and never reach a human. Set it too high and you give money away; set it too low and support drowns in tiny tickets.",
  ariaEnableFastRefund: "Enable instant refunds",
  enabled: "Enabled",
  disabled: "Disabled",
  fieldMaxAmount: "Amount cap (CNY)",
  fieldWithinHours: "Available within (hours of ordering)",
  hoursHint:
    "At least {n} hours. Setting 0 switches instant refunds off while the toggle still reads “Enabled” — harder to diagnose than simply disabling it.",

  drawerOrder: "Order {no}",
  btnConfirmDecide: "Confirm decision",
  secTicket: "The claim",
  secTicketDesc: "Submitted by the claimant — read-only",
  evidenceCount: "{n}",
  none: "None",
  fieldReason: "Reason given",
  secDecide: "Platform decision",
  secDecideDesc: "Refund amount, liable party and funding split are interdependent — settle them together",
  fieldRefundAmount: "Refund approved (CNY)",
  refundAmountHint: "Cannot exceed what was actually paid — the server rejects anything higher.",
  fieldLiability: "Liable party",
  sharePlatform: "Platform pays",
  shareMerchant: "Supplying merchant",
  sharePickup: "Pickup point",
  shareSum: "Split total: {sum}% / {total}%",
  shareSumBad: " (must equal 100% to submit)",
  fieldVerdict: "Decision note",
  verdictPlaceholder: "Both customer and merchant see this: state which rule applied and why you decided this way",

  secResult: "Decision",
  liabilityUndecided: "Not yet decided",
  fieldShare: "Funding split",
  shareText: "Platform {p}% · merchant {m}% · pickup point {k}%",
  refundSplitPending:
    "Refund split reversal (E4) depends on Settlement (P-12), which is not wired up yet — this refund is decided but the split has not been reversed; once connected it must be replayed from this flag.",
};

export const AFTER_SALES_COPY: PageCopy<typeof zh> = { zh, en };
