// 售后治理文案（矩阵 P-6.1）。
import type { PageCopy } from "@/lib/use-copy";

const zh = {

  liabMerchant: "供货商家",
  liabMerchantHint: "商品本身的问题：坏果、少发、货不对板",
  liabPickup: "自提点商家",
  liabPickupHint: "承接环节的问题：错发、丢件、保管不当",
  liabPlatform: "平台",
  liabPlatformHint: "规则或系统问题：超时未配送、价格展示错误",

  toastDecided: "已裁决，退款待资金域执行",
  toastRuleSaved: "极速退规则已保存",

  colAsNo: "售后单号",
  colOrderNo: "订单号",
  colMerchant: "商家",
  colBuyer: "买家",
  colType: "类型",
  colAmount: "金额",
  colReason: "原因",
  colEvidence: "凭证",
  colLiability: "责任",
  colCreatedAt: "申请时间",
  colStatus: "状态",
  colActions: "操作",
  actionDecide: "裁决",
  actionView: "查看",

  readOnlyWhat: "售后裁决",
  readOnlyNote: "不能介入、裁决或判定责任",
  interveneNotice:
    "平台介入队列：商家与用户谈不拢时才到这里。裁决要给出「支不支持退款」与「责任方」—— 矩阵 M4（出资方比例）尚未拍板，暂不支持按比例分摊，先落责任、金额仍是申请时那笔。",
  kpiIntervene: "平台介入待裁决",
  kpiInterveneSub: "用户在等结果",
  kpiInterveneNone: "无积压",
  kpiPending: "待处置金额",
  kpiPendingSub: "尚未退款的申请合计",
  kpiPageCount: "本页工单",
  searchPlaceholder: "搜索售后单号 / 订单号 / 商家 / 原因",
  filterType: "按类型筛选",
  filterTypeAll: "全部类型",
  filterStatus: "按状态筛选",
  filterStatusAll: "全部状态",
  emptyIntervene: "没有需要平台介入的争议。这是好事 —— 说明商家自己把问题解决了。",
  emptyTickets: "没有符合条件的售后单。清空筛选，或换个状态看看。",

  ruleTitle: "极速退阈值",
  ruleReadOnlyWhat: "极速退阈值配置",
  ruleReadOnlyNote: "不能修改金额上限与时限",
  ruleNotice: "满足阈值的小额售后由系统自动通过，不占人工。阈值给大了是白送钱，给小了客服会被小额工单淹没。",
  ariaEnableFastRefund: "启用极速退",
  enabled: "已启用",
  disabled: "已停用",
  fieldMaxAmount: "金额上限（元）",
  fieldWithinHours: "下单后可用时限（小时）",
  /** `{n}` 是最小小时数 */
  hoursHint: "至少 {n} 小时：填 0 等于关掉极速退，但开关还显示「已启用」，比停用更难排查。",

  /** `{no}` 是订单号 */
  drawerOrder: "订单 {no}",
  btnConfirmDecide: "确认裁决",
  secTicket: "工单情况",
  secTicketDesc: "以下为申请方提交的内容，不可修改",
  /** `{n}` 是凭证张数 */
  evidenceCount: "{n} 张",
  none: "无",
  fieldReason: "申请原因",
  secDecide: "平台裁决",
  secDecideDesc: "退不退款与责任方互相牵连，请一起确认",
  fieldRefund: "裁决结果",
  refundYes: "支持退款",
  refundNo: "维持商家决定",
  refundAmountNote: "退款金额就是申请时的这笔，裁决不改金额",
  fieldLiability: "责任方",
  fieldVerdict: "裁决说明",
  verdictPlaceholder: "用户与商家都会看到：写清楚依据了哪条规则、为什么这么判",

  secResult: "裁决结果",
  liabilityUndecided: "尚未判定",
  refundDecided: "支持退款",
  refundRejected: "维持商家决定",
};

const en: typeof zh = {

  liabMerchant: "Supplying merchant",
  liabMerchantHint: "A problem with the goods themselves: spoiled produce, short shipment, wrong item",
  liabPickup: "Pickup-point merchant",
  liabPickupHint: "A problem in handling: wrong handover, lost parcel, poor storage",
  liabPlatform: "Platform",
  liabPlatformHint: "A rule or system problem: missed delivery window, wrong price shown",

  toastDecided: "Decided — the refund now awaits execution in Settlement",
  toastRuleSaved: "Instant-refund rules saved",

  colAsNo: "After-sales no.",
  colOrderNo: "Order no.",
  colMerchant: "Merchant",
  colBuyer: "Buyer",
  colType: "Type",
  colAmount: "Amount",
  colReason: "Reason",
  colEvidence: "Evidence",
  colLiability: "Liability",
  colCreatedAt: "Filed at",
  colStatus: "Status",
  colActions: "Actions",
  actionDecide: "Decide",
  actionView: "View",

  readOnlyWhat: "after-sales adjudication",
  readOnlyNote: "cannot intervene, decide or assign liability",
  interveneNotice:
    "The platform review queue: cases land here only when merchant and customer cannot agree. A decision must give both whether to refund and the liable party — matrix item M4 (who pays what) is not settled, so funding splits aren't supported yet; the amount stays whatever was originally claimed.",
  kpiIntervene: "Awaiting platform decision",
  kpiInterveneSub: "Customers are waiting",
  kpiInterveneNone: "Nothing queued",
  kpiPending: "Amount at stake",
  kpiPendingSub: "Total of claims not yet refunded",
  kpiPageCount: "Tickets on this page",
  searchPlaceholder: "Search after-sales no. / order no. / merchant / reason",
  filterType: "Filter by type",
  filterTypeAll: "All types",
  filterStatus: "Filter by status",
  filterStatusAll: "All statuses",
  emptyIntervene: "No disputes need platform review. That is good news — the merchants sorted it out themselves.",
  emptyTickets: "No after-sales tickets match these filters. Clear them, or try another status.",

  ruleTitle: "Instant-refund thresholds",
  ruleReadOnlyWhat: "instant-refund threshold settings",
  ruleReadOnlyNote: "cannot change the amount cap or the time limit",
  ruleNotice:
    "Small claims under the threshold are approved automatically and never reach a human. Set it too high and you give money away; set it too low and support drowns in tiny tickets.",
  ariaEnableFastRefund: "Enable instant refunds",
  enabled: "Enabled",
  disabled: "Disabled",
  fieldMaxAmount: "Amount cap (CNY)",
  fieldWithinHours: "Available within (hours of ordering)",
  hoursHint:
    "At least {n} hours. Setting 0 switches instant refunds off while the toggle still reads “Enabled” — harder to diagnose than simply disabling it.",

  drawerOrder: "Order {no}",
  btnConfirmDecide: "Confirm decision",
  secTicket: "The claim",
  secTicketDesc: "Submitted by the claimant — read-only",
  evidenceCount: "{n}",
  none: "None",
  fieldReason: "Reason given",
  secDecide: "Platform decision",
  secDecideDesc: "Whether to refund and the liable party are interdependent — settle them together",
  fieldRefund: "Decision",
  refundYes: "Support the refund",
  refundNo: "Uphold the merchant's decision",
  refundAmountNote: "The refund is whatever was originally claimed — a decision doesn't change the amount",
  fieldLiability: "Liable party",
  fieldVerdict: "Decision note",
  verdictPlaceholder: "Both customer and merchant see this: state which rule applied and why you decided this way",

  secResult: "Decision",
  liabilityUndecided: "Not yet decided",
  refundDecided: "Refund supported",
  refundRejected: "Merchant's decision upheld",
};

export const AFTER_SALES_COPY: PageCopy<typeof zh> = { zh, en };
