// 电子元器件文案（矩阵 P-19）。**独立服务 elec-svc 的运营面**，不并进别的域的 copy ——
// 这是内部面：真名、电话、供应商原价都在这几页上。
import type { PageCopy } from "@/lib/use-copy";

const zh = {
  // ── 通用 ──
  colStatus: "状态",
  colCreated: "时间",
  colPhone: "电话",
  colQty: "数量",
  colPrice: "单价",
  colDc: "批号",
  colLead: "交期",
  colMpn: "料号",
  colMfr: "厂牌",
  colSupplier: "供应商",
  spot: "现货",
  leadDays: "{n} 天",
  leadUnknown: "未说",
  taxIn: "含税",
  taxEx: "未税",
  none: "—",
  save: "保存",
  cancel: "取消",
  searchPh: "输入后回车",

  // ── 询报价 ──
  rfqViewOrders: "询价单",
  rfqViewQuotes: "报价记录",
  rfqStatusAll: "全部状态",
  rfqColNo: "单号",
  rfqColBuyer: "买家",
  rfqColLines: "料号",
  rfqColProgress: "派单 / 回话 / 有效报价",
  rfqLinesMore: "{mpn} 等 {n} 项",
  rfqEmpty: "还没有询价单。买家在元器件小程序里提交询价后会出现在这里。",
  rfqReq: "要求",
  rfqRemark: "备注",
  rfqNotified: "结果已通知买家",
  rfqNotNotified: "结果还没送到买家",
  rfqLine: "第 {n} 行",
  rfqTarget: "目标价 {p}",
  rfqSources: "库里谁有货",
  rfqSourcesEmpty: "库里没有这个料号的货 —— 可以在询价单里手工指派给可能有货的供应商",
  rfqOffers: "派给了谁 · 各自回了什么",
  rfqOffersEmpty: "这一行还没派给任何供应商",
  rfqBuyerPrice: "买家看到 {p}",
  rfqSupplierRemark: "给平台的备注：{r}",
  rfqSupplierRemarkFwd: "备注（转发模式下买家也看得到）：{r}",
  rfqPriceMode: "报价模式",
  rfqModeMARKUP: "加价",
  rfqModeFORWARD: "转发",
  rfqModeMARKUPDesc: "买家看到平台价，供应商显示为报价 A / B / C",
  rfqModeFORWARDDesc: "买家看到供应商原价与匿名编号，像直连；平台仍看得到全部",
  rfqModeLocked: "已有一行选定报价或单子已结束，不能再改",
  rfqModeChanged: "已改为「{m}」",
  rfqMfrRaw: "{m}，未认出",
  rfqPublic: "公开求购",
  rfqPublicDesc: "库里没人有货，{t} 起公开给供应商，在求购大厅里自己挑着报",
  rfqViaOPEN: "大厅认领",
  rfqPlatform: "平台报价（含税，元）",
  rfqPlatformPh: "留空 = 没找到货",
  rfqQuoteQty: "能供多少",
  rfqQuoteDcYear: "批次年份",
  rfqQuoteLead: "交期天数（现货 0）",
  rfqValidDays: "报价有效（天）",
  rfqNote: "给买家的说明",
  rfqSaveQuote: "保存并通知买家",
  rfqSaveQuoteHint: "保存后买家当场收到通知，可以直接接受 —— 没填价的行按「没找到货」告诉他",
  rfqQuoted: "已报价并通知买家",
  rfqDispatchPh: "供应商号，逗号分隔",
  rfqDispatch: "再派给",
  rfqDispatched: "已派出",
  rfqClose: "关单",
  rfqCloseNoSource: "暂无货源",
  rfqCloseCancelled: "买家不要了",
  rfqCloseDone: "已成交",
  rfqCloseTitle: "关掉 {no}？",
  rfqCloseDesc: "选「暂无货源」会通知买家。关单后这张单不能再报价",
  rfqClosed: "已关单",
  rfqNoQuotePerm: "录入报价、关单与指派",
  rfqNoQuoteNote: "只能看，不能报价、关单或手工指派",
  quoteColRfq: "询价单 / 行",
  quoteColWanted: "要 / 能供",
  quoteColBuyerPrice: "买家看到",
  quoteColValid: "有效至",
  quoteEmpty: "还没有供应商报过价 —— 询价派出去、供应商在求购里报价后会出现在这里",

  // ── 供应商 ──
  supKwPh: "公司名 / 电话 / 代号，回车",
  supStatusAll: "全部状态",
  supColCompany: "公司",
  supColKind: "类型 · 城市",
  supColContact: "联系人",
  supColOn: "在售",
  supColExpiring: "7 天内到期",
  supColLastUpload: "最近上传",
  supUnnamed: "（还没填公司名）",
  supEmpty: "还没有供应商。在元器件小程序里点「成为供应商」后会出现在这里。",
  supMaskCode: "匿名代号",
  supSuspendedBecause: "暂停理由：{r}",
  supExpired: "已过期（买家看不到）",
  supDispatch: "近 {d} 天派单",
  supDispatchLine: "派 {sent} · 看过 {viewed} · 回话 {responded} · 报价 {quoted} · 被选中 {accepted}",
  supRegisterNotified: "入驻已推企业微信",
  supRegisterNotNotified: "入驻没推到企业微信",
  supStock: "他的库存",
  supStockEmpty: "他还没有库存 —— 供应商在小程序里上传库存表、确认上架后会出现在这里",
  supSuspend: "暂停",
  supSuspendTitle: "暂停 {name}？",
  supSuspendDesc: "他的货会当场从买家那边撤下来；理由只给平台看，他只收到「已暂停」",
  supSuspended: "已暂停",
  supResume: "恢复",
  supResumed: "已恢复，他的货重新给买家看",
  supEdit: "改资料",
  supSaved: "已保存",
  supManageWhat: "暂停、恢复与改资料",
  supManageNote: "只能看，不能暂停、恢复或改资料",
  // AGENT 在元器件里指厂牌的授权分销商。别写成「代理」加「商」—— 那三个字在本仓库是上游项目的业务名词，守卫挡着
  kindAGENT: "授权代理",
  kindTRADER: "贸易商",
  kindFACTORY: "工厂余料",
  kindOTHER: "其他",
  fCompany: "公司名称",
  fKind: "类型",
  fCity: "所在城市",
  fContact: "联系人",
  fPhone: "联系手机",
  stockAll: "全部",
  stockExpiring: "将到期",
  stockExpired: "已到期",

  // ── 料号与库存 ──
  partViewParts: "料号",
  partViewStocks: "库存行",
  partPh: "料号，开头 / 中段都能搜（不计入买家的搜索需求）",
  partEmpty: "输入料号搜索",
  partNone: "没有搜到",
  partColPkg: "封装",
  partColSuppliers: "几家有货",
  partColTotal: "合计数量",
  partColBuyerFrom: "买家看到起价",
  partUnknownMfr: "厂牌不明（原文：{raw}）",
  partBands: "买家看到：库存档 {q} · 货源档 {s}",
  partSources: "谁有货",
  stockSupplierPh: "供应商号（选填）",
  stockEmpty: "没有符合条件的库存 —— 换个料号或供应商号再查，或把筛选切回「全部」",
  stockValid: "有效至 {d}",

  // ── 基础数据 ──
  baseUnknown: "认不出的厂牌",
  baseUnknownHint: "供应商上传与买家询价里认不出的厂牌写法，按两边合计次数排。补成别名后，既有库存当场改认，下次上传、派单与求购大厅也认得出",
  baseUnknownEmpty: "没有认不出的厂牌写法 —— 上传与询价里的厂牌都认得出，不用补别名",
  baseColRaw: "写法",
  baseColRows: "库存行",
  baseColSuppliersParts: "几家 · 几个料号",
  baseColRfq: "询价里",
  baseRfqLines: "{n} 行 · {b} 人",
  baseSampleRfq: "看最近一单",
  baseColSuggest: "建议",
  baseToAlias: "补成 {mfr} 的别名",
  basePickMfr: "选厂牌",
  baseToAliasNone: "先选厂牌",
  baseAliasDone: "已补成别名：改认 {rows} 行库存、{parts} 个料号",
  baseMfrs: "厂牌",
  baseMfrPh: "代码 / 名称",
  baseAddMfr: "加厂牌",
  baseColCode: "代码",
  baseColName: "名称",
  baseColAliases: "别名数",
  baseColParts: "料号数",
  baseMerged: "已并入 {to}",
  baseRename: "改名",
  baseAliases: "别名",
  baseAliasesOf: "{code} 的别名",
  baseAliasPh: "原样写，如 Texas Instruments Inc.",
  baseAddAlias: "加别名",
  baseAliasSeed: "种子",
  baseAliasOps: "运营加的",
  fMfrCode: "厂牌代码（建了不能改）",
  fNameEn: "英文名",
  fNameCn: "中文名",
  baseMfrSaved: "已保存",
  baseMfrEmpty: "没有符合的厂牌 —— 换个代码或名称再查，或点「加厂牌」新建",
  baseAliasEmpty: "这家厂牌还没有别名 —— 在上面输入供应商表里的写法，加上后既有库存当场改认",
  hdr: "库存表的表头写法",
  hdrHint: "供应商表里的表头认成哪个字段，改了当场生效。「各家学到的」是供应商上传时自己选过列的写法，几家都这么写就提升为全局",
  hdrGlobal: "全局",
  hdrLearned: "各家学到的",
  hdrSearchPh: "写法",
  hdrAddPh: "表头原文",
  hdrAdd: "加写法",
  hdrPickField: "选字段",
  hdrColField: "认成",
  hdrColSource: "来源",
  hdrColUsers: "几家在用",
  hdrColLast: "最近一次",
  hdrActive: "在用",
  hdrDisabled: "已停用",
  hdrDisable: "停用",
  hdrEnable: "启用",
  hdrPromote: "提升为全局",
  hdrSaved: "已保存，下次上传就按这个认",
  hdrPromoted: "已提升为全局，所有供应商下次上传都认得出",
  hdrEmptyGlobal: "没有符合的写法 —— 换个词再搜，或在上面加一条",
  hdrEmptyLearned: "还没有各家学到的写法 —— 供应商上传时手工选过列，这里才会有",
  fieldMPN: "料号",
  fieldMFR: "厂牌",
  fieldQTY: "数量",
  fieldDC: "批号",
  fieldPACKAGE: "封装",
  fieldPRICE: "单价",
  fieldMOQ: "起订量",
  fieldSPQ: "最小包装",
  fieldPACKING: "包装方式",
  fieldCONDITION: "货况",
  fieldCURRENCY: "币种",
  fieldLEAD: "交期",
  fieldREGION: "所在地",

  // ── 状态 ──
  stSUBMITTED: "待报价",
  stQUOTED: "已报价",
  stEXPIRED: "报价已过期",
  stACCEPTED: "已接受",
  stCLOSED: "已结束",
  supACTIVE: "正常",
  supSUSPENDED: "已暂停",
  dsSENT: "未看",
  dsVIEWED: "看了没回",
  dsQUOTED: "报了价",
  dsDECLINED: "拒了",
  qsACTIVE: "有效",
  qsWITHDRAWN: "已撤回",
  qsACCEPTED: "被选中",
  qsNOT_CHOSEN: "未被选中",
  qsEXPIRED: "已过期",
  // 买家的要求（「不限」的不显示）
  invNONE: "不开票",
  invVAT_NORMAL: "普票",
  invVAT_SPECIAL: "专票",
  dcY1: "一年内批次",
  dcY2: "两年内批次",
  condORIGINAL: "只要原装原包",
  condNEW: "原装即可",
  packREEL: "必须整盘",
  packCUT_TAPE: "可以剪带",
  needBy: "{n} 天内到货",
  allowAlt: "可用替代型号",
};

const en: typeof zh = {
  colStatus: "Status",
  colCreated: "Time",
  colPhone: "Phone",
  colQty: "Qty",
  colPrice: "Unit price",
  colDc: "Date code",
  colLead: "Lead time",
  colMpn: "Part number",
  colMfr: "Manufacturer",
  colSupplier: "Supplier",
  spot: "In stock",
  leadDays: "{n} days",
  leadUnknown: "Not stated",
  taxIn: "incl. tax",
  taxEx: "excl. tax",
  none: "—",
  save: "Save",
  cancel: "Cancel",
  searchPh: "Type and press Enter",

  rfqViewOrders: "RFQs",
  rfqViewQuotes: "Quote records",
  rfqStatusAll: "All statuses",
  rfqColNo: "RFQ no.",
  rfqColBuyer: "Buyer",
  rfqColLines: "Parts",
  rfqColProgress: "Dispatched / replied / valid quotes",
  rfqLinesMore: "{mpn} and {n} more",
  rfqEmpty: "No RFQs yet. They appear here once buyers submit them in the components mini program.",
  rfqReq: "Requirements",
  rfqRemark: "Remark",
  rfqNotified: "Buyer has been notified",
  rfqNotNotified: "Result has not reached the buyer",
  rfqLine: "Line {n}",
  rfqTarget: "Target {p}",
  rfqSources: "Who has stock",
  rfqSourcesEmpty: "No stock for this part. You can dispatch the RFQ line to suppliers who may have it",
  rfqOffers: "Dispatched to · replies",
  rfqOffersEmpty: "Not dispatched to any supplier yet",
  rfqBuyerPrice: "Buyer sees {p}",
  rfqSupplierRemark: "Note to platform: {r}",
  rfqSupplierRemarkFwd: "Note (visible to the buyer in forward mode): {r}",
  rfqPriceMode: "Pricing",
  rfqModeMARKUP: "Markup",
  rfqModeFORWARD: "Forward",
  rfqModeMARKUPDesc: "Buyer sees the platform price; suppliers show as Quote A / B / C",
  rfqModeFORWARDDesc: "Buyer sees the supplier's own price and anonymous code, like a direct deal; the platform still sees everything",
  rfqModeLocked: "A line already has a chosen quote, or the RFQ has ended — can't change",
  rfqModeChanged: "Switched to {m}",
  rfqMfrRaw: "{m}, unrecognized",
  rfqPublic: "Open request",
  rfqPublicDesc: "No one has stock; open to suppliers since {t} — they pick it from the request board",
  rfqViaOPEN: "From board",
  rfqPlatform: "Platform quote (incl. tax, CNY)",
  rfqPlatformPh: "Leave empty = not found",
  rfqQuoteQty: "Can supply",
  rfqQuoteDcYear: "Date code year",
  rfqQuoteLead: "Lead days (0 = in stock)",
  rfqValidDays: "Valid for (days)",
  rfqNote: "Note to buyer",
  rfqSaveQuote: "Save and notify buyer",
  rfqSaveQuoteHint: "The buyer is notified immediately and can accept right away. Lines without a price are reported as not found",
  rfqQuoted: "Quoted and buyer notified",
  rfqDispatchPh: "Supplier nos., comma separated",
  rfqDispatch: "Dispatch to",
  rfqDispatched: "Dispatched",
  rfqClose: "Close",
  rfqCloseNoSource: "No source",
  rfqCloseCancelled: "Buyer cancelled",
  rfqCloseDone: "Deal done",
  rfqCloseTitle: "Close {no}?",
  rfqCloseDesc: "\"No source\" notifies the buyer. A closed RFQ can no longer be quoted",
  rfqClosed: "Closed",
  rfqNoQuotePerm: "quoting, closing and dispatching",
  rfqNoQuoteNote: "View only: cannot quote, close or dispatch",
  quoteColRfq: "RFQ / line",
  quoteColWanted: "Wanted / can supply",
  quoteColBuyerPrice: "Buyer sees",
  quoteColValid: "Valid until",
  quoteEmpty: "No supplier quotes yet. They appear once dispatched suppliers quote in the mini program",

  supKwPh: "Company / phone / code, press Enter",
  supStatusAll: "All statuses",
  supColCompany: "Company",
  supColKind: "Type · city",
  supColContact: "Contact",
  supColOn: "On sale",
  supColExpiring: "Expiring in 7 days",
  supColLastUpload: "Last upload",
  supUnnamed: "(company name not filled)",
  supEmpty: "No suppliers yet. They appear here after tapping \"Become a supplier\" in the mini program.",
  supMaskCode: "Anonymous code",
  supSuspendedBecause: "Suspended because: {r}",
  supExpired: "Expired (hidden from buyers)",
  supDispatch: "Dispatches, last {d} days",
  supDispatchLine: "Sent {sent} · viewed {viewed} · replied {responded} · quoted {quoted} · chosen {accepted}",
  supRegisterNotified: "Sign-up pushed to WeCom",
  supRegisterNotNotified: "Sign-up not pushed to WeCom",
  supStock: "Stock",
  supStockEmpty: "No stock yet. It appears after the supplier uploads a stock sheet and confirms it in the mini program",
  supSuspend: "Suspend",
  supSuspendTitle: "Suspend {name}?",
  supSuspendDesc: "Their stock is removed from buyers immediately. The reason is internal; they only see \"suspended\"",
  supSuspended: "Suspended",
  supResume: "Resume",
  supResumed: "Resumed; their stock is visible to buyers again",
  supEdit: "Edit profile",
  supSaved: "Saved",
  supManageWhat: "suspend, resume and edit",
  supManageNote: "View only: cannot suspend, resume or edit",
  kindAGENT: "Agent",
  kindTRADER: "Trader",
  kindFACTORY: "Factory surplus",
  kindOTHER: "Other",
  fCompany: "Company name",
  fKind: "Type",
  fCity: "City",
  fContact: "Contact",
  fPhone: "Contact phone",
  stockAll: "All",
  stockExpiring: "Expiring",
  stockExpired: "Expired",

  partViewParts: "Parts",
  partViewStocks: "Stock lines",
  partPh: "Part number; prefix or middle both work (not counted as buyer demand)",
  partEmpty: "Search by part number",
  partNone: "Nothing found",
  partColPkg: "Package",
  partColSuppliers: "Suppliers",
  partColTotal: "Total qty",
  partColBuyerFrom: "Buyer price from",
  partUnknownMfr: "Unknown manufacturer (raw: {raw})",
  partBands: "Buyers see: stock band {q} · source band {s}",
  partSources: "Who has stock",
  stockSupplierPh: "Supplier no. (optional)",
  stockEmpty: "No matching stock. Try another part or supplier no., or switch the filter back to All",
  stockValid: "Valid until {d}",

  baseUnknown: "Unrecognised manufacturers",
  baseUnknownHint: "Spellings that uploads and buyer RFQs could not map, most frequent first (both combined). Once added as an alias, existing stock is re-mapped immediately, and future uploads, dispatch and the request board recognise it",
  baseUnknownEmpty: "No unrecognised spellings: every manufacturer in uploads and RFQs is recognised",
  baseColRaw: "Spelling",
  baseColRows: "Stock lines",
  baseColSuppliersParts: "Suppliers · parts",
  baseColRfq: "In RFQs",
  baseRfqLines: "{n} lines · {b} buyers",
  baseSampleRfq: "Latest RFQ",
  baseColSuggest: "Suggestion",
  baseToAlias: "Add as alias of {mfr}",
  basePickMfr: "Pick manufacturer",
  baseToAliasNone: "Pick one first",
  baseAliasDone: "Alias added: {rows} stock lines and {parts} parts re-mapped",
  baseMfrs: "Manufacturers",
  baseMfrPh: "Code / name",
  baseAddMfr: "Add manufacturer",
  baseColCode: "Code",
  baseColName: "Name",
  baseColAliases: "Aliases",
  baseColParts: "Parts",
  baseMerged: "Merged into {to}",
  baseRename: "Rename",
  baseAliases: "Aliases",
  baseAliasesOf: "Aliases of {code}",
  baseAliasPh: "As written, e.g. Texas Instruments Inc.",
  baseAddAlias: "Add alias",
  baseAliasSeed: "Seed",
  baseAliasOps: "Added by ops",
  fMfrCode: "Code (cannot change later)",
  fNameEn: "English name",
  fNameCn: "Chinese name",
  baseMfrSaved: "Saved",
  baseMfrEmpty: "No matching manufacturer. Try another code or name, or add one",
  baseAliasEmpty: "No aliases yet. Add the spelling used in supplier sheets; existing stock is re-mapped immediately",
  hdr: "Stock sheet headers",
  hdrHint: "Which field each supplier column header maps to; changes apply immediately. \"Learned\" lists headers suppliers mapped by hand; promote the ones several suppliers use",
  hdrGlobal: "Global",
  hdrLearned: "Learned",
  hdrSearchPh: "Header",
  hdrAddPh: "Header as written",
  hdrAdd: "Add header",
  hdrPickField: "Pick field",
  hdrColField: "Maps to",
  hdrColSource: "Source",
  hdrColUsers: "Suppliers using",
  hdrColLast: "Last used",
  hdrActive: "Active",
  hdrDisabled: "Disabled",
  hdrDisable: "Disable",
  hdrEnable: "Enable",
  hdrPromote: "Promote to global",
  hdrSaved: "Saved; the next upload uses it",
  hdrPromoted: "Promoted: every supplier's next upload recognises it",
  hdrEmptyGlobal: "No matching header. Try another word, or add one above",
  hdrEmptyLearned: "Nothing learned yet. Headers appear here once a supplier maps a column by hand",
  fieldMPN: "Part number",
  fieldMFR: "Manufacturer",
  fieldQTY: "Quantity",
  fieldDC: "Date code",
  fieldPACKAGE: "Package",
  fieldPRICE: "Unit price",
  fieldMOQ: "MOQ",
  fieldSPQ: "SPQ",
  fieldPACKING: "Packing",
  fieldCONDITION: "Condition",
  fieldCURRENCY: "Currency",
  fieldLEAD: "Lead time",
  fieldREGION: "Location",

  stSUBMITTED: "Awaiting quote",
  stQUOTED: "Quoted",
  stEXPIRED: "Quote expired",
  stACCEPTED: "Accepted",
  stCLOSED: "Closed",
  supACTIVE: "Active",
  supSUSPENDED: "Suspended",
  dsSENT: "Not viewed",
  dsVIEWED: "Viewed, no reply",
  dsQUOTED: "Quoted",
  dsDECLINED: "Declined",
  qsACTIVE: "Valid",
  qsWITHDRAWN: "Withdrawn",
  qsACCEPTED: "Chosen",
  qsNOT_CHOSEN: "Not chosen",
  qsEXPIRED: "Expired",
  invNONE: "No invoice",
  invVAT_NORMAL: "VAT normal invoice",
  invVAT_SPECIAL: "VAT special invoice",
  dcY1: "Date code within 1 year",
  dcY2: "Date code within 2 years",
  condORIGINAL: "Factory sealed only",
  condNEW: "New original",
  packREEL: "Full reel only",
  packCUT_TAPE: "Cut tape OK",
  needBy: "Needed within {n} days",
  allowAlt: "Alternatives OK",
};

export const ELEC_COPY: PageCopy<typeof zh> = { zh, en };
export type ElecCopy = typeof zh;
