-- 回填存量商品的规格：把「维度」补回去，顺带把值编号盖上。
--
-- **要解决的问题**：线上 198 件带规格的商品里，只有 1 件的规格组带 templateNo。
-- 其余 197 件存的是 `{"name":"规格","options":["10斤装","20斤装"]}` —— 自由文本，
-- 维度未知。而 MerchantGoodsServiceImpl#saveSkus 对没有 templateNo 的组直接 continue，
-- 于是 f2086c41（别名与规范化）、V223（计件档位）、V226（补类目维度）对这批商品
-- **一条都用不上**：208 个 SKU 里盖上值编号的只有 4 个。
--
-- 它们本来就不该长这样：这些商品建的时候类目还没配规格库，建品页掉回老模板的品类兜底，
-- 而那条兜底的组名恰好就叫「规格」（V225 已把种子改名，但改名不追溯已存的商品）。
--
-- **怎么定维度**：拿商品的类目 → 该类目绑的维度 → 逐个试着解释这一组的全部取值，
-- **只有恰好一个维度能解释全部取值时才回填**。两个维度都能解释（歧义）或一个都不能，
-- 一律跳过 —— 猜错一个维度比空着更糟：它会把这件商品混进错误的比价池。
-- 198 件里这样定得下来的是 105 件，其余 92 件的情况写在末尾。
--
-- **组名一并改正**：只改**恰好等于「规格」**的那些（老兜底留下的空名字），
-- 改成维度的正名 —— 数量 65、重量 27、处理方式 5、时长 5、容量 1、尺码 1。
-- 商家自己起过名字的一律不动。
--
-- **每条 UPDATE 都带原文精确匹配的闸门**（`AND spec_groups = '<原样>'`）：
-- 这批 UPDATE 是按 2026-08-25 的快照生成的，商家若在这中间改过这件商品，
-- 那一条就不该再套用旧快照 —— 条件不成立、UPDATE 不生效，比覆盖掉他的编辑好。
-- 同理 SKU 那批只在 option_value_nos 仍为空时才写，重复执行也是幂等的。
--
-- 生成脚本与中间数据不进仓库（一次性的），判据全部写在上面，可按注释复算。

-- ── 1. 商品：补 templateNo / optionCodes，并改正组名 ──
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["10斤装", "20斤装"], "optionCodes": ["W5KG", "W10KG"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G0001' AND spec_groups = '[{"name":"规格","options":["10斤装","20斤装"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "容量", "options": ["5L"], "optionCodes": ["V5L"], "templateNo": "SD_VOLUME"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G0002' AND spec_groups = '[{"name":"规格","options":["5L"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["4枚装"], "optionCodes": ["C4"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G0003' AND spec_groups = '[{"name":"规格","options":["4枚装"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["4盒装"], "optionCodes": ["C4"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G0004' AND spec_groups = '[{"name":"规格","options":["4盒装"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "size", "options": ["S", "M"], "optionCodes": ["SZS", "SZM"], "templateNo": "SD_SIZE"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201211530002513' AND spec_groups = '[{"name":"size","options":["S","M"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["4盒"], "optionCodes": ["C4"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201710080013706' AND spec_groups = '[{"name":"规格","options":["4盒"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "处理方式", "options": ["整只"], "optionCodes": ["CUTWHOLE"], "templateNo": "SD_CUT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201710080015357' AND spec_groups = '[{"name":"规格","options":["整只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["400g"], "optionCodes": ["W400G"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201710080017683' AND spec_groups = '[{"name":"规格","options":["400g"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["20粒"], "optionCodes": ["C20"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201710080019327' AND spec_groups = '[{"name":"规格","options":["20粒"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["20片"], "optionCodes": ["C20"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201710080021569' AND spec_groups = '[{"name":"规格","options":["20片"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "时长", "options": ["2小时"], "optionCodes": ["D120"], "templateNo": "SD_DURATION"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201710090023760' AND spec_groups = '[{"name":"规格","options":["2小时"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "时长", "options": ["4小时"], "optionCodes": ["D240"], "templateNo": "SD_DURATION"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201710090025281' AND spec_groups = '[{"name":"规格","options":["4小时"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["24包"], "optionCodes": ["C24"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712510081746' AND spec_groups = '[{"name":"规格","options":["24包"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["27卷"], "optionCodes": ["C27"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712510083032' AND spec_groups = '[{"name":"规格","options":["27卷"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["3kg"], "optionCodes": ["W3KG"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712510085855' AND spec_groups = '[{"name":"规格","options":["3kg"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["500g"], "optionCodes": ["W500G"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712520087792' AND spec_groups = '[{"name":"规格","options":["500g"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["1.5kg"], "optionCodes": ["W1500G"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712520089990' AND spec_groups = '[{"name":"规格","options":["1.5kg"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["4支"], "optionCodes": ["C4"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712520093200' AND spec_groups = '[{"name":"规格","options":["4支"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["4盒"], "optionCodes": ["C4"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712530097277' AND spec_groups = '[{"name":"规格","options":["4盒"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["2斤"], "optionCodes": ["W1KG"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712530105631' AND spec_groups = '[{"name":"规格","options":["2斤"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["2斤"], "optionCodes": ["W1KG"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712540109545' AND spec_groups = '[{"name":"规格","options":["2斤"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["2斤"], "optionCodes": ["W1KG"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712540117867' AND spec_groups = '[{"name":"规格","options":["2斤"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["500g"], "optionCodes": ["W500G"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712550125010' AND spec_groups = '[{"name":"规格","options":["500g"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["500g"], "optionCodes": ["W500G"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712550127694' AND spec_groups = '[{"name":"规格","options":["500g"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["400g"], "optionCodes": ["W400G"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712560129460' AND spec_groups = '[{"name":"规格","options":["400g"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["400g"], "optionCodes": ["W400G"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712560131589' AND spec_groups = '[{"name":"规格","options":["400g"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["500g"], "optionCodes": ["W500G"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712560133080' AND spec_groups = '[{"name":"规格","options":["500g"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["400g"], "optionCodes": ["W400G"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712560135911' AND spec_groups = '[{"name":"规格","options":["400g"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["3颗"], "optionCodes": ["C3"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712560137908' AND spec_groups = '[{"name":"规格","options":["3颗"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["2斤"], "optionCodes": ["W1KG"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712560139072' AND spec_groups = '[{"name":"规格","options":["2斤"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["2斤"], "optionCodes": ["W1KG"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712570141035' AND spec_groups = '[{"name":"规格","options":["2斤"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["2斤"], "optionCodes": ["W1KG"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712570143620' AND spec_groups = '[{"name":"规格","options":["2斤"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["3斤"], "optionCodes": ["W1500G"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712570145946' AND spec_groups = '[{"name":"规格","options":["3斤"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["2斤"], "optionCodes": ["W1KG"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712570147069' AND spec_groups = '[{"name":"规格","options":["2斤"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["500g"], "optionCodes": ["W500G"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712570149571' AND spec_groups = '[{"name":"规格","options":["500g"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["500g"], "optionCodes": ["W500G"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712580151979' AND spec_groups = '[{"name":"规格","options":["500g"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["2斤"], "optionCodes": ["W1KG"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712580153678' AND spec_groups = '[{"name":"规格","options":["2斤"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "处理方式", "options": ["整只"], "optionCodes": ["CUTWHOLE"], "templateNo": "SD_CUT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712580155056' AND spec_groups = '[{"name":"规格","options":["整只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["400g"], "optionCodes": ["W400G"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712580157699' AND spec_groups = '[{"name":"规格","options":["400g"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "处理方式", "options": ["半只"], "optionCodes": ["CUTHALF"], "templateNo": "SD_CUT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712580159059' AND spec_groups = '[{"name":"规格","options":["半只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "处理方式", "options": ["半只"], "optionCodes": ["CUTHALF"], "templateNo": "SD_CUT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712590161876' AND spec_groups = '[{"name":"规格","options":["半只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "处理方式", "options": ["整只"], "optionCodes": ["CUTWHOLE"], "templateNo": "SD_CUT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712590163463' AND spec_groups = '[{"name":"规格","options":["整只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["400g"], "optionCodes": ["W400G"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712590165993' AND spec_groups = '[{"name":"规格","options":["400g"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["4只"], "optionCodes": ["C4"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712590167663' AND spec_groups = '[{"name":"规格","options":["4只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["500g"], "optionCodes": ["W500G"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201712590169036' AND spec_groups = '[{"name":"规格","options":["500g"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["2只"], "optionCodes": ["C2"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713000173526' AND spec_groups = '[{"name":"规格","options":["2只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["3份"], "optionCodes": ["C3"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713000175333' AND spec_groups = '[{"name":"规格","options":["3份"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["6只"], "optionCodes": ["C6"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713000177260' AND spec_groups = '[{"name":"规格","options":["6只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["1条"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713000179137' AND spec_groups = '[{"name":"规格","options":["1条"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["400g"], "optionCodes": ["W400G"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713000181691' AND spec_groups = '[{"name":"规格","options":["400g"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "重量", "options": ["400g"], "optionCodes": ["W400G"], "templateNo": "SD_WEIGHT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713000183679' AND spec_groups = '[{"name":"规格","options":["400g"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["12只"], "optionCodes": ["C12"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713010185703' AND spec_groups = '[{"name":"规格","options":["12只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["20只"], "optionCodes": ["C20"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713010187506' AND spec_groups = '[{"name":"规格","options":["20只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["8只"], "optionCodes": ["C8"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713010189613' AND spec_groups = '[{"name":"规格","options":["8只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["6只"], "optionCodes": ["C6"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713010191869' AND spec_groups = '[{"name":"规格","options":["6只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["2份"], "optionCodes": ["C2"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713010193772' AND spec_groups = '[{"name":"规格","options":["2份"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["2份"], "optionCodes": ["C2"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713020195275' AND spec_groups = '[{"name":"规格","options":["2份"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["4根"], "optionCodes": ["C4"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713020203081' AND spec_groups = '[{"name":"规格","options":["4根"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["6只"], "optionCodes": ["C6"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713030205450' AND spec_groups = '[{"name":"规格","options":["6只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["6只"], "optionCodes": ["C6"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713030207257' AND spec_groups = '[{"name":"规格","options":["6只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["1份"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713030209480' AND spec_groups = '[{"name":"规格","options":["1份"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["1份"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713030211272' AND spec_groups = '[{"name":"规格","options":["1份"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["20粒"], "optionCodes": ["C20"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713040215693' AND spec_groups = '[{"name":"规格","options":["20粒"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["20片"], "optionCodes": ["C20"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713040217914' AND spec_groups = '[{"name":"规格","options":["20片"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["24粒"], "optionCodes": ["C24"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713040219341' AND spec_groups = '[{"name":"规格","options":["24粒"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["10袋"], "optionCodes": ["C10"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713050221729' AND spec_groups = '[{"name":"规格","options":["10袋"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["10支"], "optionCodes": ["C10"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713050223384' AND spec_groups = '[{"name":"规格","options":["10支"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["20袋"], "optionCodes": ["C20"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713050225313' AND spec_groups = '[{"name":"规格","options":["20袋"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["9袋"], "optionCodes": ["C9"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713050227004' AND spec_groups = '[{"name":"规格","options":["9袋"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["24粒"], "optionCodes": ["C24"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713050229826' AND spec_groups = '[{"name":"规格","options":["24粒"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["32片"], "optionCodes": ["C32"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713060231945' AND spec_groups = '[{"name":"规格","options":["32片"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["6支"], "optionCodes": ["C6"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713060233387' AND spec_groups = '[{"name":"规格","options":["6支"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["20片"], "optionCodes": ["C20"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713060235638' AND spec_groups = '[{"name":"规格","options":["20片"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["60片"], "optionCodes": ["C60"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713060237008' AND spec_groups = '[{"name":"规格","options":["60片"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["60片"], "optionCodes": ["C60"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713060239767' AND spec_groups = '[{"name":"规格","options":["60片"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["100粒"], "optionCodes": ["C100"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713070241586' AND spec_groups = '[{"name":"规格","options":["100粒"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["20袋"], "optionCodes": ["C20"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713070243474' AND spec_groups = '[{"name":"规格","options":["20袋"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["100片"], "optionCodes": ["C100"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713070245351' AND spec_groups = '[{"name":"规格","options":["100片"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["10片"], "optionCodes": ["C10"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713070247493' AND spec_groups = '[{"name":"规格","options":["10片"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["50支"], "optionCodes": ["C50"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713070249600' AND spec_groups = '[{"name":"规格","options":["50支"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["100片"], "optionCodes": ["C100"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713070251759' AND spec_groups = '[{"name":"规格","options":["100片"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["50只"], "optionCodes": ["C50"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713080253186' AND spec_groups = '[{"name":"规格","options":["50只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["20只"], "optionCodes": ["C20"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713080255450' AND spec_groups = '[{"name":"规格","options":["20只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["单支"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713080257460' AND spec_groups = '[{"name":"规格","options":["单支"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["单支"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713080259161' AND spec_groups = '[{"name":"规格","options":["单支"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["单台"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713080261628' AND spec_groups = '[{"name":"规格","options":["单台"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["套装"], "optionCodes": ["CSET"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713090263493' AND spec_groups = '[{"name":"规格","options":["套装"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "尺码", "options": ["均码"], "optionCodes": ["SZONE"], "templateNo": "SD_SIZE"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713090265859' AND spec_groups = '[{"name":"规格","options":["均码"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["10片"], "optionCodes": ["C10"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713090267427' AND spec_groups = '[{"name":"规格","options":["10片"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["单瓶"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713090269435' AND spec_groups = '[{"name":"规格","options":["单瓶"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "时长", "options": ["2小时"], "optionCodes": ["D120"], "templateNo": "SD_DURATION"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713100275183' AND spec_groups = '[{"name":"规格","options":["2小时"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "时长", "options": ["4小时"], "optionCodes": ["D240"], "templateNo": "SD_DURATION"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713100277129' AND spec_groups = '[{"name":"规格","options":["4小时"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["单台"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713100283070' AND spec_groups = '[{"name":"规格","options":["单台"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["单台"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713110285187' AND spec_groups = '[{"name":"规格","options":["单台"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["单台"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713110287499' AND spec_groups = '[{"name":"规格","options":["单台"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["单台"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713110289894' AND spec_groups = '[{"name":"规格","options":["单台"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["单台"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713110291184' AND spec_groups = '[{"name":"规格","options":["单台"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "时长", "options": ["4小时"], "optionCodes": ["D240"], "templateNo": "SD_DURATION"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713120303069' AND spec_groups = '[{"name":"规格","options":["4小时"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["单只"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713130309628' AND spec_groups = '[{"name":"规格","options":["单只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["单只"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713130311210' AND spec_groups = '[{"name":"规格","options":["单只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["单只"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713130313788' AND spec_groups = '[{"name":"规格","options":["单只"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["单台"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713130315866' AND spec_groups = '[{"name":"规格","options":["单台"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["单台"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713130317037' AND spec_groups = '[{"name":"规格","options":["单台"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["单台"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713140319974' AND spec_groups = '[{"name":"规格","options":["单台"]}]';
UPDATE prd_goods SET spec_groups = '[{"name": "数量", "options": ["单件"], "optionCodes": ["C1"], "templateNo": "SD_COUNT"}]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE goods_no = 'G202608201713140329272' AND spec_groups = '[{"name":"规格","options":["单件"]}]';

-- ── 2. SKU：盖上值编号 ──
--
-- 这一列是「跨店可比」真正落地的地方：有它，三家店的同一档规格才聚得到一起。
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W5KG"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK0001' AND market = 'CN' AND option_values = '["10斤装"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W10KG"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK0002' AND market = 'CN' AND option_values = '["20斤装"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_VOLUME_V5L"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK0003' AND market = 'CN' AND option_values = '["5L"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C4"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK0004' AND market = 'CN' AND option_values = '["4枚装"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C4"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK0005' AND market = 'CN' AND option_values = '["4盒装"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_SIZE_SZS"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201217180004603' AND market = 'CN' AND option_values = '["S"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_SIZE_SZM"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201217180005176' AND market = 'CN' AND option_values = '["M"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C4"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201710080014160' AND market = 'CN' AND option_values = '["4盒"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_CUT_CUTWHOLE"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201710080016151' AND market = 'CN' AND option_values = '["整只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W400G"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201710080018986' AND market = 'CN' AND option_values = '["400g"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C20"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201710080020702' AND market = 'CN' AND option_values = '["20粒"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C20"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201710080022917' AND market = 'CN' AND option_values = '["20片"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_DURATION_D120"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201710090024145' AND market = 'CN' AND option_values = '["2小时"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_DURATION_D240"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201710090026978' AND market = 'CN' AND option_values = '["4小时"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C24"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712510082364' AND market = 'CN' AND option_values = '["24包"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C27"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712510084800' AND market = 'CN' AND option_values = '["27卷"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W3KG"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712510086862' AND market = 'CN' AND option_values = '["3kg"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W500G"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712520088377' AND market = 'CN' AND option_values = '["500g"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W1500G"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712520090287' AND market = 'CN' AND option_values = '["1.5kg"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C4"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712520094057' AND market = 'CN' AND option_values = '["4支"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C4"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712530098975' AND market = 'CN' AND option_values = '["4盒"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W1KG"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712530106170' AND market = 'CN' AND option_values = '["2斤"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W1KG"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712540110597' AND market = 'CN' AND option_values = '["2斤"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W1KG"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712550118629' AND market = 'CN' AND option_values = '["2斤"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W500G"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712550126043' AND market = 'CN' AND option_values = '["500g"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W500G"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712550128655' AND market = 'CN' AND option_values = '["500g"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W400G"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712560130175' AND market = 'CN' AND option_values = '["400g"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W400G"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712560132797' AND market = 'CN' AND option_values = '["400g"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W500G"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712560134709' AND market = 'CN' AND option_values = '["500g"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W400G"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712560136972' AND market = 'CN' AND option_values = '["400g"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C3"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712560138896' AND market = 'CN' AND option_values = '["3颗"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W1KG"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712560140500' AND market = 'CN' AND option_values = '["2斤"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W1KG"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712570142798' AND market = 'CN' AND option_values = '["2斤"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W1KG"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712570144130' AND market = 'CN' AND option_values = '["2斤"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W1500G"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712570146459' AND market = 'CN' AND option_values = '["3斤"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W1KG"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712570148790' AND market = 'CN' AND option_values = '["2斤"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W500G"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712570150897' AND market = 'CN' AND option_values = '["500g"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W500G"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712580152695' AND market = 'CN' AND option_values = '["500g"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W1KG"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712580154981' AND market = 'CN' AND option_values = '["2斤"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_CUT_CUTWHOLE"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712580156898' AND market = 'CN' AND option_values = '["整只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W400G"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712580158424' AND market = 'CN' AND option_values = '["400g"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_CUT_CUTHALF"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712580160763' AND market = 'CN' AND option_values = '["半只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_CUT_CUTHALF"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712590162111' AND market = 'CN' AND option_values = '["半只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_CUT_CUTWHOLE"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712590164598' AND market = 'CN' AND option_values = '["整只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W400G"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712590166433' AND market = 'CN' AND option_values = '["400g"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C4"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712590168067' AND market = 'CN' AND option_values = '["4只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W500G"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201712590170009' AND market = 'CN' AND option_values = '["500g"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C2"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713000174256' AND market = 'CN' AND option_values = '["2只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C3"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713000176509' AND market = 'CN' AND option_values = '["3份"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C6"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713000178515' AND market = 'CN' AND option_values = '["6只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713000180114' AND market = 'CN' AND option_values = '["1条"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W400G"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713000182842' AND market = 'CN' AND option_values = '["400g"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_WEIGHT_W400G"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713000184146' AND market = 'CN' AND option_values = '["400g"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C12"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713010186061' AND market = 'CN' AND option_values = '["12只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C20"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713010188101' AND market = 'CN' AND option_values = '["20只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C8"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713010190662' AND market = 'CN' AND option_values = '["8只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C6"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713010192587' AND market = 'CN' AND option_values = '["6只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C2"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713010194394' AND market = 'CN' AND option_values = '["2份"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C2"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713020196106' AND market = 'CN' AND option_values = '["2份"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C4"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713020204735' AND market = 'CN' AND option_values = '["4根"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C6"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713030206454' AND market = 'CN' AND option_values = '["6只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C6"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713030208889' AND market = 'CN' AND option_values = '["6只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713030210627' AND market = 'CN' AND option_values = '["1份"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713030212982' AND market = 'CN' AND option_values = '["1份"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C20"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713040216641' AND market = 'CN' AND option_values = '["20粒"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C20"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713040218962' AND market = 'CN' AND option_values = '["20片"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C24"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713050220939' AND market = 'CN' AND option_values = '["24粒"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C10"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713050222488' AND market = 'CN' AND option_values = '["10袋"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C10"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713050224535' AND market = 'CN' AND option_values = '["10支"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C20"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713050226542' AND market = 'CN' AND option_values = '["20袋"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C9"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713050228589' AND market = 'CN' AND option_values = '["9袋"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C24"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713050230502' AND market = 'CN' AND option_values = '["24粒"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C32"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713060232582' AND market = 'CN' AND option_values = '["32片"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C6"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713060234884' AND market = 'CN' AND option_values = '["6支"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C20"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713060236820' AND market = 'CN' AND option_values = '["20片"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C60"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713060238124' AND market = 'CN' AND option_values = '["60片"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C60"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713060240462' AND market = 'CN' AND option_values = '["60片"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C100"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713070242147' AND market = 'CN' AND option_values = '["100粒"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C20"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713070244792' AND market = 'CN' AND option_values = '["20袋"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C100"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713070246602' AND market = 'CN' AND option_values = '["100片"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C10"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713070248514' AND market = 'CN' AND option_values = '["10片"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C50"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713070250193' AND market = 'CN' AND option_values = '["50支"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C100"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713070252211' AND market = 'CN' AND option_values = '["100片"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C50"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713080254693' AND market = 'CN' AND option_values = '["50只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C20"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713080256661' AND market = 'CN' AND option_values = '["20只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713080258706' AND market = 'CN' AND option_values = '["单支"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713080260651' AND market = 'CN' AND option_values = '["单支"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713080262674' AND market = 'CN' AND option_values = '["单台"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_CSET"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713090264317' AND market = 'CN' AND option_values = '["套装"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_SIZE_SZONE"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713090266917' AND market = 'CN' AND option_values = '["均码"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C10"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713090268945' AND market = 'CN' AND option_values = '["10片"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713090270056' AND market = 'CN' AND option_values = '["单瓶"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_DURATION_D120"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713100276120' AND market = 'CN' AND option_values = '["2小时"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_DURATION_D240"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713100278856' AND market = 'CN' AND option_values = '["4小时"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713100284810' AND market = 'CN' AND option_values = '["单台"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713110286854' AND market = 'CN' AND option_values = '["单台"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713110288365' AND market = 'CN' AND option_values = '["单台"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713110290217' AND market = 'CN' AND option_values = '["单台"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713110292760' AND market = 'CN' AND option_values = '["单台"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_DURATION_D240"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713120304518' AND market = 'CN' AND option_values = '["4小时"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713130310064' AND market = 'CN' AND option_values = '["单只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713130312371' AND market = 'CN' AND option_values = '["单只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713130314566' AND market = 'CN' AND option_values = '["单只"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713130316795' AND market = 'CN' AND option_values = '["单台"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713130318895' AND market = 'CN' AND option_values = '["单台"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713140320193' AND market = 'CN' AND option_values = '["单台"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));
UPDATE prd_sku SET option_value_nos = '["SV_COUNT_C1"]', updated_at = NOW(), updated_by = 'SYSTEM' WHERE sku_no = 'SK202608201713140330601' AND market = 'CN' AND option_values = '["单件"]' AND (option_value_nos IS NULL OR option_value_nos IN ('', '[]'));

-- ── 剩下的 92 件，为什么没回填 ──
--
-- **69 件压在停用类目下**（卡券 32、粮油调味 12、常温水果 12、休闲零食 10、茶叶 3），
-- 这些类目一个维度都没配，其中几个还是三级类目 —— 而绑定只挂在二级，
-- 取规格时不往父类目回溯（SpecLibraryServiceImpl#activeBindings 是精确匹配）。
-- 这批商品该迁到启用类目还是该下架，是运营的判断，不在这条迁移里替他们定。
--
-- **其余是服务类的计价单位**：100㎡内、每㎡、每米、每窗、3人位、1.8m、单把。
-- 它们讲的不是「规格」而是「按什么计价」，硬塞进现有维度会把语义弄脏。
-- 该不该开一个「计价单位」维度是产品决定。同类还有「月卡」「券包」「大份」。
