-- 补回「后端有码、UI_PERM_MAP 里没有对应项」那 22 个权限码的功能点与授权。
--
-- **这是 V72 造成的回归**：V72 按当前 UI_PERM_MAP 重建功能点，而权限码从 16 个细化到
-- 68 个之后，Perms.ROLE_PERMS 长出了一批 UI_PERM_MAP 映射不出来的后端码。
-- 角色→功能点是靠 perm_code 对上的，一个后端码没有任何功能点带它，
-- 那条授权就**无处安放、静默蒸发** —— 实测 FINANCE 一个角色丢了 9/16，
-- 而没有任何报错：表现只是那个角色调某个接口 403。
--
-- 生成器已补上兜底（gen-perm-seed.mjs 末段「仅后端」那一块），此后不会再漏。
--
-- **本迁移是增量的**，不再整体替换 —— V72 把 point_code 改成 href/码派生之后，
-- 新增功能点只新增行，既有授权一律不受影响。这正是那次改造要换来的东西。

-- ── 1. 新增功能点（仅后端：有端点、运营端还没有界面入口）──
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__AFTERSALE_REFUND_READ', 'OPS_AFTERSALE', 'aftersale:refund:read', '仅后端', NULL, NULL, 'aftersale:refund:read', 'IMPLEMENTED', 0, NULL, 'ACTION', 910, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__COMMUNITY_REGION_READ', 'OPS_COMMUNITY', 'community:region:read', '仅后端', NULL, NULL, 'community:region:read', 'IMPLEMENTED', 0, NULL, 'ACTION', 911, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__DASHBOARD_OVERVIEW_READ', 'OPS_DASHBOARD', 'dashboard:overview:read', '仅后端', NULL, NULL, 'dashboard:overview:read', 'IMPLEMENTED', 0, NULL, 'ACTION', 912, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__FINANCE_INVOICE_VERIFY', 'OPS_FINANCE', 'finance:invoice:verify', '仅后端', NULL, NULL, 'finance:invoice:verify', 'IMPLEMENTED', 0, NULL, 'ACTION', 913, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__FINANCE_PAYOUT_EXECUTE', 'OPS_FINANCE', 'finance:payout:execute', '仅后端', NULL, NULL, 'finance:payout:execute', 'IMPLEMENTED', 0, NULL, 'ACTION', 914, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__FINANCE_RATE_READ', 'OPS_FINANCE', 'finance:rate:read', '仅后端', NULL, NULL, 'finance:rate:read', 'IMPLEMENTED', 0, NULL, 'ACTION', 915, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__FINANCE_RECON_READ', 'OPS_FINANCE', 'finance:recon:read', '仅后端', NULL, NULL, 'finance:recon:read', 'IMPLEMENTED', 0, NULL, 'ACTION', 916, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__FINANCE_RECON_RESOLVE', 'OPS_FINANCE', 'finance:recon:resolve', '仅后端', NULL, NULL, 'finance:recon:resolve', 'IMPLEMENTED', 0, NULL, 'ACTION', 917, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__GROUP_CAMPAIGN_READ', 'OPS_GROUP', 'group:campaign:read', '仅后端', NULL, NULL, 'group:campaign:read', 'IMPLEMENTED', 0, NULL, 'ACTION', 918, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__MARKETING_CAMPAIGN_READ', 'OPS_MARKETING', 'marketing:campaign:read', '仅后端', NULL, NULL, 'marketing:campaign:read', 'IMPLEMENTED', 0, NULL, 'ACTION', 919, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__MARKETING_COUPON_UPDATE', 'OPS_MARKETING', 'marketing:coupon:update', '仅后端', NULL, NULL, 'marketing:coupon:update', 'IMPLEMENTED', 0, NULL, 'ACTION', 920, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__MERCHANT_ADMISSION_READ', 'OPS_MERCHANT', 'merchant:admission:read', '仅后端', NULL, NULL, 'merchant:admission:read', 'IMPLEMENTED', 0, NULL, 'ACTION', 921, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__MERCHANT_ADMISSION_UPDATE', 'OPS_MERCHANT', 'merchant:admission:update', '仅后端', NULL, NULL, 'merchant:admission:update', 'IMPLEMENTED', 0, NULL, 'ACTION', 922, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__MERCHANT_CATEGORY_READ', 'OPS_MERCHANT', 'merchant:category:read', '仅后端', NULL, NULL, 'merchant:category:read', 'IMPLEMENTED', 0, NULL, 'ACTION', 923, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__MERCHANT_MODE_READ', 'OPS_MERCHANT', 'merchant:mode:read', '仅后端', NULL, NULL, 'merchant:mode:read', 'IMPLEMENTED', 0, NULL, 'ACTION', 924, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__MERCHANT_MODE_UPDATE', 'OPS_MERCHANT', 'merchant:mode:update', '仅后端', NULL, NULL, 'merchant:mode:update', 'IMPLEMENTED', 0, NULL, 'ACTION', 925, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__REVIEW_REVIEW_READ', 'OPS_REVIEW', 'review:review:read', '仅后端', NULL, NULL, 'review:review:read', 'IMPLEMENTED', 0, NULL, 'ACTION', 926, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__REVIEW_SCORE_READ', 'OPS_REVIEW', 'review:score:read', '仅后端', NULL, NULL, 'review:score:read', 'IMPLEMENTED', 0, NULL, 'ACTION', 927, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__SYSTEM_INDUSTRY_READ', 'OPS_SYSTEM', 'system:industry:read', '仅后端', NULL, NULL, 'system:industry:read', 'IMPLEMENTED', 0, NULL, 'ACTION', 928, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__SYSTEM_INDUSTRY_UPDATE', 'OPS_SYSTEM', 'system:industry:update', '仅后端', NULL, NULL, 'system:industry:update', 'IMPLEMENTED', 0, NULL, 'ACTION', 929, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__SYSTEM_PARAM_UPDATE', 'OPS_SYSTEM', 'system:param:update', '仅后端', NULL, NULL, 'system:param:update', 'IMPLEMENTED', 0, NULL, 'ACTION', 930, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;
INSERT INTO sys_function_point (point_code, function_code, name, group_name, href, ui_perm_code, perm_code, backend_status, ui_ready, matrix_code, point_type, sort, created_at, updated_at) VALUES ('ACT__SYSTEM_THEME_READ', 'OPS_SYSTEM', 'system:theme:read', '仅后端', NULL, NULL, 'system:theme:read', 'IMPLEMENTED', 0, NULL, 'ACTION', 931, NOW(), NOW()) ON DUPLICATE KEY UPDATE point_code = point_code;

-- ── 2. 内置角色对这些点的授权 ──
--    NOT EXISTS 而不是 INSERT IGNORE：uk_role_point 含 entity_no 且它是 NULL，
--    而 MySQL 唯一索引**不去重 NULL** —— IGNORE 在这张表上挡不住重复（V72 踩过）。
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__AFTERSALE_REFUND_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__AFTERSALE_REFUND_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__COMMUNITY_REGION_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__COMMUNITY_REGION_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__DASHBOARD_OVERVIEW_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__DASHBOARD_OVERVIEW_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__FINANCE_INVOICE_VERIFY', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__FINANCE_INVOICE_VERIFY' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__FINANCE_PAYOUT_EXECUTE', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__FINANCE_PAYOUT_EXECUTE' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__FINANCE_RATE_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__FINANCE_RATE_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__FINANCE_RECON_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__FINANCE_RECON_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__FINANCE_RECON_RESOLVE', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__FINANCE_RECON_RESOLVE' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__GROUP_CAMPAIGN_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__GROUP_CAMPAIGN_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__MARKETING_CAMPAIGN_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__MARKETING_CAMPAIGN_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__MARKETING_COUPON_UPDATE', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__MARKETING_COUPON_UPDATE' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__MERCHANT_ADMISSION_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__MERCHANT_ADMISSION_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__MERCHANT_ADMISSION_UPDATE', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__MERCHANT_ADMISSION_UPDATE' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__MERCHANT_CATEGORY_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__MERCHANT_CATEGORY_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__MERCHANT_MODE_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__MERCHANT_MODE_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__MERCHANT_MODE_UPDATE', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__MERCHANT_MODE_UPDATE' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__REVIEW_REVIEW_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__REVIEW_REVIEW_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__REVIEW_SCORE_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__REVIEW_SCORE_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__SYSTEM_INDUSTRY_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__SYSTEM_INDUSTRY_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__SYSTEM_INDUSTRY_UPDATE', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__SYSTEM_INDUSTRY_UPDATE' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__SYSTEM_PARAM_UPDATE', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__SYSTEM_PARAM_UPDATE' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPER_ADMIN', 'ACT__SYSTEM_THEME_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPER_ADMIN' AND x.point_code='ACT__SYSTEM_THEME_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'BD', 'ACT__AFTERSALE_REFUND_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='BD' AND x.point_code='ACT__AFTERSALE_REFUND_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'BD', 'ACT__DASHBOARD_OVERVIEW_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='BD' AND x.point_code='ACT__DASHBOARD_OVERVIEW_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'BD', 'ACT__MERCHANT_CATEGORY_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='BD' AND x.point_code='ACT__MERCHANT_CATEGORY_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'BD', 'ACT__MERCHANT_MODE_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='BD' AND x.point_code='ACT__MERCHANT_MODE_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'BD', 'ACT__MERCHANT_MODE_UPDATE', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='BD' AND x.point_code='ACT__MERCHANT_MODE_UPDATE' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'GOODS_OPS', 'ACT__AFTERSALE_REFUND_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='GOODS_OPS' AND x.point_code='ACT__AFTERSALE_REFUND_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'GOODS_OPS', 'ACT__DASHBOARD_OVERVIEW_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='GOODS_OPS' AND x.point_code='ACT__DASHBOARD_OVERVIEW_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'GOODS_OPS', 'ACT__GROUP_CAMPAIGN_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='GOODS_OPS' AND x.point_code='ACT__GROUP_CAMPAIGN_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'GOODS_OPS', 'ACT__MARKETING_CAMPAIGN_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='GOODS_OPS' AND x.point_code='ACT__MARKETING_CAMPAIGN_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'GOODS_OPS', 'ACT__MARKETING_COUPON_UPDATE', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='GOODS_OPS' AND x.point_code='ACT__MARKETING_COUPON_UPDATE' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPPORT', 'ACT__AFTERSALE_REFUND_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPPORT' AND x.point_code='ACT__AFTERSALE_REFUND_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPPORT', 'ACT__DASHBOARD_OVERVIEW_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPPORT' AND x.point_code='ACT__DASHBOARD_OVERVIEW_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPPORT', 'ACT__REVIEW_REVIEW_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPPORT' AND x.point_code='ACT__REVIEW_REVIEW_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'SUPPORT', 'ACT__REVIEW_SCORE_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='SUPPORT' AND x.point_code='ACT__REVIEW_SCORE_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'CAMPAIGN_OPS', 'ACT__AFTERSALE_REFUND_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='CAMPAIGN_OPS' AND x.point_code='ACT__AFTERSALE_REFUND_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'CAMPAIGN_OPS', 'ACT__DASHBOARD_OVERVIEW_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='CAMPAIGN_OPS' AND x.point_code='ACT__DASHBOARD_OVERVIEW_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'CAMPAIGN_OPS', 'ACT__GROUP_CAMPAIGN_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='CAMPAIGN_OPS' AND x.point_code='ACT__GROUP_CAMPAIGN_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'CAMPAIGN_OPS', 'ACT__MARKETING_CAMPAIGN_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='CAMPAIGN_OPS' AND x.point_code='ACT__MARKETING_CAMPAIGN_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'CAMPAIGN_OPS', 'ACT__MARKETING_COUPON_UPDATE', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='CAMPAIGN_OPS' AND x.point_code='ACT__MARKETING_COUPON_UPDATE' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'COMMUNITY_OPS', 'ACT__AFTERSALE_REFUND_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='COMMUNITY_OPS' AND x.point_code='ACT__AFTERSALE_REFUND_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'COMMUNITY_OPS', 'ACT__COMMUNITY_REGION_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='COMMUNITY_OPS' AND x.point_code='ACT__COMMUNITY_REGION_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'COMMUNITY_OPS', 'ACT__DASHBOARD_OVERVIEW_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='COMMUNITY_OPS' AND x.point_code='ACT__DASHBOARD_OVERVIEW_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'COMMUNITY_OPS', 'ACT__SYSTEM_INDUSTRY_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='COMMUNITY_OPS' AND x.point_code='ACT__SYSTEM_INDUSTRY_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'COMMUNITY_OPS', 'ACT__SYSTEM_INDUSTRY_UPDATE', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='COMMUNITY_OPS' AND x.point_code='ACT__SYSTEM_INDUSTRY_UPDATE' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'AUDITOR', 'ACT__REVIEW_REVIEW_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='AUDITOR' AND x.point_code='ACT__REVIEW_REVIEW_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'AUDITOR', 'ACT__REVIEW_SCORE_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='AUDITOR' AND x.point_code='ACT__REVIEW_SCORE_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'FINANCE', 'ACT__AFTERSALE_REFUND_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='FINANCE' AND x.point_code='ACT__AFTERSALE_REFUND_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'FINANCE', 'ACT__DASHBOARD_OVERVIEW_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='FINANCE' AND x.point_code='ACT__DASHBOARD_OVERVIEW_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'FINANCE', 'ACT__FINANCE_INVOICE_VERIFY', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='FINANCE' AND x.point_code='ACT__FINANCE_INVOICE_VERIFY' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'FINANCE', 'ACT__FINANCE_PAYOUT_EXECUTE', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='FINANCE' AND x.point_code='ACT__FINANCE_PAYOUT_EXECUTE' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'FINANCE', 'ACT__FINANCE_RATE_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='FINANCE' AND x.point_code='ACT__FINANCE_RATE_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'FINANCE', 'ACT__FINANCE_RECON_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='FINANCE' AND x.point_code='ACT__FINANCE_RECON_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'FINANCE', 'ACT__FINANCE_RECON_RESOLVE', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='FINANCE' AND x.point_code='ACT__FINANCE_RECON_RESOLVE' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'FINANCE', 'ACT__MERCHANT_ADMISSION_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='FINANCE' AND x.point_code='ACT__MERCHANT_ADMISSION_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'FINANCE', 'ACT__MERCHANT_ADMISSION_UPDATE', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='FINANCE' AND x.point_code='ACT__MERCHANT_ADMISSION_UPDATE' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'RISK', 'ACT__AFTERSALE_REFUND_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='RISK' AND x.point_code='ACT__AFTERSALE_REFUND_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'RISK', 'ACT__DASHBOARD_OVERVIEW_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='RISK' AND x.point_code='ACT__DASHBOARD_OVERVIEW_READ' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'TECH_OPS', 'ACT__SYSTEM_PARAM_UPDATE', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='TECH_OPS' AND x.point_code='ACT__SYSTEM_PARAM_UPDATE' AND x.end_code='OPS');
INSERT INTO sys_role_point (role_code, point_code, end_code, created_at, updated_at) SELECT 'TECH_OPS', 'ACT__SYSTEM_THEME_READ', 'OPS', NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role_point x WHERE x.role_code='TECH_OPS' AND x.point_code='ACT__SYSTEM_THEME_READ' AND x.end_code='OPS');
