// 会员与人档（P8 · O1–O7）。
import type { PageCopy } from "@/lib/use-copy";

const zh = {
  title: "会员与人档",
  tabMembers: "会员名单",
  tabPersons: "人档",
  tabReach: "触达健康度",
  tabCoupons: "券（敞口）",
  tabActivities: "活动（敞口）",

  searchTail: "手机号后四位",
  searchTailHint: "只接受四位。后四位会撞是有意的：先看到几个候选，再按商家、下单时间确认是哪一个",
  entityNo: "商家",
  allEntities: "全部商家",

  colMember: "会员",
  colEntity: "归属商家",
  colLevel: "分层",
  colOrders: "单数",
  colSpent: "累计",
  colReach: "消息",
  colJoined: "成为会员",
  reachOn: "可发",
  reachOff: "已关",
  lead: "线索",

  personTitle: "人档 {no}",
  personHint: "一份人档串起他在几家店的会员身份 —— 这正是人档存在的理由",
  noAccount: "还没注册账号",
  reveal: "查看完整手机号",
  revealReason: "查看理由（至少四个字，会写进审计）",
  revealDone: "完整号：{phone}",
  revealHint: "这是唯一能把后四位还原成真实号码的地方。谁在什么时候看了谁的号，都会留下记录",

  reachHint: "按跳过率倒序，同率再按退订率。跳过率高 = 在反复给同一批人发、被频次限制拦下；退订多 = 发的内容没人要。这一页只有计数，看不到商家的标签名与人群条件",
  lvTitle: "会员分层口径",
  lvHint: "全平台统一，商家只读。改了不会立刻重算：明天凌晨 3 点起生效；要马上看效果，去「定时任务」手动运行「会员分层重算」",
  lvSleep: "沉睡：超过几天没下单",
  lvLoyal: "熟客：近 90 天至少几单",
  lvRegular: "常客：近 90 天至少几单",
  lvSummary: "沉睡 = 超过 {s} 天没下单 · 熟客 ≥ {l} 单 · 常客 ≥ {r} 单（近 90 天）",
  lvLastRun: "上次重算 {t} · 变更 {n} 人，其中新变沉睡 {z} 人 · 用时 {ms} ms",
  lvNeverRun: "重算任务还没跑过 —— 会员分层目前只在下单时更新",
  lvEdit: "修改口径",
  lvSave: "保存",
  lvCancel: "取消",
  lvSaved: "已保存，明天凌晨起按新口径重算",
  lvInvalid: "口径不自洽：沉睡 7–365 天，常客门槛须低于熟客门槛",
  memberReadOnlyWhat: "会员活动停用",
  memberReadOnlyNote: "只能查看，不能停用进行中的会员活动",
  emptyMembers: "先输入手机号后四位才会有结果。平台不提供全量会员名单 —— 会员归属在各商家自己的体系里，这一页只做「按手机号反查具体某个人」。",
  emptyMemberships: "这个人名下没有任何会员卡。会员卡由商家在自己的门店发放，平台不代发，所以这里为空是正常的。",
  emptyReach: "还没有主体开通会员能力。开通入口在商家侧，平台这一页只做查看与停用。",
  emptyCoupons: "还没有任何会员券。券由商家在自己的会员体系里配置，这里只列已配置出来的。",
  emptyActivities: "还没有任何会员活动。活动由商家在自己的会员体系里发起，这里只列已发起的。",
  colSent: "近 30 天发送",
  colMembers: "会员数",
  colTagCount: "标签数",
  colSegmentCount: "人群数",
  colTasks: "触达次数",
  colSkipRate: "跳过率",
  colOptOut: "已退订",
  colOptOutRate: "退订率",

  couponHint: "这一页看的是敞口，不是券本身：谁家的券没设预算、不限量、单张优惠过大",
  colTitle: "券名",
  colIssued: "已领 / 发行",
  colBudget: "预算",
  colExposure: "最大敞口",
  colFlags: "风险",
  unlimited: "不限",
  none: "未设",

  activityHint: "长期又不限量的活动没有停下来的那一天 —— 这一列就是为了让它跑不掉",
  colActivity: "活动",
  colSchedule: "排期",
  colQuota: "限量",
  colAudience: "受众",
  audienceAll: "所有人",
  audienceN: "{n} 条",
  stop: "强制停止",
  stopReason: "停止原因（商家看得见）",
  stopDone: "已停止",

    // 风险标记平铺成 flag_* —— useCopy 的口径是扁平 Record<string,string>，
    // 嵌套一层会让整份文案的类型对不上（而报错指向的是 useCopy 那一行，看不出根因）
  flag_NO_BUDGET: "没设预算",
  flag_UNLIMITED: "不限量",
  flag_HIGH_VALUE: "单张优惠大",
  flag_NEARLY_OUT: "快发完",
  flag_ALWAYS_ON_UNCAPPED: "长期且无上限",
  flag_QUOTA_NEARLY_OUT: "限量快用完",
  flag_ENDED_BY_QUOTA: "已到量结束",
};

const en: typeof zh = {
  title: "Members & persons",
  tabMembers: "Members",
  tabPersons: "Person",
  tabReach: "Messaging health",
  tabCoupons: "Coupons (exposure)",
  tabActivities: "Activities (exposure)",

  searchTail: "Last 4 digits",
  searchTailHint: "Exactly four. Collisions are intentional: you see candidates and confirm by store or order time",
  entityNo: "Merchant",
  allEntities: "All merchants",

  colMember: "Member",
  colEntity: "Merchant",
  colLevel: "Tier",
  colOrders: "Orders",
  colSpent: "Spent",
  colReach: "Messages",
  colJoined: "Member since",
  reachOn: "On",
  reachOff: "Off",
  lead: "Lead",

  personTitle: "Person {no}",
  personHint: "One person record ties together their memberships across stores",
  noAccount: "Not registered yet",
  reveal: "Reveal full phone",
  revealReason: "Reason (at least four characters, written to the audit log)",
  revealDone: "Full number: {phone}",
  revealHint: "This is the only place that turns the last four digits back into a real number. Every view is recorded",

  reachHint: "Sorted by skip rate, then opt-out rate. High skip rate = sending to the same people again and again, blocked by frequency limits; many opt-outs = nobody wants the content. Counts only — merchants' tag names and segment rules are not shown",
  lvTitle: "Member tier rules",
  lvHint: "Platform-wide; merchants can only view. Saving does not recalculate immediately: takes effect from 03:00 tomorrow. To see it now, run \"Member tier recalculation\" under Scheduled jobs",
  lvSleep: "Dormant: days without an order",
  lvLoyal: "Loyal: min orders in 90 days",
  lvRegular: "Regular: min orders in 90 days",
  lvSummary: "Dormant = no order for over {s} days · Loyal ≥ {l} · Regular ≥ {r} orders (last 90 days)",
  lvLastRun: "Last run {t} · {n} changed, {z} newly dormant · {ms} ms",
  lvNeverRun: "Recalculation has never run — tiers only update when an order is paid",
  lvEdit: "Edit rules",
  lvSave: "Save",
  lvCancel: "Cancel",
  lvSaved: "Saved. New rules apply from tonight's recalculation",
  lvInvalid: "Inconsistent rules: dormant 7–365 days, regular threshold must be below loyal",
  memberReadOnlyWhat: "stopping membership campaigns",
  memberReadOnlyNote: "view only — running campaigns cannot be stopped",
  emptyMembers: "Type the last four digits of a phone number to get results. The platform does not keep a full member roster — memberships live in each merchant's own system, and this page only looks one person up by phone.",
  emptyMemberships: "This person holds no membership cards. Cards are issued by merchants in their own stores — the platform never issues them, so an empty list here is normal.",
  emptyReach: "No entity has enabled membership yet. Merchants turn it on from their own side; this page only views and suspends.",
  emptyCoupons: "No membership coupons yet. Merchants configure them in their own membership setup; this page only lists what they configured.",
  emptyActivities: "No membership campaigns yet. Merchants start them from their own membership setup; this page only lists what they started.",
  colSent: "Sent (30d)",
  colMembers: "Members",
  colTagCount: "Tags",
  colSegmentCount: "Segments",
  colTasks: "Sends",
  colSkipRate: "Skip rate",
  colOptOut: "Opted out",
  colOptOutRate: "Opt-out rate",

  couponHint: "This page is about exposure, not coupons: who has no budget, no cap, or an unusually large discount",
  colTitle: "Coupon",
  colIssued: "Claimed / issued",
  colBudget: "Budget",
  colExposure: "Max exposure",
  colFlags: "Risk",
  unlimited: "No limit",
  none: "None",

  activityHint: "An always-on activity with no cap never stops — this column exists to catch it",
  colActivity: "Activity",
  colSchedule: "Schedule",
  colQuota: "Quota",
  colAudience: "Audience",
  audienceAll: "Everyone",
  audienceN: "{n} rules",
  stop: "Force stop",
  stopReason: "Reason (visible to the merchant)",
  stopDone: "Stopped",

  flag_NO_BUDGET: "No budget",
  flag_UNLIMITED: "Unlimited",
  flag_HIGH_VALUE: "Large discount",
  flag_NEARLY_OUT: "Nearly out",
  flag_ALWAYS_ON_UNCAPPED: "Always-on, uncapped",
  flag_QUOTA_NEARLY_OUT: "Quota nearly used",
  flag_ENDED_BY_QUOTA: "Ended on quota",
};

export const MEMBERS_COPY: PageCopy<typeof zh> = { zh, en };

/** 拆出去的组件靠它接文案（与 marketing/copy.ts 同一写法） */
export type MembersCopy = typeof zh;
