// 结算与资金文案（矩阵 P-12.1 / P-12.2）。
import type { PageCopy } from "@/lib/use-copy";

const zh = {
  tabSettlements: "结算单",
  tabSplits: "分账明细",
  tabRefundBack: "退款回退",
  tabRates: "费率配置",
  tabWithdraw: "提现审批",
  tabInvoice: "发票与个税",

  withdrawNotice: "这是运营端唯一会把钱打出去的动作。通过后落「已通过」而不是「已打款」—— 打款结果来自渠道回执，界面上不提供「标记已打款」，那样等于允许在钱没到账时把单子做平。超过 {n} 元必须写复核说明。",
  searchWithdraw: "搜提现单号 / 商家",
  filterWdStatus: "按提现状态筛选",
  filterWdStatusAll: "全部提现状态",
  wdPending: "待审批",
  wdApproved: "已通过待打款",
  wdRejected: "已驳回",
  wdPaid: "已打款",
  wdFailed: "打款失败",
  colWithdrawNo: "提现单号",
  colWdAmount: "申请金额",
  colAvailable: "可提余额",
  colBankAccount: "收款账户",
  colWdStatus: "状态",
  colAppliedAt: "申请时间",
  colDecidedAt: "审批时间",
  actionApprove: "审批",
  emptyWithdraw: "没有符合条件的提现申请。商家在 B 端发起提现后会出现在这里。",
  withdrawTitle: "提现 {no}",
  secWdOverview: "提现概况",
  secPrecheck: "打款前置条件",
  checkAccount: "已报备分账接收方",
  checkAccountBad: "未报备分账接收方 —— 批了钱也打不出去",
  checkNotBanned: "商家经营正常",
  checkNotBannedBad: "商家处于封禁中 —— 请先走解封流程",
  checkBalance: "金额未超可提余额",
  checkBalanceBad: "申请金额超过可提余额",
  checkMin: "金额达到单笔下限",
  checkMinBad: "低于单笔下限 {n} 元 —— 手续费比本金还贵",
  precheckHint: "余额取的是申请那一刻的快照，不是实时值 —— 审批看的是「他申请时能提多少」。",
  secWdRemark: "说明",
  fieldReviewNote: "复核说明",
  fieldRejectReason: "驳回原因",
  reviewNotePlaceholder: "例：已与商家电话核对账户，录音存档 #2026-0804",
  rejectReasonPlaceholder: "例：账户户名与主体不一致，请更正后重新申请",
  reviewNoteHint: "金额超过 {n} 元，通过前必须写复核说明。",
  rejectReasonHint: "驳回原因会原样出现在商家 B 端，不写等于让人猜。",
  lastRemark: "上次说明：{text}",
  btnApprove: "通过",
  btnReject: "驳回",
  toastWdApproved: "已通过，等渠道打款回执",
  toastWdRejected: "已驳回，原因已回商家",
  withdrawReadOnlyWhat: "提现审批",

  invoiceNotice: "开票与个税同页：它们是同一个问题的两半 —— 开票是对外的凭证，代扣是对内的扣除。开票金额不能超过该周期已结算金额，超出部分没有真实交易对应。",
  searchInvoice: "搜开票单号 / 商家 / 抬头",
  filterIvStatus: "按开票状态筛选",
  filterIvStatusAll: "全部开票状态",
  ivPending: "待开票",
  ivIssued: "已开票",
  ivRejected: "已驳回",
  colInvoiceNo: "开票单号",
  actionView: "查看",
  none: "—",
  colTitleType: "抬头类型",
  colTitle: "抬头",
  colTaxNo: "纳税人识别号",
  colIvAmount: "申请金额",
  colSettled: "该周期已结算",
  colIvStatus: "状态",
  titleCompany: "企业",
  titlePersonal: "个人",
  actionIssue: "开票",
  emptyInvoice: "没有符合条件的开票申请。商家在 B 端申请开票后会出现在这里。",
  invoiceTitle: "开票 {no}",
  secIvOverview: "申请概况",
  warnOverSettled: "申请金额超过该周期已结算金额，超出部分没有真实交易对应，不能开。",
  warnMissingTaxNo: "企业抬头缺纳税人识别号，请让商家补填后再开。",
  secIssue: "开票处理",
  fieldSerialNo: "发票流水号",
  serialPlaceholder: "例：FP20260801001",
  serialHint: "开票后写回这里，商家在 B 端凭它查票。没有流水号的「已开票」查不到票。",
  ivRejectPlaceholder: "例：开票金额超过已结算金额，请按实际金额重新申请",
  secIssued: "已开票",
  secIvRemark: "处理说明",
  btnIssueInvoice: "确认开票",
  btnRejectInvoice: "驳回",
  toastIvIssued: "已开票，流水号已回商家",
  toastIvRejected: "已驳回开票申请",
  taxTitle: "个税代扣规则",
  taxNotice: "只对个人主体商家生效：个体户与企业自行申报，平台不代扣。起征点以下不扣 —— 不设起征点会给每一笔几块钱的提现都产生一条扣税记录。",
  fieldThreshold: "起征点（元）",
  thresholdHint: "单期收入低于它不代扣。",
  fieldTaxRate: "代扣税率（%）",
  taxRateHint: "上限 {n}%，超过一定是配置错误。",
  toastTaxSaved: "个税规则已保存",
  taxReadOnlyWhat: "个税代扣规则",

  trafficMerchantOwned: "商家自带",
  trafficPlatform: "平台流量",
  trafficInvite: "邀请",
  trafficChannel: "渠道",

  /** `{no}` 是结算单号 */
  toastSplitDone: "{no} 分账完成",
  toastFrozenBack: "已解冻回平台",
  toastRefundBack: "已回退分账，售后单标记已清除",
  toastRateSaved: "费率配置已保存",

  colSettleNo: "结算单号",
  colMerchant: "商家",
  colPeriod: "周期",
  colOrderCount: "子订单数",
  colGross: "应结",
  colPlatformFee: "平台佣金",
  colServiceFee: "履约服务费",
  colNet: "实付商家",
  colRetry: "重试",
  /** `{n}` 是重试次数 */
  retryMaxed: "{n}（已达上限）",
  colStatus: "状态",
  colActions: "操作",
  settleClosed: "已结束",

  /** `{no}` 是结算单号 */
  confirmSplitTitle: "下发分账指令 {no}",
  /** `{name}` 商家名，`{amount}` 金额 */
  confirmSplitDesc: "将向 {name} 分账 {amount}。这是动钱的操作，确认前请核对应结与佣金。",
  confirmSplitOk: "下发分账",
  btnRetrySplit: "重试分账",
  btnSplit: "下发分账",
  btnFreezeBack: "解冻回平台",

  colSplitNo: "分账单号",
  colOrder: "子订单",
  colTraffic: "流量来源",
  colFeeRate: "适用费率",
  colGrossAmount: "成交额",
  colPickup: "自提点",

  colAsNo: "售后单号",
  colOrderNo: "订单号",
  colRefundAmount: "退款金额",
  colShare: "赔付比例",
  /** `{p}` 平台、`{m}` 商家、`{k}` 自提点 */
  shareText: "平台 {p}% · 商家 {m}% · 自提点 {k}%",
  shareUndecided: "未判定",
  colVerdict: "裁决说明",
  /** `{no}` 是售后单号 */
  confirmBackTitle: "回退分账 {no}",
  /** `{amount}` 是金额 */
  confirmBackDesc: "按裁决比例把 {amount} 从各方账户回退。执行后该售后单的待回退标记会被清除。",
  confirmBackOk: "执行回退",
  btnExecuteBack: "执行回退",

  readOnlyWhat: "分账执行与回退",
  readOnlyNote: "不能下发分账、解冻或回退",
  kpiPending: "待分账金额",
  kpiPendingSub: "尚未打给商家的钱",
  kpiPageCount: "本页结算单",
  kpiMaxed: "已达重试上限",
  kpiMaxedSub: "需人工介入",
  settleNotice:
    "分账前置：商家必须已报备分账接收方（ADR-002）。未报备的单点下发会被服务端拒绝 —— 这不是前端拦一下，是钱真的分不出去。",
  searchSettle: "搜索结算单号 / 商家 / 周期",
  searchSplit: "搜索分账单号 / 子订单 / 商家",
  filterStatus: "按状态筛选",
  filterStatusAll: "全部状态",
  emptySettle: "没有符合条件的结算单。结算单按商家 × 周期生成，本周期还没有成交就是空的。",
  emptySplit: "还没有分账明细。它按子订单生成，一个订单一条。",
  refundBackNotice:
    "这里的每一条都来自售后裁决（P-6.1）打的待回退标记 —— 队列由售后单派生，不另建实体：另建就有两份真相，且一定会不同步。执行后标记清除，队列自然消掉。",
  emptyRefundBack: "没有待回退的分账。售后裁决完成后，需要回退的单会自动出现在这里。",

  frNotice:
    "费率**只增不改**：调价是插一个新版本，旧版本永久保留 —— 这样才答得出「上个月那批单当时按什么费率算的」。费率以下单时快照为准，调整不影响已生成的结算单。",
  frEffectiveTitle: "此刻生效的费率",
  frEffectiveHint: "四格 = 经营模式 × 流量来源。两者正交：自营的这个数是进销差价（毛利），第三方的是服务收入（佣金），算法一样、记账口径不同。",
  frAddTitle: "新增费率版本",
  frFieldRate: "费率（万分比）",
  frFieldFrom: "生效时刻",
  frFromHint: "留空 = 立即生效；填未来时刻 = 预约生效。",
  frFieldRemark: "调整原因",
  frRemarkHint: "回查时这句话比数字更有用。",
  frAdd: "新增版本",
  frAdding: "提交中…",
  frToastAdded: "已新增费率版本",
  frHistoryTitle: "全部版本（{n}）",
  frColMode: "经营模式",
  frColSource: "流量来源",
  frColRate: "费率",
  frColEffectiveFrom: "生效时刻",
  frColState: "状态",
  frColRemark: "调整原因",
  frModeSelfOperated: "自营",
  frModeThirdParty: "第三方",
  frInitial: "初始版本",
  frScheduled: "待生效",
  frActive: "生效中",
  frDisabled: "已停用",
  rateTitle: "费率配置",
  rateReadOnlyWhat: "费率配置",
  rateReadOnlyNote: "不能调整佣金费率与兜底天数",
  rateNotice:
    "R15（履约服务费口径）与 R16（分档费率）尚未拍板 —— 这里的默认值是「起点」不是结论。自带客流建议 0：商家自己把客人带来的单还抽佣，商家就会把客人带去别处成交。",
  rateTierTitle: "按流量来源分档（平台佣金）",
  /** `{label}` 是流量来源名 */
  rateFieldBp: "{label}（万分比）",
  fieldPickupRate: "自提点履约服务费默认费率（万分比）",
  /** `{pct}` 是换算后的百分比 */
  pickupRateHint: "= {pct}；自提点自己配了费率就用它自己的（社区与网点页可改）。",
  fieldFreezeDays: "超时兜底天数",
  /** `{n}` 是最小天数 */
  freezeHint: "冻结超过该天数仍未分账成功，解冻回平台。至少 {n} 天 —— 太短会把还在正常重试的单提前收走。",
};

const en: typeof zh = {
  tabSettlements: "Settlements",
  tabSplits: "Split details",
  tabRefundBack: "Refund reversal",
  tabRates: "Rates",
  tabWithdraw: "Withdrawal approval",
  tabInvoice: "Invoices & withholding",

  withdrawNotice: "This is the only action in the console that sends money out. Approving marks it “approved, awaiting payout”, never “paid” — the payout result comes from the channel receipt, and there is no “mark as paid” button, because that would let a case be closed while the money has not landed. Above ¥{n} a review note is required.",
  searchWithdraw: "Search withdrawal no. / merchant",
  filterWdStatus: "Filter by withdrawal state",
  filterWdStatusAll: "All withdrawal states",
  wdPending: "Awaiting approval",
  wdApproved: "Approved, awaiting payout",
  wdRejected: "Rejected",
  wdPaid: "Paid",
  wdFailed: "Payout failed",
  colWithdrawNo: "Withdrawal no.",
  colWdAmount: "Requested",
  colAvailable: "Available",
  colBankAccount: "Payout account",
  colWdStatus: "State",
  colAppliedAt: "Requested at",
  colDecidedAt: "Decided at",
  actionApprove: "Review",
  emptyWithdraw: "No withdrawal requests match. Requests raised by merchants in the B-end app land here.",
  withdrawTitle: "Withdrawal {no}",
  secWdOverview: "Request overview",
  secPrecheck: "Payout preconditions",
  checkAccount: "Payout account registered",
  checkAccountBad: "No payout account registered — approving sends money nowhere",
  checkNotBanned: "Merchant trading normally",
  checkNotBannedBad: "Merchant is banned — lift the ban first",
  checkBalance: "Within available balance",
  checkBalanceBad: "Request exceeds the available balance",
  checkMin: "Meets the per-request minimum",
  checkMinBad: "Below the ¥{n} minimum — the channel fee costs more than the amount",
  precheckHint: "The balance is the snapshot taken when the request was raised, not a live figure — approval judges what they could withdraw at that moment.",
  secWdRemark: "Note",
  fieldReviewNote: "Review note",
  fieldRejectReason: "Rejection reason",
  reviewNotePlaceholder: "e.g. Account confirmed with the merchant by phone, recording #2026-0804",
  rejectReasonPlaceholder: "e.g. Account holder does not match the registered entity; correct it and reapply",
  reviewNoteHint: "Above ¥{n}, a review note is required before approving.",
  rejectReasonHint: "The rejection reason reaches the merchant verbatim; leaving it blank makes them guess.",
  lastRemark: "Previous note: {text}",
  btnApprove: "Approve",
  btnReject: "Reject",
  toastWdApproved: "Approved — awaiting the channel payout receipt",
  toastWdRejected: "Rejected — the reason went back to the merchant",
  withdrawReadOnlyWhat: "withdrawal approval",

  invoiceNotice: "Invoices and withholding share a page: they are two halves of one question — the invoice is the outward document, withholding the inward deduction. An invoice cannot exceed what was settled for that period; anything beyond has no real transaction behind it.",
  searchInvoice: "Search invoice no. / merchant / title",
  filterIvStatus: "Filter by invoice state",
  filterIvStatusAll: "All invoice states",
  ivPending: "Awaiting issue",
  ivIssued: "Issued",
  ivRejected: "Rejected",
  colInvoiceNo: "Request no.",
  actionView: "View",
  none: "—",
  colTitleType: "Title type",
  colTitle: "Invoice title",
  colTaxNo: "Tax ID",
  colIvAmount: "Requested",
  colSettled: "Settled this period",
  colIvStatus: "State",
  titleCompany: "Company",
  titlePersonal: "Individual",
  actionIssue: "Issue",
  emptyInvoice: "No invoice requests match. Requests raised by merchants in the B-end app land here.",
  invoiceTitle: "Invoice request {no}",
  secIvOverview: "Request overview",
  warnOverSettled: "The requested amount exceeds what was settled this period; the excess has no real transaction behind it and cannot be invoiced.",
  warnMissingTaxNo: "A company title needs a tax ID — ask the merchant to supply it first.",
  secIssue: "Handle the request",
  fieldSerialNo: "Invoice serial no.",
  serialPlaceholder: "e.g. FP20260801001",
  serialHint: "Write it back here after issuing; the merchant looks the invoice up by it. An “issued” with no serial cannot be found.",
  ivRejectPlaceholder: "e.g. Amount exceeds what was settled; reapply for the actual figure",
  secIssued: "Issued",
  secIvRemark: "Handling note",
  btnIssueInvoice: "Issue invoice",
  btnRejectInvoice: "Reject",
  toastIvIssued: "Issued — the serial number went back to the merchant",
  toastIvRejected: "Invoice request rejected",
  taxTitle: "Withholding rules",
  taxNotice: "Applies to individual merchants only: sole traders and companies file for themselves. Nothing is withheld below the threshold — without one, every few-yuan withdrawal spawns a withholding entry.",
  fieldThreshold: "Threshold (¥)",
  thresholdHint: "Income below this in a period is not withheld against.",
  fieldTaxRate: "Withholding rate (%)",
  taxRateHint: "Capped at {n}% — anything higher is a configuration error.",
  toastTaxSaved: "Withholding rules saved",
  taxReadOnlyWhat: "withholding rules",

  trafficMerchantOwned: "Merchant-owned",
  trafficPlatform: "Platform traffic",
  trafficInvite: "Referral",
  trafficChannel: "Channel",

  toastSplitDone: "{no} paid out",
  toastFrozenBack: "Released back to the platform",
  toastRefundBack: "Split reversed; the after-sales flag is cleared",
  toastRateSaved: "Rate settings saved",

  colSettleNo: "Settlement no.",
  colMerchant: "Merchant",
  colPeriod: "Period",
  colOrderCount: "Sub-orders",
  colGross: "Gross due",
  colPlatformFee: "Platform commission",
  colServiceFee: "Fulfillment fee",
  colNet: "Net to merchant",
  colRetry: "Retries",
  retryMaxed: "{n} (limit reached)",
  colStatus: "Status",
  colActions: "Actions",
  settleClosed: "Closed",

  confirmSplitTitle: "Release payout {no}",
  confirmSplitDesc: "This pays {name} {amount}. Money actually moves — check the gross and commission before confirming.",
  confirmSplitOk: "Release payout",
  btnRetrySplit: "Retry payout",
  btnSplit: "Release payout",
  btnFreezeBack: "Release to platform",

  colSplitNo: "Split no.",
  colOrder: "Sub-order",
  colTraffic: "Traffic source",
  colFeeRate: "Rate applied",
  colGrossAmount: "Order value",
  colPickup: "Pickup point",

  colAsNo: "After-sales no.",
  colOrderNo: "Order no.",
  colRefundAmount: "Refund amount",
  colShare: "Liability split",
  shareText: "Platform {p}% · merchant {m}% · pickup point {k}%",
  shareUndecided: "Not decided",
  colVerdict: "Decision note",
  confirmBackTitle: "Reverse split {no}",
  confirmBackDesc: "Claws back {amount} from each party per the decided split. The after-sales reversal flag is cleared afterwards.",
  confirmBackOk: "Reverse",
  btnExecuteBack: "Reverse",

  readOnlyWhat: "payout execution & reversal",
  readOnlyNote: "cannot release payouts, release funds or reverse splits",
  kpiPending: "Awaiting payout",
  kpiPendingSub: "Money not yet sent to merchants",
  kpiPageCount: "Settlements on this page",
  kpiMaxed: "Retry limit reached",
  kpiMaxedSub: "Needs a human",
  settleNotice:
    "Prerequisite: the merchant must have registered a payout account (ADR-002). Releasing to an unregistered merchant is rejected by the server — this is not a front-end guard, the money genuinely cannot move.",
  searchSettle: "Search settlement no. / merchant / period",
  searchSplit: "Search split no. / sub-order / merchant",
  filterStatus: "Filter by status",
  filterStatusAll: "All statuses",
  emptySettle: "No settlements match these filters. Settlements are generated per merchant × period, so an untraded period is empty.",
  emptySplit: "No split details yet. They are generated per sub-order, one row each.",
  refundBackNotice:
    "Every row here comes from a reversal flag set by an after-sales decision (P-6.1) — the queue is derived from after-sales tickets rather than stored separately: a separate store would mean two sources of truth, guaranteed to drift. Executing clears the flag and the row disappears.",
  emptyRefundBack: "No splits awaiting reversal. Rows appear automatically once an after-sales decision requires one.",

  frNotice:
    "Rates are append-only: a change adds a new version and the old ones are kept forever — that is what makes \"which rate applied to last month's orders\" answerable. Rates are snapshotted at order time, so changes never affect settlements already generated.",
  frEffectiveTitle: "Rates in effect now",
  frEffectiveHint: "Four cells = business mode × traffic source. The two are orthogonal: under self-operated this number is a gross margin, under third-party it is commission — same arithmetic, different accounting.",
  frAddTitle: "Add a rate version",
  frFieldRate: "Rate (basis points)",
  frFieldFrom: "Effective from",
  frFromHint: "Leave empty for immediate effect; set a future time to schedule it.",
  frFieldRemark: "Reason for the change",
  frRemarkHint: "When looking back, this sentence is more useful than the number.",
  frAdd: "Add version",
  frAdding: "Submitting…",
  frToastAdded: "Rate version added",
  frHistoryTitle: "All versions ({n})",
  frColMode: "Business mode",
  frColSource: "Traffic source",
  frColRate: "Rate",
  frColEffectiveFrom: "Effective from",
  frColState: "State",
  frColRemark: "Reason",
  frModeSelfOperated: "Self-operated",
  frModeThirdParty: "Third-party",
  frInitial: "Initial",
  frScheduled: "Scheduled",
  frActive: "Active",
  frDisabled: "Disabled",
  rateTitle: "Rate settings",
  rateReadOnlyWhat: "rate settings",
  rateReadOnlyNote: "cannot change commission rates or the fallback window",
  rateNotice:
    "R15 (how the fulfillment fee is defined) and R16 (tiered rates) are not settled yet — these defaults are a starting point, not a conclusion. Zero is suggested for merchant-owned traffic: charge commission on customers the merchant brought in themselves and they will take those customers elsewhere.",
  rateTierTitle: "Tiered by traffic source (platform commission)",
  rateFieldBp: "{label} (basis points)",
  fieldPickupRate: "Default pickup-point fulfillment fee (basis points)",
  pickupRateHint: "= {pct}; a pickup point with its own rate uses that instead (editable on the Communities page).",
  fieldFreezeDays: "Fallback window (days)",
  freezeHint:
    "Funds frozen longer than this without a successful payout are released back to the platform. At least {n} days — any shorter and orders still retrying normally get pulled early.",
};

export const FINANCE_COPY: PageCopy<typeof zh> = { zh, en };

/** 拆出去的 tab 组件靠它接文案。 */
export type FinanceCopy = typeof zh;
