// 结算与资金文案（矩阵 P-12.1 / P-12.2）。
import type { PageCopy } from "@/lib/use-copy";

const zh = {
  ppTitle: "积分端开关",
  ppLoading: "加载中…",
  ppNotSecurityGate: "⚠️ 这不是合规硬闸。端标识来自客户端请求头、天然可伪造，而且今天还不是每个端都在发。它能做到的是「让自报家门的那个端不发/不用积分」，做不到的是「保证某个端一定拿不到积分」——要后者得在端侧和签名上做文章。另：这里存的是**禁用名单**，没勾中的端一律照常。",
  ppEarnDeny: "这些端不发放积分",
  ppEarnHint: "判定读的是**下单时的端快照**，不是当前请求 —— 发分发生在支付成功那一刻，那条路上常常根本没有用户在场（支付回调、超时自动确认）。改这里只影响将来，已经发出去的分不追回。",
  ppRedeemDeny: "这些端不能用积分抵扣",
  ppRedeemHint: "判定读的是**当前请求的端** —— 抵扣是用户当场发起的动作，与发放恰好相反。结算页会显示余额并说明原因，不会把入口静默藏掉。",
  ppOfflineRedeem: "当面付款可以用积分抵扣",
  ppOfflineHint: "默认开。积分成本本来就在商家（ADR-006），线下反而比线上简单：商家当面少收即是抵扣，平台零动作。关掉的话，所有当面付的单都拿不到抵扣额度。",
  ppOddPair: "{clients} 配成了「不发放但可核销」。这是合法组合（停止发分、但已有的分还能花掉），所以不拦你 —— 如果不是有意的，记得两边一起勾。",
  ppSave: "保存",
  ppSaving: "保存中…",
  ptHint: "恒等式：流通中的积分应当等于池子里的钱。两个数分开看的话，失衡要等到有人主动比对才会发现 —— 所以这一页把差额直接算出来。本页只读：池子的钱由流水推出，要调整就补一笔有类型的流水。",
  ptCirculating: "流通中的积分",
  ptPoolBalance: "池子余额",
  ptPeriodRedeem: "本期兑付",
  ptGapTitle: "差额（池子 − 流通）",
  ptBalanced: "已平",
  ptGapPoolMore: "池子多了：收了钱但没发出对应的分，查发放链路",
  ptGapPoolLess: "池子少了：发了分但没收到对应的钱，查发分服务费入账",
  ptByChannelTitle: "按通道分账本",
  ptByChannelHint: "账面是一个池子，钱实际分散在各通道账户 —— 只看总数的话，一个溢一个空时总数仍然是平的",
  ptColChannel: "通道",
  ptColMarket: "市场",
  ptColBalance: "余额",
  ptEmpty: "暂无通道账本",

  withdrawNotice: "这是运营端唯一会把钱打出去的动作。通过后落「已通过」而不是「已打款」—— 打款结果来自渠道回执，界面上不提供「标记已打款」，那样等于允许在钱没到账时把单子做平。超过 {n} 元必须写复核说明。",
  searchWithdraw: "搜提现单号 / 商家",
  filterWdStatus: "按提现状态筛选",
  filterWdStatusAll: "全部提现状态",
  wdPending: "待审批",
  wdApproved: "已通过待打款",
  wdRejected: "已驳回",
  wdPaid: "已打款",
  wdFailed: "打款失败",
  colWithdrawNo: "提现单号",
  colWdAmount: "申请金额",
  colAvailable: "可提余额",
  colBankAccount: "收款账户",
  colWdStatus: "状态",
  colAppliedAt: "申请时间",
  colDecidedAt: "审批时间",
  actionApprove: "审批",
  emptyWithdraw: "没有符合条件的提现申请。商家在 B 端发起提现后会出现在这里。",
  withdrawTitle: "提现 {no}",
  secWdOverview: "提现概况",
  secPrecheck: "打款前置条件",
  checkAccount: "已报备分账接收方",
  checkAccountBad: "未报备分账接收方 —— 批了钱也打不出去",
  checkNotBanned: "商家经营正常",
  checkNotBannedBad: "商家处于封禁中 —— 请先走解封流程",
  checkBalance: "金额未超可提余额",
  checkBalanceBad: "申请金额超过可提余额",
  checkMin: "金额达到单笔下限",
  checkMinBad: "低于单笔下限 {n} 元 —— 手续费比本金还贵",
  precheckHint: "余额取的是申请那一刻的快照，不是实时值 —— 审批看的是「他申请时能提多少」。",
  secWdRemark: "说明",
  fieldReviewNote: "复核说明",
  fieldRejectReason: "驳回原因",
  reviewNotePlaceholder: "例：已与商家电话核对账户，录音存档 #2026-0804",
  rejectReasonPlaceholder: "例：账户户名与主体不一致，请更正后重新申请",
  reviewNoteHint: "金额超过 {n} 元，通过前必须写复核说明。",
  rejectReasonHint: "驳回原因会原样出现在商家 B 端，不写等于让人猜。",
  lastRemark: "上次说明：{text}",
  btnApprove: "通过",
  btnReject: "驳回",
  toastWdApproved: "已通过，等渠道打款回执",
  toastWdRejected: "已驳回，原因已回商家",
  withdrawReadOnlyWhat: "提现审批",

  invoiceNotice: "开票与个税同页：它们是同一个问题的两半 —— 开票是对外的凭证，代扣是对内的扣除。开票金额不能超过该周期已结算金额，超出部分没有真实交易对应。",
  searchInvoice: "搜开票单号 / 商家 / 抬头",
  filterIvStatus: "按开票状态筛选",
  filterIvStatusAll: "全部开票状态",
  ivPending: "待开票",
  ivIssued: "已开票",
  ivRejected: "已驳回",
  colInvoiceNo: "开票单号",
  actionView: "查看",
  none: "—",
  colTitleType: "抬头类型",
  colTitle: "抬头",
  colTaxNo: "纳税人识别号",
  colIvAmount: "申请金额",
  colSettled: "该周期已结算",
  colIvStatus: "状态",
  titleCompany: "企业",
  titlePersonal: "个人",
  actionIssue: "开票",
  emptyInvoice: "没有符合条件的开票申请。商家在 B 端申请开票后会出现在这里。",
  invoiceTitle: "开票 {no}",
  secIvOverview: "申请概况",
  warnOverSettled: "申请金额超过该周期已结算金额，超出部分没有真实交易对应，不能开。",
  warnMissingTaxNo: "企业抬头缺纳税人识别号，请让商家补填后再开。",
  secIssue: "开票处理",
  fieldSerialNo: "发票流水号",
  serialPlaceholder: "例：FP20260801001",
  serialHint: "开票后写回这里，商家在 B 端凭它查票。没有流水号的「已开票」查不到票。",
  ivRejectPlaceholder: "例：开票金额超过已结算金额，请按实际金额重新申请",
  secIssued: "已开票",
  secIvRemark: "处理说明",
  btnIssueInvoice: "确认开票",
  btnRejectInvoice: "驳回",
  toastIvIssued: "已开票，流水号已回商家",
  toastIvRejected: "已驳回开票申请",
  taxTitle: "个税代扣规则",
  taxNotice: "只对个人主体商家生效：个体户与企业自行申报，平台不代扣。起征点以下不扣 —— 不设起征点会给每一笔几块钱的提现都产生一条扣税记录。",
  fieldThreshold: "起征点（元）",
  thresholdHint: "单期收入低于它不代扣。",
  fieldTaxRate: "代扣税率（%）",
  taxRateHint: "上限 {n}%，超过一定是配置错误。",
  toastTaxSaved: "个税规则已保存",
  // ── 平台开票抬头（P0-11）。后端一直有，运营端此前没有入口 ──
  itTitle: "平台开票抬头",
  itNotice: "供应商照着这份抬头给平台开票。**公司全称与税号缺一不可** —— 缺了票开不出来，而账已经挂在那里。五项留空时下面显示「未配置」，那不是加载失败。",
  itUnset: "未配置",
  itCompany: "公司全称",
  itTaxNo: "纳税人识别号",
  itAddress: "注册地址",
  itPhone: "注册电话",
  itBank: "开户行与账号",
  itSave: "保存抬头",
  toastItSaved: "开票抬头已保存",
  taxReadOnlyWhat: "个税代扣规则",

  trafficMerchantOwned: "商家自带",
  trafficPlatform: "平台流量",
  trafficInvite: "邀请",
  trafficChannel: "渠道",

  /** `{no}` 是结算单号 */
  toastSplitDone: "{no} 分账完成",
  toastFrozenBack: "已解冻回平台",
  toastRefundBack: "已回退分账，售后单标记已清除",
  toastRateSaved: "费率配置已保存",

  colSettleNo: "结算单号",
  colMerchant: "商家",
  colPeriod: "周期",
  colOrderCount: "子订单数",
  colGross: "应结",
  colPlatformFee: "平台佣金",
  colServiceFee: "履约服务费",
  colNet: "实付商家",
  colRetry: "重试",
  /** `{n}` 是重试次数 */
  retryMaxed: "{n}（已达上限）",
  colStatus: "状态",
  colActions: "操作",
  settleClosed: "已结束",

  /** `{no}` 是结算单号 */
  confirmSplitTitle: "下发分账指令 {no}",
  /** `{name}` 商家名，`{amount}` 金额 */
  confirmSplitDesc: "将向 {name} 分账 {amount}。这是动钱的操作，确认前请核对应结与佣金。",
  confirmSplitOk: "下发分账",
  btnRetrySplit: "重试分账",
  btnSplit: "下发分账",
  btnFreezeBack: "解冻回平台",

  colSplitNo: "分账单号",
  colOrder: "子订单",
  colTraffic: "流量来源",
  colFeeRate: "适用费率",
  colGrossAmount: "成交额",
  colPickup: "自提点",

  colAsNo: "售后单号",
  colOrderNo: "订单号",
  colRefundAmount: "退款金额",
  colShare: "赔付比例",
  /** `{p}` 平台、`{m}` 商家、`{k}` 自提点 */
  shareText: "平台 {p}% · 商家 {m}% · 自提点 {k}%",
  shareUndecided: "未判定",
  colVerdict: "裁决说明",
  /** `{no}` 是售后单号 */
  confirmBackTitle: "回退分账 {no}",
  /** `{amount}` 是金额 */
  confirmBackDesc: "按裁决比例把 {amount} 从各方账户回退。执行后该售后单的待回退标记会被清除。",
  confirmBackOk: "执行回退",
  btnExecuteBack: "执行回退",

  readOnlyWhat: "分账执行与回退",
  readOnlyNote: "不能下发分账、解冻或回退",
  kpiPending: "待分账金额",
  kpiPendingSub: "尚未打给商家的钱",
  kpiPageCount: "本页结算单",
  kpiMaxed: "已达重试上限",
  kpiMaxedSub: "需人工介入",
  settleNotice:
    "分账前置：商家必须已报备分账接收方（ADR-002）。未报备的单点下发会被服务端拒绝 —— 这不是前端拦一下，是钱真的分不出去。",
  searchSettle: "搜索结算单号 / 商家 / 周期",
  searchSplit: "搜索分账单号 / 子订单 / 商家",
  filterStatus: "按状态筛选",
  filterStatusAll: "全部状态",
  emptySettle: "没有符合条件的结算单。结算单按商家 × 周期生成，本周期还没有成交就是空的。",
  emptySplit: "还没有分账明细。它按子订单生成，一个订单一条。",
  refundBackNotice:
    "这里的每一条都来自售后裁决（P-6.1）打的待回退标记 —— 队列由售后单派生，不另建实体：另建就有两份真相，且一定会不同步。执行后标记清除，队列自然消掉。",
  emptyRefundBack: "没有待回退的分账。售后裁决完成后，需要回退的单会自动出现在这里。",

  frNotice:
    "费率**只增不改**：调价是插一个新版本，旧版本永久保留 —— 这样才答得出「上个月那批单当时按什么费率算的」。费率以下单时快照为准，调整不影响已生成的结算单。",
  frEffectiveTitle: "此刻生效的费率",
  frEffectiveHint: "四格 = 经营模式 × 流量来源。两者正交：自营的这个数是进销差价（毛利），第三方的是服务收入（佣金），算法一样、记账口径不同。",
  frAddTitle: "新增费率版本",
  frFieldRate: "费率（万分比）",
  frFieldFrom: "生效时刻",
  frFromHint: "留空 = 立即生效；填未来时刻 = 预约生效。",
  frFieldRemark: "调整原因",
  frRemarkHint: "回查时这句话比数字更有用。",
  frAdd: "新增版本",
  frAdding: "提交中…",
  frToastAdded: "已新增费率版本",
  frHistoryTitle: "全部版本（{n}）",
  frColMode: "经营模式",
  frColSource: "流量来源",
  frColRate: "费率",
  frColEffectiveFrom: "生效时刻",
  frColState: "状态",
  frColRemark: "调整原因",
  frModeSelfOperated: "自营",
  frModeThirdParty: "第三方",
  frInitial: "初始版本",
  frScheduled: "待生效",
  frActive: "生效中",
  frDisabled: "已停用",

  pcNotice:
    "通道费率与平台佣金是两笔钱：这里配的是**通道向我们收**的手续费，佣金在「分档费率与服务费」那一栏。同样只增不改 —— 结算时按下单时刻的版本算，调整不影响已生成的账。",
  pcTitle: "支付通道",
  pcColChannel: "通道",
  pcColState: "状态",
  pcColMarkets: "可用市场",
  pcColCurrency: "币种",
  pcColSettleCycle: "结算周期",
  pcColRate: "当前费率",
  pcNoRate: "未配置",
  pcNoRateHint: "没有配过费率，结算时取不到版本 —— 不是 0%。",
  pcEnabled: "启用中",
  pcDisabled: "已停用",
  /* 动作词与状态词分开：按钮上写「要做的事」，状态列写「现在是什么」 */
  pcActionEnable: "启用",
  pcActionDisable: "停用",
  pcAllMarkets: "全部市场",
  pcEmpty: "还没有配置支付通道。没有通道，商家进不了件，也收不了钱。",

  // ── 账期批次
  sbNotice: "批次管「能不能放」，单据管「放得成不成」。这一页回答的是钱卡在哪一批 —— 单笔明细在「结算单与分账」那一栏。",
  sbReadOnlyWhat: "放行与挂起",
  sbReadOnlyNote: "没有这个权限只能看，处置要财务或风控来做。",
  sbColBatch: "批次号",
  sbColEntity: "主体",
  sbColChannel: "通道",
  sbColCycle: "账期",
  sbColStatus: "状态",
  sbColBills: "笔数",
  sbColNet: "应放款",
  sbColDue: "应结日",
  sbColScope: "对账覆盖",
  sbColDecided: "处置人",
  sbStatusAll: "全部状态",
  sbStatusDRAFT: "收单中",
  sbStatusCOLLECTED: "已截批",
  sbStatusRECONCILING: "对账中",
  sbStatusBLOCKED: "已挂起",
  sbStatusRECONCILED: "待放款",
  sbStatusRELEASED: "已放款",
  /* 今天只有 A 侧。显示成「已对账」是一句自证的话 —— 没有对方账单时我们只验了自己 */
  sbScopeSelfOnly: "仅我方自查",
  sbScopeBoth: "含渠道账单",
  sbTimeoutReleased: "超时自动放行",
  sbEmpty: "还没有账期批次。可结算的单会自动成批。",
  sbBlockedTitle: "待处置的挂起批次",
  sbUnitBill: "笔",
  sbExpireHint: "超时未处置将自动放行：",
  sbRemarkLabel: "处置原因（必填）",
  sbRemarkPh: "写清凭什么放行或继续挂起 —— 事后要能回答这个问题",
  sbRelease: "放行",
  sbHold: "继续挂起",
  sbToastDecided: "已处置",

  // ── 商家欠款
  dbNotice: "欠款与保证金方向相反：保证金是商家的钱（将来要退还），欠款是商家欠平台的。货款抵扣是自动的，这一页只做保证金抵扣。",
  dbReadOnlyWhat: "保证金抵扣",
  dbReadOnlyNote: "没有这个权限只能看。动商家本金要财务来做。",
  dbEntityLabel: "主体号",
  dbEntityPh: "输入主体号，如 M0001",
  dbPickFirst: "先输入主体号 —— 欠款是按商家看的，没有主体号无从查起。",
  dbBalance: "当前欠款",
  dbNoDebt: "这家没有欠款。绝大多数商家从没欠过，这是常态。",
  dbColType: "类型",
  dbColAmount: "变动",
  dbColAfter: "变动后",
  dbColSource: "源头 / 批次",
  dbColReason: "说明",
  dbColAt: "时间",
  dbTypeINCUR: "产生",
  dbTypeOFFSET: "货款抵扣",
  dbTypeDEPOSIT: "保证金抵扣",
  dbTypeWRITE_OFF: "核销",
  dbEmptyTxns: "没有欠款流水。",
  dbOffsetTitle: "用保证金抵扣",
  dbOffsetWhy: "这一步是人工的，不自动 —— 动的是商家的本金，而未经同意扣款的合规边界还没定（法务待确认）。自动的那条链路上一分钱都不动本金。",
  dbOffsetAmount: "抵扣金额（元）",
  dbOffsetAmountPh: "如 100",
  dbOffsetReason: "原因（必填）",
  dbOffsetReasonPh: "写清为什么动保证金 —— 商家会问",
  dbOffsetCapHint: "实际抵扣两头封顶：不超过欠款余额，也不超过保证金可用额（冻结中的部分正被别的争议占着）。",
  dbOffsetSubmit: "确认抵扣",
  dbToastOffset: "已用保证金抵扣",
  pcDisableHint: "停用只影响**新进件与新下单**，已开通的商户与在途的单不受影响。",
  pcSubsidyYes: "支持补差",
  pcSubsidyNo: "不支持补差（该通道不开积分抵扣）",
  pcAddRateTitle: "新增通道费率版本",
  pcFieldChannel: "通道",
  pcFieldPayMethod: "支付方式",
  pcFieldLegalForm: "主体形态",
  pcAnyHint: "留空 = 该通道全部（存为 *）。填了就是这一格的专属费率，取值时精确优先于通配。",
  pcFieldMinFee: "单笔最低手续费（分）",
  pcToastAdded: "已新增通道费率版本",
  pcToastUpdated: "已保存通道设置",
  pcHistoryTitle: "{ch} 的全部版本（{n}）",
  colMode: "经营模式",
  colPayMerchant: "收款号",
  colAction: "指令",
  colResult: "结果",
  colMessage: "失败原因",
  modeSelfOperated: "自营",
  modeThirdParty: "第三方",
  noPayAccount: "未进件",
  resultOk: "成功",
  resultFail: "失败",
  rateTitle: "费率配置",
  rateReadOnlyWhat: "费率配置",
  rateReadOnlyNote: "不能调整佣金费率与兜底天数",
  rateNotice:
    "R15（履约服务费口径）与 R16（分档费率）尚未拍板 —— 这里的默认值是「起点」不是结论。自带客流建议 0：商家自己把客人带来的单还抽佣，商家就会把客人带去别处成交。",
  rateTierTitle: "按流量来源分档（平台佣金）",
  /** `{label}` 是流量来源名 */
  rateFieldBp: "{label}（万分比）",
  fieldPickupRate: "自提点履约服务费默认费率（万分比）",
  /** `{pct}` 是换算后的百分比 */
  pickupRateHint: "= {pct}；自提点自己配了费率就用它自己的（社区与网点页可改）。",
  fieldFreezeDays: "超时兜底天数",
  /** `{n}` 是最小天数 */
  freezeHint: "冻结超过该天数仍未分账成功，解冻回平台。至少 {n} 天 —— 太短会把还在正常重试的单提前收走。",

  // ── 自营应付账款 ──
  pyTitle: "自营应付账款",
  pyNotice: "自营供应商的货款走这条路：待对账 → 确认对账 → 收票（或标无票）→ 登记付款。⚠️ **票到付款**：没有核验过的进项票、也没标过无票供应商的，付不了 —— 那样付出去的钱是不能列支的。",
  pySummary: "待付 {n} 笔 · {amount}",
  pyEmpty: "没有自营应付单",
  pyColBill: "结算单",
  pyColNet: "应付",
  pyColStatus: "状态",
  pyColInvoice: "进项票",
  pyColRef: "付款流水号",
  pyConfirm: "确认对账",
  pyNoInvoice: "标为无票供应商",
  // 这条是**发给后端的 reason**，不是界面文案。
  // ⚠️ 后端 `markNoInvoice` 只校验它非空，**并不存**（见 SettleServiceImpl）——
  // 而那段代码的注释写着「无票是要付出税务代价的，得说得出为什么」。
  // 也就是说这个「理由」两边合起来是走过场：前端塞一句写死的话，
  // 去满足一个会把它扔掉的校验。等后端真的存了，这里要换成运营手填。
  pyNoInvoiceReason: "无票供应商",
  pyPay: "登记付款",
  pyConfirmPay: "确认",
  pyRefPlaceholder: "网银流水号",
  payNeedConfirm: "先确认对账",
  payNeedInvoice: "票还没到",
  payAlreadyPaid: "已付款",
  payableStatus_PENDING_RECON: "待对账",
  payableStatus_CONFIRMED: "待付款",
  payableStatus_PAID: "已付款",
  invoiceStatus_PENDING_INVOICE: "待收票",
  invoiceStatus_SUBMITTED: "已提交",
  invoiceStatus_VERIFIED: "已核验",
  invoiceStatus_REJECTED: "已驳回",
  invoiceStatus_NO_INVOICE: "无票供应商",

  // ── 进项票 ──
  piTitle: "进项票",
  piNotice: "供应商开给平台的票，它决定**平台能不能付款**。抬头与主体名对不上的不能核验 —— 那种票入不了账，硬核验过去只会把问题推到报税那天。",
  piSummary: "待核验 {n} 张",
  piEmpty: "没有待处理的进项票",
  piColInvoice: "发票",
  piColTitle: "抬头",
  piColAmount: "金额",
  piColSettle: "覆盖结算单",
  piColStatus: "状态",
  piVerify: "核验通过",
  piReject: "驳回",
  piCannotVerify: "抬头不符，不能核验",
  piTitleMismatch: "抬头与主体名不一致",
  piRejectPlaceholder: "驳回原因（原样回商家）",
  purchaseInvoiceStatus_PENDING: "待提交",
  purchaseInvoiceStatus_SUBMITTED: "待核验",
  purchaseInvoiceStatus_VERIFIED: "已核验",
  purchaseInvoiceStatus_REJECTED: "已驳回",

  // ── 买家开票申请 ──
  brTitle: "买家开票申请",
  brNotice: "买家为自己的订单要的发票，决定他能不能报销。⚠️ 与「进项票」「商家开票申请」是三张不同的票：这一页按**订单**走，另两页按主体与账期走。",
  brSummary: "待处理 {n} 条",
  brEmpty: "没有待处理的开票申请",
  brColOrder: "订单",
  brColTitle: "抬头",
  brColAmount: "金额",
  brColStatus: "状态",
  brMarkIssued: "标记已开",
  brReject: "驳回",
  brNoTaxNo: "缺税号",
  brInvoiceNoPlaceholder: "发票号码",
  brRejectPlaceholder: "驳回原因（原样回买家）",
  titleType_PERSONAL: "个人",
  titleType_COMPANY: "单位",
  buyerInvoiceStatus_PENDING: "待开票",
  buyerInvoiceStatus_ISSUED: "已开票",
  buyerInvoiceStatus_REJECTED: "已驳回",

  all: "全部",
  confirm: "确认",
  cancel: "取消",

};

const en: typeof zh = {
  ppTitle: "Points client policy",
  ppLoading: "Loading…",
  ppNotSecurityGate: "⚠️ This is not a security gate. The client identifier comes from a request header and can be forged, and not every client sends it yet. It can stop a client that identifies itself; it cannot guarantee a given client never earns points — that needs client-side work and signing. Note this stores a deny list: clients not selected are unaffected.",
  ppEarnDeny: "These clients do not earn points",
  ppEarnHint: "Judged against the client recorded on the order, not the current request — points are granted at payment, and there is often no user present at all (payment callback, auto-confirm). Changes affect future grants only; points already granted are never clawed back.",
  ppRedeemDeny: "These clients cannot redeem points",
  ppRedeemHint: "Judged against the current request's client — redeeming is something the user does right now, the opposite of earning. Checkout still shows the balance and the reason; the entry point is never silently hidden.",
  ppOfflineRedeem: "Points can be redeemed when paying on site",
  ppOfflineHint: "On by default. The cost of points sits with the merchant (ADR-006), so paying on site is simpler than online: the merchant just collects less. Turning this off removes redemption from every on-site order.",
  ppOddPair: "{clients} set to earn-denied but redeem-allowed. That is a valid combination (stop granting, let existing points be spent), so it is not blocked — but if it was not deliberate, set both.",
  ppSave: "Save",
  ppSaving: "Saving…",
  ptHint: "Identity: points in circulation should equal the money in the pool. Viewed separately, an imbalance only surfaces when someone compares them by hand — so this page computes the gap directly. Read-only: the pool balance is derived from flows; to adjust it, post a typed flow.",
  ptCirculating: "Points in circulation",
  ptPoolBalance: "Pool balance",
  ptPeriodRedeem: "Redeemed this period",
  ptGapTitle: "Gap (pool − circulation)",
  ptBalanced: "Balanced",
  ptGapPoolMore: "Pool is higher: money collected without issuing matching points — check the granting path",
  ptGapPoolLess: "Pool is lower: points issued without collecting the matching fee — check issuance fee postings",
  ptByChannelTitle: "Ledger by channel",
  ptByChannelHint: "One pool on paper, but the money sits in separate channel accounts — a total alone stays balanced while one overflows and another runs dry",
  ptColChannel: "Channel",
  ptColMarket: "Market",
  ptColBalance: "Balance",
  ptEmpty: "No channel ledger yet",

  withdrawNotice: "This is the only action in the console that sends money out. Approving marks it “approved, awaiting payout”, never “paid” — the payout result comes from the channel receipt, and there is no “mark as paid” button, because that would let a case be closed while the money has not landed. Above ¥{n} a review note is required.",
  searchWithdraw: "Search withdrawal no. / merchant",
  filterWdStatus: "Filter by withdrawal state",
  filterWdStatusAll: "All withdrawal states",
  wdPending: "Awaiting approval",
  wdApproved: "Approved, awaiting payout",
  wdRejected: "Rejected",
  wdPaid: "Paid",
  wdFailed: "Payout failed",
  colWithdrawNo: "Withdrawal no.",
  colWdAmount: "Requested",
  colAvailable: "Available",
  colBankAccount: "Payout account",
  colWdStatus: "State",
  colAppliedAt: "Requested at",
  colDecidedAt: "Decided at",
  actionApprove: "Review",
  emptyWithdraw: "No withdrawal requests match. Requests raised by merchants in the B-end app land here.",
  withdrawTitle: "Withdrawal {no}",
  secWdOverview: "Request overview",
  secPrecheck: "Payout preconditions",
  checkAccount: "Payout account registered",
  checkAccountBad: "No payout account registered — approving sends money nowhere",
  checkNotBanned: "Merchant trading normally",
  checkNotBannedBad: "Merchant is banned — lift the ban first",
  checkBalance: "Within available balance",
  checkBalanceBad: "Request exceeds the available balance",
  checkMin: "Meets the per-request minimum",
  checkMinBad: "Below the ¥{n} minimum — the channel fee costs more than the amount",
  precheckHint: "The balance is the snapshot taken when the request was raised, not a live figure — approval judges what they could withdraw at that moment.",
  secWdRemark: "Note",
  fieldReviewNote: "Review note",
  fieldRejectReason: "Rejection reason",
  reviewNotePlaceholder: "e.g. Account confirmed with the merchant by phone, recording #2026-0804",
  rejectReasonPlaceholder: "e.g. Account holder does not match the registered entity; correct it and reapply",
  reviewNoteHint: "Above ¥{n}, a review note is required before approving.",
  rejectReasonHint: "The rejection reason reaches the merchant verbatim; leaving it blank makes them guess.",
  lastRemark: "Previous note: {text}",
  btnApprove: "Approve",
  btnReject: "Reject",
  toastWdApproved: "Approved — awaiting the channel payout receipt",
  toastWdRejected: "Rejected — the reason went back to the merchant",
  withdrawReadOnlyWhat: "withdrawal approval",

  invoiceNotice: "Invoices and withholding share a page: they are two halves of one question — the invoice is the outward document, withholding the inward deduction. An invoice cannot exceed what was settled for that period; anything beyond has no real transaction behind it.",
  searchInvoice: "Search invoice no. / merchant / title",
  filterIvStatus: "Filter by invoice state",
  filterIvStatusAll: "All invoice states",
  ivPending: "Awaiting issue",
  ivIssued: "Issued",
  ivRejected: "Rejected",
  colInvoiceNo: "Request no.",
  actionView: "View",
  none: "—",
  colTitleType: "Title type",
  colTitle: "Invoice title",
  colTaxNo: "Tax ID",
  colIvAmount: "Requested",
  colSettled: "Settled this period",
  colIvStatus: "State",
  titleCompany: "Company",
  titlePersonal: "Individual",
  actionIssue: "Issue",
  emptyInvoice: "No invoice requests match. Requests raised by merchants in the B-end app land here.",
  invoiceTitle: "Invoice request {no}",
  secIvOverview: "Request overview",
  warnOverSettled: "The requested amount exceeds what was settled this period; the excess has no real transaction behind it and cannot be invoiced.",
  warnMissingTaxNo: "A company title needs a tax ID — ask the merchant to supply it first.",
  secIssue: "Handle the request",
  fieldSerialNo: "Invoice serial no.",
  serialPlaceholder: "e.g. FP20260801001",
  serialHint: "Write it back here after issuing; the merchant looks the invoice up by it. An “issued” with no serial cannot be found.",
  ivRejectPlaceholder: "e.g. Amount exceeds what was settled; reapply for the actual figure",
  secIssued: "Issued",
  secIvRemark: "Handling note",
  btnIssueInvoice: "Issue invoice",
  btnRejectInvoice: "Reject",
  toastIvIssued: "Issued — the serial number went back to the merchant",
  toastIvRejected: "Invoice request rejected",
  taxTitle: "Withholding rules",
  taxNotice: "Applies to individual merchants only: sole traders and companies file for themselves. Nothing is withheld below the threshold — without one, every few-yuan withdrawal spawns a withholding entry.",
  fieldThreshold: "Threshold (¥)",
  thresholdHint: "Income below this in a period is not withheld against.",
  fieldTaxRate: "Withholding rate (%)",
  taxRateHint: "Capped at {n}% — anything higher is a configuration error.",
  toastTaxSaved: "Withholding rules saved",
  itTitle: "Platform invoice title",
  itNotice: "Suppliers invoice the platform against these details. The company name and tax number are both required — without them no invoice can be issued, while the payable is already sitting there. When all five are blank the panel shows «Not configured»; that is not a loading failure.",
  itUnset: "Not configured",
  itCompany: "Company name",
  itTaxNo: "Tax number",
  itAddress: "Registered address",
  itPhone: "Registered phone",
  itBank: "Bank and account",
  itSave: "Save title",
  toastItSaved: "Invoice title saved",
  taxReadOnlyWhat: "withholding rules",

  trafficMerchantOwned: "Merchant-owned",
  trafficPlatform: "Platform traffic",
  trafficInvite: "Referral",
  trafficChannel: "Channel",

  toastSplitDone: "{no} paid out",
  toastFrozenBack: "Released back to the platform",
  toastRefundBack: "Split reversed; the after-sales flag is cleared",
  toastRateSaved: "Rate settings saved",

  colSettleNo: "Settlement no.",
  colMerchant: "Merchant",
  colPeriod: "Period",
  colOrderCount: "Sub-orders",
  colGross: "Gross due",
  colPlatformFee: "Platform commission",
  colServiceFee: "Fulfillment fee",
  colNet: "Net to merchant",
  colRetry: "Retries",
  retryMaxed: "{n} (limit reached)",
  colStatus: "Status",
  colActions: "Actions",
  settleClosed: "Closed",

  confirmSplitTitle: "Release payout {no}",
  confirmSplitDesc: "This pays {name} {amount}. Money actually moves — check the gross and commission before confirming.",
  confirmSplitOk: "Release payout",
  btnRetrySplit: "Retry payout",
  btnSplit: "Release payout",
  btnFreezeBack: "Release to platform",

  colSplitNo: "Split no.",
  colOrder: "Sub-order",
  colTraffic: "Traffic source",
  colFeeRate: "Rate applied",
  colGrossAmount: "Order value",
  colPickup: "Pickup point",

  colAsNo: "After-sales no.",
  colOrderNo: "Order no.",
  colRefundAmount: "Refund amount",
  colShare: "Liability split",
  shareText: "Platform {p}% · merchant {m}% · pickup point {k}%",
  shareUndecided: "Not decided",
  colVerdict: "Decision note",
  confirmBackTitle: "Reverse split {no}",
  confirmBackDesc: "Claws back {amount} from each party per the decided split. The after-sales reversal flag is cleared afterwards.",
  confirmBackOk: "Reverse",
  btnExecuteBack: "Reverse",

  readOnlyWhat: "payout execution & reversal",
  readOnlyNote: "cannot release payouts, release funds or reverse splits",
  kpiPending: "Awaiting payout",
  kpiPendingSub: "Money not yet sent to merchants",
  kpiPageCount: "Settlements on this page",
  kpiMaxed: "Retry limit reached",
  kpiMaxedSub: "Needs a human",
  settleNotice:
    "Prerequisite: the merchant must have registered a payout account (ADR-002). Releasing to an unregistered merchant is rejected by the server — this is not a front-end guard, the money genuinely cannot move.",
  searchSettle: "Search settlement no. / merchant / period",
  searchSplit: "Search split no. / sub-order / merchant",
  filterStatus: "Filter by status",
  filterStatusAll: "All statuses",
  emptySettle: "No settlements match these filters. Settlements are generated per merchant × period, so an untraded period is empty.",
  emptySplit: "No split details yet. They are generated per sub-order, one row each.",
  refundBackNotice:
    "Every row here comes from a reversal flag set by an after-sales decision (P-6.1) — the queue is derived from after-sales tickets rather than stored separately: a separate store would mean two sources of truth, guaranteed to drift. Executing clears the flag and the row disappears.",
  emptyRefundBack: "No splits awaiting reversal. Rows appear automatically once an after-sales decision requires one.",

  frNotice:
    "Rates are append-only: a change adds a new version and the old ones are kept forever — that is what makes \"which rate applied to last month's orders\" answerable. Rates are snapshotted at order time, so changes never affect settlements already generated.",
  frEffectiveTitle: "Rates in effect now",
  frEffectiveHint: "Four cells = business mode × traffic source. The two are orthogonal: under self-operated this number is a gross margin, under third-party it is commission — same arithmetic, different accounting.",
  frAddTitle: "Add a rate version",
  frFieldRate: "Rate (basis points)",
  frFieldFrom: "Effective from",
  frFromHint: "Leave empty for immediate effect; set a future time to schedule it.",
  frFieldRemark: "Reason for the change",
  frRemarkHint: "When looking back, this sentence is more useful than the number.",
  frAdd: "Add version",
  frAdding: "Submitting…",
  frToastAdded: "Rate version added",
  frHistoryTitle: "All versions ({n})",
  frColMode: "Business mode",
  frColSource: "Traffic source",
  frColRate: "Rate",
  frColEffectiveFrom: "Effective from",
  frColState: "State",
  frColRemark: "Reason",
  frModeSelfOperated: "Self-operated",
  frModeThirdParty: "Third-party",
  frInitial: "Initial",
  frScheduled: "Scheduled",
  frActive: "Active",
  frDisabled: "Disabled",

  pcNotice:
    "Channel fees and platform commission are two different things: this page sets what the **channel charges us**; commission lives under Tiered rates. Same rule — versions only, never edited in place. Settlement uses the version in force when the order was placed.",
  pcTitle: "Payment channels",
  pcColChannel: "Channel",
  pcColState: "State",
  pcColMarkets: "Markets",
  pcColCurrency: "Currency",
  pcColSettleCycle: "Settlement cycle",
  pcColRate: "Current rate",
  pcNoRate: "Not configured",
  pcNoRateHint: "No rate has ever been set, so settlement finds no version — this is not 0%.",
  pcEnabled: "Enabled",
  pcDisabled: "Disabled",
  pcActionEnable: "Enable",
  pcActionDisable: "Disable",
  pcAllMarkets: "All markets",
  pcEmpty: "No payment channel is configured. Without one, merchants cannot onboard or take money.",

  sbNotice: "A batch decides whether money can be released; a bill decides whether the release succeeds. This page answers which batch the money is stuck in.",
  sbReadOnlyWhat: "release and hold",
  sbReadOnlyNote: "Without this permission you can only look; finance or risk must decide.",
  sbColBatch: "Batch",
  sbColEntity: "Merchant",
  sbColChannel: "Channel",
  sbColCycle: "Cycle",
  sbColStatus: "Status",
  sbColBills: "Bills",
  sbColNet: "Payable",
  sbColDue: "Due",
  sbColScope: "Recon scope",
  sbColDecided: "Decided by",
  sbStatusAll: "All statuses",
  sbStatusDRAFT: "Collecting",
  sbStatusCOLLECTED: "Closed",
  sbStatusRECONCILING: "Reconciling",
  sbStatusBLOCKED: "Held",
  sbStatusRECONCILED: "Ready",
  sbStatusRELEASED: "Released",
  sbScopeSelfOnly: "Self-check only",
  sbScopeBoth: "With channel statement",
  sbTimeoutReleased: "Auto-released on timeout",
  sbEmpty: "No batches yet. Settleable bills are batched automatically.",
  sbBlockedTitle: "Held batches awaiting a decision",
  sbUnitBill: "bills",
  sbExpireHint: "Auto-released if not handled by:",
  sbRemarkLabel: "Reason (required)",
  sbRemarkPh: "Say why you are releasing or holding — this must answer for itself later",
  sbRelease: "Release",
  sbHold: "Keep holding",
  sbToastDecided: "Decision recorded",

  dbNotice: "Debt is the opposite of a deposit: the deposit is the merchant's money held by us; debt is what they owe us. Settlement offsets are automatic — this page only does deposit offsets.",
  dbReadOnlyWhat: "deposit offset",
  dbReadOnlyNote: "Without this permission you can only look. Touching principal is finance's call.",
  dbEntityLabel: "Merchant no.",
  dbEntityPh: "e.g. M0001",
  dbPickFirst: "Enter a merchant number — debt is tracked per merchant.",
  dbBalance: "Outstanding debt",
  dbNoDebt: "No debt. Most merchants never have any — that is the normal case.",
  dbColType: "Type",
  dbColAmount: "Change",
  dbColAfter: "Balance after",
  dbColSource: "Source / batch",
  dbColReason: "Note",
  dbColAt: "Time",
  dbTypeINCUR: "Incurred",
  dbTypeOFFSET: "Settlement offset",
  dbTypeDEPOSIT: "Deposit offset",
  dbTypeWRITE_OFF: "Written off",
  dbEmptyTxns: "No debt transactions.",
  dbOffsetTitle: "Offset with deposit",
  dbOffsetWhy: "This step is manual by design — it touches the merchant's principal, and the legal boundary for deducting without consent is still open. The automatic path never touches principal.",
  dbOffsetAmount: "Amount (yuan)",
  dbOffsetAmountPh: "e.g. 100",
  dbOffsetReason: "Reason (required)",
  dbOffsetReasonPh: "Say why the deposit is being touched — the merchant will ask",
  dbOffsetCapHint: "Capped at both ends: never more than the debt, never more than the available deposit (frozen amounts are reserved for other disputes).",
  dbOffsetSubmit: "Confirm offset",
  dbToastOffset: "Offset with deposit",
  pcDisableHint: "Disabling affects **new onboarding and new orders only**. Merchants already onboarded and orders in flight are unaffected.",
  pcSubsidyYes: "Supports subsidy",
  pcSubsidyNo: "No subsidy support (points offset stays off for this channel)",
  pcAddRateTitle: "Add a channel rate version",
  pcFieldChannel: "Channel",
  pcFieldPayMethod: "Payment method",
  pcFieldLegalForm: "Entity type",
  pcAnyHint: "Leave blank for all of them (stored as *). Fill it in for a rate specific to that combination; exact matches win over wildcards.",
  pcFieldMinFee: "Minimum fee per transaction (cents)",
  pcToastAdded: "Channel rate version added",
  pcToastUpdated: "Channel settings saved",
  pcHistoryTitle: "All versions for {ch} ({n})",
  colMode: "Business mode",
  colPayMerchant: "Payment account",
  colAction: "Instruction",
  colResult: "Result",
  colMessage: "Failure reason",
  modeSelfOperated: "Self-operated",
  modeThirdParty: "Third-party",
  noPayAccount: "Not onboarded",
  resultOk: "Success",
  resultFail: "Failed",
  rateTitle: "Rate settings",
  rateReadOnlyWhat: "rate settings",
  rateReadOnlyNote: "cannot change commission rates or the fallback window",
  rateNotice:
    "R15 (how the fulfillment fee is defined) and R16 (tiered rates) are not settled yet — these defaults are a starting point, not a conclusion. Zero is suggested for merchant-owned traffic: charge commission on customers the merchant brought in themselves and they will take those customers elsewhere.",
  rateTierTitle: "Tiered by traffic source (platform commission)",
  rateFieldBp: "{label} (basis points)",
  fieldPickupRate: "Default pickup-point fulfillment fee (basis points)",
  pickupRateHint: "= {pct}; a pickup point with its own rate uses that instead (editable on the Communities page).",
  fieldFreezeDays: "Fallback window (days)",
  freezeHint:
    "Funds frozen longer than this without a successful payout are released back to the platform. At least {n} days — any shorter and orders still retrying normally get pulled early.",

  pyTitle: "Self-operated payables",
  pyNotice: "How self-operated suppliers get paid: awaiting reconciliation → confirmed → invoice received (or marked exempt) → payment logged. ⚠️ **Invoice before payment**: without a verified purchase invoice, or an explicit invoice-exempt mark, it cannot be paid — that money would not be deductible.",
  pySummary: "{n} unpaid · {amount}",
  pyEmpty: "No self-operated payables",
  pyColBill: "Settlement",
  pyColNet: "Payable",
  pyColStatus: "Status",
  pyColInvoice: "Invoice",
  pyColRef: "Bank reference",
  pyConfirm: "Confirm reconciliation",
  pyNoInvoice: "Mark invoice-exempt",
  pyNoInvoiceReason: "Invoice-exempt supplier",
  pyPay: "Log payment",
  pyConfirmPay: "Confirm",
  pyRefPlaceholder: "Bank reference no.",
  payNeedConfirm: "Reconcile first",
  payNeedInvoice: "Invoice not received",
  payAlreadyPaid: "Paid",
  payableStatus_PENDING_RECON: "Awaiting reconciliation",
  payableStatus_CONFIRMED: "Awaiting payment",
  payableStatus_PAID: "Paid",
  invoiceStatus_PENDING_INVOICE: "Awaiting invoice",
  invoiceStatus_SUBMITTED: "Submitted",
  invoiceStatus_VERIFIED: "Verified",
  invoiceStatus_REJECTED: "Rejected",
  invoiceStatus_NO_INVOICE: "Invoice-exempt",

  piTitle: "Purchase invoices",
  piNotice: "Invoices suppliers issue to the platform — they decide whether the platform can pay. An invoice whose title does not match the entity name cannot be verified; forcing it through only defers the problem to tax filing.",
  piSummary: "{n} awaiting verification",
  piEmpty: "No purchase invoices to handle",
  piColInvoice: "Invoice",
  piColTitle: "Title",
  piColAmount: "Amount",
  piColSettle: "Covers",
  piColStatus: "Status",
  piVerify: "Verify",
  piReject: "Reject",
  piCannotVerify: "Title mismatch — cannot verify",
  piTitleMismatch: "Title does not match entity",
  piRejectPlaceholder: "Reason (sent to the merchant verbatim)",
  purchaseInvoiceStatus_PENDING: "Pending",
  purchaseInvoiceStatus_SUBMITTED: "Awaiting verification",
  purchaseInvoiceStatus_VERIFIED: "Verified",
  purchaseInvoiceStatus_REJECTED: "Rejected",

  brTitle: "Buyer invoice requests",
  brNotice: "Invoices buyers request for their own orders. ⚠️ Three different invoices live in this area: this page is keyed by **order**, the other two by entity and period.",
  brSummary: "{n} pending",
  brEmpty: "No pending invoice requests",
  brColOrder: "Order",
  brColTitle: "Title",
  brColAmount: "Amount",
  brColStatus: "Status",
  brMarkIssued: "Mark issued",
  brReject: "Reject",
  brNoTaxNo: "Missing tax no.",
  brInvoiceNoPlaceholder: "Invoice number",
  brRejectPlaceholder: "Reason (sent to the buyer verbatim)",
  titleType_PERSONAL: "Personal",
  titleType_COMPANY: "Company",
  buyerInvoiceStatus_PENDING: "Pending",
  buyerInvoiceStatus_ISSUED: "Issued",
  buyerInvoiceStatus_REJECTED: "Rejected",

  all: "All",
  confirm: "Confirm",
  cancel: "Cancel",

};

export const FINANCE_COPY: PageCopy<typeof zh> = { zh, en };

/** 拆出去的 tab 组件靠它接文案。 */
export type FinanceCopy = typeof zh;
