// 商品与类目文案（矩阵 P-3.1 / P-3.2 / P-3.3）。
import type { PageCopy } from "@/lib/use-copy";

const zh = {
  gaReadOnly: "当前角色只能查看，不能审核商品。",
  gaColNo: "商品号",
  gaColTitle: "标题",
  gaColType: "形态",
  gaColCategory: "类目",
  gaCategoryEmpty: "未设置",
  gaColMerchant: "商家",
  gaColActions: "操作",
  gaAction: "审核",
  gaEmpty: "没有待审商品",
  // ── 社区池重建（P-3.2）。后端一直有，运营端此前没有入口 ──
  rsTitle: "重建社区池",
  rsNotice: "社区池是「这件商品出现在哪些社区」的派生索引。两种情况要重建：① 改过可见性口径之后（存量池行是旧口径写下的）；② 商家报「我明明上架了，买家搜不到」而经营范围看着没问题时。重建只重算索引，不改商品本身。",
  rsScope: "只重建某个商家（留空 = 全部）",
  rsPlaceholder: "商家号，如 M901",
  rsRun: "开始重建",
  rsRunning: "重建中…",
  rsDone: "重建完成，涉及 {n} 件商品",
  rsDoneZero: "重建完成，没有需要更新的商品 —— 这说明池子本来就是对的，不是没跑",
  gaSectionInfo: "商品信息",
  gaDraftSection: "本次过审将生效的变更",
  gaDraftHint: "线上仍在售旧版；「通过」后按下表原子换新。这份差异与商家发布确认页出自同一份计算。",
  gaDraftBlocked: "有档位引用了已停用的规格值，通过会在换版时失败：",
  gaDraftNoChange: "草稿与线上一致 —— 通过不会改变买家看到的内容",
  gaSectionDecide: "审核",
  gaReasonLabel: "审核意见",
  gaReasonPh: "驳回必填 —— 商家拿不到理由就只能反复重提，每次都要再占一次审核人力",
  gaApprove: "通过",
  gaReject: "驳回",
  gaApproved: "已通过",
  gaRejected: "已驳回，理由已发给商家",
  gaRejectedTag: "这件商品此前被驳回过",

  marketCN: "中国",
  marketSG: "新加坡",

  stdNotice: "标准品是商家建品时的模子：他搜到一条、取用，标题图和规格就自动填好，只需要填价和库存。录得越全，商家建品越省事，跨店比价也才成立。",
  stdSearch: "搜编号 / 名称 / 别名",
  stdFilterCategory: "按类目筛",
  stdFilterCategoryAll: "全部类目",
  stdShowArchived: "含已归档",
  stdFilterSource: "按出处筛",
  stdFilterSourceAll: "全部出处",
  stdSourceOps: "运营录入",
  stdSourceOff: "开放库导入",
  stdColSource: "出处",
  stdPickAll: "本页全选",
  stdPickedN: "已选 {n} 条（仅本页）",
  stdPickClear: "取消选择",
  stdBulkEnable: "批量启用",
  stdBulkArchive: "批量归档",
  stdBulkArchiveTitle: "归档选中的 {n} 条标准品？",
  stdToastBulk: "已改动 {n} 条",
  stdNew: "新建标准品",
  stdEmpty: "还没有标准品 —— 商家建品时会看到空的搜索结果",
  stdColNo: "编号",
  stdColTitle: "名称",
  stdColCategory: "类目",
  stdColSpecs: "规格（编码 · 文案）",
  stdColRefCount: "被引用",
  stdColArchivedAt: "归档时间",
  stdEdit: "编辑",
  stdConfirmArchiveTitle: "归档「{name}」？",
  stdConfirmArchiveDesc: "归档只是让它不再出现在商家的搜索结果里。已经引用它建出来的商品照常在售、照常可编辑 —— 编号是溯源不是外键。",
  stdConfirmArchiveOk: "归档",
  stdDrawerNew: "新建标准品",
  stdDrawerEdit: "编辑标准品",
  stdFieldTitle: "名称",
  stdTitlePh: "如 本地菠菜",
  stdFieldCategory: "类目",
  stdCategoryPh: "选择类目",
  stdCategoryHint: "类目决定商品形态（生鲜要截单、服务不发货），商家取用后改不掉它。",
  stdFieldSubtitle: "副标题",
  stdFieldKeywords: "别名",
  stdKeywordsPh: "空格分隔，如 土豆 马铃薯 洋芋",
  stdKeywordsHint: "商家嘴里的词与标题对不上时，他会以为标准库里没有 —— 然后自建一条，跨店可比就在这一次丢了。",
  stdFieldSpecs: "规格组",
  stdSpecsHint: "每个选项都要填编码。没有编码的标准品与商家手输没有区别，它唯一的作用是让人以为规格统一了。",
  stdGroupNamePh: "维度名，如 重量",
  stdOptionCodePh: "编码 W1JIN",
  stdOptionLabelPh: "文案 1斤",
  stdAddGroup: "＋ 规格组",
  stdRemoveGroup: "删除该组",
  stdAddOption: "＋ 选项",
  stdRemoveOption: "删除",
  stdToastSaved: "标准品已保存",
  stdToastArchived: "已归档",
  stdToastUnarchived: "已恢复",
  toastApproved: "已通过，商品已上架",
  toastRejected: "已驳回，原因已发给商家",
  toastForcedOff: "已强制下架",
  toastGoodsForcedOff: "已强制下架并撤销过审，原因已发给商家",
  toastPresaleSaved: "预售配置已保存",
  toastCatArchived: "类目已归档",

  /** `{n}` 是在售数 */
  catOnSale: "（在售 {n}）",
  detail: "详情",

  colSkuNo: "商品编码",
  colTitle: "商品",
  colMerchant: "商家",
  colCategory: "类目",
  colPricing: "多市场定价",
  /** `{m}` 是市场代码 */
  priceMissing: "{m} 缺价",
  /** `{v}` 是已格式化的价格，如 ¥8.90 */
  priceFrom: "{v} 起",
  colI18n: "译文",
  /** `{langs}` 是缺失语言 */
  i18nMissing: "缺 {langs}",
  i18nComplete: "齐全",
  colStock: "库存",
  colSkuCount: "规格数",
  colStatus: "状态",
  colActions: "操作",
  actionAudit: "审核",
  actionView: "查看",

  colPresaleQuota: "预售额度",
  colSold: "已售",
  colCutoffAt: "截单时间",
  colArriveAt: "到货时间",
  actionEditPresale: "改配置",

  readOnlyWhat: "商品审核与强制下架",
  readOnlyNote: "不能通过、驳回或下架",

  catTreeTitle: "平台类目树（两级）",
  catMoveUp: "↑",
  catMoveDown: "↓",
  catDragHint: "拖动可调整顺序（只能在同一级、同一个父类目里挪）",
  catBulkSelected: "已选 {n} 项",
  catBulkOn: "批量启用",
  catBulkOff: "批量停用",
  catBulkClear: "取消选择",
  catBulkOffTitle: "停用选中的 {n} 个二级类目？",
  catBulkOffDesc: "归到这些类目下的商品还在，只是 C 端入口收起来。还挂着在售商品的会被跳过。",
  catBulkOffOk: "停用",
  catBulkDone: "已处理 {n} 项，跳过 {m} 项",
  catBulkNone: "选中的都处理不了：一级不参与批量，挂着在售商品的要先把商品移走",
  catBulkTip: "批量只作用于二级 —— 一级要连带下面一整组，得一个个确认",
  catEnableParentTitle: "上级「{name}」是停用的，一起启用吗？",
  catEnableParentDesc: "只开这一条的话它挂在一棵关着的树上：商家选不到、C 端也不出现。",
  catEnableParentOk: "一起启用",
  catEnableTopTitle: "同时启用「{name}」下面的二级吗？",
  catEnableTopDesc: "有 {n} 个二级还是停用的。只开一级的话，商家点进去是空的。",
  catEnableTopOk: "一起启用",
  catDisableTopTitle: "同时停用「{name}」下面的二级吗？",
  catDisableTopDesc: "有 {n} 个二级还开着。留着的话它们在搜索与专题里仍会露出来。",
  catDisableTopOk: "一起停用",
  catOffBlockedGoods: "还有 {n} 件商品在这一类下，先移走才能停用",
  catDisableImpactTitle: "停用「{name}」",
  catDisableImpactDesc:
    "这一类下面还有 {n} 件商品，其中 {on} 件在售。停用后：商家仍能看到和编辑它们，但上架会被类目校验挡下，买家侧的类目筛选与导购也不再命中。要不要先把这些商品移到别的类目？",
  catDisableImpactOk: "照样停用",
  catOffBlockedChild: "二级「{name}」下还有 {n} 件商品，先移走才能整棵停用",
  catI18nMissing: "缺译",
  catI18nMissingHint: "缺英文名，C 端英文界面会回落显示中文",
  catPreview: "买家侧预览",
  catPreviewDesc: "按当前配置渲染：只显示启用中的类目，顺序与买家看到的一致。它读的是这一页的数据，不是去抓线上页面。",
  catPreviewLang: "语言",
  catPreviewZh: "中文",
  catPreviewEn: "English",
  catPreviewPane: "类目栏",
  catPreviewFallback: "回落中文",
  catPreviewEmptyGroup: "这一类下没有启用中的二级 —— 买家点进来是空的",
  catColName: "类目",
  catColTemplate: "形态",
  catColGoods: "商品数",
  catColOrder: "顺序",
  catColStatus: "启用",
  catNoGateShort: "—",
  catGateNeed: "需证",
  catGateBroken: "码已停用",
  catSearchPh: "搜类目名",
  catAllTemplates: "全部形态",
  catShowOff: "含已停用",
  catStat: "{a} 个一级 · {b} 个二级 · {c} 个已停用",
  catNoChild: "还没有二级类目",
  catSubCount: "{n} 项",
  catAddChild: "+ 加二级",
  catEnabled: "已启用 —— 商家能选、C 端会出现",
  catDisabled: "已停用 —— 商家选不到；已归到这一类的商品不受影响",
  catNew: "新建类目",
  catEdit: "编辑类目",
  catSave: "保存",
  catSaved: "类目已保存",
  catFormBasic: "类目信息",
  fieldCatName: "类目名称",
  fieldCatNameEn: "英文名",
  fieldParent: "上级类目",
  catParentNone: "不选 = 新建一级类目",
  catTemplateInherited: "继承上级，不可改",
  fieldRequiredCode: "经营门槛（授权码）",
  catNoGate: "无门槛（谁都能卖）",
  catGateHint: "门槛码是准入的判据，上面那行资质文案只是给人看的。只列启用中的码：挂一个停用的码，这个类目就永远拒绝所有人。",
  catCodeUnusable: "⚠ 这个码已停用或不存在 —— 该类目现在谁都上不了架，运营也授不出去",
  tplStandard: "标品",
  tplFresh: "生鲜",
  tplService: "服务",
  tplVoucher: "卡券",
  tplVirtual: "虚拟商品",
  loading: "加载中…",
  emptyTree: "还没有类目。类目树是商品的骨架，缺它商家无法提审商品。",
  catDetailTitle: "类目详情",
  catDetailHint: "点左侧任一类目的「详情」，查看它的模板、资质与多语言名称。",
  fieldCatNo: "类目编号",
  fieldLevel: "层级",
  /** `{n}` 是级数 */
  levelN: "{n} 级",
  fieldTemplate: "属性模板",
  fieldQualification: "资质要求",
  /** `{code}` 是校验编码 */
  requiredCode: "校验编码：{code}",
  noQualification: "无门槛",
  fieldI18nName: "多语言名称",
  i18nFallback: "缺失（回落到中文）",
  fieldSkuCount: "在售商品",
  /** `{name}` 是类目名 */
  confirmArchiveTitle: "归档类目 {name}",
  confirmArchiveDesc: "归档后该类目不再出现在 C 端类目树；若它还有子类目或在售商品，服务端会拒绝。",
  confirmArchiveOk: "归档",
  btnArchiveCat: "归档该类目",
  /** 从类目详情跳到商品池，并带上这个类目当筛选条件 */
  btnViewCatGoods: "查看该类目商品",

  searchSku: "搜索商品编码 / 标题 / 商家",
  filterStatus: "按状态筛选",
  filterStatusAll: "全部状态",
  filterMerchant: "按商家筛选",
  filterMerchantAll: "全部商家",
  filterCategory: "按类目筛选",
  filterCategoryAll: "全部类目",
  emptySku: "没有符合条件的商品。商家在 B 端建好商品提审后会出现在这里。",

  kpiPresale: "预售中商品",
  kpiOversell: "超卖商品",
  kpiOversellSub: "需人工决定补货还是退单",
  kpiOversellNone: "无超卖",
  kpiOversellQty: "超卖件数",
  stockNotice:
    "超卖只报警不自动处置：补货还是退单要人判断，自动关单会把还能补上的团也关掉。截单时间必须早于到货时间 —— 否则货到了还能继续下单，必然超卖。",
  emptyStock: "当前没有预售商品。生鲜的预售额度与截单时间在这里配。",

  btnReject: "驳回",
  btnConfirmReject: "确认驳回",
  btnApprove: "通过并上架",
  btnForceOff: "强制下架",
  btnConfirmForceOff: "确认强制下架",
  fieldGoodsAction: "平台动作（整件商品）",
  btnForceOffGoods: "强制下架整件商品",
  btnConfirmForceOffGoods: "确认下架并撤销过审",
  /*
   * ⚠️ 这句原先的后半段是「错的」：「只压某个规格用下面每条规格上的按钮」。
   * 规格行上的通过/驳回/下架，后端一律「解析到父商品再执行」
   * （`prd_sku` 没有审核态，审的是「这件商品能不能卖」）——
   * 也就是说对一行点驳回，整件商品连同其他规格一起被打回。
   * 照原文操作的运营会以为自己只压了一个规格。
   */
  forceOffGoodsHint: "整件下架 = 撤销过审：商品回到已驳回，商家必须改完重新提审，不能自己一键上回去。",
  skuScopeWarn: "⚠️ 规格行上的通过 / 驳回 / 下架作用于整件商品，不是只作用于这一个规格 —— 审核判的是「这件商品能不能卖」，标题、图、类目、资质都在商品上。",
  fieldSkuList: "规格列表",
  fieldCreatedAt: "创建时间",
  fieldPricing: "多市场定价（B6：各市场分别定价）",
  priceMissingBlocking: "缺价，无法上架",
  fieldI18nCopy: "三语文案（P-3.2.5）",
  i18nFallbackLong: "缺失，按回落规则展示中文",
  fieldRejectReason: "驳回原因",
  fieldForceOffReason: "强制下架原因",
  fieldGoodsForceOffReason: "撤销过审原因（商家原样看到）",
  reasonPlaceholder: "商家会原样看到：写清楚哪里不合规、怎么改",
  fieldHandledReason: "处理原因",

  presaleTitle: "预售配置",
  save: "保存",
  fieldQuota: "预售额度",
  quotaHint: "0 表示不做预售，只卖现货库存。",
  fieldCutoff: "截单时间（ISO）",
  cutoffHint: "必须早于到货时间，否则货到了还能继续下单。",
  fieldArrive: "到货时间（ISO）",
  arriveHint: "留空表示不改。它是「截单必须早于到货」这条校验的基准 —— 不填的话那条校验校不到东西。",

  // ── 规格库（V195）
  slNoticeCommon:
    "通用规格：值的含义跨类目一致 —— 锅的黑和手机的黑是同一个黑。改这里的一条会在所有绑了它的类目上生效，也就是所有商家的建品页。量纲维度（重量、容量、口径）的每个值都要有归一量，没有它按规格排序会把 1kg 排在 500g 前面。",
  slNoticeSpecial:
    "专用规格：值的含义只在某一类目下成立 —— 「段位」只有婴幼儿食品讲得通，「房型」只有家政讲得通。它们通常只被一个类目绑，改动范围小，但同样不能与通用维度重名。",
  slSearch: "搜索维度名 / 语义码",
  slNewDim: "新建规格项",
  slEditDim: "编辑规格项",
  slColName: "规格项",
  slColType: "取值类型",
  slColInUse: "被几个类目用",
  slColValues: "取值",
  slAddValue: "＋ 取值",
  slEditValue: "编辑取值",
  slEnum: "枚举",
  slQuant: "数值",
  slSale: "销售规格（进 SKU）",
  slProp: "描述属性（不进 SKU）",
  slPromote: "提升为平台值",
  slPromoteHint: "改的只是归属，编号不变 —— 已经按它建好的商品不用重建",
  slPromoted: "已提升为平台值",
  slEmpty: "还没有规格项。商家建品时选不到任何推荐规格，只能自由手输。",
  slFieldName: "名称",
  slNameHint: "用通名、二到四字。「规格」「型号」「类型」这类万能词不能用 —— 它们什么都不说，商家看到一个叫「规格」的规格组仍旧不知道该填什么",
  slFieldCode: "语义码",
  slCodeHint: "值编号与 optionCode 都以它为前缀。定下就不该改 —— 改码等于换一根聚合轴，之前按老码建的商品就聚合不到一起了",
  slValueCodeHint: "维度内唯一。对外仍叫 optionCode",
  slFieldValueType: "取值类型",
  slValueTypeHint: "数值型的值必须有归一量（500g / 半斤 / 0.5kg 都是 500），排序与同规格比价靠它",
  slFieldUnit: "单位",
  slUnitHint: "归一后的基准单位：重量 g、容量 ml、长度 m、口径 cm、时长分钟",
  slFieldUsage: "用途",
  slUsageHint: "销售规格会进 SKU 笛卡尔积（每个组合各有价与库存）；描述属性整件商品一个值。材质、产地、保质期多数时候属于后者 —— 塞进规格组会让组合数爆炸",
  slFieldLabel: "展示文案",
  slLabelHint: "商家和买家看到的那个词。改它不影响已建商品（那边存的是快照）",
  slFieldNumeric: "归一量",
  slNumericHint: "换算到基准单位后的数字。1斤填 500、2斤填 1000 —— 单位不用填，跟维度走",
  slFieldAliases: "别名",
  slAliasesHint: "空格或逗号分隔。商家输入命中别名时会被认成这一档，而不是新造一个值",
  slFieldSort: "排序",

  // ── 类目 × 规格（可编辑）
  csEditTitle: "配置「{name}」的规格",
  csPickDims: "可选维度",
  csSectionSale: "销售规格",
  csSectionSaleHint: "买家要挑一档，每一档单独定价、单独算库存。排第一的是主维度，建品时自动带出来。",
  csSectionProp: "商品参数",
  csSectionPropHint: "只写给买家看，不分 SKU、不影响价格和库存。没有主维度，顺序也不影响什么。",
  csPickSale: "加销售规格",
  csPickProp: "加商品参数",
  csPicked: "已选维度",
  csSetPrimary: "设为主维度",
  csUnbind: "移除",
  csPickValues: "取值",
  // 取值这一层：顺序 = 商家建品时看到的先后。「排在前面的会被选中得多」 ——
  // 常用档位排前面，商家少翻少手输，而手输的值没有规格编码、参与不了聚合
  // 类目树上的规格列。「红色的「未配」是这一列的全部意义」 ——
  // 配了几个是次要信息，没配才是要人动手的那一行
  fieldCatNameEnHint: "留空则英文界面显示中文",
  // 「照某个类目配」。从零挑 4 个维度、每个再挑 3–5 个取值是二十来次点击，
  // 而新类目往往和某个同级几乎一样
  csCopyFromPh: "照哪个类目配…",
  csCopyDo: "照它配",
  catColSpecs: "规格",
  catSpecsNone: "配规格",
  catSpecsGo: "去配「{name}」的规格",
  csValsRest: "还没选的取值",
  csValsAllHint: "全部可选",
  csValMoveL: "往前",
  csValMoveR: "往后",
  csValDrop: "移出",
  csRenameHint: "双击改名",
  csRenamePrompt: "在「{cat}」下把「{label}」显示成：",
  csEditOk: "保存绑定",
  csEdit: "配置",

  // ── 类目 × 规格总览（规格库 V195）
  cpmTitle: "类目 × 支付方式",
  cpmNotice: "这是「能不能当面付」四层判定的第 ① 层（类目 → 主体资质 → 门店 → 商品），四层取交集，任何一层说不就是不。⚠️ 这张表是「黑名单」：没有行即放行，配一条才是禁止 —— 所以空着是正常的，不是缺口。一期主力用的是「主体资质」那一层。",
  cpmSummary: "已禁 {blocked} / 共 {total} 个类目",
  cpmColCategory: "二级类目",
  cpmColOffline: "当面付",
  cpmAllowed: "允许",
  cpmBlocked: "已禁止",
  cpmBlock: "禁止",
  cpmAllow: "恢复允许",
  cpmEmpty: "暂无类目",
  cptTitle: "类目 × 积分",
  cptNotice: "积分发放规则「由平台按类目统一管理，商家不参与配置」 —— 依据是实测：线上 199 件商品里，用商品级配置配了积分的是 0 件。没配规则的类目走平台兜底，而兜底是所有类目共用的一个数：生鲜与家电按同一个比例发分，怎么算都不对。所以这一页空着就是缺口。",
  cptSummary: "已配 {n} / 共 {total} 个类目",
  cptColCategory: "二级类目",
  cptColRule: "发放规则",
  cptNone: "未配置",
  cptEdit: "配置",
  cptSave: "保存",
  cptClear: "清除",
  cptRatio: "按比例",
  cptFixed: "定额",
  cptRatioText: "成交额的 {v}%",
  cptFixedText: "每单 {v} 分",
  cptEmpty: "暂无类目",
  csTitle: "类目 × 规格",
  csNotice:
    "商家建品时能选到什么规格，取决于这张表。一条都没配的类目会标红 —— 那一类的商家只能手输，而手输的选项没有规格编码，三家店的「500g」「五百克」「0.5kg」永远聚不到一起。主维度是选完类目自动预填的那一个。",
  csColCategory: "类目",
  csColType: "品类",
  csColDims: "已配规格",
  csColDetail: "维度与取值",
  csPrimary: "主",
  csUniversal: "通用",
  csDedicated: "专用",
  csProp: "属性",
  csNone: "未配置",
  csExpand: "展开取值",
  csCollapse: "收起",
  csSummary: "{total} 个在售类目，{configured} 个已配规格，{gap} 个还空着",
  csEmpty: "还没有任何类目绑定规格。",

  // ── 规格模板（P-3.4 / E27）
  tplNotice:
    "平台模板是跨店可比的基础：商家建品时选它，选项上的规格编码决定了三家店写的「5 斤」「五斤」「2.5kg」能不能聚合到一起。归档不是删除 —— 历史商品还靠模板号解释它当初用的编码。",
  tplSearch: "搜索模板名 / 模板号 / 规格编码",
  tplFilterCategory: "按品类筛选",
  tplFilterCategoryAll: "全部品类",
  tplShowArchived: "含已归档",
  tplColNo: "模板号",
  tplColName: "规格维度",
  tplColCategory: "适用品类",
  tplCategoryAny: "不限品类",
  tplColOptions: "选项（编码 · 名称）",
  tplColArchivedAt: "归档时间",
  tplColStatus: "状态",
  tplStatusActive: "启用中",
  tplStatusArchived: "已归档",
  tplEmpty: "还没有平台模板。商家建品时选不到模板，只能自由手输规格 —— 那样各店的写法聚合不到一起。",
  tplNew: "新建模板",
  tplEdit: "编辑",
  tplArchive: "归档",
  tplUnarchive: "恢复",
  /** `{name}` 是模板名 */
  tplConfirmArchiveTitle: "归档模板 {name}",
  tplConfirmArchiveDesc: "归档后商家建品时不再看到它。已经用过它的商品不受影响 —— 归档不是删除。",
  tplConfirmArchiveOk: "归档",
  tplDrawerNew: "新建平台模板",
  tplDrawerEdit: "编辑平台模板",
  tplFieldName: "规格维度名",
  tplNamePh: "如「重量」「香型」",
  tplFieldCategory: "适用品类",
  tplFieldOptions: "选项",
  tplOptionsHint: "每个选项都要填规格编码 —— 没有编码的平台模板与商家自己手输的没有区别。",
  tplOptionCodePh: "编码，如 W_500G",
  tplOptionLabelPh: "名称，如 500g",
  tplAddOption: "加一个选项",
  tplRemoveOption: "删除",
  toastTplSaved: "模板已保存，商家建品时立刻能选到",
  toastTplArchived: "模板已归档，商家侧不再下发",
  toastTplUnarchived: "模板已恢复",
  topicNotice: "主题是「这周首页摆什么」，与类目、活动都不是一回事：类目决定这是什么货、要什么资质，活动决定打几折。摆到一起不等于降价。",
  topicNew: "新建专题",
  topicEdit: "编辑",
  topicPick: "挑商品",
  topicArchive: "归档",
  topicUnarchive: "取消归档",
  topicArchived: "已归档",
  topicActive: "生效中",
  topicColTitle: "专题名",
  topicColSubtitle: "副标题",
  topicColSort: "排序",
  topicColRange: "档期",
  topicColGoods: "商品",
  topicColStatus: "状态",
  topicAlways: "常设",
  topicEmpty: "空专题",
  topicGoodsCount: "{n} 件",
  topicSectionBasic: "基本信息",
  topicSectionGoods: "专题商品",
  topicStart: "开始时间",
  topicEnd: "结束时间",
  topicRangeHint: "两头都可以留空：留空即常设专题。填一个假的结束时间，它会在某天悄悄消失。",
  topicSave: "保存",
  topicSaved: "已保存",
  topicPickTitle: "{name} · 挑商品",
  topicPickNotice: "只列在售商品。摆一件已下架或待审的货进来，买家点进去看到的是空位，而这里显示它在专题里。",
  topicPicked: "已选 {n} 件",
  topicPoolEmpty: "没有在售商品可挑",
  topicSaveGoods: "保存专题商品",
  topicGoodsSaved: "专题商品已更新",
  topicLoadFailed: "当前专题商品加载失败，保存会覆盖成你现在勾的这些",

};

const en: typeof zh = {
  gaReadOnly: "Your role can view goods but not review them.",
  gaColNo: "Goods no.",
  gaColTitle: "Title",
  gaColType: "Form",
  gaColCategory: "Category",
  gaCategoryEmpty: "Not set",
  gaColMerchant: "Merchant",
  gaColActions: "Actions",
  gaAction: "Review",
  gaEmpty: "Nothing waiting for review",
  rsTitle: "Rebuild community pools",
  rsNotice: "The community pool is a derived index of «which communities does this item appear in». Rebuild it when: (1) the visibility rule changed — existing rows were written under the old rule; or (2) a merchant reports «I listed it but buyers cannot find it» while the service scope looks fine. Rebuilding only recomputes the index; it does not touch the items themselves.",
  rsScope: "Limit to one merchant (blank = all)",
  rsPlaceholder: "Merchant no, e.g. M901",
  rsRun: "Rebuild",
  rsRunning: "Rebuilding…",
  rsDone: "Done — {n} items rebuilt",
  rsDoneZero: "Done — nothing needed updating, which means the pools were already correct (not that it did not run)",
  gaSectionInfo: "Goods",
  gaDraftSection: "Changes that take effect on approval",
  gaDraftHint: "Buyers still see the old version; approval swaps it atomically per the table below. Same computation as the merchant's publish preview.",
  gaDraftBlocked: "Some options reference retired spec values; approval will fail at swap: ",
  gaDraftNoChange: "The draft matches the live version — approval changes nothing buyers see",
  gaSectionDecide: "Decision",
  gaReasonLabel: "Decision note",
  gaReasonPh: "Required when rejecting — without a reason they resubmit blindly, costing another review",
  gaApprove: "Approve",
  gaReject: "Reject",
  gaApproved: "Approved",
  gaRejected: "Rejected — the reason has been sent to the merchant",
  gaRejectedTag: "This item was rejected before",

  marketCN: "China",
  marketSG: "Singapore",

  stdNotice: "A standard product is the mould merchants build from: they search, pick one, and title/photos/specs fill themselves — only price and stock are left. The fuller this library, the less merchants type, and only then does cross-store comparison hold.",
  stdSearch: "Search no. / title / alias",
  stdFilterCategory: "Filter by category",
  stdFilterCategoryAll: "All categories",
  stdShowArchived: "Include archived",
  stdFilterSource: "By source",
  stdFilterSourceAll: "All sources",
  stdSourceOps: "Entered by ops",
  stdSourceOff: "Imported",
  stdColSource: "Source",
  stdPickAll: "Select all on this page",
  stdPickedN: "{n} selected (this page only)",
  stdPickClear: "Clear",
  stdBulkEnable: "Enable selected",
  stdBulkArchive: "Archive selected",
  stdBulkArchiveTitle: "Archive the {n} selected standard products?",
  stdToastBulk: "{n} changed",
  stdNew: "New standard product",
  stdEmpty: "No standard products yet — merchants will search and find nothing",
  stdColNo: "No.",
  stdColTitle: "Title",
  stdColCategory: "Category",
  stdColSpecs: "Specs (code / label)",
  stdColRefCount: "Used by",
  stdColArchivedAt: "Archived at",
  stdEdit: "Edit",
  stdConfirmArchiveTitle: "Archive {name}?",
  stdConfirmArchiveDesc: "Archiving only removes it from merchant search. Products already built from it stay on sale and editable — the number is a trace, not a foreign key.",
  stdConfirmArchiveOk: "Archive",
  stdDrawerNew: "New standard product",
  stdDrawerEdit: "Edit standard product",
  stdFieldTitle: "Title",
  stdTitlePh: "e.g. Local spinach",
  stdFieldCategory: "Category",
  stdCategoryPh: "Pick a category",
  stdCategoryHint: "Category decides the product type (fresh needs a cutoff, services do not ship). Merchants cannot change it after picking.",
  stdFieldSubtitle: "Subtitle",
  stdFieldKeywords: "Aliases",
  stdKeywordsPh: "Space separated, e.g. potato spud",
  stdKeywordsHint: "When the merchant's word does not match the title, they assume it is not here — and build their own, losing comparability right there.",
  stdFieldSpecs: "Spec groups",
  stdSpecsHint: "Every option needs a code. Without codes a standard product is no better than free text — it only makes people believe specs are unified.",
  stdGroupNamePh: "Dimension, e.g. Weight",
  stdOptionCodePh: "Code W1JIN",
  stdOptionLabelPh: "Label 1 jin",
  stdAddGroup: "+ Spec group",
  stdRemoveGroup: "Remove group",
  stdAddOption: "+ Option",
  stdRemoveOption: "Remove",
  stdToastSaved: "Standard product saved",
  stdToastArchived: "Archived",
  stdToastUnarchived: "Restored",
  toastApproved: "Approved — the product is live",
  toastRejected: "Rejected — the reason has been sent to the merchant",
  toastForcedOff: "Taken down",
  toastGoodsForcedOff: "Delisted and approval revoked; the reason went to the merchant",
  toastPresaleSaved: "Presale settings saved",
  toastCatArchived: "Category archived",

  catOnSale: " ({n} on sale)",
  detail: "Details",

  colSkuNo: "SKU code",
  colTitle: "Product",
  colMerchant: "Merchant",
  colCategory: "Category",
  colPricing: "Per-market pricing",
  priceMissing: "{m} has no price",
  priceFrom: "from {v}",
  colI18n: "Translations",
  i18nMissing: "Missing {langs}",
  i18nComplete: "Complete",
  colStock: "Stock",
  colSkuCount: "Variants",
  colStatus: "Status",
  colActions: "Actions",
  actionAudit: "Review",
  actionView: "View",

  colPresaleQuota: "Presale quota",
  colSold: "Sold",
  colCutoffAt: "Order cut-off",
  colArriveAt: "Arrival",
  actionEditPresale: "Edit settings",

  readOnlyWhat: "product review & takedown",
  readOnlyNote: "cannot approve, reject or take down",

  catTreeTitle: "Platform categories (2 levels)",
  catMoveUp: "↑",
  catMoveDown: "↓",
  catDragHint: "Drag to reorder (within the same level and parent only)",
  catBulkSelected: "{n} selected",
  catBulkOn: "Enable selected",
  catBulkOff: "Disable selected",
  catBulkClear: "Clear",
  catBulkOffTitle: "Disable the {n} selected sub-categories?",
  catBulkOffDesc: "Goods stay where they are — only the shopper-side entry is hidden. Ones with goods on sale are skipped.",
  catBulkOffOk: "Disable",
  catBulkDone: "{n} done, {m} skipped",
  catBulkNone: "Nothing to do: top levels are excluded, and ones with goods on sale need the goods moved first",
  catBulkTip: "Bulk applies to sub-categories only — a top level takes its whole group with it and is confirmed one at a time",
  catEnableParentTitle: "Parent “{name}” is disabled — enable it too?",
  catEnableParentDesc: "On its own it hangs under a disabled branch: merchants cannot pick it and it never shows on the buyer side.",
  catEnableParentOk: "Enable both",
  catEnableTopTitle: "Also enable the sub-categories under “{name}”?",
  catEnableTopDesc: "{n} are still disabled. Enabling only the parent leaves merchants an empty list.",
  catEnableTopOk: "Enable all",
  catDisableTopTitle: "Also disable the sub-categories under “{name}”?",
  catDisableTopDesc: "{n} are still enabled — they would keep showing up in search and topics.",
  catDisableTopOk: "Disable all",
  catOffBlockedGoods: "{n} products still sit in this category — move them first",
  catDisableImpactTitle: "Disable “{name}”",
  catDisableImpactDesc:
    "{n} products still sit in this category, {on} of them on sale. After disabling: merchants can still see and edit them, but listing will be blocked by the category check, and buyer-side filters and browsing will no longer match them. Move them to another category first?",
  catDisableImpactOk: "Disable anyway",
  catOffBlockedChild: "Sub-category “{name}” still holds {n} products — move them before disabling the whole branch",
  catI18nMissing: "no EN",
  catI18nMissingHint: "No English name — the English UI falls back to Chinese",
  catPreview: "Shopper preview",
  catPreviewDesc: "Rendered from the current configuration: enabled categories only, in the order shoppers see. It reads this page's data — it does not fetch the live site.",
  catPreviewLang: "Language",
  catPreviewZh: "Chinese",
  catPreviewEn: "English",
  catPreviewPane: "Category bar",
  catPreviewFallback: "falls back to Chinese",
  catPreviewEmptyGroup: "No enabled sub-categories — shoppers would land on an empty list",
  catColName: "Category",
  catColTemplate: "Form",
  catColGoods: "Products",
  catColOrder: "Order",
  catColStatus: "Enabled",
  catNoGateShort: "—",
  catGateNeed: "licence",
  catGateBroken: "code disabled",
  catSearchPh: "Search categories",
  catAllTemplates: "All forms",
  catShowOff: "Include disabled",
  catStat: "{a} top-level · {b} sub · {c} disabled",
  catNoChild: "No sub-categories yet",
  catSubCount: "{n}",
  catAddChild: "+ Add sub",
  catEnabled: "Enabled — merchants can pick it and it shows to shoppers",
  catDisabled: "Disabled — merchants cannot pick it; existing products are unaffected",
  catNew: "New category",
  catEdit: "Edit category",
  catSave: "Save",
  catSaved: "Category saved",
  catFormBasic: "Category",
  fieldCatName: "Name",
  fieldCatNameEn: "English name",
  fieldParent: "Parent",
  catParentNone: "None = create a top-level category",
  catTemplateInherited: "inherited from the parent, read-only",
  fieldRequiredCode: "Licence gate (permission code)",
  catNoGate: "No gate (anyone may sell)",
  catGateHint: "The code is what admission actually checks — the qualification text above is for humans. Only enabled codes are listed: a disabled one would refuse everybody, forever.",
  catCodeUnusable: "⚠ This code is disabled or missing — nobody can list here, and ops cannot grant it either",
  tplStandard: "Standard",
  tplFresh: "Fresh",
  tplService: "Service",
  tplVoucher: "Voucher",
  tplVirtual: "Virtual",
  loading: "Loading…",
  emptyTree: "No categories yet. The category tree is the skeleton products hang from; without it merchants cannot submit anything for review.",
  catDetailTitle: "Category details",
  catDetailHint: "Pick “Details” on any category at the left to see its template, required credentials and translated names.",
  fieldCatNo: "Category no.",
  fieldLevel: "Level",
  levelN: "Level {n}",
  fieldTemplate: "Attribute template",
  fieldQualification: "Required credentials",
  requiredCode: "Validation code: {code}",
  noQualification: "None required",
  fieldI18nName: "Translated names",
  i18nFallback: "Missing (falls back to Chinese)",
  fieldSkuCount: "Products on sale",
  confirmArchiveTitle: "Archive category {name}",
  confirmArchiveDesc:
    "Once archived the category disappears from the C-end tree; if it still has child categories or products on sale, the server rejects it.",
  confirmArchiveOk: "Archive",
  btnArchiveCat: "Archive this category",
  btnViewCatGoods: "View products in this category",

  searchSku: "Search SKU code / title / merchant",
  filterStatus: "Filter by status",
  filterStatusAll: "All statuses",
  filterMerchant: "Filter by merchant",
  filterMerchantAll: "All merchants",
  filterCategory: "Filter by category",
  filterCategoryAll: "All categories",
  emptySku: "No products match these filters. They appear here once merchants create and submit them in the B-end app.",

  kpiPresale: "Products on presale",
  kpiOversell: "Oversold products",
  kpiOversellSub: "Someone must choose: restock or refund",
  kpiOversellNone: "None oversold",
  kpiOversellQty: "Units oversold",
  stockNotice:
    "Overselling raises an alert but is never handled automatically: restocking versus refunding is a judgement call, and auto-cancelling would close group buys that could still have been fulfilled. The cut-off must come before the arrival time — otherwise orders keep coming in after the goods land, which guarantees overselling.",
  emptyStock: "No products on presale. Presale quotas and cut-off times for fresh produce are configured here.",

  btnReject: "Reject",
  btnConfirmReject: "Confirm reject",
  btnApprove: "Approve & publish",
  btnForceOff: "Take down",
  btnConfirmForceOff: "Confirm takedown",
  fieldGoodsAction: "Platform action (whole product)",
  btnForceOffGoods: "Take down the whole product",
  btnConfirmForceOffGoods: "Confirm takedown and revoke approval",
  forceOffGoodsHint: "Taking down the whole product revokes its approval: it returns to rejected and the merchant must fix it and resubmit — they cannot put it back themselves.",
  skuScopeWarn: "⚠️ Approve / reject / take down on a variant row applies to the WHOLE product, not just that variant — review decides whether the product may be sold, and title, photos, category and licences all live on the product.",
  fieldSkuList: "Variants",
  fieldCreatedAt: "Created at",
  fieldPricing: "Per-market pricing (B6: priced separately per market)",
  priceMissingBlocking: "No price — cannot publish",
  fieldI18nCopy: "Copy in three languages (P-3.2.5)",
  i18nFallbackLong: "Missing — Chinese is shown per the fallback rule",
  fieldRejectReason: "Rejection reason",
  fieldForceOffReason: "Takedown reason",
  fieldGoodsForceOffReason: "Reason for revoking approval (the merchant sees it verbatim)",
  reasonPlaceholder: "The merchant sees this verbatim: say what breaks the rules and how to fix it",
  fieldHandledReason: "Reason recorded",

  presaleTitle: "Presale settings",
  save: "Save",
  fieldQuota: "Presale quota",
  quotaHint: "0 means no presale — only stock on hand is sold.",
  fieldCutoff: "Order cut-off (ISO)",
  cutoffHint: "Must be before the arrival time, otherwise orders keep coming in after the goods land.",
  fieldArrive: "Arrival time (ISO)",
  arriveHint: "Leave blank to keep the current value. It is what the cut-off is checked against — without it that check has nothing to compare.",

  slNoticeCommon:
    "Universal specs: the meaning of a value is the same across categories — black on a pan and black on a phone are the same black. Changing one here affects every category bound to it, which means every merchant's product form. Every value of a quantitative dimension needs a normalised number, without which sorting puts 1kg before 500g.",
  slNoticeSpecial:
    "Dedicated specs: the values only make sense inside one category — “stage” only for baby food, “rooms” only for housekeeping. They are usually bound to a single category, so the blast radius is small, but they still must not clash with a universal dimension's name.",
  slSearch: "Search dimension name / code",
  slNewDim: "New dimension",
  slEditDim: "Edit dimension",
  slColName: "Dimension",
  slColType: "Value type",
  slColInUse: "Categories using it",
  slColValues: "Values",
  slAddValue: "+ Value",
  slEditValue: "Edit value",
  slEnum: "Enum",
  slQuant: "Numeric",
  slSale: "Sales spec (into SKU)",
  slProp: "Attribute (no SKU)",
  slPromote: "Promote to platform",
  slPromoteHint: "Only the ownership changes — the id stays, so products already built on it need no rework",
  slPromoted: "Promoted to a platform value",
  slEmpty: "No dimensions yet. Merchants get no suggested specs and must type everything freely.",
  slFieldName: "Name",
  slNameHint: "A common noun, two to four characters. Catch-all words are rejected — they say nothing, and a spec group called “spec” still leaves the merchant guessing",
  slFieldCode: "Code",
  slCodeHint: "Value ids and optionCode are prefixed with it. Once set it should not change — changing a code swaps the aggregation axis and past products stop grouping",
  slValueCodeHint: "Unique inside the dimension. Still called optionCode on the wire",
  slFieldValueType: "Value type",
  slValueTypeHint: "Numeric values need a normalised number (500g / half a jin / 0.5kg are all 500); sorting and same-spec price comparison depend on it",
  slFieldUnit: "Unit",
  slUnitHint: "The normalised base unit: g for weight, ml for volume, m for length, cm for diameter, minutes for duration",
  slFieldUsage: "Usage",
  slUsageHint: "A sales spec enters the SKU matrix (each combination has its own price and stock); an attribute has one value per product. Material, origin and shelf life are usually the latter — putting them in spec groups explodes the combination count",
  slFieldLabel: "Label",
  slLabelHint: "What merchants and buyers see. Changing it does not affect existing products — those store a snapshot",
  slFieldNumeric: "Normalised value",
  slNumericHint: "The number after converting to the base unit. One jin is 500, two jin is 1000 — no unit needed, it follows the dimension",
  slFieldAliases: "Aliases",
  slAliasesHint: "Space or comma separated. Merchant input matching an alias resolves to this value instead of creating a new one",
  slFieldSort: "Sort",

  csEditTitle: "Configure specs for “{name}”",
  csPickDims: "Available",
  csSectionSale: "Variants",
  csSectionSaleHint: "Buyers pick one; each is priced and stocked separately. The first one is primary and is applied automatically when creating a product.",
  csSectionProp: "Details",
  csSectionPropHint: "Shown to buyers only — no SKUs, no effect on price or stock. No primary, and order does not matter.",
  csPickSale: "Add a variant dimension",
  csPickProp: "Add a detail",
  csPicked: "Dimensions",
  csSetPrimary: "Make primary",
  csUnbind: "Remove",
  csPickValues: "Values",
  fieldCatNameEnHint: "Empty → English UI shows the Chinese name",
  csCopyFromPh: "Copy from…",
  csCopyDo: "Copy",
  catColSpecs: "Specs",
  catSpecsNone: "Set up",
  catSpecsGo: "Configure specs for “{name}”",
  csValsRest: "Not selected",
  csValsAllHint: "All available",
  csValMoveL: "Earlier",
  csValMoveR: "Later",
  csValDrop: "Remove",
  csRenameHint: "Double-click to rename",
  csRenamePrompt: "Show “{label}” inside “{cat}” as:",
  csEditOk: "Save bindings",
  csEdit: "Configure",

  cpmTitle: "Categories × payment mode",
  cpmNotice: "Layer ① of the four that decide whether an order can be paid on site (category → licence → store → product); all four are intersected, so any one of them saying no is a no. ⚠️ This table is a deny list: no row means allowed, a row means blocked — an empty table is normal, not a gap. The licence layer is the one doing the work in phase one.",
  cpmSummary: "{blocked} blocked of {total} categories",
  cpmColCategory: "Level-2 category",
  cpmColOffline: "Pay on site",
  cpmAllowed: "Allowed",
  cpmBlocked: "Blocked",
  cpmBlock: "Block",
  cpmAllow: "Allow",
  cpmEmpty: "No categories",
  cptTitle: "Categories × points",
  cptNotice: "Points rules are set by the platform per category; merchants do not configure them — measured: of 199 live products, 0 had a product-level points rule. Categories without a rule fall back to a single platform number shared by every category, which cannot be right for both groceries and appliances. So an empty row here is a gap.",
  cptSummary: "{n} configured of {total} categories",
  cptColCategory: "Level-2 category",
  cptColRule: "Earning rule",
  cptNone: "Not set",
  cptEdit: "Configure",
  cptSave: "Save",
  cptClear: "Clear",
  cptRatio: "Percentage",
  cptFixed: "Fixed",
  cptRatioText: "{v}% of order value",
  cptFixedText: "{v} points per order",
  cptEmpty: "No categories",
  csTitle: "Categories × specs",
  csNotice:
    "What a merchant can pick when creating a product comes from this table. Categories with nothing configured are flagged — merchants there can only type freely, and free text has no option code, so “500g”, “half a jin” and “0.5kg” never group together. The primary dimension is the one pre-filled once a category is chosen.",
  csColCategory: "Category",
  csColType: "Type",
  csColDims: "Specs",
  csColDetail: "Dimensions & values",
  csPrimary: "Primary",
  csUniversal: "Universal",
  csDedicated: "Dedicated",
  csProp: "Attribute",
  csNone: "Not configured",
  csExpand: "Show values",
  csCollapse: "Hide",
  csSummary: "{total} live categories · {configured} configured · {gap} still empty",
  csEmpty: "No category has specs bound yet.",

  tplNotice:
    "Platform templates are what makes specs comparable across shops: merchants pick one when creating a product, and the option code decides whether “5 jin”, “five jin” and “2.5kg” group together. Archiving is not deleting — past products still need the template to explain the codes they used.",
  tplSearch: "Search name / template no. / option code",
  tplFilterCategory: "Filter by category type",
  tplFilterCategoryAll: "All category types",
  tplShowArchived: "Include archived",
  tplColNo: "Template no.",
  tplColName: "Spec dimension",
  tplColCategory: "Category type",
  tplCategoryAny: "Any category",
  tplColOptions: "Options (code · label)",
  tplColArchivedAt: "Archived at",
  tplColStatus: "Status",
  tplStatusActive: "Active",
  tplStatusArchived: "Archived",
  tplEmpty: "No platform templates yet. Merchants have nothing to pick and must type specs freely — and free text does not group across shops.",
  tplNew: "New template",
  tplEdit: "Edit",
  tplArchive: "Archive",
  tplUnarchive: "Restore",
  tplConfirmArchiveTitle: "Archive template {name}",
  tplConfirmArchiveDesc: "Merchants stop seeing it when creating products. Products that already use it are unaffected — archiving is not deleting.",
  tplConfirmArchiveOk: "Archive",
  tplDrawerNew: "New platform template",
  tplDrawerEdit: "Edit platform template",
  tplFieldName: "Spec dimension",
  tplNamePh: "e.g. Weight, Scent",
  tplFieldCategory: "Category type",
  tplFieldOptions: "Options",
  tplOptionsHint: "Every option needs an option code — without one a platform template is no different from what a merchant types by hand.",
  tplOptionCodePh: "Code, e.g. W_500G",
  tplOptionLabelPh: "Label, e.g. 500g",
  tplAddOption: "Add an option",
  tplRemoveOption: "Remove",
  toastTplSaved: "Template saved — merchants can pick it right away",
  toastTplArchived: "Archived — merchants no longer see it",
  toastTplUnarchived: "Template restored",
  topicNotice: "A topic answers “what goes on the home page this week”. It is neither a category (what the goods are and what licences they need) nor a campaign (what the discount is). Grouping is not discounting.",
  topicNew: "New topic",
  topicEdit: "Edit",
  topicPick: "Pick products",
  topicArchive: "Archive",
  topicUnarchive: "Unarchive",
  topicArchived: "Archived",
  topicActive: "Live",
  topicColTitle: "Topic",
  topicColSubtitle: "Subtitle",
  topicColSort: "Order",
  topicColRange: "Window",
  topicColGoods: "Products",
  topicColStatus: "Status",
  topicAlways: "Always on",
  topicEmpty: "Empty",
  topicGoodsCount: "{n} items",
  topicSectionBasic: "Basics",
  topicSectionGoods: "Products in this topic",
  topicStart: "Starts",
  topicEnd: "Ends",
  topicRangeHint: "Both ends may be left blank — blank means always on. A made-up end date makes the topic vanish one day.",
  topicSave: "Save",
  topicSaved: "Saved",
  topicPickTitle: "{name} · pick products",
  topicPickNotice: "Only products on sale are listed. Adding a delisted or pending one leaves a blank slot for shoppers while this page still shows it in the topic.",
  topicPicked: "{n} selected",
  topicPoolEmpty: "No products on sale to pick",
  topicSaveGoods: "Save products",
  topicGoodsSaved: "Topic products updated",
  topicLoadFailed: "Could not load the current selection — saving will replace it with what you ticked",

};

export const PRODUCTS_COPY: PageCopy<typeof zh> = { zh, en };

/** 拆出去的 tab 组件靠它接文案。 */
export type ProductsCopy = typeof zh;
