// 进销存文案（矩阵 P-18）。**独立模块**：不并进 products/copy.ts ——
// 那份是电商侧商品与类目的文案，两边合起来只会让「这条属于谁」再也说不清。
import type { PageCopy } from "@/lib/use-copy";

const zh = {
  invReadOnly: "库存只读。运营改了商家的数，「这个数是谁改的」就多了一个答案，而商家不会知道——要改让商家自己改，或走工单留痕。",
  invHealthNotice: "这三类商品正在给买家制造失败的下单：点进去、加购、然后发现买不了。每一条都能定位到商家与门店。",
  invHealthAll: "全部",
  invHealthNegative: "负库存",
  invHealthZeroOnSale: "零库存仍在架",
  invHealthStale: "90 天未动销",
  invColMerchant: "商家",
  invColItem: "商品",
  invColOnHand: "实存",
  invColReserved: "预留",
  invColAvailable: "可用",
  invColIdle: "闲置",
  invIdleDays: "{n} 天",
  invHealthEmpty: "没有不健康的库存——这一页空着是好事。",
  invLedgerNotice: "商家库存的变动明细，只读。客服回答「我的货怎么少了」时的依据。",
  invColTime: "时间",
  invColDoc: "单据",
  invColReason: "原因",
  invColDelta: "变动",
  invColAfter: "变动后",
  invColOperator: "操作人",
  invLedgerOwnerPh: "商家编号（必填）",
  invLedgerPickOwner: "先填一个商家编号——台账是「看某一个商家」的东西。",
  invLedgerItemPh: "商品 / SKU 编号",
  invLedgerSearch: "查询",
  // 原因码的中文名。**枚举取自建表注释**（inv_inbound_order.source_type /
  // inv_outbound_order.purpose）—— 台账的 reason_code 是这两者的快照。
  // 认不出的码原样显示，不显示空白：后端加了新码时「看得懂但没翻译」远好过「这一格是空的」。
  invReasonPURCHASE: "采购入库",
  invReasonRETURN: "退货入库",
  invReasonTRANSFER_IN: "调拨入",
  invReasonCOUNT_GAIN: "盘盈",
  invReasonSALE: "销售出库",
  invReasonTRANSFER_OUT: "调拨出",
  invReasonSCRAP: "报损",
  invReasonCOUNT_LOSS: "盘亏",
  invReasonINTERNAL: "领用",
  invReasonOTHER: "其他",
  invLedgerMore: "再读一页",
  invLedgerEnd: "到底了",
  invLedgerEmpty: "还没有变动记录。",
  invReconTitle: "库存对差",
  invReconNotice: "平台侧与进销存侧逐条比。这是切换真相源的唯一判据：连续为零才准切——直接切等于切换那天开始超卖，而无从回溯是从哪一刻起的。",
  invReconClean: "干净",
  invReconDirty: "有差异，不得切换",
  invReconScanned: "扫描 SKU",
  invReconSkipped: "已搬过",
  invReconDiffs: "差异条数",
  invColSku: "SKU",
  invColPlatform: "平台侧",
  invColInventory: "进销存侧",
  invColGap: "差",
  invReconNoDiff: "逐条比过，没有差异。",
  invReconHowTo: "差异只有三种来源，按可能性排：① 某条写库存的路径没经过 StockPort（平台侧还有几处直接改数）② 搬运那一刻正好有单在扣，重查一次会自己好 ③ 真有 bug。",
};

const en: typeof zh = {
  invReadOnly: "Read-only. If ops can change a merchant's numbers, \"who changed this\" gains a second answer the merchant never sees — let the merchant change it, or go through a ticket.",
  invHealthNotice: "These three kinds are actively producing failed orders: a buyer taps in, adds to cart, then finds they cannot buy. Every row points at a merchant and a store.",
  invHealthAll: "All",
  invHealthNegative: "Negative",
  invHealthZeroOnSale: "Zero but listed",
  invHealthStale: "Idle 90 days",
  invColMerchant: "Merchant",
  invColItem: "Item",
  invColOnHand: "On hand",
  invColReserved: "Reserved",
  invColAvailable: "Available",
  invColIdle: "Idle",
  invIdleDays: "{n} d",
  invHealthEmpty: "Nothing unhealthy — an empty page is the good outcome here.",
  invLedgerNotice: "A merchant's stock movements, read-only. What support reads when asked \"where did my stock go\".",
  invColTime: "Time",
  invColDoc: "Document",
  invColReason: "Reason",
  invColDelta: "Change",
  invColAfter: "After",
  invColOperator: "By",
  invLedgerOwnerPh: "Merchant no. (required)",
  invLedgerPickOwner: "Enter a merchant number first — a ledger is always about one merchant.",
  invLedgerItemPh: "Item / SKU no.",
  invLedgerSearch: "Search",
  invReasonPURCHASE: "Purchase in",
  invReasonRETURN: "Return in",
  invReasonTRANSFER_IN: "Transfer in",
  invReasonCOUNT_GAIN: "Count gain",
  invReasonSALE: "Sale out",
  invReasonTRANSFER_OUT: "Transfer out",
  invReasonSCRAP: "Scrap",
  invReasonCOUNT_LOSS: "Count loss",
  invReasonINTERNAL: "Internal use",
  invReasonOTHER: "Other",
  invLedgerMore: "Load more",
  invLedgerEnd: "End of list",
  invLedgerEmpty: "No movements yet.",
  invReconTitle: "Stock reconciliation",
  invReconNotice: "Platform side versus inventory side, row by row. This is the only gate for switching the source of truth: it must read clean for N consecutive days — switching blind means overselling from that day on, with no way back to when it started.",
  invReconClean: "Clean",
  invReconDirty: "Differences — do not switch",
  invReconScanned: "SKUs scanned",
  invReconSkipped: "Already migrated",
  invReconDiffs: "Differences",
  invColSku: "SKU",
  invColPlatform: "Platform",
  invColInventory: "Inventory",
  invColGap: "Gap",
  invReconNoDiff: "Compared row by row — no differences.",
  invReconHowTo: "A difference has three possible causes, most likely first: (1) some write path bypassed StockPort — a few platform services still set stock directly; (2) an order was deducting at the moment of migration, re-check and it clears itself; (3) a real bug.",
};

export const INVENTORY_COPY: PageCopy<typeof zh> = { zh, en };

/** 拆出去的 tab 组件靠它接文案。 */
export type InventoryCopy = typeof zh;
