// 进销存文案（矩阵 P-18）。**独立模块**：不并进 products/copy.ts ——
// 那份是电商侧商品与类目的文案，两边合起来只会让「这条属于谁」再也说不清。
import type { PageCopy } from "@/lib/use-copy";

const zh = {
  invReadOnly: "库存只读。运营改了商家的数，「这个数是谁改的」就多了一个答案，而商家不会知道——要改让商家自己改，或走工单留痕。",
  invHealthNotice: "这三类商品正在给买家制造失败的下单：点进去、加购、然后发现买不了。每一条都能定位到商家与门店。",
  invHealthAll: "全部",
  invHealthNegative: "负库存",
  invHealthZeroOnSale: "零库存仍在架",
  invHealthStale: "90 天未动销",
  invColMerchant: "商家",
  invColItem: "商品",
  invColOnHand: "实存",
  invColReserved: "预留",
  invColAvailable: "可用",
  invColIdle: "闲置",
  invIdleDays: "{n} 天",
  invHealthEmpty: "没有不健康的库存——这一页空着是好事。",
  invBalancesEmpty: "这家店没有要处理的库存。",
  invFlagShortage: "缺货",
  invFlagStale: "滞销",
  invLedgerNotice: "商家库存的变动明细，只读。客服回答「我的货怎么少了」时的依据。",
  invColTime: "时间",
  invColDoc: "单据",
  invColReason: "原因",
  invColDelta: "变动",
  invColAfter: "变动后",
  invColOperator: "操作人",
  invLedgerOwnerPh: "商家编号（必填）",
  invLedgerPickOwner: "先填一个商家编号——台账是「看某一个商家」的东西。",
  invLedgerItemPh: "商品 / SKU 编号",
  invLedgerSearch: "查询",
  // 原因码的中文名。**枚举取自建表注释**（inv_inbound_order.source_type /
  // inv_outbound_order.purpose）—— 台账的 reason_code 是这两者的快照。
  // 认不出的码原样显示，不显示空白：后端加了新码时「看得懂但没翻译」远好过「这一格是空的」。
  invReasonPURCHASE: "采购入库",
  invReasonRETURN: "退货入库",
  invReasonTRANSFER_IN: "调拨入",
  invReasonCOUNT_GAIN: "盘盈",
  invReasonSALE: "销售出库",
  invReasonTRANSFER_OUT: "调拨出",
  invReasonSCRAP: "报损",
  invReasonCOUNT_LOSS: "盘亏",
  invReasonINTERNAL: "领用",
  invReasonOTHER: "其他",
  invLedgerMore: "再读一页",
  invLedgerEnd: "到底了",
  invLedgerEmpty: "还没有变动记录。",
  invReconTitle: "库存对差",
  invReconNotice: "平台侧与进销存侧逐条比。这是切换真相源的唯一判据：连续为零才准切——直接切等于切换那天开始超卖，而无从回溯是从哪一刻起的。",
  invReconClean: "干净",
  invReconDirty: "有差异，不得切换",
  invReconScanned: "扫描 SKU",
  invReconPending: "待搬",
  invReconPendingHint: "还有没搬过来的 SKU。它们在进销存侧余额是 0——现在切真相源，这些货当天全都卖不了。等搬运作业把它扫到 0 再说。",
  invReconSkipped: "已搬过",
  invReconDiffs: "差异条数",
  invColSku: "SKU",
  invColPlatform: "平台侧",
  invColInventory: "进销存侧",
  invColHeld: "预留 平台/进销存",
  invColGap: "差",
  invReconNoDiff: "逐条比过，没有差异。",
  invReconHeldHint: "预留对不上同样会超卖：实存一样、而平台占着 5 件进销存没占，切过去那 5 件就重新可售了。搬运要连在途的锁一起搬。",
  invCredNotice: "这是本模块唯一的写口，而它改的不是货、是「谁能读这些货」。对方换了对接商或密钥泄露，处置只能在这儿。",
  invCredEntity: "商家编号",
  invCredEntityPh: "先填商家编号，再看它发过哪些钥匙",
  invCredIssue: "签发新钥匙",
  invCredName: "给了谁",
  invCredNamePh: "某某 ERP（生产）",
  invCredScopes: "能做什么",
  invCredScopeRead: "读库存与流水",
  invCredScopeSync: "回写库存",
  invCredExpires: "有效期至",
  invCredExpiresHint: "留空 = 不过期。长期对接也建议给个期限——一把永不过期的钥匙，泄露了就没有自然终点。",
  invColKey: "App Key",
  invColScopes: "范围",
  invColStatus: "状态",
  invColLastUsed: "最近使用",
  invColExpires: "有效期",
  invCredActive: "在用",
  invCredRevoked: "已吊销",
  invCredNever: "从未使用",
  invCredNoExpiry: "不过期",
  invCredRevoke: "吊销",
  invCredRevokeTitle: "吊销这把钥匙？",
  invCredRevokeBody: "对方会立刻调不通。吊销不删记录——「什么时候停的」要查得到。要恢复只能重新签发一把新的。",
  invCredEmpty: "这家店还没有发过开放对接的钥匙。",
  invCredIssuedTitle: "钥匙已签发",
  invCredSecretOnce: "下面这串 Secret 只出现这一次。关掉这个框之后库里只剩哈希，任何地方都拿不回来——丢了只能吊销重发。",
  invCredCopy: "复制",
  invCredCopied: "已复制",
  invCredDone: "我已经存好了",
  invReconHowTo: "差异只有三种来源，按可能性排：① 某条写库存的路径没经过 StockPort（平台侧还有几处直接改数）② 搬运那一刻正好有单在扣，重查一次会自己好 ③ 真有 bug。",

  // ── 链路健康（M3）────────────────────────────────────────────────────
  lhHelpTitle: "这一页和「库存对差」有什么不同",
  lhHelp:
    "对差读的是「数据」（账上有多少、实际有多少），这一页读的是「链路」（事件投出去了没有）。"
    + "2026-09-02 投递任务停着，一条建品事件躺了六个小时 —— 那件货在库存里不存在，"
    + "商家看不到、盘不着、进不了货，而任何地方都不会报错；它当时的唯一痕迹是对差页上的「待搬 1 个」。"
    + "积压里混着两种东西：「没人碰过」（投递任务没在跑）和「一直在失败」（消费者在抛异常），"
    + "两者该找的人不同，而条数看不出区别。",
  lhChanToInv: "平台 → 进销存",
  lhChanToPlatform: "进销存 → 平台",
  lhOk: "通畅",
  lhBacklog: "处理中",
  lhStalled: "投递没在跑",
  lhFailing: "消费者报错",
  lhPending: "积压",
  lhNeverTried: "没人碰过",
  lhNeverTriedHint: "（投递停了）",
  lhRetrying: "反复失败",
  lhRetryingHint: "（消费者报错）",
  // 最老一条才是判据：积压 1 条可能只是正在处理的那一瞬
  lhOldest: "最老一条",
  lhLastSent: "最近成功",
  lhNeverSent: "从没成功过",
  lhMaxRetry: "最大重试",
  lhLastError: "最近一条错误",
  lhLoadFailed: "链路状态取不到 —— 这不等于链路正常，先报障",

  // ── 补投影与存疑打标（M2）─────────────────────────────────────────────
  invRepair: "补投影",
  // 两步：先试算再确认。一步到位的话，第一个点它的人就已经写了库
  invRepairTitle: "把 {n} 条账外 SKU 搬进进销存？",
  invRepairDesc: "这些货在平台侧有账、在进销存里没有 —— 商家看不到、盘不着、进不了货。搬过去的数就是平台侧那个数，落成一张 INIT 单据，不会凭空造出库存。刚才已经试算过一遍，这一步才真写。",
  invRepairConfirm: "确认搬运",
  invRepairNothing: "没有待搬的 —— 投影是齐的",
  invRepairDone: "已搬 {n} 条",
  invColAction: "动作",
  invDoubt: "标记存疑",
  invDoubtTitle: "把 {name} 的库存标记为存疑？",
  // 明说它不做什么：一个「悄悄降权」的标记比下架更糟 —— 商家看不到、也申诉不了
  invDoubtDesc: "记进这家商家的信用档案，运营与商家的对接人都看得到，可申诉。「它不会下架、不会封店、也不会影响曝光」 —— 平台今天没有曝光权重这套机制。要让商家知道该改什么，配合「链条画像」里的提醒一起用。",
  invDoubtConfirm: "记录存疑",
  invDoubtDone: "已记入信用档案",

  // ── 单商家进销存概况（M5）─────────────────────────────────────────────
  // 「没搬进来」与「搬了但一笔没记」在下面那张表上都是一片空白，要分开说
  invDigestNoOwner: "{no} 还没有搬进进销存 —— 这不是「没记账」，是这家在进销存里压根不存在。去「链路健康」看投影是不是断了。",
  invDigestItems: "建账",
  invDigestLedger: "流水",
  invDigestLast: "最近一笔",
  invDigestNever: "从没记过",
  invDigestShortage: "低于安全库存",
  invDigestStale: "长期未动销",
  invDigestNeverUsed: "建了账，一笔没记",
};

const en: typeof zh = {
  invReadOnly: "Read-only. If ops can change a merchant's numbers, \"who changed this\" gains a second answer the merchant never sees — let the merchant change it, or go through a ticket.",
  invHealthNotice: "These three kinds are actively producing failed orders: a buyer taps in, adds to cart, then finds they cannot buy. Every row points at a merchant and a store.",
  invHealthAll: "All",
  invHealthNegative: "Negative",
  invHealthZeroOnSale: "Zero but listed",
  invHealthStale: "Idle 90 days",
  invColMerchant: "Merchant",
  invColItem: "Item",
  invColOnHand: "On hand",
  invColReserved: "Reserved",
  invColAvailable: "Available",
  invColIdle: "Idle",
  invIdleDays: "{n} d",
  invHealthEmpty: "Nothing unhealthy — an empty page is the good outcome here.",
  invBalancesEmpty: "Nothing needs action at this merchant.",
  invFlagShortage: "Out of stock",
  invFlagStale: "Idle",
  invLedgerNotice: "A merchant's stock movements, read-only. What support reads when asked \"where did my stock go\".",
  invColTime: "Time",
  invColDoc: "Document",
  invColReason: "Reason",
  invColDelta: "Change",
  invColAfter: "After",
  invColOperator: "By",
  invLedgerOwnerPh: "Merchant no. (required)",
  invLedgerPickOwner: "Enter a merchant number first — a ledger is always about one merchant.",
  invLedgerItemPh: "Item / SKU no.",
  invLedgerSearch: "Search",
  invReasonPURCHASE: "Purchase in",
  invReasonRETURN: "Return in",
  invReasonTRANSFER_IN: "Transfer in",
  invReasonCOUNT_GAIN: "Count gain",
  invReasonSALE: "Sale out",
  invReasonTRANSFER_OUT: "Transfer out",
  invReasonSCRAP: "Scrap",
  invReasonCOUNT_LOSS: "Count loss",
  invReasonINTERNAL: "Internal use",
  invReasonOTHER: "Other",
  invLedgerMore: "Load more",
  invLedgerEnd: "End of list",
  invLedgerEmpty: "No movements yet.",
  invReconTitle: "Stock reconciliation",
  invReconNotice: "Platform side versus inventory side, row by row. This is the only gate for switching the source of truth: it must read clean for N consecutive days — switching blind means overselling from that day on, with no way back to when it started.",
  invReconClean: "Clean",
  invReconDirty: "Differences — do not switch",
  invReconScanned: "SKUs scanned",
  invReconPending: "Pending",
  invReconPendingHint: "Some SKUs have not been migrated yet. On the inventory side their balance is zero — switching the source of truth now makes those goods unbuyable that same day. Wait until the backfill drives this to zero.",
  invReconSkipped: "Already migrated",
  invReconDiffs: "Differences",
  invColSku: "SKU",
  invColPlatform: "Platform",
  invColInventory: "Inventory",
  invColHeld: "Held plat/inv",
  invColGap: "Gap",
  invReconNoDiff: "Compared row by row — no differences.",
  invReconHeldHint: "A held-quantity mismatch oversells just the same: same on-hand, but the platform holds 5 units the inventory side does not — switch now and those 5 go back on sale. The backfill has to migrate in-flight locks too.",
  invReconHowTo: "A difference has three possible causes, most likely first: (1) some write path bypassed StockPort — a few platform services still set stock directly; (2) an order was deducting at the moment of migration, re-check and it clears itself; (3) a real bug.",
  invCredNotice: "The one write endpoint in this module — and it changes who may read the stock, not the stock itself. If they switch integrators or a secret leaks, this is the only place to act.",
  invCredEntity: "Merchant no.",
  invCredEntityPh: "Enter a merchant number to see its keys",
  invCredIssue: "Issue a key",
  invCredName: "Issued to",
  invCredNamePh: "Acme ERP (production)",
  invCredScopes: "Can do",
  invCredScopeRead: "Read stock and ledger",
  invCredScopeSync: "Write stock back",
  invCredExpires: "Expires",
  invCredExpiresHint: "Blank = never. Give even long-lived integrations an end date — a key that never expires has no natural end once it leaks.",
  invColKey: "App key",
  invColScopes: "Scopes",
  invColStatus: "Status",
  invColLastUsed: "Last used",
  invColExpires: "Expires",
  invCredActive: "Active",
  invCredRevoked: "Revoked",
  invCredNever: "Never used",
  invCredNoExpiry: "Never expires",
  invCredRevoke: "Revoke",
  invCredRevokeTitle: "Revoke this key?",
  invCredRevokeBody: "Their calls stop working immediately. Revoking keeps the row — \"when was it stopped\" must stay answerable. To restore access, issue a new key.",
  invCredEmpty: "No open-API keys issued for this merchant yet.",
  invCredIssuedTitle: "Key issued",
  invCredSecretOnce: "This secret appears once. After you close this dialog only the hash remains — nowhere can it be recovered. Lose it and the only path is revoke and reissue.",
  invCredCopy: "Copy",
  invCredCopied: "Copied",
  invCredDone: "I have saved it",

  lhHelpTitle: "How this differs from reconciliation",
  lhHelp:
    "Reconciliation reads the data (booked vs actual). This page reads the link "
    + "(did the event get delivered). On 2026-09-02 the dispatcher was off and one listing event "
    + "sat for six hours — the item did not exist in inventory, the merchant could not see it, "
    + "count it or receive stock against it, and nothing anywhere raised an error. "
    + "A backlog holds two different things: never touched (dispatcher not running) and "
    + "failing repeatedly (consumer throwing). They need different people, and a count cannot tell them apart.",
  lhChanToInv: "Platform → Inventory",
  lhChanToPlatform: "Inventory → Platform",
  lhOk: "Clear",
  lhBacklog: "In flight",
  lhStalled: "Dispatcher stopped",
  lhFailing: "Consumer erroring",
  lhPending: "Backlog",
  lhNeverTried: "Never touched",
  lhNeverTriedHint: "(dispatcher off)",
  lhRetrying: "Failing",
  lhRetryingHint: "(consumer erroring)",
  lhOldest: "Oldest entry",
  lhLastSent: "Last success",
  lhNeverSent: "Never succeeded",
  lhMaxRetry: "Max retries",
  lhLastError: "Latest error",
  lhLoadFailed: "Cannot read link state — that is not the same as healthy. Report it.",

  invRepair: "Backfill",
  invRepairTitle: "Move {n} unbooked SKUs into inventory?",
  invRepairDesc: "These exist on the platform but have no inventory account — the merchant cannot see them, count them, or receive stock against them. The quantity moved is the platform's own, written as one INIT document; nothing is invented. The dry run has already happened; this step writes.",
  invRepairConfirm: "Move them",
  invRepairNothing: "Nothing to move — the projection is complete",
  invRepairDone: "Moved {n}",
  invColAction: "Action",
  invDoubt: "Flag stock",
  invDoubtTitle: "Flag stock for {name} as doubtful?",
  invDoubtDesc: "Recorded in this merchant's credit file, visible to ops and to the merchant's account manager, and appealable. It does not delist, suspend, or affect exposure — the platform has no exposure-weighting mechanism today. Pair it with a nudge from the chain profile so the merchant knows what to fix.",
  invDoubtConfirm: "Record it",
  invDoubtDone: "Recorded in the credit file",

  invDigestNoOwner: "{no} has never been projected into inventory — this is not \"no entries\", the merchant does not exist there at all. Check Link health for a broken projection.",
  invDigestItems: "Booked",
  invDigestLedger: "Entries",
  invDigestLast: "Last entry",
  invDigestNever: "Never",
  invDigestShortage: "Below safety",
  invDigestStale: "Stale",
  invDigestNeverUsed: "Booked, never used",
};

export const INVENTORY_COPY: PageCopy<typeof zh> = { zh, en };

/** 拆出去的 tab 组件靠它接文案。 */
export type InventoryCopy = typeof zh;
