// 履约调度文案（矩阵 P-5.1 / P-5.2）。
import type { PageCopy } from "@/lib/use-copy";

const zh = {
  tabBatches: "到货批次",
  none: "—",
  tabExpress: "快递与轨迹",
  tabCarrier: "第三方运力配置",
  carrierNotice: "这一页配错的后果不是显示不对，而是订单发不出去：没配密钥的启用后下单会当场失败、还有在途单的停用会让轨迹拉不回来、全停之后快递单无处可下。所以不能点的按钮旁边直接写了原因，不用点一次才知道。",
  colPriority: "优先级",
  colCarrierName: "运力",
  colAccount: "接入账号",
  colApiKey: "接入密钥",
  colCutoff: "每日截单",
  colSla: "承诺时效",
  colInFlight: "在途单",
  colCarrierStatus: "状态",
  colCarrierUpdatedAt: "最近修改",
  keyReady: "已配置",
  keyMissing: "未配置",
  slaHoursValue: "{n} 小时",
  inFlightCount: "{n} 单",
  carrierOn: "已启用",
  carrierOff: "已停用",
  actionEditCarrier: "编辑",
  actionCarrierOn: "启用",
  actionCarrierOff: "停用",
  gateNoKey: "未配密钥，启用后下单会失败",
  gateInFlight: "还有 {n} 个在途单",
  gateLastOne: "最后一家启用的运力",
  emptyCarrier: "还没有接入任何第三方运力。至少要接一家并启用，走快递履约的订单才发得出去。",
  editCarrierTitle: "配置 {name}",
  secCarrierBasic: "接入参数",
  secApiKey: "接入密钥",
  cutoffHint: "格式 HH:mm。过了这个点的单顺延到次日揽收。",
  priorityHint: "优先级数字越小越优先，且不能与别家重复 —— 同优先级时选哪家将取决于顺序，那是隐性行为。",
  apiKeyHint: "密钥不在运营端配置，也不在契约里出现（哪怕是脱敏的）。它由运维在服务端配好后，这里只显示配没配。",
  btnSaveCarrier: "保存配置",
  toastCarrierSaved: "运力配置已保存",
  toastCarrierOn: "已启用该运力",
  toastCarrierOff: "已停用该运力",
  carrierReadOnlyWhat: "第三方运力配置",
  tabFreight: "运费模板与超区",
  expressNotice: "轨迹来自承运商，平台不编 —— 页面上没有「手工加一条轨迹」，那样写出来的轨迹一旦与承运商记录不一致，纠纷时反而站不住。运营在这里能做的只有换运单号。",
  searchShipment: "搜快递单号 / 订单号 / 运单号 / 收件人",
  filterCarrier: "按承运商筛选",
  filterCarrierAll: "全部承运商",
  filterShipStatus: "按快递状态筛选",
  filterShipStatusAll: "全部快递状态",
  carrierSf: "顺丰",
  carrierJd: "京东",
  carrierYto: "圆通",
  shipCreated: "已下单",
  shipPickedUp: "已揽收",
  shipInTransit: "运输中",
  shipDelivered: "已签收",
  shipException: "疑难件",
  colShipmentNo: "快递单号",
  colOrderNo: "订单号",
  colCarrier: "承运商",
  colWaybill: "运单号",
  colShipStatus: "快递状态",
  colReceiver: "收件人",
  colRegion: "收件地区",
  colUpdatedAt: "最新轨迹时间",
  actionTrace: "查看轨迹",
  emptyShipment: "没有符合条件的快递单。只有走快递履约的订单才会在这里出现，自提与商家配送不产生快递单。",
  traceTitle: "轨迹 {no}",
  secShipOverview: "快递概况",
  secWaybill: "运单号",
  secTraces: "轨迹",
  waybillHint: "同一承运商下运单号不能重复：重号会把两单的轨迹搅在一起。",
  waybillLockedHint: "已签收的快递单不能改运单号 —— 货都到了再改，等于把一条已完成的轨迹指向别处。",
  fieldWaybillReason: "换单原因",
  waybillReasonPlaceholder: "例：承运商重新出单",
  btnSaveWaybill: "保存运单号",
  toastWaybillSaved: "运单号已更新，原因已写入轨迹",
  freightNotice: "运费模板与超区规则同页：它们是同一个决定的两面 —— 「这单收多少运费」与「这个地址到底发不发」。分开配必然出现算得出运费、却根本不该配送的地址。",
  colTemplateName: "模板名称",
  colFirst: "首重",
  colAdd: "续重",
  colFreeThreshold: "免邮门槛",
  colOutOfRange: "超区规则",
  colDefault: "默认",
  weightFee: "{g} 克 / {fee}",
  outOfRangeCount: "{n} 条",
  noFreeShipping: "不免邮",
  badgeDefault: "默认模板",
  actionNewTemplate: "新建模板",
  actionEdit: "编辑",
  actionArchive: "归档",
  actionRemoveRegion: "移除",
  emptyTemplate: "还没有运费模板。至少要有一个默认模板，新商家才有模板可用。",
  newTemplateTitle: "新建运费模板",
  editTemplateTitle: "编辑 {name}",
  secTemplateBasic: "计费规则",
  secOutOfRange: "超区规则",
  fieldFirstWeight: "首重（克）",
  fieldFirstFee: "首重费（元）",
  fieldAddWeight: "续重单位（克）",
  fieldAddFee: "每单位续重费（元）",
  fieldFreeThreshold: "免邮门槛（元）",
  freeThresholdHint: "填 0 表示不免邮。",
  outOfRangeHint: "同一区域只能配一条规则：配两条时命中哪条取决于顺序，那是隐性行为。不配送的区域不能填加价额。",
  fieldRegion: "区域",
  fieldOutAction: "处置",
  fieldSurcharge: "加价（元）",
  regionPlaceholder: "例：新疆维吾尔自治区",
  outReject: "不配送",
  outSurcharge: "加价配送",
  btnAddRegion: "加一条区域",
  btnSaveTemplate: "保存模板",
  toastTemplateSaved: "模板已保存",
  toastTemplateArchived: "模板已归档 —— 历史订单的运费依据仍在",
  confirmDeleteTitle: "归档运费模板？",
  confirmDeleteDesc: "「{name}」归档后，正在使用它的商家会回落到默认模板；历史订单的运费依据不受影响。",
  expressReadOnlyWhat: "运单号修改",
  freightReadOnlyWhat: "运费模板与超区规则",
  tabSorting: "分拣汇总",
  tabRedeem: "核销监控",
  tabOverdue: "逾期规则",

  nextDispatched: "标记发车",
  nextArrived: "标记到货",
  nextSigned: "确认签收",

  actionPostpone: "顺延到下一批",
  actionVoid: "作废并退款",

  /** `{no}` 是批次号 */
  toastBatchUpdated: "{no} 已更新",
  toastRuleSaved: "逾期规则已保存",

  colBatchNo: "批次号",
  colPickup: "自提点",
  colCommunity: "社区",
  colPlanArrive: "计划到货",
  colVehicle: "车次 / 司机",
  colItemCount: "件数",
  colMerchantCount: "涉及商家",
  colStatus: "状态",
  colActions: "操作",
  batchDone: "已完成",

  colSkuNo: "商品编码",
  colTitle: "商品",
  colSupplier: "供货商家",
  colQty: "应分拣",
  colShortQty: "缺件",

  colPending: "待核销",
  colRedeemed: "已核销",
  colOverdue: "逾期未取",
  colRate: "核销率",

  notice:
    "平台侧只做调度与监控，扫码核销在商家端的核销台（B-10.2）。两者成对交付 —— 只上线本页，货到了仍然没人能核销。",
  searchPlaceholder: "搜索批次号 / 自提点 / 车次",
  filterStatus: "按状态筛选",
  filterStatusAll: "全部状态",
  emptyBatches: "没有符合条件的到货批次。批次由订单截单后生成，今天还没截单时这里就是空的。",

  sortingNotice: "只列「已签收」批次的货：没签收就分拣，缺件责任分不清是路上丢的还是点上丢的。",
  emptySorting: "暂无待分拣的货。批次确认签收后，这里才会出现该点当日的分拣清单。",

  kpiPending: "待核销",
  kpiPendingSub: "用户还没来取",
  kpiOverdue: "逾期未取",
  kpiOverdueSub: "按逾期规则处置",
  kpiOverdueNone: "无逾期",
  kpiPickups: "监控中的自提点",
  emptyRedeem: "今天还没有需要核销的订单。核销发生在用户到点取货时，早上通常是空的。",

  ruleTitle: "逾期处置规则",
  ruleReadOnlyWhat: "逾期规则配置",
  ruleReadOnlyNote: "不能修改处置方式与宽限期",
  fieldAction: "超时未取如何处置",
  fieldGrace: "宽限期（小时）",
  /** `{n}` 是最小宽限小时数 */
  graceHint: "最少 {n} 小时。到点即作废会直接产生客诉，所以作废也必须留宽限期。",
  fieldMaxPostpone: "顺延次数上限",
  maxPostponeHint: "超过上限后按作废处理，避免一单在点上无限期占位。",
};

const en: typeof zh = {
  tabBatches: "Arrival batches",
  none: "—",
  tabExpress: "Courier & tracking",
  tabCarrier: "Carrier integrations",
  carrierNotice: "Get this page wrong and orders stop shipping, not just displaying wrong: enabling a carrier with no key makes every booking fail on the spot, disabling one with parcels in transit strands their tracking, and disabling them all leaves nowhere to book. So the reason a button is unavailable sits right next to it — you never have to click to find out.",
  colPriority: "Priority",
  colCarrierName: "Carrier",
  colAccount: "Account",
  colApiKey: "API key",
  colCutoff: "Daily cut-off",
  colSla: "Promised SLA",
  colInFlight: "In transit",
  colCarrierStatus: "State",
  colCarrierUpdatedAt: "Last changed",
  keyReady: "Configured",
  keyMissing: "Not configured",
  slaHoursValue: "{n} h",
  inFlightCount: "{n}",
  carrierOn: "Enabled",
  carrierOff: "Disabled",
  actionEditCarrier: "Edit",
  actionCarrierOn: "Enable",
  actionCarrierOff: "Disable",
  gateNoKey: "No API key — bookings would fail",
  gateInFlight: "{n} parcels still in transit",
  gateLastOne: "The last enabled carrier",
  emptyCarrier: "No carriers integrated yet. At least one has to be connected and enabled before courier-fulfilled orders can ship.",
  editCarrierTitle: "Configure {name}",
  secCarrierBasic: "Integration settings",
  secApiKey: "API key",
  cutoffHint: "Format HH:mm. Anything booked after it is collected the next day.",
  priorityHint: "Lower numbers go first, and no two carriers may share a priority — otherwise which one wins depends on order, and that is hidden behaviour.",
  apiKeyHint: "Keys are not set here and never appear in the contract, not even masked. Ops configure them server-side; this page only shows whether one exists.",
  btnSaveCarrier: "Save settings",
  toastCarrierSaved: "Carrier settings saved",
  toastCarrierOn: "Carrier enabled",
  toastCarrierOff: "Carrier disabled",
  carrierReadOnlyWhat: "carrier integrations",
  tabFreight: "Freight templates & out-of-range",
  expressNotice: "Tracking comes from the carrier; the platform does not write it — there is no “add a tracking entry by hand”, because an entry that disagrees with the carrier’s record works against you in a dispute. The one thing ops can change here is the waybill number.",
  searchShipment: "Search shipment / order / waybill no. / recipient",
  filterCarrier: "Filter by carrier",
  filterCarrierAll: "All carriers",
  filterShipStatus: "Filter by delivery state",
  filterShipStatusAll: "All delivery states",
  carrierSf: "SF Express",
  carrierJd: "JD Logistics",
  carrierYto: "YTO Express",
  shipCreated: "Created",
  shipPickedUp: "Picked up",
  shipInTransit: "In transit",
  shipDelivered: "Delivered",
  shipException: "Delivery problem",
  colShipmentNo: "Shipment no.",
  colOrderNo: "Order no.",
  colCarrier: "Carrier",
  colWaybill: "Waybill no.",
  colShipStatus: "Delivery state",
  colReceiver: "Recipient",
  colRegion: "Destination",
  colUpdatedAt: "Latest update",
  actionTrace: "View tracking",
  emptyShipment: "No shipments match. Only courier-fulfilled orders appear here — pickup and merchant delivery produce no shipment.",
  traceTitle: "Tracking for {no}",
  secShipOverview: "Shipment overview",
  secWaybill: "Waybill number",
  secTraces: "Tracking",
  waybillHint: "Waybill numbers must be unique within a carrier: a duplicate tangles two shipments’ tracking together.",
  waybillLockedHint: "A delivered shipment’s waybill cannot change — the goods have arrived, so repointing a finished trail helps no one.",
  fieldWaybillReason: "Why change it",
  waybillReasonPlaceholder: "e.g. The carrier reissued the waybill",
  btnSaveWaybill: "Save waybill number",
  toastWaybillSaved: "Waybill updated — the reason is in the tracking log",
  freightNotice: "Freight templates and out-of-range rules live on one page: they are two sides of one decision — what the shipping costs, and whether you ship there at all. Configured apart, you end up with addresses that price fine but should never have been served.",
  colTemplateName: "Template",
  colFirst: "First weight",
  colAdd: "Additional",
  colFreeThreshold: "Free shipping over",
  colOutOfRange: "Out-of-range",
  colDefault: "Default",
  weightFee: "{g} g / {fee}",
  outOfRangeCount: "{n} rules",
  noFreeShipping: "None",
  badgeDefault: "Default",
  actionNewTemplate: "New template",
  actionEdit: "Edit",
  actionArchive: "Archive",
  actionRemoveRegion: "Remove",
  emptyTemplate: "No freight templates yet. At least one default is needed so new merchants have something to use.",
  newTemplateTitle: "New freight template",
  editTemplateTitle: "Edit {name}",
  secTemplateBasic: "Pricing",
  secOutOfRange: "Out-of-range rules",
  fieldFirstWeight: "First weight (g)",
  fieldFirstFee: "First-weight fee (¥)",
  fieldAddWeight: "Additional unit (g)",
  fieldAddFee: "Fee per additional unit (¥)",
  fieldFreeThreshold: "Free shipping over (¥)",
  freeThresholdHint: "0 means no free shipping.",
  outOfRangeHint: "One rule per region: with two, which one wins depends on order, and that is hidden behaviour. A region you do not ship to cannot carry a surcharge.",
  fieldRegion: "Region",
  fieldOutAction: "Handling",
  fieldSurcharge: "Surcharge (¥)",
  regionPlaceholder: "e.g. Xinjiang Uygur Autonomous Region",
  outReject: "Do not ship",
  outSurcharge: "Ship with surcharge",
  btnAddRegion: "Add a region",
  btnSaveTemplate: "Save template",
  toastTemplateSaved: "Template saved",
  toastTemplateArchived: "Template archived — past orders keep their freight basis",
  confirmDeleteTitle: "Archive this freight template?",
  confirmDeleteDesc: "Merchants using “{name}” fall back to the default template; past orders keep their freight basis.",
  expressReadOnlyWhat: "changing waybill numbers",
  freightReadOnlyWhat: "freight templates and out-of-range rules",
  tabSorting: "Sorting summary",
  tabRedeem: "Redemption monitor",
  tabOverdue: "Overdue rules",

  nextDispatched: "Mark dispatched",
  nextArrived: "Mark arrived",
  nextSigned: "Confirm signed off",

  actionPostpone: "Roll over to next batch",
  actionVoid: "Void & refund",

  toastBatchUpdated: "{no} updated",
  toastRuleSaved: "Overdue rules saved",

  colBatchNo: "Batch no.",
  colPickup: "Pickup point",
  colCommunity: "Community",
  colPlanArrive: "Planned arrival",
  colVehicle: "Vehicle / driver",
  colItemCount: "Items",
  colMerchantCount: "Merchants",
  colStatus: "Status",
  colActions: "Actions",
  batchDone: "Done",

  colSkuNo: "SKU code",
  colTitle: "Product",
  colSupplier: "Supplier",
  colQty: "To sort",
  colShortQty: "Missing",

  colPending: "Awaiting pickup",
  colRedeemed: "Redeemed",
  colOverdue: "Overdue",
  colRate: "Redemption rate",

  notice:
    "The platform side only schedules and monitors; scanning happens on the merchant-side redemption console (B-10.2). The two ship as a pair — with only this page live, goods arrive and nobody can redeem them.",
  searchPlaceholder: "Search batch no. / pickup point / vehicle",
  filterStatus: "Filter by status",
  filterStatusAll: "All statuses",
  emptyBatches: "No arrival batches match these filters. Batches are created once orders close for the day, so this is empty before cut-off.",

  sortingNotice:
    "Only goods from signed-off batches are listed: sort before sign-off and you cannot tell whether a missing item was lost in transit or at the point.",
  emptySorting: "Nothing to sort yet. A point's daily sorting list appears here once its batch is signed off.",

  kpiPending: "Awaiting pickup",
  kpiPendingSub: "Customers have not collected yet",
  kpiOverdue: "Overdue",
  kpiOverdueSub: "Handled per the overdue rules",
  kpiOverdueNone: "None overdue",
  kpiPickups: "Pickup points monitored",
  emptyRedeem: "No orders need redeeming today. Redemption happens when customers arrive, so mornings are usually empty.",

  ruleTitle: "Overdue handling rules",
  ruleReadOnlyWhat: "overdue rule configuration",
  ruleReadOnlyNote: "cannot change the action or the grace period",
  fieldAction: "What happens when goods are not collected in time",
  fieldGrace: "Grace period (hours)",
  graceHint: "At least {n} hours. Voiding the moment the deadline passes generates complaints, so even voiding needs a grace period.",
  fieldMaxPostpone: "Maximum roll-overs",
  maxPostponeHint: "Beyond the limit the order is voided, so one order cannot occupy a point indefinitely.",
};

export const FULFILLMENT_COPY: PageCopy<typeof zh> = { zh, en };

/** 拆出去的 tab 组件靠它接文案。 */
export type FulfillmentCopy = typeof zh;
